/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/usr/src/extras/Nimrod/lib -o compiler/nimcache/astalgo.o compiler/nimcache/astalgo.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct tiitable142212 tiitable142212;
typedef struct tiipairseq142210 tiipairseq142210;
typedef struct tiipair142208 tiipair142208;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tsym135677 tsym135677;
typedef struct tstrtable135651 tstrtable135651;
typedef struct tsymseq135649 tsymseq135649;
typedef struct tident131018 tident131018;
typedef struct tidobj131012 tidobj131012;
typedef struct TNimObject TNimObject;
typedef struct NimStringDesc NimStringDesc;
typedef struct ttypeseq135679 ttypeseq135679;
typedef struct ttype135681 ttype135681;
typedef struct TY135771 TY135771;
typedef struct tinstantiation135667 tinstantiation135667;
typedef struct tscope135671 tscope135671;
typedef struct tlineinfo128308 tlineinfo128308;
typedef struct tnode135647 tnode135647;
typedef struct tloc135661 tloc135661;
typedef struct trope126007 trope126007;
typedef struct tlib135665 tlib135665;
typedef struct tcell38449 tcell38449;
typedef struct tcellseq38465 tcellseq38465;
typedef struct tgcheap40416 tgcheap40416;
typedef struct tcellset38461 tcellset38461;
typedef struct tpagedesc38457 tpagedesc38457;
typedef struct tmemregion22010 tmemregion22010;
typedef struct tsmallchunk21243 tsmallchunk21243;
typedef struct tllchunk22004 tllchunk22004;
typedef struct tbigchunk21245 tbigchunk21245;
typedef struct tintset21218 tintset21218;
typedef struct ttrunk21214 ttrunk21214;
typedef struct tavlnode22008 tavlnode22008;
typedef struct tgcstat40414 tgcstat40414;
typedef struct ttabiter142090 ttabiter142090;
typedef struct tidtable135693 tidtable135693;
typedef struct tidpairseq135691 tidpairseq135691;
typedef struct tidpair135689 tidpair135689;
typedef struct tnodeseq135641 tnodeseq135641;
typedef struct tidnodetable135699 tidnodetable135699;
typedef struct tidnodepairseq135697 tidnodepairseq135697;
typedef struct tidnodepair135695 tidnodepair135695;
typedef struct tidentiter142106 tidentiter142106;
typedef struct tintset132035 tintset132035;
typedef struct ttrunk132031 ttrunk132031;
typedef struct ttrunkseq132033 ttrunkseq132033;
typedef struct TY135763 TY135763;
typedef struct tlistentry100011 tlistentry100011;
typedef struct tbasechunk21241 tbasechunk21241;
typedef struct tfreecell21233 tfreecell21233;
struct tiipair142208 {
NI Key;
NI Val;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct tiitable142212 {
NI Counter;
tiipairseq142210* Data;
};
typedef N_NIMCALL_PTR(void, TY891) (void* p, NI op);
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY891 marker;
};
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tstrtable135651 {
NI Counter;
tsymseq135649* Data;
};
struct TNimObject {
TNimType* m_type;
};
struct tidobj131012 {
  TNimObject Sup;
NI Id;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
struct tident131018 {
  tidobj131012 Sup;
NimStringDesc* S;
tident131018* Next;
NI H;
};
struct tlineinfo128308 {
NI16 Line;
NI16 Col;
NI32 Fileindex;
};
struct tloc135661 {
NU8 K;
NU8 S;
NU8 Flags;
ttype135681* T;
trope126007* R;
trope126007* Heaproot;
NI A;
};
struct tsym135677 {
  tidobj131012 Sup;
NU8 Kind;
union {
struct {ttypeseq135679* Typeinstcache;
} S1;
struct {TY135771* Procinstcache;
tscope135671* Scope;
} S2;
struct {TY135771* Usedgenerics;
tstrtable135651 Tab;
} S3;
} kindU;
NU16 Magic;
ttype135681* Typ;
tident131018* Name;
tlineinfo128308 Info;
tsym135677* Owner;
NU32 Flags;
tnode135647* Ast;
NU32 Options;
NI Position;
NI Offset;
tloc135661 Loc;
tlib135665* Annex;
tnode135647* Constraint;
};
struct tcell38449 {
NI Refcount;
TNimType* Typ;
};
struct tcellseq38465 {
NI Len;
NI Cap;
tcell38449** D;
};
struct tcellset38461 {
NI Counter;
NI Max;
tpagedesc38457* Head;
tpagedesc38457** Data;
};
typedef tsmallchunk21243* TY22022[512];
typedef ttrunk21214* ttrunkbuckets21216[256];
struct tintset21218 {
ttrunkbuckets21216 Data;
};
struct tmemregion22010 {
NI Minlargeobj;
NI Maxlargeobj;
TY22022 Freesmallchunks;
tllchunk22004* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk21245* Freechunkslist;
tintset21218 Chunkstarts;
tavlnode22008* Root;
tavlnode22008* Deleted;
tavlnode22008* Last;
tavlnode22008* Freeavlnodes;
};
struct tgcstat40414 {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct tgcheap40416 {
void* Stackbottom;
NI Cyclethreshold;
tcellseq38465 Zct;
tcellseq38465 Decstack;
tcellset38461 Cycleroots;
tcellseq38465 Tempstack;
NI Recgclock;
tmemregion22010 Region;
tgcstat40414 Stat;
};
struct ttabiter142090 {
NI H;
};
struct tidpair135689 {
tidobj131012* Key;
TNimObject* Val;
};
struct tidtable135693 {
NI Counter;
tidpairseq135691* Data;
};
struct tnode135647 {
ttype135681* Typ;
tlineinfo128308 Info;
NU8 Flags;
NU8 Kind;
union {
struct {NI64 Intval;
} S1;
struct {NF64 Floatval;
} S2;
struct {NimStringDesc* Strval;
} S3;
struct {tsym135677* Sym;
} S4;
struct {tident131018* Ident;
} S5;
struct {tnodeseq135641* Sons;
} S6;
} kindU;
NimStringDesc* Comment;
};
struct tidnodepair135695 {
tidobj131012* Key;
tnode135647* Val;
};
struct tidnodetable135699 {
NI Counter;
tidnodepairseq135697* Data;
};
struct tidentiter142106 {
NI H;
tident131018* Name;
};
struct tintset132035 {
NI Counter;
NI Max;
ttrunk132031* Head;
ttrunkseq132033* Data;
};
struct ttype135681 {
  tidobj131012 Sup;
NU8 Kind;
NU8 Callconv;
NU32 Flags;
ttypeseq135679* Sons;
tnode135647* N;
tsym135677* Destructor;
tsym135677* Owner;
tsym135677* Sym;
NI64 Size;
NI Align;
tloc135661 Loc;
};
struct tinstantiation135667 {
tsym135677* Sym;
ttypeseq135679* Concretetypes;
TY135763* Usedby;
};
struct tscope135671 {
NI Depthlevel;
tstrtable135651 Symbols;
tscope135671* Parent;
};
struct trope126007 {
  TNimObject Sup;
trope126007* Left;
trope126007* Right;
NI Length;
NimStringDesc* Data;
};
struct tlistentry100011 {
  TNimObject Sup;
tlistentry100011* Prev;
tlistentry100011* Next;
};
struct tlib135665 {
  tlistentry100011 Sup;
NU8 Kind;
NIM_BOOL Generated;
NIM_BOOL Isoverriden;
trope126007* Name;
tnode135647* Path;
};
typedef NI TY21221[8];
struct tpagedesc38457 {
tpagedesc38457* Next;
NI Key;
TY21221 Bits;
};
struct tbasechunk21241 {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct tsmallchunk21243 {
  tbasechunk21241 Sup;
tsmallchunk21243* Next;
tsmallchunk21243* Prev;
tfreecell21233* Freelist;
NI Free;
NI Acc;
NF64 Data;
};
struct tllchunk22004 {
NI Size;
NI Acc;
tllchunk22004* Next;
};
struct tbigchunk21245 {
  tbasechunk21241 Sup;
tbigchunk21245* Next;
tbigchunk21245* Prev;
NI Align;
NF64 Data;
};
struct ttrunk21214 {
ttrunk21214* Next;
NI Key;
TY21221 Bits;
};
typedef tavlnode22008* TY22014[2];
struct tavlnode22008 {
TY22014 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct ttrunk132031 {
ttrunk132031* Next;
NI Key;
TY21221 Bits;
};
struct tfreecell21233 {
tfreecell21233* Next;
NI Zerofield;
};
struct tiipairseq142210 {
  TGenericSeq Sup;
  tiipair142208 data[SEQ_DECL_SIZE];
};
struct tsymseq135649 {
  TGenericSeq Sup;
  tsym135677* data[SEQ_DECL_SIZE];
};
struct ttypeseq135679 {
  TGenericSeq Sup;
  ttype135681* data[SEQ_DECL_SIZE];
};
struct TY135771 {
  TGenericSeq Sup;
  tinstantiation135667* data[SEQ_DECL_SIZE];
};
struct tidpairseq135691 {
  TGenericSeq Sup;
  tidpair135689 data[SEQ_DECL_SIZE];
};
struct tnodeseq135641 {
  TGenericSeq Sup;
  tnode135647* data[SEQ_DECL_SIZE];
};
struct tidnodepairseq135697 {
  TGenericSeq Sup;
  tidnodepair135695 data[SEQ_DECL_SIZE];
};
struct ttrunkseq132033 {
  TGenericSeq Sup;
  ttrunk132031* data[SEQ_DECL_SIZE];
};
struct TY135763 {
  TGenericSeq Sup;
  NI32 data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, TMP796)(void* p, NI op);
static N_INLINE(NI, nexttry_142196)(NI h, NI maxhash);
N_NIMCALL(NIM_BOOL, mustrehash_142191)(NI length, NI counter);
N_NIMCALL(void, strtableenlarge_146014)(tstrtable135651* t);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, strtablerawinsert_145528)(tsymseq135649** data, tsym135677* n);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell38449*, usrtocell_41843)(void* usr);
static N_INLINE(void, rtladdzct_43002)(tcell38449* c);
N_NOINLINE(void, addzct_41815)(tcellseq38465* s, tcell38449* c);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(tsym135677*, nextiter_142099)(ttabiter142090* ti, tstrtable135651 tab);
N_NIMCALL(NI, iitablerawget_148158)(tiitable142212 t, NI key);
N_NIMCALL(void, iitablerawinsert_148176)(tiipairseq142210** data, NI key, NI val);
N_NIMCALL(NI, idtablerawget_146609)(tidtable135693 t, NI key);
N_NIMCALL(void, idtablerawinsert_146696)(tidpairseq135691** data, tidobj131012* key, TNimObject* val);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NI, sonslen_136002)(tnode135647* n);
N_NIMCALL(void, internalerror_129687)(tlineinfo128308 info, NimStringDesc* errmsg);
N_NIMCALL(NI, idnodetablerawget_147467)(tidnodetable135699 t, tidobj131012* key);
N_NIMCALL(void, idnodetablerawinsert_147512)(tidnodepairseq135697** data, tidobj131012* key, tnode135647* val);
static N_INLINE(NI, cmpStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(tsym135677*, nextidentiter_142117)(tidentiter142106* ti, tstrtable135651 tab);
N_NIMCALL(tsym135677*, nextidentexcluding_146471)(tidentiter142106* ti, tstrtable135651 tab, tintset132035* excluding);
N_NIMCALL(NIM_BOOL, contains_132820)(tintset132035* s, NI key);
N_NIMCALL(tnode135647*, skipconv_142236)(tnode135647* n);
N_NIMCALL(void, symtabreplaceraw_145605)(tsymseq135649** data, tsym135677* prevsym, tsym135677* newsym);
N_NIMCALL(tsym135677*, lookupinrecord_142182)(tnode135647* n, tident131018* field);
static N_INLINE(tnode135647*, lastson_136010)(tnode135647* n);
STRING_LITERAL(TMP2439, "getSymFromList", 14);
STRING_LITERAL(TMP3058, "lookupInRecord", 14);
STRING_LITERAL(TMP3059, "lookupInRecord(record case branch)", 34);
STRING_LITERAL(TMP3060, "lookupInRecord()", 16);
TNimType NTI142212; /* TIITable */
extern TNimType NTI105; /* int */
TNimType NTI142208; /* TIIPair */
TNimType NTI142210; /* TIIPairSeq */
extern TNimType NTI135649; /* TSymSeq */
extern tgcheap40416 gch_40442;
extern TNimType NTI135691; /* TIdPairSeq */
extern TNimType NTI135697; /* TIdNodePairSeq */
N_NIMCALL(void, TMP796)(void* p, NI op) {
	tiipairseq142210* a;
	NI LOC1;
	a = (tiipairseq142210*)p;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	}
}

static N_INLINE(NI, nexttry_142196)(NI h, NI maxhash) {
	NI result;
	result = 0;
	result = (NI)((NI64)((NI64)(5 * h) + 1) & maxhash);
	return result;
}

N_NIMCALL(tsym135677*, strtableget_142084)(tstrtable135651 t, tident131018* name) {
	tsym135677* result;
	NI h;
	result = 0;
	h = (NI)((*name).H & (t.Data->Sup.len-1));
	while (1) {
		result = t.Data->data[h];
		{
			if (!(result == NIM_NIL)) goto LA4;
			goto LA1;
		}
		LA4: ;
		{
			if (!((*(*result).Name).Sup.Id == (*name).Sup.Id)) goto LA8;
			goto LA1;
		}
		LA8: ;
		h = nexttry_142196(h, (t.Data->Sup.len-1));
	} LA1: ;
	return result;
}

N_NIMCALL(NIM_BOOL, mustrehash_142191)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	result = 0;
	LOC1 = ((NI64)(length * 2) < (NI64)(counter * 3));
	if (LOC1) goto LA2;
	LOC1 = ((NI64)(length - counter) < 4);
	LA2: ;
	result = LOC1;
	return result;
}

static N_INLINE(tcell38449*, usrtocell_41843)(void* usr) {
	tcell38449* result;
	result = 0;
	result = ((tcell38449*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell38449))))));
	return result;
}

static N_INLINE(void, rtladdzct_43002)(tcell38449* c) {
	addzct_41815(&gch_40442.Zct, c);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		tcell38449* c;
		if (!!((src == NIM_NIL))) goto LA3;
		c = usrtocell_41843(src);
		(*c).Refcount += 8;
	}
	LA3: ;
	{
		tcell38449* c;
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		c = usrtocell_41843((*dest));
		{
			(*c).Refcount -= 8;
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			rtladdzct_43002(c);
		}
		LA11: ;
	}
	LA7: ;
	(*dest) = src;
}

N_NIMCALL(void, strtablerawinsert_145528)(tsymseq135649** data, tsym135677* n) {
	NI h;
	h = (NI)((*(*n).Name).H & ((*data)->Sup.len-1));
	while (1) {
		if (!!(((*data)->data[h] == NIM_NIL))) goto LA1;
		{
			if (!((*data)->data[h] == n)) goto LA4;
			goto BeforeRet;
		}
		LA4: ;
		h = nexttry_142196(h, ((*data)->Sup.len-1));
	} LA1: ;
	asgnRefNoCycle((void**) &(*data)->data[h], n);
	BeforeRet: ;
}

N_NIMCALL(void, strtableenlarge_146014)(tstrtable135651* t) {
	tsymseq135649* n;
	NI i_146047;
	NI HEX3Atmp_146070;
	NI res_146072;
	tsymseq135649* LOC6;
	n = 0;
	n = (tsymseq135649*) newSeq((&NTI135649), (NI64)((*t).Data->Sup.len * 2));
	i_146047 = 0;
	HEX3Atmp_146070 = 0;
	HEX3Atmp_146070 = ((*t).Data->Sup.len-1);
	res_146072 = 0;
	while (1) {
		if (!(res_146072 <= HEX3Atmp_146070)) goto LA1;
		i_146047 = res_146072;
		{
			if (!!(((*t).Data->data[i_146047] == NIM_NIL))) goto LA4;
			strtablerawinsert_145528(&n, (*t).Data->data[i_146047]);
		}
		LA4: ;
		res_146072 += 1;
	} LA1: ;
	LOC6 = 0;
	LOC6 = (*t).Data;
	unsureAsgnRef((void**) &(*t).Data, n);
	n = LOC6;
}

N_NIMCALL(void, strtableadd_142078)(tstrtable135651* t, tsym135677* n) {
	{
		NIM_BOOL LOC3;
		LOC3 = mustrehash_142191((*t).Data->Sup.len, (*t).Counter);
		if (!LOC3) goto LA4;
		strtableenlarge_146014(t);
	}
	LA4: ;
	strtablerawinsert_145528(&(*t).Data, n);
	(*t).Counter += 1;
}

N_NIMCALL(void, initiitable_142218)(tiitable142212* x) {
	NI i_148151;
	NI res_148153;
	(*x).Counter = 0;
	unsureAsgnRef((void**) &(*x).Data, (tiipairseq142210*) newSeq((&NTI142210), 8));
	i_148151 = 0;
	res_148153 = 0;
	while (1) {
		if (!(res_148153 <= 7)) goto LA1;
		i_148151 = res_148153;
		(*x).Data->data[i_148151].Key = (IL64(-9223372036854775807) - IL64(1));
		res_148153 += 1;
	} LA1: ;
}

N_NIMCALL(tsym135677*, nextiter_142099)(ttabiter142090* ti, tstrtable135651 tab) {
	tsym135677* result;
	result = 0;
	result = NIM_NIL;
	while (1) {
		if (!((*ti).H <= (tab.Data->Sup.len-1))) goto LA1;
		result = tab.Data->data[(*ti).H];
		(*ti).H += 1;
		{
			if (!!((result == NIM_NIL))) goto LA4;
			goto LA1;
		}
		LA4: ;
	} LA1: ;
	return result;
}

N_NIMCALL(tsym135677*, inittabiter_142093)(ttabiter142090* ti, tstrtable135651 tab) {
	tsym135677* result;
	result = 0;
	(*ti).H = 0;
	{
		if (!(tab.Counter == 0)) goto LA3;
		result = NIM_NIL;
	}
	goto LA1;
	LA3: ;
	{
		result = nextiter_142099(ti, tab);
	}
	LA1: ;
	return result;
}

N_NIMCALL(NI, iitablerawget_148158)(tiitable142212 t, NI key) {
	NI result;
	NI h;
	result = 0;
	h = 0;
	h = (NI)(key & (t.Data->Sup.len-1));
	while (1) {
		if (!!((t.Data->data[h].Key == (IL64(-9223372036854775807) - IL64(1))))) goto LA1;
		{
			if (!(t.Data->data[h].Key == key)) goto LA4;
			result = h;
			goto BeforeRet;
		}
		LA4: ;
		h = nexttry_142196(h, (t.Data->Sup.len-1));
	} LA1: ;
	result = -1;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, iitablerawinsert_148176)(tiipairseq142210** data, NI key, NI val) {
	NI h;
	h = 0;
	h = (NI)(key & ((*data)->Sup.len-1));
	while (1) {
		if (!!(((*data)->data[h].Key == (IL64(-9223372036854775807) - IL64(1))))) goto LA1;
		h = nexttry_142196(h, ((*data)->Sup.len-1));
	} LA1: ;
	(*data)->data[h].Key = key;
	(*data)->data[h].Val = val;
}

N_NIMCALL(void, iitableput_142228)(tiitable142212* t, NI key, NI val) {
	NI index;
	index = iitablerawget_148158((*t), key);
	{
		if (!(0 <= index)) goto LA3;
		(*t).Data->data[index].Val = val;
	}
	goto LA1;
	LA3: ;
	{
		{
			NIM_BOOL LOC8;
			tiipairseq142210* n;
			NI i_148638;
			NI HEX3Atmp_148672;
			NI res_148674;
			NI i_148647;
			NI HEX3Atmp_148676;
			NI res_148678;
			tiipairseq142210* LOC17;
			LOC8 = mustrehash_142191((*t).Data->Sup.len, (*t).Counter);
			if (!LOC8) goto LA9;
			n = 0;
			n = (tiipairseq142210*) newSeq((&NTI142210), (NI64)((*t).Data->Sup.len * 2));
			i_148638 = 0;
			HEX3Atmp_148672 = 0;
			HEX3Atmp_148672 = (n->Sup.len-1);
			res_148674 = 0;
			while (1) {
				if (!(res_148674 <= HEX3Atmp_148672)) goto LA11;
				i_148638 = res_148674;
				n->data[i_148638].Key = (IL64(-9223372036854775807) - IL64(1));
				res_148674 += 1;
			} LA11: ;
			i_148647 = 0;
			HEX3Atmp_148676 = 0;
			HEX3Atmp_148676 = ((*t).Data->Sup.len-1);
			res_148678 = 0;
			while (1) {
				if (!(res_148678 <= HEX3Atmp_148676)) goto LA12;
				i_148647 = res_148678;
				{
					if (!!(((*t).Data->data[i_148647].Key == (IL64(-9223372036854775807) - IL64(1))))) goto LA15;
					iitablerawinsert_148176(&n, (*t).Data->data[i_148647].Key, (*t).Data->data[i_148647].Val);
				}
				LA15: ;
				res_148678 += 1;
			} LA12: ;
			LOC17 = 0;
			LOC17 = (*t).Data;
			unsureAsgnRef((void**) &(*t).Data, n);
			n = LOC17;
		}
		LA9: ;
		iitablerawinsert_148176(&(*t).Data, key, val);
		(*t).Counter += 1;
	}
	LA1: ;
}

N_NIMCALL(NI, idtablerawget_146609)(tidtable135693 t, NI key) {
	NI result;
	NI h;
	result = 0;
	h = 0;
	h = (NI)(key & (t.Data->Sup.len-1));
	while (1) {
		if (!!((t.Data->data[h].Key == NIM_NIL))) goto LA1;
		{
			if (!((*t.Data->data[h].Key).Id == key)) goto LA4;
			result = h;
			goto BeforeRet;
		}
		LA4: ;
		h = nexttry_142196(h, (t.Data->Sup.len-1));
	} LA1: ;
	result = -1;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, idtablerawinsert_146696)(tidpairseq135691** data, tidobj131012* key, TNimObject* val) {
	NI h;
	h = 0;
	h = (NI)((*key).Id & ((*data)->Sup.len-1));
	while (1) {
		if (!!(((*data)->data[h].Key == NIM_NIL))) goto LA1;
		h = nexttry_142196(h, ((*data)->Sup.len-1));
	} LA1: ;
	asgnRefNoCycle((void**) &(*data)->data[h].Key, key);
	asgnRefNoCycle((void**) &(*data)->data[h].Val, val);
}

N_NIMCALL(void, idtableput_142147)(tidtable135693* t, tidobj131012* key, TNimObject* val) {
	NI index;
	tidpairseq135691* n;
	index = 0;
	n = 0;
	index = idtablerawget_146609((*t), (*key).Id);
	{
		if (!(0 <= index)) goto LA3;
		asgnRefNoCycle((void**) &(*t).Data->data[index].Val, val);
	}
	goto LA1;
	LA3: ;
	{
		{
			NIM_BOOL LOC8;
			NI i_147237;
			NI HEX3Atmp_147425;
			NI res_147427;
			tidpairseq135691* LOC16;
			LOC8 = mustrehash_142191((*t).Data->Sup.len, (*t).Counter);
			if (!LOC8) goto LA9;
			n = (tidpairseq135691*) newSeq((&NTI135691), (NI64)((*t).Data->Sup.len * 2));
			i_147237 = 0;
			HEX3Atmp_147425 = 0;
			HEX3Atmp_147425 = ((*t).Data->Sup.len-1);
			res_147427 = 0;
			while (1) {
				if (!(res_147427 <= HEX3Atmp_147425)) goto LA11;
				i_147237 = res_147427;
				{
					if (!!(((*t).Data->data[i_147237].Key == NIM_NIL))) goto LA14;
					idtablerawinsert_146696(&n, (*t).Data->data[i_147237].Key, (*t).Data->data[i_147237].Val);
				}
				LA14: ;
				res_147427 += 1;
			} LA11: ;
			LOC16 = 0;
			LOC16 = (*t).Data;
			unsureAsgnRef((void**) &(*t).Data, n);
			n = LOC16;
		}
		LA9: ;
		idtablerawinsert_146696(&(*t).Data, key, val);
		(*t).Counter += 1;
	}
	LA1: ;
}

N_NIMCALL(TNimObject*, idtableget_142142)(tidtable135693 t, NI key) {
	TNimObject* result;
	NI index;
	result = 0;
	index = idtablerawget_146609(t, key);
	{
		if (!(0 <= index)) goto LA3;
		result = t.Data->data[index].Val;
	}
	goto LA1;
	LA3: ;
	{
		result = NIM_NIL;
	}
	LA1: ;
	return result;
}

N_NIMCALL(NI, iitableget_142223)(tiitable142212 t, NI key) {
	NI result;
	NI index;
	result = 0;
	index = iitablerawget_148158(t, key);
	{
		if (!(0 <= index)) goto LA3;
		result = t.Data->data[index].Val;
	}
	goto LA1;
	LA3: ;
	{
		result = (IL64(-9223372036854775807) - IL64(1));
	}
	LA1: ;
	return result;
}

N_NIMCALL(tsym135677*, getmodule_142187)(tsym135677* s) {
	tsym135677* result;
	result = 0;
	result = s;
	while (1) {
		NIM_BOOL LOC2;
		LOC2 = !((result == NIM_NIL));
		if (!(LOC2)) goto LA3;
		LOC2 = !(((*result).Kind == ((NU8) 6)));
		LA3: ;
		if (!LOC2) goto LA1;
		result = (*result).Owner;
	} LA1: ;
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (NI64)((*a).Sup.len * 1));
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NIM_BOOL, samevalue_142268)(tnode135647* a, tnode135647* b) {
	NIM_BOOL result;
	result = 0;
	result = NIM_FALSE;
	switch ((*a).Kind) {
	case ((NU8) 5) ... ((NU8) 10):
	{
		{
			if (!((*b).Kind >= ((NU8) 5) && (*b).Kind <= ((NU8) 10))) goto LA4;
			result = ((*a).kindU.S1.Intval == (*b).kindU.S1.Intval);
		}
		LA4: ;
	}
	break;
	case ((NU8) 16) ... ((NU8) 18):
	{
		{
			if (!((*b).Kind >= ((NU8) 16) && (*b).Kind <= ((NU8) 18))) goto LA9;
			result = (((NF) ((*a).kindU.S2.Floatval)) == ((NF) ((*b).kindU.S2.Floatval)));
		}
		LA9: ;
	}
	break;
	case ((NU8) 20) ... ((NU8) 22):
	{
		{
			if (!((*b).Kind >= ((NU8) 20) && (*b).Kind <= ((NU8) 22))) goto LA14;
			result = eqStrings((*a).kindU.S3.Strval, (*b).kindU.S3.Strval);
		}
		LA14: ;
	}
	break;
	default:
	{
	}
	break;
	}
	return result;
}

N_NIMCALL(TNimObject*, idtableget_142137)(tidtable135693 t, tidobj131012* key) {
	TNimObject* result;
	NI index;
	result = 0;
	index = idtablerawget_146609(t, (*key).Id);
	{
		if (!(0 <= index)) goto LA3;
		result = t.Data->data[index].Val;
	}
	goto LA1;
	LA3: ;
	{
		result = NIM_NIL;
	}
	LA1: ;
	return result;
}

static N_INLINE(NI, sonslen_136002)(tnode135647* n) {
	NI result;
	result = 0;
	{
		if (!(*n).kindU.S6.Sons == 0) goto LA3;
		result = 0;
	}
	goto LA1;
	LA3: ;
	{
		result = (*n).kindU.S6.Sons->Sup.len;
	}
	LA1: ;
	return result;
}

N_NIMCALL(tsym135677*, getsymfromlist_142176)(tnode135647* list, tident131018* ident, NI start) {
	tsym135677* result;
	NI i_142835;
	NI HEX3Atmp_142872;
	NI LOC1;
	NI res_142874;
	result = 0;
	i_142835 = 0;
	HEX3Atmp_142872 = 0;
	LOC1 = sonslen_136002(list);
	HEX3Atmp_142872 = (NI64)(LOC1 - 1);
	res_142874 = start;
	while (1) {
		if (!(res_142874 <= HEX3Atmp_142872)) goto LA2;
		i_142835 = res_142874;
		{
			if (!((*(*list).kindU.S6.Sons->data[i_142835]).Kind == ((NU8) 3))) goto LA5;
			result = (*(*list).kindU.S6.Sons->data[i_142835]).kindU.S4.Sym;
			{
				if (!((*(*result).Name).Sup.Id == (*ident).Sup.Id)) goto LA9;
				goto BeforeRet;
			}
			LA9: ;
		}
		goto LA3;
		LA5: ;
		{
			internalerror_129687((*list).Info, ((NimStringDesc*) &TMP2439));
		}
		LA3: ;
		res_142874 += 1;
	} LA2: ;
	result = NIM_NIL;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, idnodetablerawget_147467)(tidnodetable135699 t, tidobj131012* key) {
	NI result;
	NI h;
	result = 0;
	h = 0;
	h = (NI)((*key).Id & (t.Data->Sup.len-1));
	while (1) {
		if (!!((t.Data->data[h].Key == NIM_NIL))) goto LA1;
		{
			if (!((*t.Data->data[h].Key).Id == (*key).Id)) goto LA4;
			result = h;
			goto BeforeRet;
		}
		LA4: ;
		h = nexttry_142196(h, (t.Data->Sup.len-1));
	} LA1: ;
	result = -1;
	BeforeRet: ;
	return result;
}

N_NIMCALL(tnode135647*, idnodetableget_142159)(tidnodetable135699 t, tidobj131012* key) {
	tnode135647* result;
	NI index;
	result = 0;
	index = 0;
	index = idnodetablerawget_147467(t, key);
	{
		if (!(0 <= index)) goto LA3;
		result = t.Data->data[index].Val;
	}
	goto LA1;
	LA3: ;
	{
		result = NIM_NIL;
	}
	LA1: ;
	return result;
}

N_NIMCALL(tnode135647*, skipconv_142236)(tnode135647* n) {
	tnode135647* result;
	result = 0;
	switch ((*n).Kind) {
	case ((NU8) 67):
	case ((NU8) 66):
	case ((NU8) 70):
	case ((NU8) 68):
	case ((NU8) 69):
	{
		result = (*n).kindU.S6.Sons->data[0];
	}
	break;
	case ((NU8) 58):
	case ((NU8) 59):
	case ((NU8) 60):
	{
		result = (*n).kindU.S6.Sons->data[1];
	}
	break;
	default:
	{
		result = n;
	}
	break;
	}
	return result;
}

N_NIMCALL(void, idnodetablerawinsert_147512)(tidnodepairseq135697** data, tidobj131012* key, tnode135647* val) {
	NI h;
	h = 0;
	h = (NI)((*key).Id & ((*data)->Sup.len-1));
	while (1) {
		if (!!(((*data)->data[h].Key == NIM_NIL))) goto LA1;
		h = nexttry_142196(h, ((*data)->Sup.len-1));
	} LA1: ;
	asgnRefNoCycle((void**) &(*data)->data[h].Key, key);
	asgnRefNoCycle((void**) &(*data)->data[h].Val, val);
}

N_NIMCALL(void, idnodetableput_142164)(tidnodetable135699* t, tidobj131012* key, tnode135647* val) {
	NI index;
	index = idnodetablerawget_147467((*t), key);
	{
		if (!(0 <= index)) goto LA3;
		asgnRefNoCycle((void**) &(*t).Data->data[index].Val, val);
	}
	goto LA1;
	LA3: ;
	{
		{
			NIM_BOOL LOC8;
			tidnodepairseq135697* n;
			NI i_148038;
			NI HEX3Atmp_148074;
			NI res_148076;
			tidnodepairseq135697* LOC16;
			LOC8 = mustrehash_142191((*t).Data->Sup.len, (*t).Counter);
			if (!LOC8) goto LA9;
			n = 0;
			n = (tidnodepairseq135697*) newSeq((&NTI135697), (NI64)((*t).Data->Sup.len * 2));
			i_148038 = 0;
			HEX3Atmp_148074 = 0;
			HEX3Atmp_148074 = ((*t).Data->Sup.len-1);
			res_148076 = 0;
			while (1) {
				if (!(res_148076 <= HEX3Atmp_148074)) goto LA11;
				i_148038 = res_148076;
				{
					if (!!(((*t).Data->data[i_148038].Key == NIM_NIL))) goto LA14;
					idnodetablerawinsert_147512(&n, (*t).Data->data[i_148038].Key, (*t).Data->data[i_148038].Val);
				}
				LA14: ;
				res_148076 += 1;
			} LA11: ;
			LOC16 = 0;
			LOC16 = (*t).Data;
			unsureAsgnRef((void**) &(*t).Data, n);
			n = LOC16;
		}
		LA9: ;
		idnodetablerawinsert_147512(&(*t).Data, key, val);
		(*t).Counter += 1;
	}
	LA1: ;
}

static N_INLINE(NI, cmpStrings)(NimStringDesc* a, NimStringDesc* b) {
	NI result;
	int LOC13;
	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = 0;
		goto BeforeRet;
	}
	LA3: ;
	{
		if (!(a == NIM_NIL)) goto LA7;
		result = -1;
		goto BeforeRet;
	}
	LA7: ;
	{
		if (!(b == NIM_NIL)) goto LA11;
		result = 1;
		goto BeforeRet;
	}
	LA11: ;
	LOC13 = strcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)));
	result = ((NI) (LOC13));
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NIM_BOOL, levalue_142365)(tnode135647* a, tnode135647* b) {
	NIM_BOOL result;
	result = 0;
	result = NIM_FALSE;
	switch ((*a).Kind) {
	case ((NU8) 5) ... ((NU8) 10):
	{
		{
			if (!((*b).Kind >= ((NU8) 5) && (*b).Kind <= ((NU8) 10))) goto LA4;
			result = ((*a).kindU.S1.Intval <= (*b).kindU.S1.Intval);
		}
		LA4: ;
	}
	break;
	case ((NU8) 16) ... ((NU8) 18):
	{
		{
			if (!((*b).Kind >= ((NU8) 16) && (*b).Kind <= ((NU8) 18))) goto LA9;
			result = (((NF) ((*a).kindU.S2.Floatval)) <= ((NF) ((*b).kindU.S2.Floatval)));
		}
		LA9: ;
	}
	break;
	case ((NU8) 20) ... ((NU8) 22):
	{
		{
			if (!((*b).Kind >= ((NU8) 20) && (*b).Kind <= ((NU8) 22))) goto LA14;
			result = (cmpStrings((*a).kindU.S3.Strval, (*b).kindU.S3.Strval) <= 0);
		}
		LA14: ;
	}
	break;
	default:
	{
	}
	break;
	}
	return result;
}

N_NIMCALL(tsym135677*, nextidentiter_142117)(tidentiter142106* ti, tstrtable135651 tab) {
	tsym135677* result;
	NI h;
	NI start;
	result = 0;
	h = 0;
	start = 0;
	h = (NI)((*ti).H & (tab.Data->Sup.len-1));
	start = h;
	result = tab.Data->data[h];
	while (1) {
		if (!!((result == NIM_NIL))) goto LA1;
		{
			if (!((*(*result).Name).Sup.Id == (*(*ti).Name).Sup.Id)) goto LA4;
			goto LA1;
		}
		LA4: ;
		h = nexttry_142196(h, (tab.Data->Sup.len-1));
		{
			if (!(h == start)) goto LA8;
			result = NIM_NIL;
			goto LA1;
		}
		LA8: ;
		result = tab.Data->data[h];
	} LA1: ;
	(*ti).H = nexttry_142196(h, (tab.Data->Sup.len-1));
	return result;
}

N_NIMCALL(tsym135677*, initidentiter_142110)(tidentiter142106* ti, tstrtable135651 tab, tident131018* s) {
	tsym135677* result;
	result = 0;
	(*ti).H = (*s).H;
	unsureAsgnRef((void**) &(*ti).Name, s);
	{
		if (!(tab.Counter == 0)) goto LA3;
		result = NIM_NIL;
	}
	goto LA1;
	LA3: ;
	{
		result = nextidentiter_142117(ti, tab);
	}
	LA1: ;
	return result;
}

N_NIMCALL(tsym135677*, nextidentexcluding_146471)(tidentiter142106* ti, tstrtable135651 tab, tintset132035* excluding) {
	tsym135677* result;
	NI h;
	NI start;
	result = 0;
	h = (NI)((*ti).H & (tab.Data->Sup.len-1));
	start = h;
	result = tab.Data->data[h];
	while (1) {
		if (!!((result == NIM_NIL))) goto LA1;
		{
			NIM_BOOL LOC4;
			NIM_BOOL LOC6;
			LOC4 = ((*(*result).Name).Sup.Id == (*(*ti).Name).Sup.Id);
			if (!(LOC4)) goto LA5;
			LOC6 = contains_132820(excluding, (*result).Sup.Id);
			LOC4 = !(LOC6);
			LA5: ;
			if (!LOC4) goto LA7;
			goto LA1;
		}
		LA7: ;
		h = nexttry_142196(h, (tab.Data->Sup.len-1));
		{
			if (!(h == start)) goto LA11;
			result = NIM_NIL;
			goto LA1;
		}
		LA11: ;
		result = tab.Data->data[h];
	} LA1: ;
	(*ti).H = nexttry_142196(h, (tab.Data->Sup.len-1));
	{
		NIM_BOOL LOC15;
		LOC15 = !((result == NIM_NIL));
		if (!(LOC15)) goto LA16;
		LOC15 = contains_132820(excluding, (*result).Sup.Id);
		LA16: ;
		if (!LOC15) goto LA17;
		result = NIM_NIL;
	}
	LA17: ;
	return result;
}

N_NIMCALL(tsym135677*, firstidentexcluding_146506)(tidentiter142106* ti, tstrtable135651 tab, tident131018* s, tintset132035* excluding) {
	tsym135677* result;
	result = 0;
	(*ti).H = (*s).H;
	unsureAsgnRef((void**) &(*ti).Name, s);
	{
		if (!(tab.Counter == 0)) goto LA3;
		result = NIM_NIL;
	}
	goto LA1;
	LA3: ;
	{
		result = nextidentexcluding_146471(ti, tab, excluding);
	}
	LA1: ;
	return result;
}

N_NIMCALL(NIM_BOOL, strtableincl_146105)(tstrtable135651* t, tsym135677* n) {
	NIM_BOOL result;
	NI h;
	result = 0;
	h = (NI)((*(*n).Name).H & ((*t).Data->Sup.len-1));
	while (1) {
		tsym135677* it;
		it = (*t).Data->data[h];
		{
			if (!(it == NIM_NIL)) goto LA4;
			goto LA1;
		}
		LA4: ;
		{
			if (!((*(*it).Name).Sup.Id == (*(*n).Name).Sup.Id)) goto LA8;
			asgnRefNoCycle((void**) &(*t).Data->data[h], n);
			result = NIM_TRUE;
			goto BeforeRet;
		}
		LA8: ;
		h = nexttry_142196(h, ((*t).Data->Sup.len-1));
	} LA1: ;
	{
		NIM_BOOL LOC12;
		LOC12 = mustrehash_142191((*t).Data->Sup.len, (*t).Counter);
		if (!LOC12) goto LA13;
		strtableenlarge_146014(t);
		strtablerawinsert_145528(&(*t).Data, n);
	}
	goto LA10;
	LA13: ;
	{
		asgnRefNoCycle((void**) &(*t).Data->data[h], n);
	}
	LA10: ;
	(*t).Counter += 1;
	result = NIM_FALSE;
	BeforeRet: ;
	return result;
}

N_NIMCALL(tnode135647*, skipconvtaketype_142262)(tnode135647* n) {
	tnode135647* result;
	result = 0;
	result = skipconv_142236(n);
	asgnRefNoCycle((void**) &(*result).Typ, (*n).Typ);
	return result;
}

N_NIMCALL(void, symtabreplaceraw_145605)(tsymseq135649** data, tsym135677* prevsym, tsym135677* newsym) {
	NI h;
	h = (NI)((*(*prevsym).Name).H & ((*data)->Sup.len-1));
	while (1) {
		if (!!(((*data)->data[h] == NIM_NIL))) goto LA1;
		{
			if (!((*data)->data[h] == prevsym)) goto LA4;
			asgnRefNoCycle((void**) &(*data)->data[h], newsym);
			goto BeforeRet;
		}
		LA4: ;
		h = nexttry_142196(h, ((*data)->Sup.len-1));
	} LA1: ;
	BeforeRet: ;
}

N_NIMCALL(void, symtabreplace_146005)(tstrtable135651* t, tsym135677* prevsym, tsym135677* newsym) {
	symtabreplaceraw_145605(&(*t).Data, prevsym, newsym);
}

N_NIMCALL(NIM_BOOL, idtablehasobjectaskey_142154)(tidtable135693 t, tidobj131012* key) {
	NIM_BOOL result;
	NI index;
	result = 0;
	index = idtablerawget_146609(t, (*key).Id);
	{
		if (!(0 <= index)) goto LA3;
		result = (t.Data->data[index].Key == key);
	}
	goto LA1;
	LA3: ;
	{
		result = NIM_FALSE;
	}
	LA1: ;
	return result;
}

static N_INLINE(tnode135647*, lastson_136010)(tnode135647* n) {
	tnode135647* result;
	NI LOC1;
	result = 0;
	LOC1 = sonslen_136002(n);
	result = (*n).kindU.S6.Sons->data[(NI64)(LOC1 - 1)];
	return result;
}

N_NIMCALL(tsym135677*, lookupinrecord_142182)(tnode135647* n, tident131018* field) {
	tsym135677* result;
	result = 0;
	result = NIM_NIL;
	switch ((*n).Kind) {
	case ((NU8) 131):
	{
		NI i_142475;
		NI HEX3Atmp_142594;
		NI LOC2;
		NI res_142596;
		i_142475 = 0;
		HEX3Atmp_142594 = 0;
		LOC2 = sonslen_136002(n);
		HEX3Atmp_142594 = (NI64)(LOC2 - 1);
		res_142596 = 0;
		while (1) {
			if (!(res_142596 <= HEX3Atmp_142594)) goto LA3;
			i_142475 = res_142596;
			result = lookupinrecord_142182((*n).kindU.S6.Sons->data[i_142475], field);
			{
				if (!!((result == NIM_NIL))) goto LA6;
				goto BeforeRet;
			}
			LA6: ;
			res_142596 += 1;
		} LA3: ;
	}
	break;
	case ((NU8) 132):
	{
		NI i_142542;
		NI HEX3Atmp_142598;
		NI LOC17;
		NI res_142600;
		{
			if (!!(((*(*n).kindU.S6.Sons->data[0]).Kind == ((NU8) 3)))) goto LA11;
			internalerror_129687((*n).Info, ((NimStringDesc*) &TMP3058));
		}
		LA11: ;
		result = lookupinrecord_142182((*n).kindU.S6.Sons->data[0], field);
		{
			if (!!((result == NIM_NIL))) goto LA15;
			goto BeforeRet;
		}
		LA15: ;
		i_142542 = 0;
		HEX3Atmp_142598 = 0;
		LOC17 = sonslen_136002(n);
		HEX3Atmp_142598 = (NI64)(LOC17 - 1);
		res_142600 = 1;
		while (1) {
			if (!(res_142600 <= HEX3Atmp_142598)) goto LA18;
			i_142542 = res_142600;
			switch ((*(*n).kindU.S6.Sons->data[i_142542]).Kind) {
			case ((NU8) 85):
			case ((NU8) 88):
			{
				tnode135647* LOC20;
				LOC20 = 0;
				LOC20 = lastson_136010((*n).kindU.S6.Sons->data[i_142542]);
				result = lookupinrecord_142182(LOC20, field);
				{
					if (!!((result == NIM_NIL))) goto LA23;
					goto BeforeRet;
				}
				LA23: ;
			}
			break;
			default:
			{
				internalerror_129687((*n).Info, ((NimStringDesc*) &TMP3059));
			}
			break;
			}
			res_142600 += 1;
		} LA18: ;
	}
	break;
	case ((NU8) 3):
	{
		{
			if (!((*(*(*n).kindU.S4.Sym).Name).Sup.Id == (*field).Sup.Id)) goto LA29;
			result = (*n).kindU.S4.Sym;
		}
		LA29: ;
	}
	break;
	default:
	{
		internalerror_129687((*n).Info, ((NimStringDesc*) &TMP3060));
	}
	break;
	}
	BeforeRet: ;
	return result;
}
N_NOINLINE(void, astalgoInit)(void) {
}

N_NOINLINE(void, astalgoDatInit)(void) {
static TNimNode* TMP794[2];
static TNimNode* TMP795[2];
static TNimNode TMP480[6];
NTI142212.size = sizeof(tiitable142212);
NTI142212.kind = 18;
NTI142212.base = 0;
NTI142212.flags = 2;
TMP794[0] = &TMP480[1];
TMP480[1].kind = 1;
TMP480[1].offset = offsetof(tiitable142212, Counter);
TMP480[1].typ = (&NTI105);
TMP480[1].name = "counter";
TMP794[1] = &TMP480[2];
NTI142208.size = sizeof(tiipair142208);
NTI142208.kind = 18;
NTI142208.base = 0;
NTI142208.flags = 3;
TMP795[0] = &TMP480[4];
TMP480[4].kind = 1;
TMP480[4].offset = offsetof(tiipair142208, Key);
TMP480[4].typ = (&NTI105);
TMP480[4].name = "key";
TMP795[1] = &TMP480[5];
TMP480[5].kind = 1;
TMP480[5].offset = offsetof(tiipair142208, Val);
TMP480[5].typ = (&NTI105);
TMP480[5].name = "val";
TMP480[3].len = 2; TMP480[3].kind = 2; TMP480[3].sons = &TMP795[0];
NTI142208.node = &TMP480[3];
NTI142210.size = sizeof(tiipairseq142210*);
NTI142210.kind = 24;
NTI142210.base = (&NTI142208);
NTI142210.flags = 2;
NTI142210.marker = TMP796;
TMP480[2].kind = 1;
TMP480[2].offset = offsetof(tiitable142212, Data);
TMP480[2].typ = (&NTI142210);
TMP480[2].name = "data";
TMP480[0].len = 2; TMP480[0].kind = 2; TMP480[0].sons = &TMP794[0];
NTI142212.node = &TMP480[0];
}

