/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/usr/src/extras/Nimrod/lib -o compiler/nimcache/babelcmd.o compiler/nimcache/babelcmd.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <dirent.h>

#include <sys/types.h>

#include <string.h>

#include <sys/stat.h>

#include <sys/time.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tlineinfo128308 tlineinfo128308;
typedef struct tlinkedlist100017 tlinkedlist100017;
typedef struct tlistentry100011 tlistentry100011;
typedef struct tstringtable103609 tstringtable103609;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tkeyvaluepairseq103607 tkeyvaluepairseq103607;
typedef struct tkeyvaluepair103605 tkeyvaluepair103605;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
struct tlineinfo128308 {
NI16 Line;
NI16 Col;
NI32 Fileindex;
};
struct tlinkedlist100017 {
tlistentry100011* Head;
tlistentry100011* Tail;
NI Counter;
};
typedef NIM_CHAR TY84547[256];
typedef N_NIMCALL_PTR(void, TY891) (void* p, NI op);
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY891 marker;
};
struct TNimObject {
TNimType* m_type;
};
struct tkeyvaluepair103605 {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
struct tstringtable103609 {
  TNimObject Sup;
NI Counter;
tkeyvaluepairseq103607* Data;
NU8 Mode;
};
struct tlistentry100011 {
  TNimObject Sup;
tlistentry100011* Prev;
tlistentry100011* Next;
};
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tkeyvaluepairseq103607 {
  TGenericSeq Sup;
  tkeyvaluepair103605 data[SEQ_DECL_SIZE];
};
N_NIMCALL(NIM_BOOL, contains_100214)(tlinkedlist100017* list, NimStringDesc* data);
N_NIMCALL(void, prependstr_100414)(tlinkedlist100017* list, NimStringDesc* data);
N_NIMCALL(void, addpathrec_158191)(NimStringDesc* dir, tlineinfo128308 info);
N_NIMCALL(tstringtable103609*, nstnewStringTable)(NU8 mode);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NimStringDesc*, HEX2F_94062)(NimStringDesc* head, NimStringDesc* tail);
N_NIMCALL(void, addpackage_158115)(tstringtable103609* packages, NimStringDesc* p);
N_NIMCALL(NI, versionsplitpos_158012)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_63424, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI start);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI first);
N_NIMCALL(NIM_BOOL, HEX3CHEX2E_158045)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NI, npuParseInt)(NimStringDesc* s, NI* number, NI start);
N_NIMCALL(NimStringDesc*, nstGet)(tstringtable103609* t, NimStringDesc* key);
N_NIMCALL(void, nstPut)(tstringtable103609* t, NimStringDesc* key, NimStringDesc* val);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(void, addbabelpath_158141)(NimStringDesc* p, tlineinfo128308 info);
N_NIMCALL(void, message_129680)(tlineinfo128308 info, NU16 msg, NimStringDesc* arg);
STRING_LITERAL(TMP1107, ".", 1);
STRING_LITERAL(TMP1108, "..", 2);
STRING_LITERAL(TMP1109, "head", 4);
extern tlinkedlist100017 searchpaths_105112;
extern NI gverbosity_105116;
extern tlinkedlist100017 lazypaths_105113;

N_NIMCALL(void, addpath_158005)(NimStringDesc* path, tlineinfo128308 info) {
	{
		NIM_BOOL LOC3;
		LOC3 = contains_100214(&searchpaths_105112, path);
		if (!!(LOC3)) goto LA4;
		prependstr_100414(&searchpaths_105112, path);
	}
	LA4: ;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (NI64)((*a).Sup.len * 1));
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, versionsplitpos_158012)(NimStringDesc* s) {
	NI result;
	result = 0;
	result = (NI64)(s->Sup.len - 2);
	while (1) {
		NIM_BOOL LOC2;
		LOC2 = (1 < result);
		if (!(LOC2)) goto LA3;
		LOC2 = (((NU8)(s->data[result])) >= ((NU8)(48)) && ((NU8)(s->data[result])) <= ((NU8)(57)) || ((NU8)(s->data[result])) == ((NU8)(46)));
		LA3: ;
		if (!LOC2) goto LA1;
		result -= 1;
	} LA1: ;
	{
		if (!!(((NU8)(s->data[result]) == (NU8)(45)))) goto LA6;
		result = s->Sup.len;
	}
	LA6: ;
	return result;
}

N_NIMCALL(NIM_BOOL, HEX3CHEX2E_158045)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NI i;
	NI j;
	NI vera;
	NI verb;
	result = 0;
	{
		if (!eqStrings(a, ((NimStringDesc*) &TMP1109))) goto LA3;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA3: ;
	i = 0;
	j = 0;
	vera = 0;
	verb = 0;
	while (1) {
		NI ii;
		NI jj;
		ii = npuParseInt(a, &vera, i);
		jj = npuParseInt(b, &verb, j);
		{
			NIM_BOOL LOC8;
			LOC8 = (ii <= 0);
			if (LOC8) goto LA9;
			LOC8 = (jj <= 0);
			LA9: ;
			if (!LOC8) goto LA10;
			result = (0 < jj);
			goto BeforeRet;
		}
		LA10: ;
		{
			if (!(vera < verb)) goto LA14;
			result = NIM_TRUE;
			goto BeforeRet;
		}
		goto LA12;
		LA14: ;
		{
			if (!(verb < vera)) goto LA17;
			result = NIM_FALSE;
			goto BeforeRet;
		}
		goto LA12;
		LA17: ;
		LA12: ;
		i += ii;
		j += jj;
		{
			if (!((NU8)(a->data[i]) == (NU8)(46))) goto LA21;
			i += 1;
		}
		LA21: ;
		{
			if (!((NU8)(b->data[j]) == (NU8)(46))) goto LA25;
			j += 1;
		}
		LA25: ;
	}
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, addpackage_158115)(tstringtable103609* packages, NimStringDesc* p) {
	NI x;
	NimStringDesc* name;
	x = versionsplitpos_158012(p);
	name = copyStrLast(p, 0, (NI64)(x - 1));
	{
		NimStringDesc* version;
		if (!(x < p->Sup.len)) goto LA3;
		version = copyStr(p, (NI64)(x + 1));
		{
			NimStringDesc* LOC7;
			NIM_BOOL LOC8;
			LOC7 = 0;
			LOC7 = nstGet(packages, name);
			LOC8 = HEX3CHEX2E_158045(LOC7, version);
			if (!LOC8) goto LA9;
			nstPut(packages, name, version);
		}
		LA9: ;
	}
	goto LA1;
	LA3: ;
	{
		nstPut(packages, name, ((NimStringDesc*) &TMP1109));
	}
	LA1: ;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) (&(*dest).data[((*dest).Sup.len)- 0])), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI64)((*dest).Sup.len + 1))- 0] = 0;
	(*dest).Sup.len += 1;
}

N_NIMCALL(void, addbabelpath_158141)(NimStringDesc* p, tlineinfo128308 info) {
	{
		NIM_BOOL LOC3;
		LOC3 = contains_100214(&searchpaths_105112, p);
		if (!!(LOC3)) goto LA4;
		{
			if (!(1 <= gverbosity_105116)) goto LA8;
			message_129680(info, ((NU16) 256), p);
		}
		LA8: ;
		prependstr_100414(&lazypaths_105113, p);
	}
	LA4: ;
}

N_NIMCALL(void, addpathrec_158191)(NimStringDesc* dir, tlineinfo128308 info) {
	tstringtable103609* packages;
	NI pos;
	NU8 k_158219;
	NimStringDesc* p_158220;
	DIR* d_158229;
	NimStringDesc* p_158227;
	NimStringDesc* key_158239;
	NimStringDesc* val_158241;
	NI h_158243;
	NI HEX3Atmp_158245;
	NI res_158247;
	packages = nstnewStringTable(((NU8) 2));
	pos = (NI64)(dir->Sup.len - 1);
	{
		if (!(((NU8)(dir->data[pos])) == ((NU8)(47)) || ((NU8)(dir->data[pos])) == ((NU8)(47)))) goto LA3;
		pos += 1;
	}
	LA3: ;
	k_158219 = 0;
	p_158220 = 0;
	d_158229 = opendir(dir->data);
	{
		int LOC41;
		if (!!((d_158229 == NIM_NIL))) goto LA7;
		while (1) {
			struct dirent* x_158231;
			NimStringDesc* y_158233;
			x_158231 = readdir(d_158229);
			{
				if (!(x_158231 == NIM_NIL)) goto LA12;
				goto LA9;
			}
			LA12: ;
			y_158233 = cstrToNimstr(((NCSTRING) ((*x_158231).d_name)));
			{
				NIM_BOOL LOC16;
				struct stat s_158235;
				NU8 k_158237;
				LOC16 = !(eqStrings(y_158233, ((NimStringDesc*) &TMP1107)));
				if (!(LOC16)) goto LA17;
				LOC16 = !(eqStrings(y_158233, ((NimStringDesc*) &TMP1108)));
				LA17: ;
				if (!LOC16) goto LA18;
				memset((void*)&s_158235, 0, sizeof(s_158235));
				y_158233 = HEX2F_94062(dir, y_158233);
				{
					int LOC22;
					LOC22 = lstat(y_158233->data, &s_158235);
					if (!(LOC22 < ((NI32) 0))) goto LA23;
					goto LA9;
				}
				LA23: ;
				k_158237 = ((NU8) 0);
				{
					NIM_BOOL LOC27;
					LOC27 = S_ISDIR(s_158235.st_mode);
					if (!LOC27) goto LA28;
					k_158237 = ((NU8) 2);
				}
				LA28: ;
				{
					NIM_BOOL LOC32;
					LOC32 = S_ISLNK(s_158235.st_mode);
					if (!LOC32) goto LA33;
					k_158237 = k_158237 + 1;
				}
				LA33: ;
				k_158219 = k_158237;
				p_158220 = y_158233;
				{
					NIM_BOOL LOC37;
					LOC37 = (k_158219 == ((NU8) 2));
					if (!(LOC37)) goto LA38;
					LOC37 = !(((NU8)(p_158220->data[pos]) == (NU8)(46)));
					LA38: ;
					if (!LOC37) goto LA39;
					addpackage_158115(packages, p_158220);
				}
				LA39: ;
			}
			LA18: ;
		} LA9: ;
		LOC41 = closedir(d_158229);
	}
	LA7: ;
	p_158227 = 0;
	key_158239 = 0;
	val_158241 = 0;
	h_158243 = 0;
	HEX3Atmp_158245 = 0;
	HEX3Atmp_158245 = ((*packages).Data->Sup.len-1);
	res_158247 = 0;
	while (1) {
		if (!(res_158247 <= HEX3Atmp_158245)) goto LA42;
		h_158243 = res_158247;
		{
			NimStringDesc* res_158249;
			if (!!((*packages).Data->data[h_158243].Field0 == 0)) goto LA45;
			key_158239 = (*packages).Data->data[h_158243].Field0;
			val_158241 = (*packages).Data->data[h_158243].Field1;
			{
				if (!eqStrings(val_158241, ((NimStringDesc*) &TMP1109))) goto LA49;
				res_158249 = key_158239;
			}
			goto LA47;
			LA49: ;
			{
				NimStringDesc* LOC52;
				LOC52 = 0;
				LOC52 = rawNewString(key_158239->Sup.len + val_158241->Sup.len + 1);
appendString(LOC52, key_158239);
appendChar(LOC52, 45);
appendString(LOC52, val_158241);
				res_158249 = LOC52;
			}
			LA47: ;
			p_158227 = res_158249;
			addbabelpath_158141(p_158227, info);
		}
		LA45: ;
		res_158247 += 1;
	} LA42: ;
}

N_NIMCALL(void, babelpath_158254)(NimStringDesc* path, tlineinfo128308 info) {
	addpathrec_158191(path, info);
	addbabelpath_158141(path, info);
}
N_NOINLINE(void, babelcmdInit)(void) {
}

N_NOINLINE(void, babelcmdDatInit)(void) {
}

