/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/usr/src/extras/Nimrod/lib -o compiler/nimcache/bitsets.o compiler/nimcache/bitsets.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct tbitset219008 tbitset219008;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef N_NIMCALL_PTR(void, TY891) (void* p, NI op);
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY891 marker;
};
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tbitset219008 {
  TGenericSeq Sup;
  NI8 data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, TMP2472)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
extern TNimType NTI107; /* int8 */
TNimType NTI219008; /* TBitSet */
N_NIMCALL(void, TMP2472)(void* p, NI op) {
	tbitset219008* a;
	NI LOC1;
	a = (tbitset219008*)p;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	}
}

N_NIMCALL(void, bitsetinit_219013)(tbitset219008** b, NI length) {
	unsureAsgnRef((void**) &(*b), (tbitset219008*) newSeq((&NTI219008), length));
}

N_NIMCALL(void, bitsetincl_219043)(tbitset219008** x, NI64 elem) {
	(*x)->data[(NI64)(elem / 8)] = (NI8)((*x)->data[(NI64)(elem / 8)] | ((NI8)(NU8)(NU)((NI)((NU64)(1) << (NU64)(((NI) ((NI64)(elem % 8))))))));
}

N_NIMCALL(NIM_BOOL, bitsetcontains_219065)(tbitset219008* x, tbitset219008* y) {
	NIM_BOOL result;
	NI i_219351;
	NI HEX3Atmp_219352;
	NI res_219354;
	result = 0;
	i_219351 = 0;
	HEX3Atmp_219352 = 0;
	HEX3Atmp_219352 = (x->Sup.len-1);
	res_219354 = 0;
	while (1) {
		if (!(res_219354 <= HEX3Atmp_219352)) goto LA1;
		i_219351 = res_219354;
		{
			if (!!(((NI8)(x->data[i_219351] & (NI8)((NU8) ~(y->data[i_219351]))) == ((NI8) 0)))) goto LA4;
			result = NIM_FALSE;
			goto BeforeRet;
		}
		LA4: ;
		res_219354 += 1;
	} LA1: ;
	result = NIM_TRUE;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NIM_BOOL, bitsetequals_219060)(tbitset219008* x, tbitset219008* y) {
	NIM_BOOL result;
	NI i_219330;
	NI HEX3Atmp_219331;
	NI res_219333;
	result = 0;
	i_219330 = 0;
	HEX3Atmp_219331 = 0;
	HEX3Atmp_219331 = (x->Sup.len-1);
	res_219333 = 0;
	while (1) {
		if (!(res_219333 <= HEX3Atmp_219331)) goto LA1;
		i_219330 = res_219333;
		{
			if (!!((x->data[i_219330] == y->data[i_219330]))) goto LA4;
			result = NIM_FALSE;
			goto BeforeRet;
		}
		LA4: ;
		res_219333 += 1;
	} LA1: ;
	result = NIM_TRUE;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, bitsetunion_219019)(tbitset219008** x, tbitset219008* y) {
	NI i_219246;
	NI HEX3Atmp_219247;
	NI res_219249;
	i_219246 = 0;
	HEX3Atmp_219247 = 0;
	HEX3Atmp_219247 = ((*x)->Sup.len-1);
	res_219249 = 0;
	while (1) {
		if (!(res_219249 <= HEX3Atmp_219247)) goto LA1;
		i_219246 = res_219249;
		(*x)->data[i_219246] = (NI8)((*x)->data[i_219246] | y->data[i_219246]);
		res_219249 += 1;
	} LA1: ;
}

N_NIMCALL(void, bitsetdiff_219025)(tbitset219008** x, tbitset219008* y) {
	NI i_219267;
	NI HEX3Atmp_219268;
	NI res_219270;
	i_219267 = 0;
	HEX3Atmp_219268 = 0;
	HEX3Atmp_219268 = ((*x)->Sup.len-1);
	res_219270 = 0;
	while (1) {
		if (!(res_219270 <= HEX3Atmp_219268)) goto LA1;
		i_219267 = res_219270;
		(*x)->data[i_219267] = (NI8)((*x)->data[i_219267] & (NI8)((NU8) ~(y->data[i_219267])));
		res_219270 += 1;
	} LA1: ;
}

N_NIMCALL(void, bitsetsymdiff_219031)(tbitset219008** x, tbitset219008* y) {
	NI i_219288;
	NI HEX3Atmp_219289;
	NI res_219291;
	i_219288 = 0;
	HEX3Atmp_219289 = 0;
	HEX3Atmp_219289 = ((*x)->Sup.len-1);
	res_219291 = 0;
	while (1) {
		if (!(res_219291 <= HEX3Atmp_219289)) goto LA1;
		i_219288 = res_219291;
		(*x)->data[i_219288] = (NI8)((*x)->data[i_219288] ^ y->data[i_219288]);
		res_219291 += 1;
	} LA1: ;
}

N_NIMCALL(void, bitsetintersect_219037)(tbitset219008** x, tbitset219008* y) {
	NI i_219309;
	NI HEX3Atmp_219310;
	NI res_219312;
	i_219309 = 0;
	HEX3Atmp_219310 = 0;
	HEX3Atmp_219310 = ((*x)->Sup.len-1);
	res_219312 = 0;
	while (1) {
		if (!(res_219312 <= HEX3Atmp_219310)) goto LA1;
		i_219309 = res_219312;
		(*x)->data[i_219309] = (NI8)((*x)->data[i_219309] & y->data[i_219309]);
		res_219312 += 1;
	} LA1: ;
}

N_NIMCALL(NIM_BOOL, bitsetin_219055)(tbitset219008* x, NI64 e) {
	NIM_BOOL result;
	result = 0;
	result = !(((NI8)(x->data[(NI64)(e / 8)] & ((NI8)(NU8)(NU)((NI)((NU64)(1) << (NU64)(((NI) ((NI64)(e % 8)))))))) == ((NI8) 0)));
	return result;
}
N_NOINLINE(void, bitsetsInit)(void) {
}

N_NOINLINE(void, bitsetsDatInit)(void) {
NTI219008.size = sizeof(tbitset219008*);
NTI219008.kind = 24;
NTI219008.base = (&NTI107);
NTI219008.flags = 2;
NTI219008.marker = TMP2472;
}

