/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/usr/src/extras/Nimrod/lib -o compiler/nimcache/ccgmerge.o compiler/nimcache/ccgmerge.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>

#include <stdio.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tcgen343028 tcgen343028;
typedef struct tllstream182205 tllstream182205;
typedef struct tbaselexer183018 tbaselexer183018;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tidtable135693 tidtable135693;
typedef struct tidobj131012 tidobj131012;
typedef struct ttype135681 ttype135681;
typedef struct ttypeseq135679 ttypeseq135679;
typedef struct tnode135647 tnode135647;
typedef struct tsym135677 tsym135677;
typedef struct tloc135661 tloc135661;
typedef struct trope126007 trope126007;
typedef struct tpasscontext224003 tpasscontext224003;
typedef struct tidpairseq135691 tidpairseq135691;
typedef struct tidpair135689 tidpair135689;
typedef struct tintset132035 tintset132035;
typedef struct ttrunk132031 ttrunk132031;
typedef struct ttrunkseq132033 ttrunkseq132033;
typedef struct tlinkedlist100017 tlinkedlist100017;
typedef struct tlistentry100011 tlistentry100011;
typedef struct tcproc343024 tcproc343024;
typedef struct tnodetable135705 tnodetable135705;
typedef struct tnodepairseq135703 tnodepairseq135703;
typedef struct tnodepair135701 tnodepair135701;
typedef struct tsymseq135649 tsymseq135649;
typedef struct tnodeseq135641 tnodeseq135641;
typedef struct TY343089 TY343089;
typedef struct tblock343022 tblock343022;
typedef struct tmergesections344838 tmergesections344838;
typedef struct tcell38449 tcell38449;
typedef struct tcellseq38465 tcellseq38465;
typedef struct tgcheap40416 tgcheap40416;
typedef struct tcellset38461 tcellset38461;
typedef struct tpagedesc38457 tpagedesc38457;
typedef struct tmemregion22010 tmemregion22010;
typedef struct tsmallchunk21243 tsmallchunk21243;
typedef struct tllchunk22004 tllchunk22004;
typedef struct tbigchunk21245 tbigchunk21245;
typedef struct tintset21218 tintset21218;
typedef struct ttrunk21214 ttrunk21214;
typedef struct tavlnode22008 tavlnode22008;
typedef struct tgcstat40414 tgcstat40414;
typedef struct tlineinfo128308 tlineinfo128308;
typedef struct tident131018 tident131018;
typedef struct TY135771 TY135771;
typedef struct tinstantiation135667 tinstantiation135667;
typedef struct tscope135671 tscope135671;
typedef struct tstrtable135651 tstrtable135651;
typedef struct tlib135665 tlib135665;
typedef struct tbasechunk21241 tbasechunk21241;
typedef struct tfreecell21233 tfreecell21233;
typedef struct TY135763 TY135763;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
typedef N_NIMCALL_PTR(void, TY891) (void* p, NI op);
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY891 marker;
};
struct TNimObject {
TNimType* m_type;
};
struct tbaselexer183018 {
  TNimObject Sup;
NI Bufpos;
NCSTRING Buf;
NI Buflen;
tllstream182205* Stream;
NI Linenumber;
NI Sentinel;
NI Linestart;
};
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tidobj131012 {
  TNimObject Sup;
NI Id;
};
struct tloc135661 {
NU8 K;
NU8 S;
NU8 Flags;
ttype135681* T;
trope126007* R;
trope126007* Heaproot;
NI A;
};
struct ttype135681 {
  tidobj131012 Sup;
NU8 Kind;
NU8 Callconv;
NU32 Flags;
ttypeseq135679* Sons;
tnode135647* N;
tsym135677* Destructor;
tsym135677* Owner;
tsym135677* Sym;
NI64 Size;
NI Align;
tloc135661 Loc;
};
struct tpasscontext224003 {
  TNimObject Sup;
NIM_BOOL Fromcache;
};
typedef trope126007* tcfilesections343012[18];
struct tidpair135689 {
tidobj131012* Key;
TNimObject* Val;
};
struct tidtable135693 {
NI Counter;
tidpairseq135691* Data;
};
struct tintset132035 {
NI Counter;
NI Max;
ttrunk132031* Head;
ttrunkseq132033* Data;
};
struct tlinkedlist100017 {
tlistentry100011* Head;
tlistentry100011* Tail;
NI Counter;
};
struct tnodepair135701 {
NI H;
tnode135647* Key;
NI Val;
};
struct tnodetable135705 {
NI Counter;
tnodepairseq135703* Data;
};
typedef trope126007* TY343122[10];
struct tcgen343028 {
  tpasscontext224003 Sup;
tsym135677* Module;
NimStringDesc* Filename;
tcfilesections343012 S;
NIM_BOOL Preventstacktrace;
NIM_BOOL Usesthreadvars;
NIM_BOOL Framedeclared;
NIM_BOOL Isheaderfile;
NimStringDesc* Cfilename;
tidtable135693 Typecache;
tidtable135693 Forwtypecache;
tintset132035 Declaredthings;
tintset132035 Declaredprotos;
tlinkedlist100017 Headerfiles;
tintset132035 Typeinfomarker;
tcproc343024* Initproc;
tcproc343024* Preinitproc;
ttypeseq135679* Typestack;
tnodetable135705 Datacache;
tsymseq135649* Forwardedprocs;
NI Typenodes;
NI Nimtypes;
trope126007* Typenodesname;
trope126007* Nimtypesname;
NI Labels;
TY343122 Extensionloaders;
};
typedef trope126007* tcprocsections343016[3];
struct tblock343022 {
NI Id;
trope126007* Label;
tcprocsections343016 Sections;
NIM_BOOL Isloop;
NI16 Nestedtrystmts;
NI16 Framelen;
};
struct tcproc343024 {
tsym135677* Prc;
NIM_BOOL Beforeretneeded;
NIM_BOOL Threadvaraccessed;
tnodeseq135641* Nestedtrystmts;
NI Inexceptblock;
NI Labels;
TY343089* Blocks;
NI Breakidx;
NU32 Options;
NI Maxframelen;
tcgen343028* Module;
NI Withinloop;
NI Gcframeid;
trope126007* Gcframetype;
};
struct tmergesections344838 {
tcfilesections343012 F;
tcprocsections343016 P;
};
typedef NimStringDesc* TY344007[18];
typedef NimStringDesc* TY344012[3];
struct tcell38449 {
NI Refcount;
TNimType* Typ;
};
struct tcellseq38465 {
NI Len;
NI Cap;
tcell38449** D;
};
struct tcellset38461 {
NI Counter;
NI Max;
tpagedesc38457* Head;
tpagedesc38457** Data;
};
typedef tsmallchunk21243* TY22022[512];
typedef ttrunk21214* ttrunkbuckets21216[256];
struct tintset21218 {
ttrunkbuckets21216 Data;
};
struct tmemregion22010 {
NI Minlargeobj;
NI Maxlargeobj;
TY22022 Freesmallchunks;
tllchunk22004* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk21245* Freechunkslist;
tintset21218 Chunkstarts;
tavlnode22008* Root;
tavlnode22008* Deleted;
tavlnode22008* Last;
tavlnode22008* Freeavlnodes;
};
struct tgcstat40414 {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct tgcheap40416 {
void* Stackbottom;
NI Cyclethreshold;
tcellseq38465 Zct;
tcellseq38465 Decstack;
tcellset38461 Cycleroots;
tcellseq38465 Tempstack;
NI Recgclock;
tmemregion22010 Region;
tgcstat40414 Stat;
};
typedef NI TY21221[8];
struct ttrunk132031 {
ttrunk132031* Next;
NI Key;
TY21221 Bits;
};
struct tllstream182205 {
  TNimObject Sup;
NU8 Kind;
FILE* F;
NimStringDesc* S;
NI Rd;
NI Wr;
NI Lineoffset;
};
struct tlineinfo128308 {
NI16 Line;
NI16 Col;
NI32 Fileindex;
};
struct tnode135647 {
ttype135681* Typ;
tlineinfo128308 Info;
NU8 Flags;
NU8 Kind;
union {
struct {NI64 Intval;
} S1;
struct {NF64 Floatval;
} S2;
struct {NimStringDesc* Strval;
} S3;
struct {tsym135677* Sym;
} S4;
struct {tident131018* Ident;
} S5;
struct {tnodeseq135641* Sons;
} S6;
} kindU;
NimStringDesc* Comment;
};
struct tstrtable135651 {
NI Counter;
tsymseq135649* Data;
};
struct tsym135677 {
  tidobj131012 Sup;
NU8 Kind;
union {
struct {ttypeseq135679* Typeinstcache;
} S1;
struct {TY135771* Procinstcache;
tscope135671* Scope;
} S2;
struct {TY135771* Usedgenerics;
tstrtable135651 Tab;
} S3;
} kindU;
NU16 Magic;
ttype135681* Typ;
tident131018* Name;
tlineinfo128308 Info;
tsym135677* Owner;
NU32 Flags;
tnode135647* Ast;
NU32 Options;
NI Position;
NI Offset;
tloc135661 Loc;
tlib135665* Annex;
tnode135647* Constraint;
};
struct trope126007 {
  TNimObject Sup;
trope126007* Left;
trope126007* Right;
NI Length;
NimStringDesc* Data;
};
struct tlistentry100011 {
  TNimObject Sup;
tlistentry100011* Prev;
tlistentry100011* Next;
};
struct tpagedesc38457 {
tpagedesc38457* Next;
NI Key;
TY21221 Bits;
};
struct tbasechunk21241 {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct tsmallchunk21243 {
  tbasechunk21241 Sup;
tsmallchunk21243* Next;
tsmallchunk21243* Prev;
tfreecell21233* Freelist;
NI Free;
NI Acc;
NF64 Data;
};
struct tllchunk22004 {
NI Size;
NI Acc;
tllchunk22004* Next;
};
struct tbigchunk21245 {
  tbasechunk21241 Sup;
tbigchunk21245* Next;
tbigchunk21245* Prev;
NI Align;
NF64 Data;
};
struct ttrunk21214 {
ttrunk21214* Next;
NI Key;
TY21221 Bits;
};
typedef tavlnode22008* TY22014[2];
struct tavlnode22008 {
TY22014 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct tident131018 {
  tidobj131012 Sup;
NimStringDesc* S;
tident131018* Next;
NI H;
};
struct tinstantiation135667 {
tsym135677* Sym;
ttypeseq135679* Concretetypes;
TY135763* Usedby;
};
struct tscope135671 {
NI Depthlevel;
tstrtable135651 Symbols;
tscope135671* Parent;
};
struct tlib135665 {
  tlistentry100011 Sup;
NU8 Kind;
NIM_BOOL Generated;
NIM_BOOL Isoverriden;
trope126007* Name;
tnode135647* Path;
};
struct tfreecell21233 {
tfreecell21233* Next;
NI Zerofield;
};
struct ttypeseq135679 {
  TGenericSeq Sup;
  ttype135681* data[SEQ_DECL_SIZE];
};
struct tidpairseq135691 {
  TGenericSeq Sup;
  tidpair135689 data[SEQ_DECL_SIZE];
};
struct ttrunkseq132033 {
  TGenericSeq Sup;
  ttrunk132031* data[SEQ_DECL_SIZE];
};
struct tnodepairseq135703 {
  TGenericSeq Sup;
  tnodepair135701 data[SEQ_DECL_SIZE];
};
struct tsymseq135649 {
  TGenericSeq Sup;
  tsym135677* data[SEQ_DECL_SIZE];
};
struct tnodeseq135641 {
  TGenericSeq Sup;
  tnode135647* data[SEQ_DECL_SIZE];
};
struct TY343089 {
  TGenericSeq Sup;
  tblock343022 data[SEQ_DECL_SIZE];
};
struct TY135771 {
  TGenericSeq Sup;
  tinstantiation135667* data[SEQ_DECL_SIZE];
};
struct TY135763 {
  TGenericSeq Sup;
  NI32 data[SEQ_DECL_SIZE];
};
N_NIMCALL(tllstream182205*, llstreamopen_182228)(NimStringDesc* filename, NU8 mode);
N_NIMCALL(void, openbaselexer_183027)(tbaselexer183018* l, tllstream182205* inputstream, NI buflen);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
N_NIMCALL(void, skipuntilcmd_344258)(tbaselexer183018* l);
N_NIMCALL(NI, handlecr_183051)(tbaselexer183018* l, NI pos);
N_NIMCALL(NI, handlelf_183057)(tbaselexer183018* l, NI pos);
N_NIMCALL(void, readkey_344438)(tbaselexer183018* l, NimStringDesc** result);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newlen);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(void, internalerror_129699)(NimStringDesc* errmsg);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(void, processmergeinfo_344575)(tbaselexer183018* l, tcgen343028* m);
N_NIMCALL(void, skipwhite_344238)(tbaselexer183018* l);
N_NIMCALL(void, readtypecache_344491)(tbaselexer183018* l, tidtable135693* result);
N_NIMCALL(NI, decodevint_141251)(NCSTRING s, NI* pos);
N_NIMCALL(NimStringDesc*, decodestr_141104)(NCSTRING s, NI* pos);
N_NIMCALL(void, idtableput_142147)(tidtable135693* t, tidobj131012* key, TNimObject* val);
N_NIMCALL(ttype135681*, newfaketype_344470)(NI id);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(trope126007*, torope_126058)(NimStringDesc* s);
N_NIMCALL(void, readintset_344540)(tbaselexer183018* l, tintset132035* result);
N_NIMCALL(void, incl_132842)(tintset132035* s, NI key);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(void, closebaselexer_183036)(tbaselexer183018* l);
static N_INLINE(trope126007**, s_343159)(tcproc343024* p, NU8 s);
N_NIMCALL(void, readmergesections_344843)(NimStringDesc* cfilename, tmergesections344838* m);
N_NIMCALL(trope126007*, readverbatimsection_344401)(tbaselexer183018* l);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NIM_BOOL, atendmark_344302)(NCSTRING buf, NI pos);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(trope126007*, con_126020)(trope126007* a, trope126007* b);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell38449*, usrtocell_41843)(void* usr);
static N_INLINE(void, rtladdzct_43002)(tcell38449* c);
N_NOINLINE(void, addzct_41815)(tcellseq38465* s, tcell38449* c);
N_NIMCALL(void, app_126046)(trope126007** a, NimStringDesc* b);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(void, writetypecache_344146)(tidtable135693 a, NimStringDesc** s);
N_NIMCALL(void, encodevint_141226)(NI x, NimStringDesc** result);
N_NIMCALL(void, encodestr_141025)(NimStringDesc* s, NimStringDesc** result);
N_NIMCALL(NimStringDesc*, ropetostr_126075)(trope126007* p);
N_NIMCALL(void, writeintset_344175)(tintset132035* a, NimStringDesc** s);
static N_INLINE(NI, find_344884)(TY344007 a, NimStringDesc* item);
static N_INLINE(NI, find_344959)(TY344012 a, NimStringDesc* item);
STRING_LITERAL(TMP3465, "ccgmerge: \':\' expected", 22);
STRING_LITERAL(TMP3466, "NIM_merge_INFO", 14);
STRING_LITERAL(TMP3467, "typeCache", 9);
STRING_LITERAL(TMP3468, "declared", 8);
STRING_LITERAL(TMP3469, "typeInfo", 8);
STRING_LITERAL(TMP3470, "labels", 6);
STRING_LITERAL(TMP3471, "hasframe", 8);
STRING_LITERAL(TMP3472, "ccgmerge: \'{\' expected", 22);
STRING_LITERAL(TMP3473, "ccgmerge: unkown key: ", 22);
STRING_LITERAL(TMP3538, "ccgmerge: expected: /*\011NIM_merge_END:*/", 39);
STRING_LITERAL(TMP3539, "/*\011NIM_merge_END:*/", 19);
STRING_LITERAL(TMP3540, "", 0);
STRING_LITERAL(TMP3541, "NIM_merge_HEADERS", 17);
STRING_LITERAL(TMP3542, "NIM_merge_FORWARD_TYPES", 23);
STRING_LITERAL(TMP3543, "NIM_merge_TYPES", 15);
STRING_LITERAL(TMP3544, "NIM_merge_SEQ_TYPES", 19);
STRING_LITERAL(TMP3545, "NIM_merge_FIELD_INFO", 20);
STRING_LITERAL(TMP3546, "NIM_merge_TYPE_INFO", 19);
STRING_LITERAL(TMP3547, "NIM_merge_PROC_HEADERS", 22);
STRING_LITERAL(TMP3548, "NIM_merge_DATA", 14);
STRING_LITERAL(TMP3549, "NIM_merge_VARS", 14);
STRING_LITERAL(TMP3550, "NIM_merge_PROCS", 15);
STRING_LITERAL(TMP3551, "NIM_merge_INIT_PROC", 19);
STRING_LITERAL(TMP3552, "NIM_merge_TYPE_INIT1", 20);
STRING_LITERAL(TMP3553, "NIM_merge_TYPE_INIT2", 20);
STRING_LITERAL(TMP3554, "NIM_merge_TYPE_INIT3", 20);
STRING_LITERAL(TMP3555, "NIM_merge_DEBUG_INIT", 20);
STRING_LITERAL(TMP3556, "NIM_merge_DYNLIB_INIT", 21);
STRING_LITERAL(TMP3557, "NIM_merge_DYNLIB_DEINIT", 23);
NIM_CONST TY344007 cfilesectionnames_344006 = {((NimStringDesc*) &TMP3540),
((NimStringDesc*) &TMP3541),
((NimStringDesc*) &TMP3542),
((NimStringDesc*) &TMP3543),
((NimStringDesc*) &TMP3544),
((NimStringDesc*) &TMP3545),
((NimStringDesc*) &TMP3546),
((NimStringDesc*) &TMP3547),
((NimStringDesc*) &TMP3548),
((NimStringDesc*) &TMP3549),
((NimStringDesc*) &TMP3550),
((NimStringDesc*) &TMP3551),
((NimStringDesc*) &TMP3552),
((NimStringDesc*) &TMP3553),
((NimStringDesc*) &TMP3554),
((NimStringDesc*) &TMP3555),
((NimStringDesc*) &TMP3556),
((NimStringDesc*) &TMP3557)}
;
STRING_LITERAL(TMP3558, "NIM_merge_PROC_LOCALS", 21);
STRING_LITERAL(TMP3559, "NIM_merge_PROC_INIT", 19);
STRING_LITERAL(TMP3560, "NIM_merge_PROC_BODY", 19);
NIM_CONST TY344012 cprocsectionnames_344011 = {((NimStringDesc*) &TMP3558),
((NimStringDesc*) &TMP3559),
((NimStringDesc*) &TMP3560)}
;
STRING_LITERAL(TMP3561, "ccgmerge: unknown section: ", 27);
STRING_LITERAL(TMP3562, "ccgmerge: \'*/\' expected", 23);
STRING_LITERAL(TMP3567, "/*\011", 3);
STRING_LITERAL(TMP3568, ":*/", 3);
STRING_LITERAL(TMP3577, "/*\011NIM_merge_INFO:", 18);
STRING_LITERAL(TMP3578, "typeCache:{", 11);
STRING_LITERAL(TMP3579, "declared:{", 10);
STRING_LITERAL(TMP3580, "typeInfo:{", 10);
STRING_LITERAL(TMP3581, "labels:", 7);
STRING_LITERAL(TMP3582, " hasframe:", 10);
STRING_LITERAL(TMP3583, "*/", 2);
extern TNimType NTI183018; /* TBaseLexer */
extern TNimType NTI135643; /* PType */
extern TNimType NTI135681; /* TType */
extern NimStringDesc* tnl_123580;
extern tgcheap40416 gch_40442;
extern NU32 gglobaloptions_105108;

N_NIMCALL(void, skipuntilcmd_344258)(tbaselexer183018* l) {
	NI pos;
	pos = (*l).Bufpos;
	while (1) {
		switch (((NU8)((*l).Buf[pos]))) {
		case 13:
		{
			pos = handlecr_183051(l, pos);
		}
		break;
		case 10:
		{
			pos = handlelf_183057(l, pos);
		}
		break;
		case 0:
		{
			goto LA1;
		}
		break;
		case 47:
		{
			{
				NIM_BOOL LOC8;
				LOC8 = ((NU8)((*l).Buf[(NI64)(pos + 1)]) == (NU8)(42));
				if (!(LOC8)) goto LA9;
				LOC8 = ((NU8)((*l).Buf[(NI64)(pos + 2)]) == (NU8)(9));
				LA9: ;
				if (!LOC8) goto LA10;
				pos += 3;
				goto LA1;
			}
			LA10: ;
			pos += 1;
		}
		break;
		default:
		{
			pos += 1;
		}
		break;
		}
	} LA1: ;
	(*l).Bufpos = pos;
}

N_NIMCALL(void, readkey_344438)(tbaselexer183018* l, NimStringDesc** result) {
	NI pos;
	NCSTRING buf;
	pos = (*l).Bufpos;
	buf = (*l).Buf;
	(*result) = setLengthStr((*result), 0);
	while (1) {
		if (!(((NU8)(buf[pos])) >= ((NU8)(97)) && ((NU8)(buf[pos])) <= ((NU8)(122)) || ((NU8)(buf[pos])) >= ((NU8)(65)) && ((NU8)(buf[pos])) <= ((NU8)(90)) || ((NU8)(buf[pos])) >= ((NU8)(48)) && ((NU8)(buf[pos])) <= ((NU8)(57)) || ((NU8)(buf[pos])) == ((NU8)(95)))) goto LA1;
		(*result) = addChar((*result), buf[pos]);
		pos += 1;
	} LA1: ;
	{
		if (!!(((NU8)(buf[pos]) == (NU8)(58)))) goto LA4;
		internalerror_129699(((NimStringDesc*) &TMP3465));
	}
	LA4: ;
	(*l).Bufpos = (NI64)(pos + 1);
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (NI64)((*a).Sup.len * 1));
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, skipwhite_344238)(tbaselexer183018* l) {
	NI pos;
	pos = (*l).Bufpos;
	while (1) {
		switch (((NU8)((*l).Buf[pos]))) {
		case 13:
		{
			pos = handlecr_183051(l, pos);
		}
		break;
		case 10:
		{
			pos = handlelf_183057(l, pos);
		}
		break;
		case 32:
		{
			pos += 1;
		}
		break;
		default:
		{
			goto LA1;
		}
		break;
		}
	} LA1: ;
	(*l).Bufpos = pos;
}

N_NIMCALL(ttype135681*, newfaketype_344470)(NI id) {
	ttype135681* result;
	result = 0;
	result = (ttype135681*) newObj((&NTI135643), sizeof(ttype135681));
	(*result).Sup.Sup.m_type = (&NTI135681);
	(*result).Sup.Id = id;
	return result;
}

N_NIMCALL(void, readtypecache_344491)(tbaselexer183018* l, tidtable135693* result) {
	{
		if (!!(((NU8)((*l).Buf[(*l).Bufpos]) == (NU8)(123)))) goto LA3;
		internalerror_129699(((NimStringDesc*) &TMP3472));
	}
	LA3: ;
	(*l).Bufpos += 1;
	while (1) {
		NI key;
		NimStringDesc* value;
		ttype135681* LOC10;
		trope126007* LOC11;
		if (!!(((NU8)((*l).Buf[(*l).Bufpos]) == (NU8)(125)))) goto LA5;
		skipwhite_344238(l);
		key = decodevint_141251((*l).Buf, &(*l).Bufpos);
		{
			if (!!(((NU8)((*l).Buf[(*l).Bufpos]) == (NU8)(58)))) goto LA8;
			internalerror_129699(((NimStringDesc*) &TMP3465));
		}
		LA8: ;
		(*l).Bufpos += 1;
		value = decodestr_141104((*l).Buf, &(*l).Bufpos);
		LOC10 = 0;
		LOC10 = newfaketype_344470(key);
		LOC11 = 0;
		LOC11 = torope_126058(value);
		idtableput_142147(result, &LOC10->Sup, &LOC11->Sup);
	} LA5: ;
	(*l).Bufpos += 1;
}

N_NIMCALL(void, readintset_344540)(tbaselexer183018* l, tintset132035* result) {
	{
		if (!!(((NU8)((*l).Buf[(*l).Bufpos]) == (NU8)(123)))) goto LA3;
		internalerror_129699(((NimStringDesc*) &TMP3472));
	}
	LA3: ;
	(*l).Bufpos += 1;
	while (1) {
		NI key;
		if (!!(((NU8)((*l).Buf[(*l).Bufpos]) == (NU8)(125)))) goto LA5;
		skipwhite_344238(l);
		key = decodevint_141251((*l).Buf, &(*l).Bufpos);
		incl_132842(result, key);
	} LA5: ;
	(*l).Bufpos += 1;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) (&(*dest).data[((*dest).Sup.len)- 0])), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(void, processmergeinfo_344575)(tbaselexer183018* l, tcgen343028* m) {
	NimStringDesc* k;
	k = rawNewString(9);
	while (1) {
		skipwhite_344238(l);
		{
			NIM_BOOL LOC4;
			LOC4 = ((NU8)((*l).Buf[(*l).Bufpos]) == (NU8)(42));
			if (!(LOC4)) goto LA5;
			LOC4 = ((NU8)((*l).Buf[(NI64)((*l).Bufpos + 1)]) == (NU8)(47));
			LA5: ;
			if (!LOC4) goto LA6;
			(*l).Bufpos += 2;
			goto LA1;
		}
		LA6: ;
		readkey_344438(l, &k);
		if (eqStrings(k, ((NimStringDesc*) &TMP3467))) goto LA8;
		if (eqStrings(k, ((NimStringDesc*) &TMP3468))) goto LA9;
		if (eqStrings(k, ((NimStringDesc*) &TMP3469))) goto LA10;
		if (eqStrings(k, ((NimStringDesc*) &TMP3470))) goto LA11;
		if (eqStrings(k, ((NimStringDesc*) &TMP3471))) goto LA12;
		goto LA13;
		LA8: ;
		{
			readtypecache_344491(l, &(*m).Typecache);
		}
		goto LA14;
		LA9: ;
		{
			readintset_344540(l, &(*m).Declaredthings);
		}
		goto LA14;
		LA10: ;
		{
			readintset_344540(l, &(*m).Typeinfomarker);
		}
		goto LA14;
		LA11: ;
		{
			NI LOC19;
			LOC19 = decodevint_141251((*l).Buf, &(*l).Bufpos);
			(*m).Labels = ((NI) (LOC19));
		}
		goto LA14;
		LA12: ;
		{
			NI LOC21;
			LOC21 = decodevint_141251((*l).Buf, &(*l).Bufpos);
			(*m).Framedeclared = !((LOC21 == 0));
		}
		goto LA14;
		LA13: ;
		{
			NimStringDesc* LOC23;
			LOC23 = 0;
			LOC23 = rawNewString(k->Sup.len + 22);
appendString(LOC23, ((NimStringDesc*) &TMP3473));
appendString(LOC23, k);
			internalerror_129699(LOC23);
		}
		LA14: ;
	} LA1: ;
}

N_NIMCALL(void, readmergeinfo_344808)(NimStringDesc* cfilename, tcgen343028* m) {
	tllstream182205* s_344813;
	tbaselexer183018 l;
	NimStringDesc* k;
	s_344813 = llstreamopen_182228(cfilename, ((NU8) 0));
	{
		if (!(s_344813 == NIM_NIL)) goto LA3;
		goto BeforeRet;
	}
	LA3: ;
	memset((void*)&l, 0, sizeof(l));
	l.Sup.m_type = (&NTI183018);
	openbaselexer_183027(&l, s_344813, 8192);
	k = rawNewString(23);
	while (1) {
		skipuntilcmd_344258(&l);
		{
			if (!((NU8)(l.Buf[l.Bufpos]) == (NU8)(0))) goto LA8;
			goto LA5;
		}
		LA8: ;
		readkey_344438(&l, &k);
		{
			if (!eqStrings(k, ((NimStringDesc*) &TMP3466))) goto LA12;
			processmergeinfo_344575(&l, m);
			goto LA5;
		}
		LA12: ;
	} LA5: ;
	closebaselexer_183036(&l);
	BeforeRet: ;
}

static N_INLINE(trope126007**, s_343159)(tcproc343024* p, NU8 s) {
	trope126007** result;
	result = 0;
	result = &(*p).Blocks->data[(NI64)((*p).Blocks->Sup.len - 1)].Sections[(s)- 0];
	return result;
}

N_NIMCALL(NIM_BOOL, mergerequired_345040)(tcgen343028* m) {
	NIM_BOOL result;
	NU8 i_345074;
	NU8 res_345131;
	NU8 i_345118;
	NU8 res_345136;
	result = 0;
	i_345074 = 0;
	res_345131 = ((NU8) 1);
	while (1) {
		if (!(res_345131 <= ((NU8) 10))) goto LA1;
		i_345074 = res_345131;
		{
			if (!!(((*m).S[(i_345074)- 0] == NIM_NIL))) goto LA4;
			result = NIM_TRUE;
			goto BeforeRet;
		}
		LA4: ;
		res_345131 += 1;
	} LA1: ;
	i_345118 = 0;
	res_345136 = ((NU8) 0);
	while (1) {
		if (!(res_345136 <= ((NU8) 2))) goto LA6;
		i_345118 = res_345136;
		{
			trope126007** LOC9;
			LOC9 = s_343159((*m).Initproc, i_345118);
			if (!!(((*LOC9) == NIM_NIL))) goto LA10;
			result = NIM_TRUE;
			goto BeforeRet;
		}
		LA10: ;
		res_345136 += 1;
	} LA6: ;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NIM_BOOL, atendmark_344302)(NCSTRING buf, NI pos) {
	NIM_BOOL result;
	NI s;
	result = 0;
	s = 0;
	while (1) {
		NIM_BOOL LOC2;
		LOC2 = (s < 19);
		if (!(LOC2)) goto LA3;
		LOC2 = ((NU8)(buf[(NI64)(pos + s)]) == (NU8)(((NimStringDesc*) &TMP3539)->data[s]));
		LA3: ;
		if (!LOC2) goto LA1;
		s += 1;
	} LA1: ;
	result = (s == 19);
	return result;
}

N_NIMCALL(trope126007*, readverbatimsection_344401)(tbaselexer183018* l) {
	trope126007* result;
	NI pos;
	NCSTRING buf;
	NimStringDesc* r;
	result = 0;
	pos = (*l).Bufpos;
	buf = (*l).Buf;
	r = rawNewString(30000);
	while (1) {
		switch (((NU8)(buf[pos]))) {
		case 13:
		{
			pos = handlecr_183051(l, pos);
			buf = (*l).Buf;
			r = resizeString(r, tnl_123580->Sup.len + 0);
appendString(r, tnl_123580);
		}
		break;
		case 10:
		{
			pos = handlelf_183057(l, pos);
			buf = (*l).Buf;
			r = resizeString(r, tnl_123580->Sup.len + 0);
appendString(r, tnl_123580);
		}
		break;
		case 0:
		{
			internalerror_129699(((NimStringDesc*) &TMP3538));
			goto LA1;
		}
		break;
		default:
		{
			{
				NIM_BOOL LOC8;
				LOC8 = atendmark_344302(buf, pos);
				if (!LOC8) goto LA9;
				pos += 19;
				goto LA1;
			}
			LA9: ;
			r = addChar(r, buf[pos]);
			pos += 1;
		}
		break;
		}
	} LA1: ;
	(*l).Bufpos = pos;
	result = torope_126058(r);
	return result;
}

N_NIMCALL(void, readmergesections_344843)(NimStringDesc* cfilename, tmergesections344838* m) {
	tllstream182205* s_344849;
	tbaselexer183018 l;
	NimStringDesc* k;
	s_344849 = llstreamopen_182228(cfilename, ((NU8) 0));
	{
		if (!(s_344849 == NIM_NIL)) goto LA3;
		goto BeforeRet;
	}
	LA3: ;
	memset((void*)&l, 0, sizeof(l));
	l.Sup.m_type = (&NTI183018);
	openbaselexer_183027(&l, s_344849, 8192);
	k = rawNewString(23);
	while (1) {
		skipuntilcmd_344258(&l);
		{
			if (!((NU8)(l.Buf[l.Bufpos]) == (NU8)(0))) goto LA8;
			goto LA5;
		}
		LA8: ;
		readkey_344438(&l, &k);
		{
			if (!eqStrings(k, ((NimStringDesc*) &TMP3466))) goto LA12;
		}
		goto LA10;
		LA12: ;
		{
			NIM_BOOL LOC15;
			trope126007* verbatim;
			NI sectiona;
			LOC15 = ((NU8)(l.Buf[l.Bufpos]) == (NU8)(42));
			if (!(LOC15)) goto LA16;
			LOC15 = ((NU8)(l.Buf[(NI64)(l.Bufpos + 1)]) == (NU8)(47));
			LA16: ;
			if (!LOC15) goto LA17;
			l.Bufpos += 2;
			skipwhite_344238(&l);
			verbatim = readverbatimsection_344401(&l);
			skipwhite_344238(&l);
			sectiona = find_344884(cfilesectionnames_344006, k);
			{
				NIM_BOOL LOC21;
				LOC21 = (0 < sectiona);
				if (!(LOC21)) goto LA22;
				LOC21 = (sectiona <= 17);
				LA22: ;
				if (!LOC21) goto LA23;
				unsureAsgnRef((void**) &(*m).F[(sectiona)- 0], verbatim);
			}
			goto LA19;
			LA23: ;
			{
				NI sectionb;
				sectionb = find_344959(cprocsectionnames_344011, k);
				{
					NIM_BOOL LOC28;
					LOC28 = (0 <= sectionb);
					if (!(LOC28)) goto LA29;
					LOC28 = (sectionb <= 2);
					LA29: ;
					if (!LOC28) goto LA30;
					unsureAsgnRef((void**) &(*m).P[(sectionb)- 0], verbatim);
				}
				goto LA26;
				LA30: ;
				{
					NimStringDesc* LOC33;
					LOC33 = 0;
					LOC33 = rawNewString(k->Sup.len + 27);
appendString(LOC33, ((NimStringDesc*) &TMP3561));
appendString(LOC33, k);
					internalerror_129699(LOC33);
				}
				LA26: ;
			}
			LA19: ;
		}
		goto LA10;
		LA17: ;
		{
			internalerror_129699(((NimStringDesc*) &TMP3562));
		}
		LA10: ;
	} LA5: ;
	closebaselexer_183036(&l);
	BeforeRet: ;
}

static N_INLINE(tcell38449*, usrtocell_41843)(void* usr) {
	tcell38449* result;
	result = 0;
	result = ((tcell38449*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell38449))))));
	return result;
}

static N_INLINE(void, rtladdzct_43002)(tcell38449* c) {
	addzct_41815(&gch_40442.Zct, c);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		tcell38449* c;
		if (!!((src == NIM_NIL))) goto LA3;
		c = usrtocell_41843(src);
		(*c).Refcount += 8;
	}
	LA3: ;
	{
		tcell38449* c;
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		c = usrtocell_41843((*dest));
		{
			(*c).Refcount -= 8;
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			rtladdzct_43002(c);
		}
		LA11: ;
	}
	LA7: ;
	(*dest) = src;
}

N_NIMCALL(void, mergefiles_345142)(NimStringDesc* cfilename, tcgen343028* m) {
	tmergesections344838 old;
	NU8 i_345157;
	NU8 res_345176;
	NU8 i_345169;
	NU8 res_345181;
	memset((void*)&old, 0, sizeof(old));
	readmergesections_344843(cfilename, &old);
	i_345157 = 0;
	res_345176 = ((NU8) 0);
	while (1) {
		if (!(res_345176 <= ((NU8) 17))) goto LA1;
		i_345157 = res_345176;
		asgnRefNoCycle((void**) &(*m).S[(i_345157)- 0], con_126020(old.F[(i_345157)- 0], (*m).S[(i_345157)- 0]));
		res_345176 += 1;
	} LA1: ;
	i_345169 = 0;
	res_345181 = ((NU8) 0);
	while (1) {
		trope126007** LOC3;
		trope126007** LOC4;
		if (!(res_345181 <= ((NU8) 2))) goto LA2;
		i_345169 = res_345181;
		LOC3 = s_343159((*m).Initproc, i_345169);
		LOC4 = s_343159((*m).Initproc, i_345169);
		unsureAsgnRef((void**) &(*LOC3), con_126020(old.P[(i_345169)- 0], (*LOC4)));
		res_345181 += 1;
	} LA2: ;
}

N_NIMCALL(trope126007*, gensectionstart_344082)(NU8 ps) {
	trope126007* result;
	result = 0;
	{
		if (!!(((49152 & gglobaloptions_105108) == 0))) goto LA3;
		result = torope_126058(tnl_123580);
		app_126046(&result, ((NimStringDesc*) &TMP3567));
		app_126046(&result, cprocsectionnames_344011[(ps)- 0]);
		app_126046(&result, ((NimStringDesc*) &TMP3568));
		app_126046(&result, tnl_123580);
	}
	LA3: ;
	return result;
}

N_NIMCALL(trope126007*, gensectionend_344116)(NU8 ps) {
	trope126007* result;
	result = 0;
	{
		NimStringDesc* LOC5;
		if (!!(((49152 & gglobaloptions_105108) == 0))) goto LA3;
		LOC5 = 0;
		LOC5 = rawNewString(tnl_123580->Sup.len + 19);
appendString(LOC5, ((NimStringDesc*) &TMP3539));
appendString(LOC5, tnl_123580);
		result = torope_126058(LOC5);
	}
	LA3: ;
	return result;
}

N_NIMCALL(trope126007*, gensectionstart_344018)(NU8 fs) {
	trope126007* result;
	result = 0;
	{
		if (!!(((49152 & gglobaloptions_105108) == 0))) goto LA3;
		result = torope_126058(tnl_123580);
		app_126046(&result, ((NimStringDesc*) &TMP3567));
		app_126046(&result, cfilesectionnames_344006[(fs)- 0]);
		app_126046(&result, ((NimStringDesc*) &TMP3568));
		app_126046(&result, tnl_123580);
	}
	LA3: ;
	return result;
}

N_NIMCALL(trope126007*, gensectionend_344052)(NU8 fs) {
	trope126007* result;
	result = 0;
	{
		NimStringDesc* LOC5;
		if (!!(((49152 & gglobaloptions_105108) == 0))) goto LA3;
		LOC5 = 0;
		LOC5 = rawNewString(tnl_123580->Sup.len + 19);
appendString(LOC5, ((NimStringDesc*) &TMP3539));
appendString(LOC5, tnl_123580);
		result = torope_126058(LOC5);
	}
	LA3: ;
	return result;
}

N_NIMCALL(void, writetypecache_344146)(tidtable135693 a, NimStringDesc** s) {
	NI i;
	NI id_344152;
	TNimObject* value_344153;
	NI i_344167;
	NI HEX3Atmp_344169;
	NI res_344171;
	i = 0;
	id_344152 = 0;
	value_344153 = 0;
	i_344167 = 0;
	HEX3Atmp_344169 = 0;
	HEX3Atmp_344169 = (a.Data->Sup.len-1);
	res_344171 = 0;
	while (1) {
		if (!(res_344171 <= HEX3Atmp_344169)) goto LA1;
		i_344167 = res_344171;
		{
			NimStringDesc* LOC11;
			if (!!((a.Data->data[i_344167].Key == NIM_NIL))) goto LA4;
			id_344152 = (*a.Data->data[i_344167].Key).Id;
			value_344153 = a.Data->data[i_344167].Val;
			{
				if (!(i == 10)) goto LA8;
				i = 0;
				(*s) = resizeString((*s), tnl_123580->Sup.len + 0);
appendString((*s), tnl_123580);
			}
			goto LA6;
			LA8: ;
			{
				(*s) = addChar((*s), 32);
			}
			LA6: ;
			encodevint_141226(id_344152, s);
			(*s) = addChar((*s), 58);
			LOC11 = 0;
			LOC11 = ropetostr_126075(((trope126007*) (value_344153)));
			encodestr_141025(LOC11, s);
			i += 1;
		}
		LA4: ;
		res_344171 += 1;
	} LA1: ;
	(*s) = addChar((*s), 125);
}

N_NIMCALL(void, writeintset_344175)(tintset132035* a, NimStringDesc** s) {
	NI i;
	NI x_344181;
	ttrunk132031* r_344195;
	i = 0;
	x_344181 = 0;
	r_344195 = (*a).Head;
	while (1) {
		NI i_344197;
		if (!!((r_344195 == NIM_NIL))) goto LA1;
		i_344197 = 0;
		while (1) {
			NI w_344199;
			NI j_344201;
			if (!(i_344197 <= 7)) goto LA2;
			w_344199 = (*r_344195).Bits[(i_344197)- 0];
			j_344201 = 0;
			while (1) {
				if (!!((w_344199 == 0))) goto LA3;
				{
					if (!!((((NI) ((NI)(w_344199 & 1))) == 0))) goto LA6;
					x_344181 = (NI)((NI)((NU64)((*r_344195).Key) << (NU64)(9)) | (NI)((NU64)((NI)((NU64)(i_344197) << (NU64)(6))) + (NU64)(j_344201)));
					{
						if (!(i == 10)) goto LA10;
						i = 0;
						(*s) = resizeString((*s), tnl_123580->Sup.len + 0);
appendString((*s), tnl_123580);
					}
					goto LA8;
					LA10: ;
					{
						(*s) = addChar((*s), 32);
					}
					LA8: ;
					encodevint_141226(x_344181, s);
					i += 1;
				}
				LA6: ;
				j_344201 += 1;
				w_344199 = (NI)((NU64)(w_344199) >> (NU64)(1));
			} LA3: ;
			i_344197 += 1;
		} LA2: ;
		r_344195 = (*r_344195).Next;
	} LA1: ;
	(*s) = addChar((*s), 125);
}

N_NIMCALL(trope126007*, genmergeinfo_344207)(tcgen343028* m) {
	trope126007* result;
	NimStringDesc* s;
	result = 0;
	{
		if (!!(((gglobaloptions_105108 &(1<<((((NU8) 14))&31)))!=0))) goto LA3;
		result = NIM_NIL;
		goto BeforeRet;
	}
	LA3: ;
	s = copyString(((NimStringDesc*) &TMP3577));
	s = resizeString(s, tnl_123580->Sup.len + 0);
appendString(s, tnl_123580);
	s = resizeString(s, 11);
appendString(s, ((NimStringDesc*) &TMP3578));
	writetypecache_344146((*m).Typecache, &s);
	s = resizeString(s, 10);
appendString(s, ((NimStringDesc*) &TMP3579));
	writeintset_344175(&(*m).Declaredthings, &s);
	s = resizeString(s, 10);
appendString(s, ((NimStringDesc*) &TMP3580));
	writeintset_344175(&(*m).Typeinfomarker, &s);
	s = resizeString(s, 7);
appendString(s, ((NimStringDesc*) &TMP3581));
	encodevint_141226(((NI) ((*m).Labels)), &s);
	s = resizeString(s, 10);
appendString(s, ((NimStringDesc*) &TMP3582));
	encodevint_141226(((NI) ((*m).Framedeclared)), &s);
	s = resizeString(s, tnl_123580->Sup.len + 0);
appendString(s, tnl_123580);
	s = resizeString(s, 2);
appendString(s, ((NimStringDesc*) &TMP3583));
	result = torope_126058(s);
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, find_344884)(TY344007 a, NimStringDesc* item) {
	NI result;
	NimStringDesc* i_344936;
	NU8 i_344950;
	result = 0;
	i_344936 = 0;
	i_344950 = ((NU8) 0);
	{
		if (!(i_344950 <= ((NU8) 17))) goto LA3;
		while (1) {
			i_344936 = a[(i_344950)- 0];
			{
				if (!eqStrings(i_344936, item)) goto LA8;
				goto BeforeRet;
			}
			LA8: ;
			result += 1;
			{
				if (!(((NU8) 17) <= i_344950)) goto LA12;
				goto LA5;
			}
			LA12: ;
			i_344950 += 1;
		} LA5: ;
	}
	LA3: ;
	result = -1;
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, find_344959)(TY344012 a, NimStringDesc* item) {
	NI result;
	NimStringDesc* i_345011;
	NU8 i_345025;
	result = 0;
	i_345011 = 0;
	i_345025 = ((NU8) 0);
	{
		if (!(i_345025 <= ((NU8) 2))) goto LA3;
		while (1) {
			i_345011 = a[(i_345025)- 0];
			{
				if (!eqStrings(i_345011, item)) goto LA8;
				goto BeforeRet;
			}
			LA8: ;
			result += 1;
			{
				if (!(((NU8) 2) <= i_345025)) goto LA12;
				goto LA5;
			}
			LA12: ;
			i_345025 += 1;
		} LA5: ;
	}
	LA3: ;
	result = -1;
	BeforeRet: ;
	return result;
}
N_NOINLINE(void, ccgmergeInit)(void) {
}

N_NOINLINE(void, ccgmergeDatInit)(void) {
}

