/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/usr/src/extras/Nimrod/lib -o compiler/nimcache/hashes.o compiler/nimcache/hashes.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
typedef N_NIMCALL_PTR(void, TY891) (void* p, NI op);
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY891 marker;
};
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
static N_INLINE(NI, HEX21HEX26_101011)(NI h, NI val);
static N_INLINE(NI, HEX21HEX24_101042)(NI h);
TNimType NTI101009; /* THash */

static N_INLINE(NI, HEX21HEX26_101011)(NI h, NI val) {
	NI result;
	result = 0;
	result = (NI)((NU64)(h) + (NU64)(val));
	result = (NI)((NU64)(result) + (NU64)((NI)((NU64)(result) << (NU64)(10))));
	result = (NI)(result ^ (NI)((NU64)(result) >> (NU64)(6)));
	return result;
}

static N_INLINE(NI, HEX21HEX24_101042)(NI h) {
	NI result;
	result = 0;
	result = (NI)((NU64)(h) + (NU64)((NI)((NU64)(h) << (NU64)(3))));
	result = (NI)(result ^ (NI)((NU64)(result) >> (NU64)(11)));
	result = (NI)((NU64)(result) + (NU64)((NI)((NU64)(result) << (NU64)(15))));
	return result;
}

N_NIMCALL(NI, hash_101825)(NimStringDesc* x) {
	NI result;
	NI h;
	NI i_101837;
	NI HEX3Atmp_101845;
	NI res_101847;
	result = 0;
	h = 0;
	i_101837 = 0;
	HEX3Atmp_101845 = 0;
	HEX3Atmp_101845 = (NI64)(x->Sup.len - 1);
	res_101847 = 0;
	while (1) {
		if (!(res_101847 <= HEX3Atmp_101845)) goto LA1;
		i_101837 = res_101847;
		h = HEX21HEX26_101011(h, ((NI) (((NU8)(x->data[i_101837])))));
		res_101847 += 1;
	} LA1: ;
	result = HEX21HEX24_101042(h);
	return result;
}

N_NIMCALL(NI, hashignorestyle_101852)(NimStringDesc* x) {
	NI result;
	NI h;
	NI i_101864;
	NI HEX3Atmp_101907;
	NI res_101909;
	result = 0;
	h = 0;
	i_101864 = 0;
	HEX3Atmp_101907 = 0;
	HEX3Atmp_101907 = (NI64)(x->Sup.len - 1);
	res_101909 = 0;
	while (1) {
		if (!(res_101909 <= HEX3Atmp_101907)) goto LA1;
		i_101864 = res_101909;
		{
			NIM_CHAR c;
			c = x->data[i_101864];
			{
				if (!((NU8)(c) == (NU8)(95))) goto LA5;
				goto LA2;
			}
			LA5: ;
			{
				if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA9;
				c = ((NIM_CHAR) (((NI) ((NI64)(((NI) (((NU8)(c)))) + 32)))));
			}
			LA9: ;
			h = HEX21HEX26_101011(h, ((NI) (((NU8)(c)))));
		} LA2: ;
		res_101909 += 1;
	} LA1: ;
	result = HEX21HEX24_101042(h);
	return result;
}

N_NIMCALL(NI, hashignorecase_101915)(NimStringDesc* x) {
	NI result;
	NI h;
	NI i_101927;
	NI HEX3Atmp_101969;
	NI res_101971;
	result = 0;
	h = 0;
	i_101927 = 0;
	HEX3Atmp_101969 = 0;
	HEX3Atmp_101969 = (NI64)(x->Sup.len - 1);
	res_101971 = 0;
	while (1) {
		NIM_CHAR c;
		if (!(res_101971 <= HEX3Atmp_101969)) goto LA1;
		i_101927 = res_101971;
		c = x->data[i_101927];
		{
			if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA4;
			c = ((NIM_CHAR) (((NI) ((NI64)(((NI) (((NU8)(c)))) + 32)))));
		}
		LA4: ;
		h = HEX21HEX26_101011(h, ((NI) (((NU8)(c)))));
		res_101971 += 1;
	} LA1: ;
	result = HEX21HEX24_101042(h);
	return result;
}
N_NOINLINE(void, hashesInit)(void) {
}

N_NOINLINE(void, hashesDatInit)(void) {
NTI101009.size = sizeof(NI);
NTI101009.kind = 31;
NTI101009.base = 0;
NTI101009.flags = 3;
}

