/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/usr/src/extras/Nimrod/lib -o compiler/nimcache/importer.o compiler/nimcache/importer.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct tnode135647 tnode135647;
typedef struct tcontext261019 tcontext261019;
typedef struct tintset132035 tintset132035;
typedef struct ttrunk132031 ttrunk132031;
typedef struct ttrunkseq132033 ttrunkseq132033;
typedef struct TGenericSeq TGenericSeq;
typedef struct ttype135681 ttype135681;
typedef struct tlineinfo128308 tlineinfo128308;
typedef struct NimStringDesc NimStringDesc;
typedef struct tsym135677 tsym135677;
typedef struct tident131018 tident131018;
typedef struct tnodeseq135641 tnodeseq135641;
typedef struct tidobj131012 tidobj131012;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct ttypeseq135679 ttypeseq135679;
typedef struct TY135771 TY135771;
typedef struct tinstantiation135667 tinstantiation135667;
typedef struct tscope135671 tscope135671;
typedef struct tstrtable135651 tstrtable135651;
typedef struct tsymseq135649 tsymseq135649;
typedef struct tloc135661 tloc135661;
typedef struct trope126007 trope126007;
typedef struct tlib135665 tlib135665;
typedef struct tpasscontext224003 tpasscontext224003;
typedef struct tproccon261009 tproccon261009;
typedef struct tlinkedlist100017 tlinkedlist100017;
typedef struct tlistentry100011 tlistentry100011;
typedef struct tidtable135693 tidtable135693;
typedef struct tidpairseq135691 tidpairseq135691;
typedef struct tidpair135689 tidpair135689;
typedef struct tevalcontext252212 tevalcontext252212;
typedef struct TY261100 TY261100;
typedef struct tinstantiationpair261011 tinstantiationpair261011;
typedef struct ttabiter142090 ttabiter142090;
typedef struct tidentiter142106 tidentiter142106;
typedef struct tcell38449 tcell38449;
typedef struct tcellseq38465 tcellseq38465;
typedef struct tgcheap40416 tgcheap40416;
typedef struct tcellset38461 tcellset38461;
typedef struct tpagedesc38457 tpagedesc38457;
typedef struct tmemregion22010 tmemregion22010;
typedef struct tsmallchunk21243 tsmallchunk21243;
typedef struct tllchunk22004 tllchunk22004;
typedef struct tbigchunk21245 tbigchunk21245;
typedef struct tintset21218 tintset21218;
typedef struct ttrunk21214 ttrunk21214;
typedef struct tavlnode22008 tavlnode22008;
typedef struct tgcstat40414 tgcstat40414;
typedef struct TY135763 TY135763;
typedef struct tstackframe252204 tstackframe252204;
typedef struct tidnodetable135699 tidnodetable135699;
typedef struct tidnodepairseq135697 tidnodepairseq135697;
typedef struct tidnodepair135695 tidnodepair135695;
typedef struct tbasechunk21241 tbasechunk21241;
typedef struct tfreecell21233 tfreecell21233;
struct TGenericSeq {
NI len;
NI reserved;
};
struct tintset132035 {
NI Counter;
NI Max;
ttrunk132031* Head;
ttrunkseq132033* Data;
};
struct tlineinfo128308 {
NI16 Line;
NI16 Col;
NI32 Fileindex;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
struct tnode135647 {
ttype135681* Typ;
tlineinfo128308 Info;
NU8 Flags;
NU8 Kind;
union {
struct {NI64 Intval;
} S1;
struct {NF64 Floatval;
} S2;
struct {NimStringDesc* Strval;
} S3;
struct {tsym135677* Sym;
} S4;
struct {tident131018* Ident;
} S5;
struct {tnodeseq135641* Sons;
} S6;
} kindU;
NimStringDesc* Comment;
};
typedef N_NIMCALL_PTR(void, TY891) (void* p, NI op);
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY891 marker;
};
struct TNimObject {
TNimType* m_type;
};
struct tidobj131012 {
  TNimObject Sup;
NI Id;
};
struct tident131018 {
  tidobj131012 Sup;
NimStringDesc* S;
tident131018* Next;
NI H;
};
struct tstrtable135651 {
NI Counter;
tsymseq135649* Data;
};
struct tloc135661 {
NU8 K;
NU8 S;
NU8 Flags;
ttype135681* T;
trope126007* R;
trope126007* Heaproot;
NI A;
};
struct tsym135677 {
  tidobj131012 Sup;
NU8 Kind;
union {
struct {ttypeseq135679* Typeinstcache;
} S1;
struct {TY135771* Procinstcache;
tscope135671* Scope;
} S2;
struct {TY135771* Usedgenerics;
tstrtable135651 Tab;
} S3;
} kindU;
NU16 Magic;
ttype135681* Typ;
tident131018* Name;
tlineinfo128308 Info;
tsym135677* Owner;
NU32 Flags;
tnode135647* Ast;
NU32 Options;
NI Position;
NI Offset;
tloc135661 Loc;
tlib135665* Annex;
tnode135647* Constraint;
};
typedef N_NIMCALL_PTR(tsym135677*, TY224056) (tsym135677* m, NI32 fileidx);
struct tpasscontext224003 {
  TNimObject Sup;
NIM_BOOL Fromcache;
};
struct tlinkedlist100017 {
tlistentry100011* Head;
tlistentry100011* Tail;
NI Counter;
};
struct tidpair135689 {
tidobj131012* Key;
TNimObject* Val;
};
struct tidtable135693 {
NI Counter;
tidpairseq135691* Data;
};
typedef N_NIMCALL_PTR(tnode135647*, TY261057) (tcontext261019* c, tnode135647* n);
typedef N_NIMCALL_PTR(tnode135647*, TY261062) (tcontext261019* c, tnode135647* n, NU8 flags);
typedef N_NIMCALL_PTR(tnode135647*, TY261070) (tcontext261019* c, tnode135647* n, NU8 flags);
typedef N_NIMCALL_PTR(tnode135647*, TY261078) (tcontext261019* c, tnode135647* n);
typedef N_NIMCALL_PTR(tnode135647*, TY261083) (tcontext261019* c, tnode135647* n, tnode135647* norig, NU32 filter);
typedef N_NIMCALL_PTR(ttype135681*, TY261090) (tcontext261019* c, tnode135647* n, ttype135681* prev);
struct tinstantiationpair261011 {
tsym135677* Genericsym;
tinstantiation135667* Inst;
};
struct tcontext261019 {
  tpasscontext224003 Sup;
tsym135677* Module;
tscope135671* Currentscope;
tscope135671* Importtable;
tscope135671* Toplevelscope;
tproccon261009* P;
tsym135677* Friendmodule;
NI Instcounter;
tsymseq135649* Threadentries;
tintset132035 Ambiguoussymbols;
NI Ingenericcontext;
NI Inunrolledcontext;
NI Incompilescontext;
NI Ingenericinst;
tsymseq135649* Converters;
tsymseq135649* Patterns;
tlinkedlist100017 Optionstack;
tidtable135693 Symmapping;
tlinkedlist100017 Libs;
TY261057 Semconstexpr;
TY261062 Semexpr;
TY261070 Semoperand;
TY261078 Semconstboolexpr;
TY261083 Semoverloadedcall;
TY261090 Semtypenode;
tintset132035 Includedfiles;
tstrtable135651 Userpragmas;
tevalcontext252212* Evalcontext;
tintset132035 Unknownidents;
TY261100* Generics;
NI Lastgenericidx;
};
struct ttabiter142090 {
NI H;
};
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tscope135671 {
NI Depthlevel;
tstrtable135651 Symbols;
tscope135671* Parent;
};
struct ttype135681 {
  tidobj131012 Sup;
NU8 Kind;
NU8 Callconv;
NU32 Flags;
ttypeseq135679* Sons;
tnode135647* N;
tsym135677* Destructor;
tsym135677* Owner;
tsym135677* Sym;
NI64 Size;
NI Align;
tloc135661 Loc;
};
struct tidentiter142106 {
NI H;
tident131018* Name;
};
struct tcell38449 {
NI Refcount;
TNimType* Typ;
};
struct tcellseq38465 {
NI Len;
NI Cap;
tcell38449** D;
};
struct tcellset38461 {
NI Counter;
NI Max;
tpagedesc38457* Head;
tpagedesc38457** Data;
};
typedef tsmallchunk21243* TY22022[512];
typedef ttrunk21214* ttrunkbuckets21216[256];
struct tintset21218 {
ttrunkbuckets21216 Data;
};
struct tmemregion22010 {
NI Minlargeobj;
NI Maxlargeobj;
TY22022 Freesmallchunks;
tllchunk22004* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk21245* Freechunkslist;
tintset21218 Chunkstarts;
tavlnode22008* Root;
tavlnode22008* Deleted;
tavlnode22008* Last;
tavlnode22008* Freeavlnodes;
};
struct tgcstat40414 {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct tgcheap40416 {
void* Stackbottom;
NI Cyclethreshold;
tcellseq38465 Zct;
tcellseq38465 Decstack;
tcellset38461 Cycleroots;
tcellseq38465 Tempstack;
NI Recgclock;
tmemregion22010 Region;
tgcstat40414 Stat;
};
typedef NI TY21221[8];
struct ttrunk132031 {
ttrunk132031* Next;
NI Key;
TY21221 Bits;
};
struct tinstantiation135667 {
tsym135677* Sym;
ttypeseq135679* Concretetypes;
TY135763* Usedby;
};
struct trope126007 {
  TNimObject Sup;
trope126007* Left;
trope126007* Right;
NI Length;
NimStringDesc* Data;
};
struct tlistentry100011 {
  TNimObject Sup;
tlistentry100011* Prev;
tlistentry100011* Next;
};
struct tlib135665 {
  tlistentry100011 Sup;
NU8 Kind;
NIM_BOOL Generated;
NIM_BOOL Isoverriden;
trope126007* Name;
tnode135647* Path;
};
struct tproccon261009 {
tsym135677* Owner;
tsym135677* Resultsym;
NI Nestedloopcounter;
NI Nestedblockcounter;
NI Intrystmt;
tproccon261009* Next;
};
struct tidnodepair135695 {
tidobj131012* Key;
tnode135647* Val;
};
struct tidnodetable135699 {
NI Counter;
tidnodepairseq135697* Data;
};
typedef struct {
N_NIMCALL_PTR(tnode135647*, ClPrc) (tnode135647* n, void* ClEnv);
void* ClEnv;
} TY252237;
struct tevalcontext252212 {
  tpasscontext224003 Sup;
tsym135677* Module;
tstackframe252204* Tos;
tnode135647* Lastexception;
tnode135647* Callsite;
NU8 Mode;
NU8 Features;
tidnodetable135699 Globals;
TY252237 Gettype;
};
struct tpagedesc38457 {
tpagedesc38457* Next;
NI Key;
TY21221 Bits;
};
struct tbasechunk21241 {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct tsmallchunk21243 {
  tbasechunk21241 Sup;
tsmallchunk21243* Next;
tsmallchunk21243* Prev;
tfreecell21233* Freelist;
NI Free;
NI Acc;
NF64 Data;
};
struct tllchunk22004 {
NI Size;
NI Acc;
tllchunk22004* Next;
};
struct tbigchunk21245 {
  tbasechunk21241 Sup;
tbigchunk21245* Next;
tbigchunk21245* Prev;
NI Align;
NF64 Data;
};
struct ttrunk21214 {
ttrunk21214* Next;
NI Key;
TY21221 Bits;
};
typedef tavlnode22008* TY22014[2];
struct tavlnode22008 {
TY22014 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct tstackframe252204 {
tsym135677* Prc;
tnodeseq135641* Slots;
tnode135647* Call;
tstackframe252204* Next;
};
struct tfreecell21233 {
tfreecell21233* Next;
NI Zerofield;
};
struct ttrunkseq132033 {
  TGenericSeq Sup;
  ttrunk132031* data[SEQ_DECL_SIZE];
};
struct tnodeseq135641 {
  TGenericSeq Sup;
  tnode135647* data[SEQ_DECL_SIZE];
};
struct ttypeseq135679 {
  TGenericSeq Sup;
  ttype135681* data[SEQ_DECL_SIZE];
};
struct TY135771 {
  TGenericSeq Sup;
  tinstantiation135667* data[SEQ_DECL_SIZE];
};
struct tsymseq135649 {
  TGenericSeq Sup;
  tsym135677* data[SEQ_DECL_SIZE];
};
struct tidpairseq135691 {
  TGenericSeq Sup;
  tidpair135689 data[SEQ_DECL_SIZE];
};
struct TY261100 {
  TGenericSeq Sup;
  tinstantiationpair261011 data[SEQ_DECL_SIZE];
};
struct TY135763 {
  TGenericSeq Sup;
  NI32 data[SEQ_DECL_SIZE];
};
struct tidnodepairseq135697 {
  TGenericSeq Sup;
  tidnodepair135695 data[SEQ_DECL_SIZE];
};
static N_INLINE(NI, sonslen_136002)(tnode135647* n);
N_NIMCALL(NI32, checkmodulename_264049)(tnode135647* n);
N_NIMCALL(NimStringDesc*, getmodulename_264012)(tnode135647* n);
N_NIMCALL(NimStringDesc*, nosunixToNativePath)(NimStringDesc* path);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, nsuReplaceStr)(NimStringDesc* s, NimStringDesc* sub, NimStringDesc* by);
N_NIMCALL(NimStringDesc*, rendertree_193046)(tnode135647* n, NU8 renderflags);
static N_INLINE(NimStringDesc*, findmodule_105538)(NimStringDesc* modulename);
N_NIMCALL(NimStringDesc*, findfile_105532)(NimStringDesc* f);
N_NIMCALL(NimStringDesc*, nosaddFileExt)(NimStringDesc* filename, NimStringDesc* ext);
N_NIMCALL(void, localerror_129673)(tlineinfo128308 info, NU16 msg, NimStringDesc* arg);
N_NIMCALL(NI32, fileinfoidx_128506)(NimStringDesc* filename);
N_NIMCALL(void, message_129680)(tlineinfo128308 info, NU16 msg, NimStringDesc* arg);
N_NIMCALL(void, adddecl_262384)(tcontext261019* c, tsym135677* sym);
N_NIMCALL(void, importallsymbolsexcept_264269)(tcontext261019* c, tsym135677* frommod, tintset132035* exceptset);
N_NIMCALL(tsym135677*, inittabiter_142093)(ttabiter142090* ti, tstrtable135651 tab);
N_NIMCALL(void, internalerror_129687)(tlineinfo128308 info, NimStringDesc* errmsg);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, reprEnum)(NI e_68275, TNimType* typ);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(NIM_BOOL, empty_133107)(tintset132035* s);
N_NIMCALL(NIM_BOOL, contains_132820)(tintset132035* s, NI key);
N_NIMCALL(void, rawimportsymbol_264057)(tcontext261019* c, tsym135677* s);
N_NIMCALL(tsym135677*, strtableget_142084)(tstrtable135651 t, tident131018* name);
N_NIMCALL(void, incl_132842)(tintset132035* s, NI key);
N_NIMCALL(void, strtableadd_142078)(tstrtable135651* t, tsym135677* n);
N_NIMCALL(tsym135677*, initidentiter_142110)(tidentiter142106* ti, tstrtable135651 tab, tident131018* s);
N_NIMCALL(tsym135677*, nextidentiter_142117)(tidentiter142106* ti, tstrtable135651 tab);
N_NIMCALL(void, addconverter_261471)(tcontext261019* c, tsym135677* conv);
static N_INLINE(NIM_BOOL, haspattern_140384)(tsym135677* s);
static N_INLINE(NIM_BOOL, isroutine_140368)(tsym135677* s);
N_NIMCALL(void, addpattern_261478)(tcontext261019* c, tsym135677* p);
N_NIMCALL(tsym135677*, nextiter_142099)(ttabiter142090* ti, tstrtable135651 tab);
N_NIMCALL(void, importforwarded_264347)(tcontext261019* c, tnode135647* n, tintset132035* exceptset);
static N_INLINE(NI, len_136081)(tnode135647* n);
static N_INLINE(NI, safelen_136123)(tnode135647* n);
N_NIMCALL(void, checkminsonslen_261658)(tnode135647* n, NI length);
N_NIMCALL(tnode135647*, newsymnode_135916)(tsym135677* sym);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell38449*, usrtocell_41843)(void* usr);
static N_INLINE(void, rtladdzct_43002)(tcell38449* c);
N_NOINLINE(void, addzct_41815)(tcellseq38465* s, tcell38449* c);
N_NIMCALL(void, initintset_132899)(tintset132035* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(tident131018*, consideracc_262006)(tnode135647* n);
N_NIMCALL(void, importsymbol_264187)(tcontext261019* c, tnode135647* n, tsym135677* frommod);
N_NIMCALL(void, loadstub_215571)(tsym135677* s);
STRING_LITERAL(TMP2844, " ", 1);
STRING_LITERAL(TMP2845, "", 0);
STRING_LITERAL(TMP2846, "nim", 3);
STRING_LITERAL(TMP2847, "importAllSymbols: ", 18);
STRING_LITERAL(TMP2848, "rawImportSymbol", 15);
STRING_LITERAL(TMP2849, "\'export except\' not implemented", 31);
STRING_LITERAL(TMP2851, "importSymbol: 2", 15);
STRING_LITERAL(TMP2852, "importSymbol: 3", 15);
extern TY224056 gimportmodule_224060;
extern TNimType NTI135304; /* TSymKind */
extern tgcheap40416 gch_40442;

static N_INLINE(NI, sonslen_136002)(tnode135647* n) {
	NI result;
	result = 0;
	{
		if (!(*n).kindU.S6.Sons == 0) goto LA3;
		result = 0;
	}
	goto LA1;
	LA3: ;
	{
		result = (*n).kindU.S6.Sons->Sup.len;
	}
	LA1: ;
	return result;
}

N_NIMCALL(NimStringDesc*, getmodulename_264012)(tnode135647* n) {
	NimStringDesc* result;
	result = 0;
	switch ((*n).Kind) {
	case ((NU8) 20):
	case ((NU8) 21):
	case ((NU8) 22):
	{
		result = nosunixToNativePath((*n).kindU.S3.Strval);
	}
	break;
	case ((NU8) 2):
	{
		result = copyString((*(*n).kindU.S5.Ident).S);
	}
	break;
	case ((NU8) 3):
	{
		result = copyString((*(*(*n).kindU.S4.Sym).Name).S);
	}
	break;
	default:
	{
		NimStringDesc* LOC5;
		LOC5 = 0;
		LOC5 = rendertree_193046(n, 4);
		result = nsuReplaceStr(LOC5, ((NimStringDesc*) &TMP2844), ((NimStringDesc*) &TMP2845));
	}
	break;
	}
	return result;
}

static N_INLINE(NimStringDesc*, findmodule_105538)(NimStringDesc* modulename) {
	NimStringDesc* result;
	NimStringDesc* LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = nosaddFileExt(modulename, ((NimStringDesc*) &TMP2846));
	result = findfile_105532(LOC1);
	return result;
}

N_NIMCALL(NI32, checkmodulename_264049)(tnode135647* n) {
	NI32 result;
	NimStringDesc* modulename;
	NimStringDesc* fullpath;
	result = 0;
	modulename = getmodulename_264012(n);
	fullpath = findmodule_105538(modulename);
	{
		if (!(fullpath->Sup.len == 0)) goto LA3;
		localerror_129673((*n).Info, ((NU16) 3), modulename);
		result = ((NI32) -1);
	}
	goto LA1;
	LA3: ;
	{
		result = fileinfoidx_128506(fullpath);
	}
	LA1: ;
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) (&(*dest).data[((*dest).Sup.len)- 0])), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(NIM_BOOL, empty_133107)(tintset132035* s) {
	NIM_BOOL result;
	result = 0;
	result = ((*s).Counter == 0);
	return result;
}

static N_INLINE(NIM_BOOL, isroutine_140368)(tsym135677* s) {
	NIM_BOOL result;
	result = 0;
	result = ((258048 &(1<<(((*s).Kind)&31)))!=0);
	return result;
}

static N_INLINE(NIM_BOOL, haspattern_140384)(tsym135677* s) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	result = 0;
	LOC1 = isroutine_140368(s);
	if (!(LOC1)) goto LA2;
	LOC1 = !(((*(*(*s).Ast).kindU.S6.Sons->data[1]).Kind == ((NU8) 1)));
	LA2: ;
	result = LOC1;
	return result;
}

N_NIMCALL(void, rawimportsymbol_264057)(tcontext261019* c, tsym135677* s) {
	tsym135677* check;
	check = strtableget_142084((*(*c).Importtable).Symbols, (*s).Name);
	{
		NIM_BOOL LOC3;
		LOC3 = !((check == NIM_NIL));
		if (!(LOC3)) goto LA4;
		LOC3 = !(((*check).Sup.Id == (*s).Sup.Id));
		LA4: ;
		if (!LOC3) goto LA5;
		{
			if (!!(((258112 &(1<<(((*s).Kind)&31)))!=0))) goto LA9;
			incl_132842(&(*c).Ambiguoussymbols, (*s).Sup.Id);
			incl_132842(&(*c).Ambiguoussymbols, (*check).Sup.Id);
		}
		LA9: ;
	}
	LA5: ;
	strtableadd_142078(&(*(*c).Importtable).Symbols, s);
	{
		ttype135681* etyp;
		if (!((*s).Kind == ((NU8) 7))) goto LA13;
		etyp = (*s).Typ;
		{
			NIM_BOOL LOC17;
			NI j_264119;
			NI HEX3Atmp_264179;
			NI LOC21;
			NI res_264181;
			LOC17 = ((16386 &(IL64(1)<<(((*etyp).Kind)&IL64(63))))!=0);
			if (!(LOC17)) goto LA18;
			LOC17 = !((((*s).Flags &(1<<((((NU8) 9))&31)))!=0));
			LA18: ;
			if (!LOC17) goto LA19;
			j_264119 = 0;
			HEX3Atmp_264179 = 0;
			LOC21 = sonslen_136002((*etyp).N);
			HEX3Atmp_264179 = (NI64)(LOC21 - 1);
			res_264181 = 0;
			while (1) {
				tsym135677* e;
				tidentiter142106 it;
				if (!(res_264181 <= HEX3Atmp_264179)) goto LA22;
				j_264119 = res_264181;
				e = (*(*(*etyp).N).kindU.S6.Sons->data[j_264119]).kindU.S4.Sym;
				{
					if (!!(((*e).Kind == ((NU8) 19)))) goto LA25;
					internalerror_129687((*s).Info, ((NimStringDesc*) &TMP2848));
				}
				LA25: ;
				memset((void*)&it, 0, sizeof(it));
				check = initidentiter_142110(&it, (*(*c).Importtable).Symbols, (*e).Name);
				while (1) {
					if (!!((check == NIM_NIL))) goto LA27;
					{
						if (!((*check).Sup.Id == (*e).Sup.Id)) goto LA30;
						e = NIM_NIL;
						goto LA27;
					}
					LA30: ;
					check = nextidentiter_142117(&it, (*(*c).Importtable).Symbols);
				} LA27: ;
				{
					if (!!((e == NIM_NIL))) goto LA34;
					rawimportsymbol_264057(c, e);
				}
				LA34: ;
				res_264181 += 1;
			} LA22: ;
		}
		LA19: ;
	}
	goto LA11;
	LA13: ;
	{
		{
			if (!((*s).Kind == ((NU8) 15))) goto LA39;
			addconverter_261471(c, s);
		}
		LA39: ;
		{
			NIM_BOOL LOC43;
			LOC43 = haspattern_140384(s);
			if (!LOC43) goto LA44;
			addpattern_261478(c, s);
		}
		LA44: ;
	}
	LA11: ;
}

N_NIMCALL(void, importallsymbolsexcept_264269)(tcontext261019* c, tsym135677* frommod, tintset132035* exceptset) {
	ttabiter142090 i;
	tsym135677* s;
	memset((void*)&i, 0, sizeof(i));
	s = inittabiter_142093(&i, (*frommod).kindU.S3.Tab);
	while (1) {
		if (!!((s == NIM_NIL))) goto LA1;
		{
			if (!!(((*s).Kind == ((NU8) 6)))) goto LA4;
			{
				if (!!(((*s).Kind == ((NU8) 19)))) goto LA8;
				{
					NimStringDesc* LOC14;
					if (!!(((4978560 &(1<<(((*s).Kind)&31)))!=0))) goto LA12;
					LOC14 = 0;
					LOC14 = rawNewString(reprEnum((*s).Kind, (&NTI135304))->Sup.len + 18);
appendString(LOC14, ((NimStringDesc*) &TMP2847));
appendString(LOC14, reprEnum((*s).Kind, (&NTI135304)));
					internalerror_129687((*s).Info, LOC14);
				}
				LA12: ;
				{
					NIM_BOOL LOC17;
					NIM_BOOL LOC19;
					LOC17 = empty_133107(exceptset);
					if (LOC17) goto LA18;
					LOC19 = contains_132820(exceptset, (*(*s).Name).Sup.Id);
					LOC17 = !(LOC19);
					LA18: ;
					if (!LOC17) goto LA20;
					rawimportsymbol_264057(c, s);
				}
				LA20: ;
			}
			LA8: ;
		}
		LA4: ;
		s = nextiter_142099(&i, (*frommod).kindU.S3.Tab);
	} LA1: ;
}

static N_INLINE(NI, len_136081)(tnode135647* n) {
	NI result;
	result = 0;
	{
		if (!(*n).kindU.S6.Sons == 0) goto LA3;
		result = 0;
	}
	goto LA1;
	LA3: ;
	{
		result = (*n).kindU.S6.Sons->Sup.len;
	}
	LA1: ;
	return result;
}

static N_INLINE(NI, safelen_136123)(tnode135647* n) {
	NI result;
	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = ((*n).Kind >= ((NU8) 0) && (*n).Kind <= ((NU8) 23));
		if (LOC3) goto LA4;
		LOC3 = (*n).kindU.S6.Sons == 0;
		LA4: ;
		if (!LOC3) goto LA5;
		result = 0;
	}
	goto LA1;
	LA5: ;
	{
		result = (*n).kindU.S6.Sons->Sup.len;
	}
	LA1: ;
	return result;
}

N_NIMCALL(void, importforwarded_264347)(tcontext261019* c, tnode135647* n, tintset132035* exceptset) {
	{
		if (!n == 0) goto LA3;
		goto BeforeRet;
	}
	LA3: ;
	switch ((*n).Kind) {
	case ((NU8) 117):
	{
		tnode135647* a_264360;
		NI i_264437;
		NI HEX3Atmp_264439;
		NI LOC6;
		NI res_264441;
		a_264360 = 0;
		i_264437 = 0;
		HEX3Atmp_264439 = 0;
		LOC6 = len_136081(n);
		HEX3Atmp_264439 = LOC6 - 1;
		res_264441 = 0;
		while (1) {
			tsym135677* s;
			if (!(res_264441 <= HEX3Atmp_264439)) goto LA7;
			i_264437 = res_264441;
			a_264360 = (*n).kindU.S6.Sons->data[i_264437];
			s = (*a_264360).kindU.S4.Sym;
			{
				if (!((*s).Kind == ((NU8) 6))) goto LA10;
				importallsymbolsexcept_264269(c, s, exceptset);
			}
			goto LA8;
			LA10: ;
			{
				NIM_BOOL LOC13;
				NIM_BOOL LOC15;
				LOC13 = empty_133107(exceptset);
				if (LOC13) goto LA14;
				LOC15 = contains_132820(exceptset, (*(*s).Name).Sup.Id);
				LOC13 = !(LOC15);
				LA14: ;
				if (!LOC13) goto LA16;
				rawimportsymbol_264057(c, s);
			}
			goto LA8;
			LA16: ;
			LA8: ;
			res_264441 += 1;
		} LA7: ;
	}
	break;
	case ((NU8) 118):
	{
		localerror_129673((*n).Info, ((NU16) 4), ((NimStringDesc*) &TMP2849));
	}
	break;
	default:
	{
		NI i_264425;
		NI HEX3Atmp_264442;
		NI LOC20;
		NI res_264444;
		i_264425 = 0;
		HEX3Atmp_264442 = 0;
		LOC20 = safelen_136123(n);
		HEX3Atmp_264442 = (NI64)(LOC20 - 1);
		res_264444 = 0;
		while (1) {
			if (!(res_264444 <= HEX3Atmp_264442)) goto LA21;
			i_264425 = res_264444;
			importforwarded_264347(c, (*n).kindU.S6.Sons->data[i_264425], exceptset);
			res_264444 += 1;
		} LA21: ;
	}
	break;
	}
	BeforeRet: ;
}

N_NIMCALL(tnode135647*, evalimport_264002)(tcontext261019* c, tnode135647* n) {
	tnode135647* result;
	tintset132035 emptyset;
	NI i_264464;
	NI HEX3Atmp_264497;
	NI LOC1;
	NI res_264499;
	result = 0;
	result = n;
	memset((void*)&emptyset, 0, sizeof(emptyset));
	i_264464 = 0;
	HEX3Atmp_264497 = 0;
	LOC1 = sonslen_136002(n);
	HEX3Atmp_264497 = (NI64)(LOC1 - 1);
	res_264499 = 0;
	while (1) {
		NI32 f;
		if (!(res_264499 <= HEX3Atmp_264497)) goto LA2;
		i_264464 = res_264499;
		f = checkmodulename_264049((*n).kindU.S6.Sons->data[i_264464]);
		{
			tsym135677* m;
			if (!!((f == ((NI32) -1)))) goto LA5;
			m = gimportmodule_224060((*c).Module, f);
			{
				if (!(((*m).Flags &(1<<((((NU8) 19))&31)))!=0)) goto LA9;
				message_129680((*(*n).kindU.S6.Sons->data[i_264464]).Info, ((NU16) 224), (*(*m).Name).S);
			}
			LA9: ;
			adddecl_262384(c, m);
			importallsymbolsexcept_264269(c, m, &emptyset);
			importforwarded_264347(c, (*m).Ast, &emptyset);
		}
		LA5: ;
		res_264499 += 1;
	} LA2: ;
	return result;
}

static N_INLINE(tcell38449*, usrtocell_41843)(void* usr) {
	tcell38449* result;
	result = 0;
	result = ((tcell38449*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell38449))))));
	return result;
}

static N_INLINE(void, rtladdzct_43002)(tcell38449* c) {
	addzct_41815(&gch_40442.Zct, c);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		tcell38449* c;
		if (!!((src == NIM_NIL))) goto LA3;
		c = usrtocell_41843(src);
		(*c).Refcount += 8;
	}
	LA3: ;
	{
		tcell38449* c;
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		c = usrtocell_41843((*dest));
		{
			(*c).Refcount -= 8;
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			rtladdzct_43002(c);
		}
		LA11: ;
	}
	LA7: ;
	(*dest) = src;
}

N_NIMCALL(tnode135647*, evalimportexcept_264573)(tcontext261019* c, tnode135647* n) {
	tnode135647* result;
	NI32 f;
	result = 0;
	result = n;
	checkminsonslen_261658(n, 2);
	f = checkmodulename_264049((*n).kindU.S6.Sons->data[0]);
	{
		tsym135677* m;
		tintset132035 exceptset;
		NI i_264609;
		NI HEX3Atmp_264622;
		NI LOC5;
		NI res_264624;
		if (!!((f == ((NI32) -1)))) goto LA3;
		m = gimportmodule_224060((*c).Module, f);
		asgnRefNoCycle((void**) &(*n).kindU.S6.Sons->data[0], newsymnode_135916(m));
		adddecl_262384(c, m);
		chckNil((void*)&exceptset);
		memset((void*)&exceptset, 0, sizeof(exceptset));
		initintset_132899(&exceptset);
		i_264609 = 0;
		HEX3Atmp_264622 = 0;
		LOC5 = sonslen_136002(n);
		HEX3Atmp_264622 = (NI64)(LOC5 - 1);
		res_264624 = 1;
		while (1) {
			tident131018* ident;
			if (!(res_264624 <= HEX3Atmp_264622)) goto LA6;
			i_264609 = res_264624;
			ident = consideracc_262006((*n).kindU.S6.Sons->data[i_264609]);
			incl_132842(&exceptset, (*ident).Sup.Id);
			res_264624 += 1;
		} LA6: ;
		importallsymbolsexcept_264269(c, m, &exceptset);
		importforwarded_264347(c, (*m).Ast, &exceptset);
	}
	LA3: ;
	return result;
}

N_NIMCALL(void, importsymbol_264187)(tcontext261019* c, tnode135647* n, tsym135677* frommod) {
	tident131018* ident;
	tsym135677* s;
	ident = consideracc_262006(n);
	s = strtableget_142084((*frommod).kindU.S3.Tab, ident);
	{
		if (!(s == NIM_NIL)) goto LA3;
		localerror_129673((*n).Info, ((NU16) 61), (*ident).S);
	}
	goto LA1;
	LA3: ;
	{
		{
			if (!((*s).Kind == ((NU8) 22))) goto LA8;
			loadstub_215571(s);
		}
		LA8: ;
		{
			if (!!(((4978560 &(1<<(((*s).Kind)&31)))!=0))) goto LA12;
			internalerror_129687((*n).Info, ((NimStringDesc*) &TMP2851));
		}
		LA12: ;
		switch ((*s).Kind) {
		case ((NU8) 12):
		case ((NU8) 13):
		case ((NU8) 14):
		case ((NU8) 16):
		case ((NU8) 17):
		case ((NU8) 15):
		{
			tidentiter142106 it;
			tsym135677* e;
			memset((void*)&it, 0, sizeof(it));
			e = initidentiter_142110(&it, (*frommod).kindU.S3.Tab, (*s).Name);
			while (1) {
				if (!!((e == NIM_NIL))) goto LA15;
				{
					if (!!(((*(*e).Name).Sup.Id == (*(*s).Name).Sup.Id))) goto LA18;
					internalerror_129687((*n).Info, ((NimStringDesc*) &TMP2852));
				}
				LA18: ;
				rawimportsymbol_264057(c, e);
				e = nextidentiter_142117(&it, (*frommod).kindU.S3.Tab);
			} LA15: ;
		}
		break;
		default:
		{
			rawimportsymbol_264057(c, s);
		}
		break;
		}
	}
	LA1: ;
}

N_NIMCALL(tnode135647*, evalfrom_264007)(tcontext261019* c, tnode135647* n) {
	tnode135647* result;
	NI32 f;
	result = 0;
	result = n;
	checkminsonslen_261658(n, 2);
	f = checkmodulename_264049((*n).kindU.S6.Sons->data[0]);
	{
		tsym135677* m;
		NI i_264539;
		NI HEX3Atmp_264566;
		NI LOC5;
		NI res_264568;
		if (!!((f == ((NI32) -1)))) goto LA3;
		m = gimportmodule_224060((*c).Module, f);
		asgnRefNoCycle((void**) &(*n).kindU.S6.Sons->data[0], newsymnode_135916(m));
		adddecl_262384(c, m);
		i_264539 = 0;
		HEX3Atmp_264566 = 0;
		LOC5 = sonslen_136002(n);
		HEX3Atmp_264566 = (NI64)(LOC5 - 1);
		res_264568 = 1;
		while (1) {
			if (!(res_264568 <= HEX3Atmp_264566)) goto LA6;
			i_264539 = res_264568;
			{
				if (!!(((*(*n).kindU.S6.Sons->data[i_264539]).Kind == ((NU8) 23)))) goto LA9;
				importsymbol_264187(c, (*n).kindU.S6.Sons->data[i_264539], m);
			}
			LA9: ;
			res_264568 += 1;
		} LA6: ;
	}
	LA3: ;
	return result;
}

N_NIMCALL(void, importallsymbols_264339)(tcontext261019* c, tsym135677* frommod) {
	tintset132035 exceptset;
	memset((void*)&exceptset, 0, sizeof(exceptset));
	importallsymbolsexcept_264269(c, frommod, &exceptset);
}
N_NOINLINE(void, importerInit)(void) {
}

N_NOINLINE(void, importerDatInit)(void) {
}

