/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/usr/src/extras/Nimrod/lib -o compiler/nimcache/intsets.o compiler/nimcache/intsets.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct tintset132035 tintset132035;
typedef struct ttrunk132031 ttrunk132031;
typedef struct ttrunkseq132033 ttrunkseq132033;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcell38449 tcell38449;
typedef struct tcellset38461 tcellset38461;
typedef struct tgcheap40416 tgcheap40416;
typedef struct tcellseq38465 tcellseq38465;
typedef struct tpagedesc38457 tpagedesc38457;
typedef struct tmemregion22010 tmemregion22010;
typedef struct tsmallchunk21243 tsmallchunk21243;
typedef struct tllchunk22004 tllchunk22004;
typedef struct tbigchunk21245 tbigchunk21245;
typedef struct tintset21218 tintset21218;
typedef struct ttrunk21214 ttrunk21214;
typedef struct tavlnode22008 tavlnode22008;
typedef struct tgcstat40414 tgcstat40414;
typedef struct tbasechunk21241 tbasechunk21241;
typedef struct tfreecell21233 tfreecell21233;
struct TGenericSeq {
NI len;
NI reserved;
};
struct tintset132035 {
NI Counter;
NI Max;
ttrunk132031* Head;
ttrunkseq132033* Data;
};
typedef N_NIMCALL_PTR(void, TY891) (void* p, NI op);
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY891 marker;
};
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NI TY21221[8];
struct ttrunk132031 {
ttrunk132031* Next;
NI Key;
TY21221 Bits;
};
struct tcell38449 {
NI Refcount;
TNimType* Typ;
};
struct tcellseq38465 {
NI Len;
NI Cap;
tcell38449** D;
};
struct tcellset38461 {
NI Counter;
NI Max;
tpagedesc38457* Head;
tpagedesc38457** Data;
};
typedef tsmallchunk21243* TY22022[512];
typedef ttrunk21214* ttrunkbuckets21216[256];
struct tintset21218 {
ttrunkbuckets21216 Data;
};
struct tmemregion22010 {
NI Minlargeobj;
NI Maxlargeobj;
TY22022 Freesmallchunks;
tllchunk22004* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk21245* Freechunkslist;
tintset21218 Chunkstarts;
tavlnode22008* Root;
tavlnode22008* Deleted;
tavlnode22008* Last;
tavlnode22008* Freeavlnodes;
};
struct tgcstat40414 {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct tgcheap40416 {
void* Stackbottom;
NI Cyclethreshold;
tcellseq38465 Zct;
tcellseq38465 Decstack;
tcellset38461 Cycleroots;
tcellseq38465 Tempstack;
NI Recgclock;
tmemregion22010 Region;
tgcstat40414 Stat;
};
struct tpagedesc38457 {
tpagedesc38457* Next;
NI Key;
TY21221 Bits;
};
struct tbasechunk21241 {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct tsmallchunk21243 {
  tbasechunk21241 Sup;
tsmallchunk21243* Next;
tsmallchunk21243* Prev;
tfreecell21233* Freelist;
NI Free;
NI Acc;
NF64 Data;
};
struct tllchunk22004 {
NI Size;
NI Acc;
tllchunk22004* Next;
};
struct tbigchunk21245 {
  tbasechunk21241 Sup;
tbigchunk21245* Next;
tbigchunk21245* Prev;
NI Align;
NF64 Data;
};
struct ttrunk21214 {
ttrunk21214* Next;
NI Key;
TY21221 Bits;
};
typedef tavlnode22008* TY22014[2];
struct tavlnode22008 {
TY22014 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct tfreecell21233 {
tfreecell21233* Next;
NI Zerofield;
};
struct ttrunkseq132033 {
  TGenericSeq Sup;
  ttrunk132031* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP899)(void* p, NI op);
N_NIMCALL(void, TMP900)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(ttrunk132031*, intsetget_132214)(tintset132035* t, NI key);
static N_INLINE(NI, nexttry_132207)(NI h, NI maxhash);
N_NIMCALL(void, incl_132842)(tintset132035* s, NI key);
N_NIMCALL(ttrunk132031*, intsetput_132659)(tintset132035* t, NI key);
static N_INLINE(NIM_BOOL, mustrehash_132046)(NI length, NI counter);
N_NIMCALL(void, intsetenlarge_132604)(tintset132035* t);
N_NIMCALL(void, intsetrawinsert_132234)(tintset132035* t, ttrunkseq132033** data, ttrunk132031* desc);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_43824)(tcell38449* c);
static N_INLINE(NIM_BOOL, canbecycleroot_41865)(tcell38449* c);
static N_INLINE(void, rtladdcycleroot_42436)(tcell38449* c);
N_NOINLINE(void, incl_39256)(tcellset38461* s, tcell38449* cell);
static N_INLINE(tcell38449*, usrtocell_41843)(void* usr);
static N_INLINE(void, decref_43402)(tcell38449* c);
static N_INLINE(void, rtladdzct_43002)(tcell38449* c);
N_NOINLINE(void, addzct_41815)(tcellseq38465* s, tcell38449* c);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
TNimType NTI132035; /* TIntSet */
extern TNimType NTI105; /* int */
TNimType NTI132031; /* TTrunk */
extern TNimType NTI21221; /* array[0..7, int] */
TNimType NTI132029; /* PTrunk */
TNimType NTI132033; /* TTrunkSeq */
extern tgcheap40416 gch_40442;
N_NIMCALL(void, TMP899)(void* p, NI op) {
	ttrunk132031* a;
	NI LOC1;
	a = (ttrunk132031*)p;
	nimGCvisit((void*)(*a).Next, op);
	for (LOC1 = 0; LOC1 < 8; LOC1++) {
	}
}
N_NIMCALL(void, TMP900)(void* p, NI op) {
	ttrunkseq132033* a;
	NI LOC1;
	a = (ttrunkseq132033*)p;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1], op);
	}
}

N_NIMCALL(void, initintset_132899)(tintset132035* Result) {
	unsureAsgnRef((void**) &(*Result).Data, (ttrunkseq132033*) newSeq((&NTI132033), 8));
	(*Result).Max = 7;
	(*Result).Counter = 0;
	unsureAsgnRef((void**) &(*Result).Head, NIM_NIL);
}

static N_INLINE(NI, nexttry_132207)(NI h, NI maxhash) {
	NI result;
	result = 0;
	result = (NI)((NI64)((NI64)(5 * h) + 1) & maxhash);
	return result;
}

N_NIMCALL(ttrunk132031*, intsetget_132214)(tintset132035* t, NI key) {
	ttrunk132031* result;
	NI h;
	result = 0;
	h = (NI)(key & (*t).Max);
	while (1) {
		if (!!(((*t).Data->data[h] == NIM_NIL))) goto LA1;
		{
			if (!((*(*t).Data->data[h]).Key == key)) goto LA4;
			result = (*t).Data->data[h];
			goto BeforeRet;
		}
		LA4: ;
		h = nexttry_132207(h, (*t).Max);
	} LA1: ;
	result = NIM_NIL;
	BeforeRet: ;
	return result;
}

static N_INLINE(NIM_BOOL, mustrehash_132046)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	result = 0;
	LOC1 = ((NI64)(length * 2) < (NI64)(counter * 3));
	if (LOC1) goto LA2;
	LOC1 = ((NI64)(length - counter) < 4);
	LA2: ;
	result = LOC1;
	return result;
}

static N_INLINE(NIM_BOOL, canbecycleroot_41865)(tcell38449* c) {
	NIM_BOOL result;
	result = 0;
	result = !((((*(*c).Typ).flags &(1<<((((NU8) 1))&7)))!=0));
	return result;
}

static N_INLINE(void, rtladdcycleroot_42436)(tcell38449* c) {
	{
		if (!!((((NI) ((NI)((*c).Refcount & 3))) == 3))) goto LA3;
		(*c).Refcount = (NI)((NI)((*c).Refcount & -4) | 3);
		incl_39256(&gch_40442.Cycleroots, c);
	}
	LA3: ;
}

static N_INLINE(void, incref_43824)(tcell38449* c) {
	(*c).Refcount = (NI)((NU64)((*c).Refcount) + (NU64)(8));
	{
		NIM_BOOL LOC3;
		LOC3 = canbecycleroot_41865(c);
		if (!LOC3) goto LA4;
		rtladdcycleroot_42436(c);
	}
	LA4: ;
}

static N_INLINE(tcell38449*, usrtocell_41843)(void* usr) {
	tcell38449* result;
	result = 0;
	result = ((tcell38449*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell38449))))));
	return result;
}

static N_INLINE(void, rtladdzct_43002)(tcell38449* c) {
	addzct_41815(&gch_40442.Zct, c);
}

static N_INLINE(void, decref_43402)(tcell38449* c) {
	{
		(*c).Refcount -= 8;
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		rtladdzct_43002(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		LOC6 = canbecycleroot_41865(c);
		if (!LOC6) goto LA7;
		rtladdcycleroot_42436(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tcell38449* LOC5;
		if (!!((src == NIM_NIL))) goto LA3;
		LOC5 = usrtocell_41843(src);
		incref_43824(LOC5);
	}
	LA3: ;
	{
		tcell38449* LOC10;
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		LOC10 = usrtocell_41843((*dest));
		decref_43402(LOC10);
	}
	LA8: ;
	(*dest) = src;
}

N_NIMCALL(void, intsetrawinsert_132234)(tintset132035* t, ttrunkseq132033** data, ttrunk132031* desc) {
	NI h;
	h = (NI)((*desc).Key & (*t).Max);
	while (1) {
		if (!!(((*data)->data[h] == NIM_NIL))) goto LA1;
		h = nexttry_132207(h, (*t).Max);
	} LA1: ;
	asgnRef((void**) &(*data)->data[h], desc);
}

N_NIMCALL(void, intsetenlarge_132604)(tintset132035* t) {
	ttrunkseq132033* n;
	NI oldmax;
	NI i_132630;
	NI res_132654;
	ttrunkseq132033* LOC6;
	n = 0;
	oldmax = (*t).Max;
	(*t).Max = (NI64)((NI64)((NI64)((*t).Max + 1) * 2) - 1);
	n = (ttrunkseq132033*) newSeq((&NTI132033), (NI64)((*t).Max + 1));
	i_132630 = 0;
	res_132654 = 0;
	while (1) {
		if (!(res_132654 <= oldmax)) goto LA1;
		i_132630 = res_132654;
		{
			if (!!(((*t).Data->data[i_132630] == NIM_NIL))) goto LA4;
			intsetrawinsert_132234(&(*t), &n, (*t).Data->data[i_132630]);
		}
		LA4: ;
		res_132654 += 1;
	} LA1: ;
	LOC6 = 0;
	LOC6 = (*t).Data;
	unsureAsgnRef((void**) &(*t).Data, n);
	n = LOC6;
}

N_NIMCALL(ttrunk132031*, intsetput_132659)(tintset132035* t, NI key) {
	ttrunk132031* result;
	NI h;
	result = 0;
	h = (NI)(key & (*t).Max);
	while (1) {
		if (!!(((*t).Data->data[h] == NIM_NIL))) goto LA1;
		{
			if (!((*(*t).Data->data[h]).Key == key)) goto LA4;
			result = (*t).Data->data[h];
			goto BeforeRet;
		}
		LA4: ;
		h = nexttry_132207(h, (*t).Max);
	} LA1: ;
	{
		NIM_BOOL LOC8;
		LOC8 = mustrehash_132046((NI64)((*t).Max + 1), (*t).Counter);
		if (!LOC8) goto LA9;
		intsetenlarge_132604(t);
	}
	LA9: ;
	(*t).Counter += 1;
	h = (NI)(key & (*t).Max);
	while (1) {
		if (!!(((*t).Data->data[h] == NIM_NIL))) goto LA11;
		h = nexttry_132207(h, (*t).Max);
	} LA11: ;
	result = (ttrunk132031*) newObj((&NTI132029), sizeof(ttrunk132031));
	asgnRef((void**) &(*result).Next, (*t).Head);
	(*result).Key = key;
	unsureAsgnRef((void**) &(*t).Head, result);
	asgnRef((void**) &(*t).Data->data[h], result);
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, incl_132842)(tintset132035* s, NI key) {
	ttrunk132031* t;
	NI u;
	t = intsetput_132659(s, (NI)((NU64)(key) >> (NU64)(9)));
	u = (NI)(key & 511);
	(*t).Bits[((NI)((NU64)(((NI) (u))) >> (NU64)(6)))- 0] = (NI)((*t).Bits[((NI)((NU64)(((NI) (u))) >> (NU64)(6)))- 0] | (NI)((NU64)(1) << (NU64)(((NI) ((NI)(((NI) (u)) & 63))))));
}

N_NIMCALL(NIM_BOOL, containsorincl_132875)(tintset132035* s, NI key) {
	NIM_BOOL result;
	ttrunk132031* t;
	result = 0;
	t = intsetget_132214(&(*s), (NI)((NU64)(key) >> (NU64)(9)));
	{
		NI u;
		if (!!((t == NIM_NIL))) goto LA3;
		u = (NI)(key & 511);
		result = !(((NI)((*t).Bits[((NI)((NU64)(((NI) (u))) >> (NU64)(6)))- 0] & (NI)((NU64)(1) << (NU64)(((NI) ((NI)(((NI) (u)) & 63)))))) == 0));
		{
			if (!!(result)) goto LA7;
			(*t).Bits[((NI)((NU64)(((NI) (u))) >> (NU64)(6)))- 0] = (NI)((*t).Bits[((NI)((NU64)(((NI) (u))) >> (NU64)(6)))- 0] | (NI)((NU64)(1) << (NU64)(((NI) ((NI)(((NI) (u)) & 63))))));
		}
		LA7: ;
	}
	goto LA1;
	LA3: ;
	{
		incl_132842(s, key);
		result = NIM_FALSE;
	}
	LA1: ;
	return result;
}

N_NIMCALL(NIM_BOOL, contains_132820)(tintset132035* s, NI key) {
	NIM_BOOL result;
	ttrunk132031* t;
	result = 0;
	t = intsetget_132214(s, (NI)((NU64)(key) >> (NU64)(9)));
	{
		NI u;
		if (!!((t == NIM_NIL))) goto LA3;
		u = (NI)(key & 511);
		result = !(((NI)((*t).Bits[((NI)((NU64)(((NI) (u))) >> (NU64)(6)))- 0] & (NI)((NU64)(1) << (NU64)(((NI) ((NI)(((NI) (u)) & 63)))))) == 0));
	}
	goto LA1;
	LA3: ;
	{
		result = NIM_FALSE;
	}
	LA1: ;
	return result;
}

N_NIMCALL(void, assign_132916)(tintset132035* dest, tintset132035* src) {
	ttrunk132031* it;
	(*dest).Counter = (*src).Counter;
	(*dest).Max = (*src).Max;
	unsureAsgnRef((void**) &(*dest).Data, (ttrunkseq132033*) newSeq((&NTI132033), (*src).Data->Sup.len));
	it = (*src).Head;
	while (1) {
		NI h;
		ttrunk132031* n;
		if (!!((it == NIM_NIL))) goto LA1;
		h = (NI)((*it).Key & (*dest).Max);
		while (1) {
			if (!!(((*dest).Data->data[h] == NIM_NIL))) goto LA2;
			h = nexttry_132207(h, (*dest).Max);
		} LA2: ;
		n = 0;
		n = (ttrunk132031*) newObj((&NTI132029), sizeof(ttrunk132031));
		asgnRef((void**) &(*n).Next, (*dest).Head);
		(*n).Key = (*it).Key;
		memcpy((void*)(*n).Bits, (NIM_CONST void*)(*it).Bits, sizeof((*n).Bits));
		unsureAsgnRef((void**) &(*dest).Head, n);
		asgnRef((void**) &(*dest).Data->data[h], n);
		it = (*it).Next;
	} LA1: ;
}

N_NIMCALL(void, excl_132853)(tintset132035* s, NI key) {
	ttrunk132031* t;
	t = intsetget_132214(&(*s), (NI)((NU64)(key) >> (NU64)(9)));
	{
		NI u;
		if (!!((t == NIM_NIL))) goto LA3;
		u = (NI)(key & 511);
		(*t).Bits[((NI)((NU64)(((NI) (u))) >> (NU64)(6)))- 0] = (NI)((*t).Bits[((NI)((NU64)(((NI) (u))) >> (NU64)(6)))- 0] & (NI)((NU64) ~((NI)((NU64)(1) << (NU64)(((NI) ((NI)(((NI) (u)) & 63))))))));
	}
	LA3: ;
}
N_NOINLINE(void, intsetsInit)(void) {
}

N_NOINLINE(void, intsetsDatInit)(void) {
static TNimNode* TMP897[4];
static TNimNode* TMP898[3];
static TNimNode TMP414[9];
NTI132035.size = sizeof(tintset132035);
NTI132035.kind = 18;
NTI132035.base = 0;
NTI132035.flags = 2;
TMP897[0] = &TMP414[1];
TMP414[1].kind = 1;
TMP414[1].offset = offsetof(tintset132035, Counter);
TMP414[1].typ = (&NTI105);
TMP414[1].name = "counter";
TMP897[1] = &TMP414[2];
TMP414[2].kind = 1;
TMP414[2].offset = offsetof(tintset132035, Max);
TMP414[2].typ = (&NTI105);
TMP414[2].name = "max";
TMP897[2] = &TMP414[3];
NTI132031.size = sizeof(ttrunk132031);
NTI132031.kind = 18;
NTI132031.base = 0;
TMP898[0] = &TMP414[5];
TMP414[5].kind = 1;
TMP414[5].offset = offsetof(ttrunk132031, Next);
TMP414[5].typ = (&NTI132029);
TMP414[5].name = "next";
TMP898[1] = &TMP414[6];
TMP414[6].kind = 1;
TMP414[6].offset = offsetof(ttrunk132031, Key);
TMP414[6].typ = (&NTI105);
TMP414[6].name = "key";
TMP898[2] = &TMP414[7];
TMP414[7].kind = 1;
TMP414[7].offset = offsetof(ttrunk132031, Bits);
TMP414[7].typ = (&NTI21221);
TMP414[7].name = "bits";
TMP414[4].len = 3; TMP414[4].kind = 2; TMP414[4].sons = &TMP898[0];
NTI132031.node = &TMP414[4];
NTI132029.size = sizeof(ttrunk132031*);
NTI132029.kind = 22;
NTI132029.base = (&NTI132031);
NTI132029.marker = TMP899;
TMP414[3].kind = 1;
TMP414[3].offset = offsetof(tintset132035, Head);
TMP414[3].typ = (&NTI132029);
TMP414[3].name = "head";
TMP897[3] = &TMP414[8];
NTI132033.size = sizeof(ttrunkseq132033*);
NTI132033.kind = 24;
NTI132033.base = (&NTI132029);
NTI132033.flags = 2;
NTI132033.marker = TMP900;
TMP414[8].kind = 1;
TMP414[8].offset = offsetof(tintset132035, Data);
TMP414[8].typ = (&NTI132033);
TMP414[8].name = "data";
TMP414[0].len = 4; TMP414[0].kind = 2; TMP414[0].sons = &TMP897[0];
NTI132035.node = &TMP414[0];
}

