/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/usr/src/extras/Nimrod/lib -o compiler/nimcache/lambdalifting.o compiler/nimcache/lambdalifting.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct tsym135677 tsym135677;
typedef struct tidobj131012 tidobj131012;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct ttypeseq135679 ttypeseq135679;
typedef struct ttype135681 ttype135681;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY135771 TY135771;
typedef struct tinstantiation135667 tinstantiation135667;
typedef struct tscope135671 tscope135671;
typedef struct tstrtable135651 tstrtable135651;
typedef struct tsymseq135649 tsymseq135649;
typedef struct tident131018 tident131018;
typedef struct tlineinfo128308 tlineinfo128308;
typedef struct tnode135647 tnode135647;
typedef struct tloc135661 tloc135661;
typedef struct trope126007 trope126007;
typedef struct tlib135665 tlib135665;
typedef struct NimStringDesc NimStringDesc;
typedef struct tnodeseq135641 tnodeseq135641;
typedef struct TY71082 TY71082;
typedef struct tcell38449 tcell38449;
typedef struct tcellseq38465 tcellseq38465;
typedef struct tgcheap40416 tgcheap40416;
typedef struct tcellset38461 tcellset38461;
typedef struct tpagedesc38457 tpagedesc38457;
typedef struct tmemregion22010 tmemregion22010;
typedef struct tsmallchunk21243 tsmallchunk21243;
typedef struct tllchunk22004 tllchunk22004;
typedef struct tbigchunk21245 tbigchunk21245;
typedef struct tintset21218 tintset21218;
typedef struct ttrunk21214 ttrunk21214;
typedef struct tavlnode22008 tavlnode22008;
typedef struct tgcstat40414 tgcstat40414;
typedef struct toutercontext242023 toutercontext242023;
typedef struct tenv242019 tenv242019;
typedef struct tintset132035 tintset132035;
typedef struct ttrunk132031 ttrunk132031;
typedef struct ttrunkseq132033 ttrunkseq132033;
typedef struct tidtable135693 tidtable135693;
typedef struct tidpairseq135691 tidpairseq135691;
typedef struct tidpair135689 tidpair135689;
typedef struct tidnodetable135699 tidnodetable135699;
typedef struct tidnodepairseq135697 tidnodepairseq135697;
typedef struct tidnodepair135695 tidnodepair135695;
typedef struct TY242030 TY242030;
typedef struct tdep242017 tdep242017;
typedef struct tinnercontext242021 tinnercontext242021;
typedef struct titercontext245236 titercontext245236;
typedef struct TY135763 TY135763;
typedef struct tlistentry100011 tlistentry100011;
typedef struct tbasechunk21241 tbasechunk21241;
typedef struct tfreecell21233 tfreecell21233;
typedef N_NIMCALL_PTR(void, TY891) (void* p, NI op);
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY891 marker;
};
struct TNimObject {
TNimType* m_type;
};
struct tidobj131012 {
  TNimObject Sup;
NI Id;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct tstrtable135651 {
NI Counter;
tsymseq135649* Data;
};
struct tlineinfo128308 {
NI16 Line;
NI16 Col;
NI32 Fileindex;
};
struct tloc135661 {
NU8 K;
NU8 S;
NU8 Flags;
ttype135681* T;
trope126007* R;
trope126007* Heaproot;
NI A;
};
struct tsym135677 {
  tidobj131012 Sup;
NU8 Kind;
union {
struct {ttypeseq135679* Typeinstcache;
} S1;
struct {TY135771* Procinstcache;
tscope135671* Scope;
} S2;
struct {TY135771* Usedgenerics;
tstrtable135651 Tab;
} S3;
} kindU;
NU16 Magic;
ttype135681* Typ;
tident131018* Name;
tlineinfo128308 Info;
tsym135677* Owner;
NU32 Flags;
tnode135647* Ast;
NU32 Options;
NI Position;
NI Offset;
tloc135661 Loc;
tlib135665* Annex;
tnode135647* Constraint;
};
struct ttype135681 {
  tidobj131012 Sup;
NU8 Kind;
NU8 Callconv;
NU32 Flags;
ttypeseq135679* Sons;
tnode135647* N;
tsym135677* Destructor;
tsym135677* Owner;
tsym135677* Sym;
NI64 Size;
NI Align;
tloc135661 Loc;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
struct tnode135647 {
ttype135681* Typ;
tlineinfo128308 Info;
NU8 Flags;
NU8 Kind;
union {
struct {NI64 Intval;
} S1;
struct {NF64 Floatval;
} S2;
struct {NimStringDesc* Strval;
} S3;
struct {tsym135677* Sym;
} S4;
struct {tident131018* Ident;
} S5;
struct {tnodeseq135641* Sons;
} S6;
} kindU;
NimStringDesc* Comment;
};
struct TY71082 {
NimStringDesc* Field0;
NI Field1;
};
struct tcell38449 {
NI Refcount;
TNimType* Typ;
};
struct tcellseq38465 {
NI Len;
NI Cap;
tcell38449** D;
};
struct tcellset38461 {
NI Counter;
NI Max;
tpagedesc38457* Head;
tpagedesc38457** Data;
};
typedef tsmallchunk21243* TY22022[512];
typedef ttrunk21214* ttrunkbuckets21216[256];
struct tintset21218 {
ttrunkbuckets21216 Data;
};
struct tmemregion22010 {
NI Minlargeobj;
NI Maxlargeobj;
TY22022 Freesmallchunks;
tllchunk22004* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk21245* Freechunkslist;
tintset21218 Chunkstarts;
tavlnode22008* Root;
tavlnode22008* Deleted;
tavlnode22008* Last;
tavlnode22008* Freeavlnodes;
};
struct tgcstat40414 {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct tgcheap40416 {
void* Stackbottom;
NI Cyclethreshold;
tcellseq38465 Zct;
tcellseq38465 Decstack;
tcellset38461 Cycleroots;
tcellseq38465 Tempstack;
NI Recgclock;
tmemregion22010 Region;
tgcstat40414 Stat;
};
struct tintset132035 {
NI Counter;
NI Max;
ttrunk132031* Head;
ttrunkseq132033* Data;
};
struct tidpair135689 {
tidobj131012* Key;
TNimObject* Val;
};
struct tidtable135693 {
NI Counter;
tidpairseq135691* Data;
};
struct tidnodepair135695 {
tidobj131012* Key;
tnode135647* Val;
};
struct tidnodetable135699 {
NI Counter;
tidnodepairseq135697* Data;
};
struct toutercontext242023 {
tsym135677* Fn;
tenv242019* Currentenv;
tintset132035 Capturedvars;
tintset132035 Processed;
tidtable135693 Localstoenv;
tidnodetable135699 Localstoaccess;
tidtable135693 Lambdastoenv;
toutercontext242023* Up;
};
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tdep242017 {
tenv242019* Field0;
tsym135677* Field1;
};
struct tenv242019 {
  TNimObject Sup;
tnode135647* Attachednode;
tsym135677* Closure;
tsymseq135649* Capturedvars;
TY242030* Deps;
tenv242019* Up;
ttype135681* Tup;
};
struct tinnercontext242021 {
tsym135677* Fn;
tsym135677* Closureparam;
tidnodetable135699 Localstoaccess;
};
struct tident131018 {
  tidobj131012 Sup;
NimStringDesc* S;
tident131018* Next;
NI H;
};
struct titercontext245236 {
tsym135677* Iter;
tsym135677* Closureparam;
tsym135677* State;
tsym135677* Resultsym;
tintset132035 Capturedvars;
ttype135681* Tup;
};
struct tinstantiation135667 {
tsym135677* Sym;
ttypeseq135679* Concretetypes;
TY135763* Usedby;
};
struct tscope135671 {
NI Depthlevel;
tstrtable135651 Symbols;
tscope135671* Parent;
};
struct trope126007 {
  TNimObject Sup;
trope126007* Left;
trope126007* Right;
NI Length;
NimStringDesc* Data;
};
struct tlistentry100011 {
  TNimObject Sup;
tlistentry100011* Prev;
tlistentry100011* Next;
};
struct tlib135665 {
  tlistentry100011 Sup;
NU8 Kind;
NIM_BOOL Generated;
NIM_BOOL Isoverriden;
trope126007* Name;
tnode135647* Path;
};
typedef NI TY21221[8];
struct tpagedesc38457 {
tpagedesc38457* Next;
NI Key;
TY21221 Bits;
};
struct tbasechunk21241 {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct tsmallchunk21243 {
  tbasechunk21241 Sup;
tsmallchunk21243* Next;
tsmallchunk21243* Prev;
tfreecell21233* Freelist;
NI Free;
NI Acc;
NF64 Data;
};
struct tllchunk22004 {
NI Size;
NI Acc;
tllchunk22004* Next;
};
struct tbigchunk21245 {
  tbasechunk21241 Sup;
tbigchunk21245* Next;
tbigchunk21245* Prev;
NI Align;
NF64 Data;
};
struct ttrunk21214 {
ttrunk21214* Next;
NI Key;
TY21221 Bits;
};
typedef tavlnode22008* TY22014[2];
struct tavlnode22008 {
TY22014 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct ttrunk132031 {
ttrunk132031* Next;
NI Key;
TY21221 Bits;
};
struct tfreecell21233 {
tfreecell21233* Next;
NI Zerofield;
};
struct ttypeseq135679 {
  TGenericSeq Sup;
  ttype135681* data[SEQ_DECL_SIZE];
};
struct TY135771 {
  TGenericSeq Sup;
  tinstantiation135667* data[SEQ_DECL_SIZE];
};
struct tsymseq135649 {
  TGenericSeq Sup;
  tsym135677* data[SEQ_DECL_SIZE];
};
struct tnodeseq135641 {
  TGenericSeq Sup;
  tnode135647* data[SEQ_DECL_SIZE];
};
struct ttrunkseq132033 {
  TGenericSeq Sup;
  ttrunk132031* data[SEQ_DECL_SIZE];
};
struct tidpairseq135691 {
  TGenericSeq Sup;
  tidpair135689 data[SEQ_DECL_SIZE];
};
struct tidnodepairseq135697 {
  TGenericSeq Sup;
  tidnodepair135695 data[SEQ_DECL_SIZE];
};
struct TY242030 {
  TGenericSeq Sup;
  tdep242017 data[SEQ_DECL_SIZE];
};
struct TY135763 {
  TGenericSeq Sup;
  NI32 data[SEQ_DECL_SIZE];
};
static N_INLINE(NIM_BOOL, interestingvar_242999)(tsym135677* s);
N_NIMCALL(NIM_BOOL, isgenericroutine_140345)(tsym135677* s);
N_NIMCALL(tnode135647*, newnodeit_135925)(NU8 kind, tlineinfo128308 info, ttype135681* typ);
N_NIMCALL(tsym135677*, copysym_135968)(tsym135677* s, NIM_BOOL keepid);
N_NIMCALL(tsym135677*, gethiddenparam_242647)(tsym135677* routine);
static N_INLINE(tnode135647*, lastson_136010)(tnode135647* n);
static N_INLINE(NI, sonslen_136002)(tnode135647* n);
N_NIMCALL(tnode135647*, newnodei_135920)(NU8 kind, tlineinfo128308 info);
N_NIMCALL(void, addvar_244079)(tnode135647* father, tnode135647* v);
N_NIMCALL(void, addson_136028)(tnode135647* father, tnode135647* son);
N_NIMCALL(tnode135647*, newsymnode_135916)(tsym135677* sym);
N_NIMCALL(void, add_136175)(tnode135647* father, tnode135647* son);
N_NIMCALL(tnode135647*, newcall_242611)(tsym135677* a, tsym135677* b);
N_NIMCALL(tsym135677*, getsyssym_218034)(NimStringDesc* name);
N_NIMCALL(tnode135647*, makeclosure_243217)(tsym135677* prc, tsym135677* env, tlineinfo128308 info);
N_NIMCALL(ttype135681*, getsystype_218018)(NU8 kind);
static N_INLINE(NI, len_136081)(tnode135647* n);
static N_INLINE(tnode135647*, HEX5BHEX5D_136276)(tnode135647* n, NI i);
N_NIMCALL(void, internalerror_129699)(NimStringDesc* errmsg);
N_NIMCALL(tnode135647*, newnodei_137203)(NU8 kind, tlineinfo128308 info, NI children);
N_NIMCALL(tnode135647*, newinttypenode_135895)(NU8 kind, NI64 intval, ttype135681* typ);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell38449*, usrtocell_41843)(void* usr);
static N_INLINE(void, rtladdzct_43002)(tcell38449* c);
N_NOINLINE(void, addzct_41815)(tcellseq38465* s, tcell38449* c);
N_NIMCALL(toutercontext242023*, newoutercontext_242046)(tsym135677* fn, toutercontext242023* up);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP2727)(void* p, NI op);
N_NIMCALL(void, TMP2728)(void* p, NI op);
N_NIMCALL(void, TMP2729)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(void, initintset_132899)(tintset132035* Result);
N_NIMCALL(void, initidnodetable_135951)(tidnodetable135699* x);
N_NIMCALL(void, initidtable_135941)(tidtable135693* x);
N_NIMCALL(tnode135647*, closurecreationpoint_243669)(tnode135647* n);
N_NIMCALL(tenv242019*, newenv_242093)(tsym135677* outerproc, tenv242019* up, tnode135647* n);
static N_INLINE(void, nimGCunref)(void* p);
static N_INLINE(void, decref_43402)(tcell38449* c);
static N_INLINE(NIM_BOOL, canbecycleroot_41865)(tcell38449* c);
static N_INLINE(void, rtladdcycleroot_42436)(tcell38449* c);
N_NOINLINE(void, incl_39256)(tcellset38461* s, tcell38449* cell);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(ttype135681*, newtype_135881)(NU8 kind, tsym135677* owner);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_43824)(tcell38449* c);
N_NIMCALL(void, internalerror_129687)(tlineinfo128308 info, NimStringDesc* errmsg);
N_NIMCALL(void, idtableput_142147)(tidtable135693* t, tidobj131012* key, TNimObject* val);
N_NIMCALL(void, searchforinnerprocs_243675)(toutercontext242023* o, tnode135647* n);
static N_INLINE(NIM_BOOL, isinnerproc_242813)(tsym135677* s, tsym135677* outerproc);
N_NIMCALL(NIM_BOOL, containsorincl_132875)(tintset132035* s, NI key);
N_NIMCALL(tinnercontext242021*, newinnercontext_242071)(tsym135677* fn);
N_NIMCALL(void, TMP2732)(void* p, NI op);
N_NIMCALL(tnode135647*, getbody_215576)(tsym135677* s);
N_NIMCALL(void, gathervars_243047)(toutercontext242023* o, tinnercontext242021* i, tnode135647* n);
N_NIMCALL(void, capturevar_242910)(toutercontext242023* o, tinnercontext242021* i, tsym135677* local, tlineinfo128308 info);
N_NIMCALL(TNimObject*, idtableget_142137)(tidtable135693 t, tidobj131012* key);
static N_INLINE(NIM_BOOL, illegalcapture_242888)(tsym135677* s);
N_NIMCALL(ttype135681*, skiptypes_202116)(ttype135681* t, NU64 kinds);
N_NIMCALL(void, localerror_129673)(tlineinfo128308 info, NU16 msg, NimStringDesc* arg);
N_NIMCALL(tnode135647*, idnodetableget_142159)(tidnodetable135699 t, tidobj131012* key);
N_NIMCALL(void, addclosureparam_242839)(tinnercontext242021* i, tenv242019* e);
N_NIMCALL(tsym135677*, newsym_135874)(NU8 symkind, tident131018* name, tsym135677* owner, tlineinfo128308 info);
N_NIMCALL(tident131018*, getident_131448)(NimStringDesc* identifier);
N_NIMCALL(void, rawaddson_138897)(ttype135681* father, ttype135681* son);
N_NIMCALL(void, addhiddenparam_242618)(tsym135677* routine, tsym135677* param);
N_NIMCALL(void, addcapturedvar_242162)(tenv242019* e, tsym135677* v);
N_NIMCALL(TGenericSeq*, incrSeq)(TGenericSeq* seq, NI elemsize);
N_NIMCALL(void, addfield_242154)(ttype135681* tup, tsym135677* s);
static N_INLINE(ttype135681*, skipintlit_218324)(ttype135681* t);
static N_INLINE(NI, sonslen_136006)(ttype135681* n);
N_NIMCALL(tnode135647*, indirectaccess_242424)(tnode135647* a, tsym135677* b, tlineinfo128308 info);
N_NIMCALL(tsym135677*, getsymfromlist_142176)(tnode135647* list, tident131018* ident, NI start);
N_NIMCALL(tsym135677*, adddep_242233)(tenv242019* e, tenv242019* d, tsym135677* owner);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(void, incl_132842)(tintset132035* s, NI key);
N_NIMCALL(void, idnodetableput_142164)(tidnodetable135699* t, tidobj131012* key, tnode135647* val);
N_NIMCALL(void, dummyclosureparam_242858)(toutercontext242023* o, tinnercontext242021* i);
N_NIMCALL(tnode135647*, transforminnerproc_243236)(toutercontext242023* o, tinnercontext242021* i, tnode135647* n);
N_NIMCALL(tnode135647*, transformouterproc_244164)(toutercontext242023* o, tnode135647* n);
N_NIMCALL(tnode135647*, generateclosurecreation_244116)(toutercontext242023* o, tenv242019* scope);
N_NIMCALL(tsym135677*, getclosurevar_244086)(toutercontext242023* o, tenv242019* e);
N_NIMCALL(tnode135647*, indirectaccess_242603)(tsym135677* a, tsym135677* b, tlineinfo128308 info);
N_NIMCALL(tnode135647*, newasgnstmt_244051)(tnode135647* le, tnode135647* ri, tlineinfo128308 info);
N_NIMCALL(NIM_BOOL, contains_132820)(tintset132035* s, NI key);
N_NIMCALL(tnode135647*, transformouterconv_243171)(tnode135647* n);
N_NIMCALL(tnode135647*, generatethunk_243157)(tnode135647* prc, ttype135681* dest);
N_NIMCALL(ttype135681*, getstatetype_245637)(tsym135677* iter);
N_NIMCALL(tnode135647*, newintnode_135890)(NU8 kind, NI64 intval);
N_NIMCALL(tsym135677*, newiterresult_245244)(tsym135677* iter);
N_NIMCALL(tnode135647*, transfiterbody_245428)(titercontext245236* c, tnode135647* n);
static N_INLINE(NIM_BOOL, interestingitervar_245403)(tsym135677* s);
N_NIMCALL(NimStringDesc*, HEX24_129777)(TY71082 x);
STRING_LITERAL(TMP2457, "internalNew", 11);
STRING_LITERAL(TMP2462, "compiler/lambdalifting.nim", 26);
NIM_CONST TY71082 TMP2461 = {((NimStringDesc*) &TMP2462),
754}
;
STRING_LITERAL(TMP2730, "liftLambdas: strange params", 27);
STRING_LITERAL(TMP2733, ":env", 4);
STRING_LITERAL(TMP2734, ":up", 3);
STRING_LITERAL(TMP2735, "no environment computed", 23);
STRING_LITERAL(TMP2736, "too complex environment handling required", 41);
STRING_LITERAL(TMP2737, "transformOuter", 14);
STRING_LITERAL(TMP2738, ":state", 6);
extern tnode135647* emptynode_136305;
extern tgcheap40416 gch_40442;
extern NU8 gcmd_105110;
TNimType NTI242023; /* TOuterContext */
extern TNimType NTI135645; /* PSym */
extern TNimType NTI1009; /* TObject */
TNimType NTI242019; /* TEnv */
extern TNimType NTI135639; /* PNode */
extern TNimType NTI135649; /* TSymSeq */
TNimType NTI242017; /* TDep */
TNimType NTI242030; /* seq[TDep] */
extern TNimType NTI135643; /* PType */
TNimType NTI242015; /* PEnv */
extern TNimType NTI132035; /* TIntSet */
extern TNimType NTI135693; /* TIdTable */
extern TNimType NTI135699; /* TIdNodeTable */
TNimType NTI242013; /* POuterContext */
TNimType NTI242021; /* TInnerContext */
TNimType NTI242011; /* PInnerContext */

static N_INLINE(NIM_BOOL, interestingvar_242999)(tsym135677* s) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	result = 0;
	LOC1 = ((1051432 &(1<<(((*s).Kind)&31)))!=0);
	if (!(LOC1)) goto LA2;
	LOC1 = !((((*s).Flags &(1<<((((NU8) 3))&31)))!=0));
	LA2: ;
	result = LOC1;
	return result;
}

N_NIMCALL(void, semcapturesym_243024)(tsym135677* s, tsym135677* owner) {
	{
		NIM_BOOL LOC3;
		NIM_BOOL LOC4;
		LOC4 = interestingvar_242999(s);
		if (!(LOC4)) goto LA5;
		LOC4 = !(((*owner).Sup.Id == (*(*s).Owner).Sup.Id));
		LA5: ;
		LOC3 = LOC4;
		if (!(LOC3)) goto LA6;
		LOC3 = !(((*s).Kind == ((NU8) 11)));
		LA6: ;
		if (!LOC3) goto LA7;
		{
			NIM_BOOL LOC11;
			NIM_BOOL LOC13;
			LOC11 = !(((*owner).Typ == NIM_NIL));
			if (!(LOC11)) goto LA12;
			LOC13 = isgenericroutine_140345(owner);
			LOC11 = !(LOC13);
			LA12: ;
			if (!LOC11) goto LA14;
			(*(*owner).Typ).Callconv = ((NU8) 8);
		}
		LA14: ;
	}
	LA7: ;
}

static N_INLINE(NI, sonslen_136002)(tnode135647* n) {
	NI result;
	result = 0;
	{
		if (!(*n).kindU.S6.Sons == 0) goto LA3;
		result = 0;
	}
	goto LA1;
	LA3: ;
	{
		result = (*n).kindU.S6.Sons->Sup.len;
	}
	LA1: ;
	return result;
}

static N_INLINE(tnode135647*, lastson_136010)(tnode135647* n) {
	tnode135647* result;
	NI LOC1;
	result = 0;
	LOC1 = sonslen_136002(n);
	result = (*n).kindU.S6.Sons->data[(NI64)(LOC1 - 1)];
	return result;
}

N_NIMCALL(tsym135677*, gethiddenparam_242647)(tsym135677* routine) {
	tsym135677* result;
	tnode135647* params;
	tnode135647* hidden;
	result = 0;
	params = (*(*routine).Ast).kindU.S6.Sons->data[3];
	hidden = lastson_136010(params);
	result = (*hidden).kindU.S4.Sym;
	return result;
}

N_NIMCALL(void, addvar_244079)(tnode135647* father, tnode135647* v) {
	tnode135647* vpart;
	vpart = newnodei_135920(((NU8) 35), (*v).Info);
	addson_136028(vpart, v);
	addson_136028(vpart, emptynode_136305);
	addson_136028(vpart, emptynode_136305);
	addson_136028(father, vpart);
}

N_NIMCALL(tnode135647*, newcall_242611)(tsym135677* a, tsym135677* b) {
	tnode135647* result;
	tnode135647* LOC1;
	tnode135647* LOC2;
	result = 0;
	result = newnodei_135920(((NU8) 27), (*a).Info);
	LOC1 = 0;
	LOC1 = newsymnode_135916(a);
	add_136175(result, LOC1);
	LOC2 = 0;
	LOC2 = newsymnode_135916(b);
	add_136175(result, LOC2);
	return result;
}

N_NIMCALL(tnode135647*, makeclosure_243217)(tsym135677* prc, tsym135677* env, tlineinfo128308 info) {
	tnode135647* result;
	tnode135647* LOC1;
	result = 0;
	result = newnodeit_135925(((NU8) 148), info, (*prc).Typ);
	LOC1 = 0;
	LOC1 = newsymnode_135916(prc);
	add_136175(result, LOC1);
	{
		ttype135681* LOC6;
		tnode135647* LOC7;
		if (!(env == NIM_NIL)) goto LA4;
		LOC6 = 0;
		LOC6 = getsystype_218018(((NU8) 5));
		LOC7 = 0;
		LOC7 = newnodeit_135925(((NU8) 23), info, LOC6);
		add_136175(result, LOC7);
	}
	goto LA2;
	LA4: ;
	{
		tnode135647* LOC9;
		LOC9 = 0;
		LOC9 = newsymnode_135916(env);
		add_136175(result, LOC9);
	}
	LA2: ;
	return result;
}

N_NIMCALL(tnode135647*, liftitersym_245693)(tnode135647* n) {
	tnode135647* result;
	tsym135677* iter;
	tsym135677* env;
	tsym135677* LOC1;
	tnode135647* v;
	tnode135647* LOC2;
	tsym135677* LOC3;
	tnode135647* LOC4;
	tnode135647* LOC5;
	result = 0;
	result = newnodeit_135925(((NU8) 124), (*n).Info, (*n).Typ);
	iter = (*n).kindU.S4.Sym;
	LOC1 = 0;
	LOC1 = gethiddenparam_242647(iter);
	env = copysym_135968(LOC1, NIM_FALSE);
	(*env).Kind = ((NU8) 9);
	v = newnodei_135920(((NU8) 99), (*n).Info);
	LOC2 = 0;
	LOC2 = newsymnode_135916(env);
	addvar_244079(v, LOC2);
	add_136175(result, v);
	LOC3 = 0;
	LOC3 = getsyssym_218034(((NimStringDesc*) &TMP2457));
	LOC4 = 0;
	LOC4 = newcall_242611(LOC3, env);
	add_136175(result, LOC4);
	LOC5 = 0;
	LOC5 = makeclosure_243217(iter, env, (*n).Info);
	add_136175(result, LOC5);
	return result;
}

static N_INLINE(NI, len_136081)(tnode135647* n) {
	NI result;
	result = 0;
	{
		if (!(*n).kindU.S6.Sons == 0) goto LA3;
		result = 0;
	}
	goto LA1;
	LA3: ;
	{
		result = (*n).kindU.S6.Sons->Sup.len;
	}
	LA1: ;
	return result;
}

static N_INLINE(tnode135647*, HEX5BHEX5D_136276)(tnode135647* n, NI i) {
	tnode135647* result;
	result = 0;
	result = (*n).kindU.S6.Sons->data[i];
	return result;
}

static N_INLINE(tcell38449*, usrtocell_41843)(void* usr) {
	tcell38449* result;
	result = 0;
	result = ((tcell38449*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell38449))))));
	return result;
}

static N_INLINE(void, rtladdzct_43002)(tcell38449* c) {
	addzct_41815(&gch_40442.Zct, c);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		tcell38449* c;
		if (!!((src == NIM_NIL))) goto LA3;
		c = usrtocell_41843(src);
		(*c).Refcount += 8;
	}
	LA3: ;
	{
		tcell38449* c;
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		c = usrtocell_41843((*dest));
		{
			(*c).Refcount -= 8;
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			rtladdzct_43002(c);
		}
		LA11: ;
	}
	LA7: ;
	(*dest) = src;
}

N_NIMCALL(tnode135647*, liftforloop_245805)(tnode135647* body) {
	tnode135647* result;
	NI l;
	tnode135647* call;
	tsym135677* env;
	tnode135647* loopbody;
	tnode135647* whileloop;
	ttype135681* LOC22;
	tnode135647* v2;
	tnode135647* vpart;
	NU8 LOC23;
	NI i_246033;
	NI HEX3Atmp_246291;
	NI res_246293;
	tnode135647* bs;
	result = 0;
	l = len_136081(body);
	{
		NIM_BOOL LOC3;
		tnode135647* LOC5;
		NimStringDesc* LOC8;
		LOC3 = ((*body).Kind == ((NU8) 94));
		if (!(LOC3)) goto LA4;
		LOC5 = 0;
		LOC5 = HEX5BHEX5D_136276(body, (NI64)(l - 2));
		LOC3 = ((*LOC5).Kind == ((NU8) 27) || (*LOC5).Kind == ((NU8) 29) || (*LOC5).Kind == ((NU8) 30) || (*LOC5).Kind == ((NU8) 31) || (*LOC5).Kind == ((NU8) 26) || (*LOC5).Kind == ((NU8) 28) || (*LOC5).Kind == ((NU8) 32));
		LA4: ;
		if (!!(LOC3)) goto LA6;
		LOC8 = 0;
		LOC8 = HEX24_129777(TMP2461);
		internalerror_129699(LOC8);
	}
	LA6: ;
	call = HEX5BHEX5D_136276(body, (NI64)(l - 2));
	result = newnodei_135920(((NU8) 114), (*body).Info);
	env = 0;
	{
		NIM_BOOL LOC11;
		tnode135647* LOC12;
		tnode135647* LOC14;
		tsym135677* iter;
		tnode135647* LOC17;
		tsym135677* LOC18;
		tnode135647* v;
		tnode135647* LOC19;
		tsym135677* LOC20;
		tnode135647* LOC21;
		LOC12 = 0;
		LOC12 = HEX5BHEX5D_136276(call, 0);
		LOC11 = ((*LOC12).Kind == ((NU8) 3));
		if (!(LOC11)) goto LA13;
		LOC14 = 0;
		LOC14 = HEX5BHEX5D_136276(call, 0);
		LOC11 = ((*(*LOC14).kindU.S4.Sym).Kind == ((NU8) 14));
		LA13: ;
		if (!LOC11) goto LA15;
		LOC17 = 0;
		LOC17 = HEX5BHEX5D_136276(call, 0);
		iter = (*LOC17).kindU.S4.Sym;
		LOC18 = 0;
		LOC18 = gethiddenparam_242647(iter);
		env = copysym_135968(LOC18, NIM_FALSE);
		v = newnodei_135920(((NU8) 99), (*body).Info);
		LOC19 = 0;
		LOC19 = newsymnode_135916(env);
		addvar_244079(v, LOC19);
		add_136175(result, v);
		LOC20 = 0;
		LOC20 = getsyssym_218034(((NimStringDesc*) &TMP2457));
		LOC21 = 0;
		LOC21 = newcall_242611(LOC20, env);
		add_136175(result, LOC21);
	}
	LA15: ;
	loopbody = newnodei_137203(((NU8) 114), (*body).Info, 3);
	whileloop = newnodei_137203(((NU8) 96), (*body).Info, 2);
	LOC22 = 0;
	LOC22 = getsystype_218018(((NU8) 1));
	asgnRefNoCycle((void**) &(*whileloop).kindU.S6.Sons->data[0], newinttypenode_135895(((NU8) 6), 1, LOC22));
	asgnRefNoCycle((void**) &(*whileloop).kindU.S6.Sons->data[1], loopbody);
	add_136175(result, whileloop);
	v2 = newnodei_135920(((NU8) 100), (*body).Info);
	{
		if (!(l == 3)) goto LA26;
		LOC23 = ((NU8) 35);
	}
	goto LA24;
	LA26: ;
	{
		LOC23 = ((NU8) 36);
	}
	LA24: ;
	vpart = newnodei_135920(LOC23, (*body).Info);
	i_246033 = 0;
	HEX3Atmp_246291 = 0;
	HEX3Atmp_246291 = (NI64)(l - 3);
	res_246293 = 0;
	while (1) {
		tnode135647* LOC30;
		tnode135647* LOC31;
		if (!(res_246293 <= HEX3Atmp_246291)) goto LA29;
		i_246033 = res_246293;
		LOC30 = 0;
		LOC30 = HEX5BHEX5D_136276(body, i_246033);
		(*(*LOC30).kindU.S4.Sym).Kind = ((NU8) 9);
		LOC31 = 0;
		LOC31 = HEX5BHEX5D_136276(body, i_246033);
		addson_136028(vpart, LOC31);
		res_246293 += 1;
	} LA29: ;
	addson_136028(vpart, emptynode_136305);
	{
		if (!!(env == 0)) goto LA34;
		asgnRefNoCycle((void**) &(*call).kindU.S6.Sons->data[0], makeclosure_243217((*(*call).kindU.S6.Sons->data[0]).kindU.S4.Sym, env, (*body).Info));
	}
	LA34: ;
	addson_136028(vpart, call);
	addson_136028(v2, vpart);
	asgnRefNoCycle((void**) &(*loopbody).kindU.S6.Sons->data[0], v2);
	bs = newnodei_135920(((NU8) 151), (*body).Info);
	addson_136028(bs, (*call).kindU.S6.Sons->data[0]);
	asgnRefNoCycle((void**) &(*loopbody).kindU.S6.Sons->data[1], bs);
	asgnRefNoCycle((void**) &(*loopbody).kindU.S6.Sons->data[2], HEX5BHEX5D_136276(body, (NI64)(l - 1)));
	return result;
}
N_NIMCALL(void, TMP2727)(void* p, NI op) {
	TY242030* a;
	NI LOC1;
	a = (TY242030*)p;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field0, op);
	nimGCvisit((void*)a->data[LOC1].Field1, op);
	}
}
N_NIMCALL(void, TMP2728)(void* p, NI op) {
	tenv242019* a;
	a = (tenv242019*)p;
	nimGCvisit((void*)(*a).Attachednode, op);
	nimGCvisit((void*)(*a).Closure, op);
	nimGCvisit((void*)(*a).Capturedvars, op);
	nimGCvisit((void*)(*a).Deps, op);
	nimGCvisit((void*)(*a).Up, op);
	nimGCvisit((void*)(*a).Tup, op);
}
N_NIMCALL(void, TMP2729)(void* p, NI op) {
	toutercontext242023* a;
	a = (toutercontext242023*)p;
	nimGCvisit((void*)(*a).Fn, op);
	nimGCvisit((void*)(*a).Currentenv, op);
	nimGCvisit((void*)(*a).Capturedvars.Head, op);
	nimGCvisit((void*)(*a).Capturedvars.Data, op);
	nimGCvisit((void*)(*a).Processed.Head, op);
	nimGCvisit((void*)(*a).Processed.Data, op);
	nimGCvisit((void*)(*a).Localstoenv.Data, op);
	nimGCvisit((void*)(*a).Localstoaccess.Data, op);
	nimGCvisit((void*)(*a).Lambdastoenv.Data, op);
	nimGCvisit((void*)(*a).Up, op);
}

N_NIMCALL(toutercontext242023*, newoutercontext_242046)(tsym135677* fn, toutercontext242023* up) {
	toutercontext242023* result;
	result = 0;
	result = (toutercontext242023*) newObj((&NTI242013), sizeof(toutercontext242023));
	asgnRefNoCycle((void**) &(*result).Fn, fn);
	initintset_132899(&(*result).Capturedvars);
	initintset_132899(&(*result).Processed);
	initidnodetable_135951(&(*result).Localstoaccess);
	initidtable_135941(&(*result).Localstoenv);
	initidtable_135941(&(*result).Lambdastoenv);
	return result;
}

N_NIMCALL(tnode135647*, closurecreationpoint_243669)(tnode135647* n) {
	tnode135647* result;
	result = 0;
	result = newnodei_135920(((NU8) 114), (*n).Info);
	add_136175(result, emptynode_136305);
	add_136175(result, n);
	return result;
}

static N_INLINE(NIM_BOOL, canbecycleroot_41865)(tcell38449* c) {
	NIM_BOOL result;
	result = 0;
	result = !((((*(*c).Typ).flags &(1<<((((NU8) 1))&7)))!=0));
	return result;
}

static N_INLINE(void, rtladdcycleroot_42436)(tcell38449* c) {
	{
		if (!!((((NI) ((NI)((*c).Refcount & 3))) == 3))) goto LA3;
		(*c).Refcount = (NI)((NI)((*c).Refcount & -4) | 3);
		incl_39256(&gch_40442.Cycleroots, c);
	}
	LA3: ;
}

static N_INLINE(void, decref_43402)(tcell38449* c) {
	{
		(*c).Refcount -= 8;
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		rtladdzct_43002(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		LOC6 = canbecycleroot_41865(c);
		if (!LOC6) goto LA7;
		rtladdcycleroot_42436(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
}

static N_INLINE(void, nimGCunref)(void* p) {
	tcell38449* LOC1;
	LOC1 = usrtocell_41843(p);
	decref_43402(LOC1);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell38449* c;
	c = usrtocell_41843(p);
	{
		(*c).Refcount -= 8;
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		rtladdzct_43002(c);
	}
	LA3: ;
}

static N_INLINE(void, incref_43824)(tcell38449* c) {
	(*c).Refcount = (NI)((NU64)((*c).Refcount) + (NU64)(8));
	{
		NIM_BOOL LOC3;
		LOC3 = canbecycleroot_41865(c);
		if (!LOC3) goto LA4;
		rtladdcycleroot_42436(c);
	}
	LA4: ;
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tcell38449* LOC5;
		if (!!((src == NIM_NIL))) goto LA3;
		LOC5 = usrtocell_41843(src);
		incref_43824(LOC5);
	}
	LA3: ;
	{
		tcell38449* LOC10;
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		LOC10 = usrtocell_41843((*dest));
		decref_43402(LOC10);
	}
	LA8: ;
	(*dest) = src;
}

N_NIMCALL(tenv242019*, newenv_242093)(tsym135677* outerproc, tenv242019* up, tnode135647* n) {
	tenv242019* result;
	result = 0;
	result = (tenv242019*) newObj((&NTI242015), sizeof(tenv242019));
	(*result).Sup.m_type = (&NTI242019);
	if ((*result).Deps) nimGCunref((*result).Deps);
	(*result).Deps = (TY242030*) newSeqRC1((&NTI242030), 0);
	if ((*result).Capturedvars) nimGCunrefNoCycle((*result).Capturedvars);
	(*result).Capturedvars = (tsymseq135649*) newSeqRC1((&NTI135649), 0);
	asgnRefNoCycle((void**) &(*result).Tup, newtype_135881(((NU8) 18), outerproc));
	asgnRefNoCycle((void**) &(*(*result).Tup).N, newnodei_135920(((NU8) 131), (*outerproc).Info));
	asgnRef((void**) &(*result).Up, up);
	asgnRefNoCycle((void**) &(*result).Attachednode, n);
	return result;
}

static N_INLINE(NIM_BOOL, isinnerproc_242813)(tsym135677* s, tsym135677* outerproc) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	NIM_BOOL LOC2;
	NIM_BOOL LOC5;
	result = 0;
	LOC2 = ((45056 &(1<<(((*s).Kind)&31)))!=0);
	if (!(LOC2)) goto LA3;
	LOC2 = ((*s).Owner == outerproc);
	LA3: ;
	LOC1 = LOC2;
	if (!(LOC1)) goto LA4;
	LOC5 = isgenericroutine_140345(s);
	LOC1 = !(LOC5);
	LA4: ;
	result = LOC1;
	return result;
}
N_NIMCALL(void, TMP2732)(void* p, NI op) {
	tinnercontext242021* a;
	a = (tinnercontext242021*)p;
	nimGCvisit((void*)(*a).Fn, op);
	nimGCvisit((void*)(*a).Closureparam, op);
	nimGCvisit((void*)(*a).Localstoaccess.Data, op);
}

N_NIMCALL(tinnercontext242021*, newinnercontext_242071)(tsym135677* fn) {
	tinnercontext242021* result;
	result = 0;
	result = (tinnercontext242021*) newObj((&NTI242011), sizeof(tinnercontext242021));
	asgnRefNoCycle((void**) &(*result).Fn, fn);
	initidnodetable_135951(&(*result).Localstoaccess);
	return result;
}

static N_INLINE(NIM_BOOL, illegalcapture_242888)(tsym135677* s) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	ttype135681* LOC2;
	result = 0;
	LOC2 = 0;
	LOC2 = skiptypes_202116((*s).Typ, IL64(211106232576256));
	LOC1 = ((IL64(281475119316992) &(IL64(1)<<(((*LOC2).Kind)&IL64(63))))!=0);
	if (LOC1) goto LA3;
	LOC1 = ((*s).Kind == ((NU8) 11));
	LA3: ;
	result = LOC1;
	return result;
}

N_NIMCALL(void, addhiddenparam_242618)(tsym135677* routine, tsym135677* param) {
	tnode135647* params;
	tnode135647* LOC1;
	params = (*(*routine).Ast).kindU.S6.Sons->data[3];
	(*param).Position = len_136081(params);
	LOC1 = 0;
	LOC1 = newsymnode_135916(param);
	addson_136028(params, LOC1);
	(*(*routine).Typ).Flags |=((NI32)(1)<<((((NU8) 13))%(sizeof(NI32)*8)));
}

N_NIMCALL(void, addclosureparam_242839)(tinnercontext242021* i, tenv242019* e) {
	tsym135677* cp;
	tident131018* LOC1;
	LOC1 = 0;
	LOC1 = getident_131448(((NimStringDesc*) &TMP2733));
	cp = newsym_135874(((NU8) 3), LOC1, (*i).Fn, (*(*i).Fn).Info);
	(*cp).Flags |=((NI32)(1)<<((((NU8) 2))%(sizeof(NI32)*8)));
	asgnRefNoCycle((void**) &(*cp).Typ, newtype_135881(((NU8) 22), (*i).Fn));
	rawaddson_138897((*cp).Typ, (*e).Tup);
	asgnRefNoCycle((void**) &(*i).Closureparam, cp);
	addhiddenparam_242618((*i).Fn, (*i).Closureparam);
}

static N_INLINE(ttype135681*, skipintlit_218324)(ttype135681* t) {
	ttype135681* result;
	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = ((*t).Kind == ((NU8) 31));
		if (!(LOC3)) goto LA4;
		LOC3 = !(((*t).N == NIM_NIL));
		LA4: ;
		if (!LOC3) goto LA5;
		result = getsystype_218018(((NU8) 31));
	}
	goto LA1;
	LA5: ;
	{
		result = t;
	}
	LA1: ;
	return result;
}

static N_INLINE(NI, sonslen_136006)(ttype135681* n) {
	NI result;
	result = 0;
	{
		if (!(*n).Sons == 0) goto LA3;
		result = 0;
	}
	goto LA1;
	LA3: ;
	{
		result = (*n).Sons->Sup.len;
	}
	LA1: ;
	return result;
}

N_NIMCALL(void, addfield_242154)(ttype135681* tup, tsym135677* s) {
	tsym135677* field;
	ttype135681* t;
	tnode135647* LOC1;
	field = newsym_135874(((NU8) 18), (*s).Name, (*s).Owner, (*s).Info);
	t = skipintlit_218324((*s).Typ);
	asgnRefNoCycle((void**) &(*field).Typ, t);
	(*field).Position = sonslen_136006(tup);
	LOC1 = 0;
	LOC1 = newsymnode_135916(field);
	addson_136028((*tup).N, LOC1);
	rawaddson_138897(tup, t);
}

N_NIMCALL(void, addcapturedvar_242162)(tenv242019* e, tsym135677* v) {
	tsym135677* x_242201;
	tsymseq135649* HEX3Atmp_242227;
	NI i_242229;
	x_242201 = 0;
	HEX3Atmp_242227 = 0;
	HEX3Atmp_242227 = (*e).Capturedvars;
	i_242229 = 0;
	while (1) {
		if (!(i_242229 < HEX3Atmp_242227->Sup.len)) goto LA1;
		x_242201 = HEX3Atmp_242227->data[i_242229];
		{
			if (!(x_242201 == v)) goto LA4;
			goto BeforeRet;
		}
		LA4: ;
		i_242229 += 1;
	} LA1: ;
	(*e).Capturedvars = (tsymseq135649*) incrSeq(&((*e).Capturedvars)->Sup, sizeof(tsym135677*));
	asgnRefNoCycle((void**) &(*e).Capturedvars->data[(*e).Capturedvars->Sup.len-1], v);
	addfield_242154((*e).Tup, v);
	BeforeRet: ;
}

N_NIMCALL(tnode135647*, indirectaccess_242424)(tnode135647* a, tsym135677* b, tlineinfo128308 info) {
	tnode135647* result;
	tnode135647* deref;
	tsym135677* field;
	tnode135647* LOC1;
	result = 0;
	deref = newnodei_135920(((NU8) 65), info);
	asgnRefNoCycle((void**) &(*deref).Typ, (*(*a).Typ).Sons->data[0]);
	field = getsymfromlist_142176((*(*deref).Typ).N, (*b).Name, 0);
	addson_136028(deref, a);
	result = newnodei_135920(((NU8) 45), info);
	addson_136028(result, deref);
	LOC1 = 0;
	LOC1 = newsymnode_135916(field);
	addson_136028(result, LOC1);
	asgnRefNoCycle((void**) &(*result).Typ, (*field).Typ);
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) (&(*dest).data[((*dest).Sup.len)- 0])), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(tsym135677*, adddep_242233)(tenv242019* e, tenv242019* d, tsym135677* owner) {
	tsym135677* result;
	tenv242019* x_242274;
	tsym135677* field_242275;
	TY242030* HEX3Atmp_242418;
	NI i_242420;
	NI pos;
	NimStringDesc* LOC6;
	NimStringDesc* LOC7;
	tident131018* LOC8;
	tdep242017 LOC9;
	result = 0;
	x_242274 = 0;
	field_242275 = 0;
	HEX3Atmp_242418 = 0;
	HEX3Atmp_242418 = (*e).Deps;
	i_242420 = 0;
	while (1) {
		if (!(i_242420 < HEX3Atmp_242418->Sup.len)) goto LA1;
		x_242274 = HEX3Atmp_242418->data[i_242420].Field0;
		field_242275 = HEX3Atmp_242418->data[i_242420].Field1;
		{
			if (!(x_242274 == d)) goto LA4;
			result = field_242275;
			goto BeforeRet;
		}
		LA4: ;
		i_242420 += 1;
	} LA1: ;
	pos = sonslen_136006((*e).Tup);
	LOC6 = 0;
	LOC7 = 0;
	LOC7 = nimIntToStr(pos);
	LOC6 = rawNewString(LOC7->Sup.len + 3);
appendString(LOC6, ((NimStringDesc*) &TMP2734));
appendString(LOC6, LOC7);
	LOC8 = 0;
	LOC8 = getident_131448(LOC6);
	result = newsym_135874(((NU8) 18), LOC8, owner, (*owner).Info);
	asgnRefNoCycle((void**) &(*result).Typ, newtype_135881(((NU8) 22), owner));
	(*result).Position = pos;
	rawaddson_138897((*result).Typ, (*d).Tup);
	addfield_242154((*e).Tup, result);
	memset((void*)&LOC9, 0, sizeof(LOC9));
	LOC9.Field0 = d;
	LOC9.Field1 = result;
	(*e).Deps = (TY242030*) incrSeq(&((*e).Deps)->Sup, sizeof(tdep242017));
	asgnRef((void**) &(*e).Deps->data[(*e).Deps->Sup.len-1].Field0, LOC9.Field0);
	asgnRefNoCycle((void**) &(*e).Deps->data[(*e).Deps->Sup.len-1].Field1, LOC9.Field1);
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, capturevar_242910)(toutercontext242023* o, tinnercontext242021* i, tsym135677* local, tlineinfo128308 info) {
	tenv242019* it;
	TNimObject* LOC1;
	tenv242019* e;
	tnode135647* access;
	LOC1 = 0;
	LOC1 = idtableget_142137((*o).Localstoenv, &local->Sup);
	it = ((tenv242019*) (LOC1));
	{
		if (!(it == NIM_NIL)) goto LA4;
		goto BeforeRet;
	}
	LA4: ;
	{
		NIM_BOOL LOC8;
		NIM_BOOL LOC9;
		LOC9 = illegalcapture_242888(local);
		if (LOC9) goto LA10;
		LOC9 = !(((*(*o).Fn).Sup.Id == (*(*local).Owner).Sup.Id));
		LA10: ;
		LOC8 = LOC9;
		if (LOC8) goto LA11;
		LOC8 = !(((257 &(1<<(((*(*(*i).Fn).Typ).Callconv)&15)))!=0));
		LA11: ;
		if (!LOC8) goto LA12;
		localerror_129673(info, ((NU16) 216), (*(*local).Name).S);
	}
	LA12: ;
	(*(*(*i).Fn).Typ).Callconv = ((NU8) 8);
	(*(*(*i).Fn).Typ).Flags |=((NI32)(1)<<((((NU8) 13))%(sizeof(NI32)*8)));
	e = (*o).Currentenv;
	{
		TNimObject* LOC16;
		LOC16 = 0;
		LOC16 = idtableget_142137((*o).Lambdastoenv, &(*i).Fn->Sup);
		if (!(LOC16 == NIM_NIL)) goto LA17;
		idtableput_142147(&(*o).Lambdastoenv, &(*i).Fn->Sup, &e->Sup);
	}
	LA17: ;
	{
		tnode135647* LOC21;
		LOC21 = 0;
		LOC21 = idnodetableget_142159((*i).Localstoaccess, &local->Sup);
		if (!!((LOC21 == NIM_NIL))) goto LA22;
		goto BeforeRet;
	}
	LA22: ;
	{
		if (!((*i).Closureparam == NIM_NIL)) goto LA26;
		addclosureparam_242839(i, e);
	}
	LA26: ;
	access = newsymnode_135916((*i).Closureparam);
	addcapturedvar_242162(it, local);
	{
		if (!(it == e)) goto LA30;
	}
	goto LA28;
	LA30: ;
	{
		tsym135677* LOC33;
		LOC33 = 0;
		LOC33 = adddep_242233(e, it, (*i).Fn);
		access = indirectaccess_242424(access, LOC33, info);
	}
	LA28: ;
	access = indirectaccess_242424(access, local, info);
	incl_132842(&(*o).Capturedvars, (*local).Sup.Id);
	idnodetableput_142164(&(*i).Localstoaccess, &local->Sup, access);
	BeforeRet: ;
}

N_NIMCALL(void, gathervars_243047)(toutercontext242023* o, tinnercontext242021* i, tnode135647* n) {
	{
		if (!(n == NIM_NIL)) goto LA3;
		goto BeforeRet;
	}
	LA3: ;
	switch ((*n).Kind) {
	case ((NU8) 3):
	{
		tsym135677* s;
		s = (*n).kindU.S4.Sym;
		{
			NIM_BOOL LOC8;
			LOC8 = interestingvar_242999(s);
			if (!(LOC8)) goto LA9;
			LOC8 = !(((*(*i).Fn).Sup.Id == (*(*s).Owner).Sup.Id));
			LA9: ;
			if (!LOC8) goto LA10;
			capturevar_242910(o, i, s, (*n).Info);
		}
		goto LA6;
		LA10: ;
		{
			NIM_BOOL LOC13;
			NIM_BOOL LOC14;
			tenv242019* env;
			TNimObject* LOC19;
			LOC14 = isinnerproc_242813(s, (*o).Fn);
			if (!(LOC14)) goto LA15;
			LOC14 = (((*(*s).Typ).Flags &(1<<((((NU8) 13))&31)))!=0);
			LA15: ;
			LOC13 = LOC14;
			if (!(LOC13)) goto LA16;
			LOC13 = !((s == (*i).Fn));
			LA16: ;
			if (!LOC13) goto LA17;
			LOC19 = 0;
			LOC19 = idtableget_142137((*o).Lambdastoenv, &(*i).Fn->Sup);
			env = ((tenv242019*) (LOC19));
			{
				if (!(env == NIM_NIL)) goto LA22;
				internalerror_129687((*n).Info, ((NimStringDesc*) &TMP2735));
			}
			LA22: ;
			{
				tsym135677* LOC28;
				if (!!(((*o).Currentenv == env))) goto LA26;
				LOC28 = 0;
				LOC28 = adddep_242233((*o).Currentenv, env, (*i).Fn);
				internalerror_129687((*n).Info, ((NimStringDesc*) &TMP2736));
			}
			LA26: ;
		}
		goto LA6;
		LA17: ;
		LA6: ;
	}
	break;
	case ((NU8) 1) ... ((NU8) 2):
	case ((NU8) 4) ... ((NU8) 23):
	{
	}
	break;
	default:
	{
		NI k_243139;
		NI HEX3Atmp_243150;
		NI LOC31;
		NI res_243152;
		k_243139 = 0;
		HEX3Atmp_243150 = 0;
		LOC31 = sonslen_136002(n);
		HEX3Atmp_243150 = (NI64)(LOC31 - 1);
		res_243152 = 0;
		while (1) {
			if (!(res_243152 <= HEX3Atmp_243150)) goto LA32;
			k_243139 = res_243152;
			gathervars_243047(o, i, (*n).kindU.S6.Sons->data[k_243139]);
			res_243152 += 1;
		} LA32: ;
	}
	break;
	}
	BeforeRet: ;
}

N_NIMCALL(void, dummyclosureparam_242858)(toutercontext242023* o, tinnercontext242021* i) {
	tenv242019* e;
	e = (*o).Currentenv;
	{
		TNimObject* LOC3;
		LOC3 = 0;
		LOC3 = idtableget_142137((*o).Lambdastoenv, &(*i).Fn->Sup);
		if (!(LOC3 == NIM_NIL)) goto LA4;
		idtableput_142147(&(*o).Lambdastoenv, &(*i).Fn->Sup, &e->Sup);
	}
	LA4: ;
	{
		if (!((*i).Closureparam == NIM_NIL)) goto LA8;
		addclosureparam_242839(i, e);
	}
	LA8: ;
}

N_NIMCALL(tnode135647*, transforminnerproc_243236)(toutercontext242023* o, tinnercontext242021* i, tnode135647* n) {
	tnode135647* result;
	result = 0;
	switch ((*n).Kind) {
	case ((NU8) 1) ... ((NU8) 2):
	case ((NU8) 4) ... ((NU8) 23):
	{
	}
	break;
	case ((NU8) 3):
	{
		tsym135677* s;
		s = (*n).kindU.S4.Sym;
		{
			if (!(s == (*i).Fn)) goto LA5;
			result = makeclosure_243217(s, (*i).Closureparam, (*n).Info);
		}
		goto LA3;
		LA5: ;
		{
			NIM_BOOL LOC8;
			LOC8 = isinnerproc_242813(s, (*o).Fn);
			if (!(LOC8)) goto LA9;
			LOC8 = ((*(*s).Typ).Callconv == ((NU8) 8));
			LA9: ;
			if (!LOC8) goto LA10;
			result = makeclosure_243217(s, (*i).Closureparam, (*n).Info);
		}
		goto LA3;
		LA10: ;
		{
			result = idnodetableget_142159((*i).Localstoaccess, &(*n).kindU.S4.Sym->Sup);
		}
		LA3: ;
	}
	break;
	case ((NU8) 51):
	case ((NU8) 52):
	{
		result = transforminnerproc_243236(o, i, (*n).kindU.S6.Sons->data[0]);
	}
	break;
	case ((NU8) 79):
	case ((NU8) 80):
	case ((NU8) 81):
	case ((NU8) 82):
	case ((NU8) 83):
	case ((NU8) 84):
	{
	}
	break;
	default:
	{
		NI j_243629;
		NI HEX3Atmp_243662;
		NI LOC16;
		NI res_243664;
		j_243629 = 0;
		HEX3Atmp_243662 = 0;
		LOC16 = sonslen_136002(n);
		HEX3Atmp_243662 = (NI64)(LOC16 - 1);
		res_243664 = 0;
		while (1) {
			tnode135647* x;
			if (!(res_243664 <= HEX3Atmp_243662)) goto LA17;
			j_243629 = res_243664;
			x = transforminnerproc_243236(o, i, (*n).kindU.S6.Sons->data[j_243629]);
			{
				if (!!((x == NIM_NIL))) goto LA20;
				asgnRefNoCycle((void**) &(*n).kindU.S6.Sons->data[j_243629], x);
			}
			LA20: ;
			res_243664 += 1;
		} LA17: ;
	}
	break;
	}
	return result;
}

N_NIMCALL(void, searchforinnerprocs_243675)(toutercontext242023* o, tnode135647* n) {
	{
		if (!(n == NIM_NIL)) goto LA3;
		goto BeforeRet;
	}
	LA3: ;
	switch ((*n).Kind) {
	case ((NU8) 1) ... ((NU8) 2):
	case ((NU8) 4) ... ((NU8) 23):
	{
	}
	break;
	case ((NU8) 3):
	{
		{
			NIM_BOOL LOC9;
			NIM_BOOL LOC11;
			tinnercontext242021* inner;
			tnode135647* body;
			LOC9 = isinnerproc_242813((*n).kindU.S4.Sym, (*o).Fn);
			if (!(LOC9)) goto LA10;
			LOC11 = containsorincl_132875(&(*o).Processed, (*(*n).kindU.S4.Sym).Sup.Id);
			LOC9 = !(LOC11);
			LA10: ;
			if (!LOC9) goto LA12;
			inner = newinnercontext_242071((*n).kindU.S4.Sym);
			body = getbody_215576((*n).kindU.S4.Sym);
			gathervars_243047(o, inner, body);
			{
				NIM_BOOL LOC16;
				LOC16 = ((*inner).Closureparam == NIM_NIL);
				if (!(LOC16)) goto LA17;
				LOC16 = ((*(*(*n).kindU.S4.Sym).Typ).Callconv == ((NU8) 8));
				LA17: ;
				if (!LOC16) goto LA18;
				dummyclosureparam_242858(o, inner);
			}
			LA18: ;
			{
				tnode135647* ti;
				if (!!(((*inner).Closureparam == NIM_NIL))) goto LA22;
				ti = transforminnerproc_243236(o, inner, body);
				{
					if (!!((ti == NIM_NIL))) goto LA26;
					asgnRefNoCycle((void**) &(*(*(*n).kindU.S4.Sym).Ast).kindU.S6.Sons->data[6], ti);
				}
				LA26: ;
			}
			LA22: ;
		}
		LA12: ;
	}
	break;
	case ((NU8) 51):
	case ((NU8) 52):
	{
		searchforinnerprocs_243675(o, (*n).kindU.S6.Sons->data[0]);
	}
	break;
	case ((NU8) 96):
	case ((NU8) 94):
	case ((NU8) 95):
	case ((NU8) 111):
	{
		NI body;
		NI LOC30;
		NI i_243840;
		NI HEX3Atmp_244029;
		NI res_244031;
		tenv242019* oldenv;
		tnode135647* ex;
		LOC30 = len_136081(n);
		body = (NI64)(LOC30 - 1);
		i_243840 = 0;
		HEX3Atmp_244029 = 0;
		HEX3Atmp_244029 = (NI64)(body - 1);
		res_244031 = 0;
		while (1) {
			if (!(res_244031 <= HEX3Atmp_244029)) goto LA31;
			i_243840 = res_244031;
			searchforinnerprocs_243675(o, (*n).kindU.S6.Sons->data[i_243840]);
			res_244031 += 1;
		} LA31: ;
		oldenv = (*o).Currentenv;
		ex = closurecreationpoint_243669((*n).kindU.S6.Sons->data[body]);
		asgnRef((void**) &(*o).Currentenv, newenv_242093((*o).Fn, oldenv, ex));
		searchforinnerprocs_243675(o, (*n).kindU.S6.Sons->data[body]);
		asgnRefNoCycle((void**) &(*n).kindU.S6.Sons->data[body], ex);
		asgnRef((void**) &(*o).Currentenv, oldenv);
	}
	break;
	case ((NU8) 99):
	case ((NU8) 100):
	{
		NI i_243891;
		NI HEX3Atmp_244037;
		NI LOC33;
		NI res_244039;
		i_243891 = 0;
		HEX3Atmp_244037 = 0;
		LOC33 = sonslen_136002(n);
		HEX3Atmp_244037 = (NI64)(LOC33 - 1);
		res_244039 = 0;
		while (1) {
			tnode135647* it;
			if (!(res_244039 <= HEX3Atmp_244037)) goto LA34;
			i_243891 = res_244039;
			it = (*n).kindU.S6.Sons->data[i_243891];
			{
				if (!((*it).Kind == ((NU8) 123))) goto LA37;
			}
			goto LA35;
			LA37: ;
			{
				NI l;
				if (!((*it).Kind == ((NU8) 35))) goto LA40;
				l = sonslen_136002(it);
				{
					if (!!(((*(*it).kindU.S6.Sons->data[0]).Kind == ((NU8) 3)))) goto LA44;
					internalerror_129687((*it).Info, ((NimStringDesc*) &TMP2737));
				}
				LA44: ;
				idtableput_142147(&(*o).Localstoenv, &(*(*it).kindU.S6.Sons->data[0]).kindU.S4.Sym->Sup, &(*o).Currentenv->Sup);
				searchforinnerprocs_243675(o, (*it).kindU.S6.Sons->data[(NI64)(l - 1)]);
			}
			goto LA35;
			LA40: ;
			{
				NI l;
				NI j_243978;
				NI HEX3Atmp_244033;
				NI res_244035;
				if (!((*it).Kind == ((NU8) 36))) goto LA47;
				l = sonslen_136002(it);
				j_243978 = 0;
				HEX3Atmp_244033 = 0;
				HEX3Atmp_244033 = (NI64)(l - 3);
				res_244035 = 0;
				while (1) {
					if (!(res_244035 <= HEX3Atmp_244033)) goto LA49;
					j_243978 = res_244035;
					idtableput_142147(&(*o).Localstoenv, &(*(*it).kindU.S6.Sons->data[j_243978]).kindU.S4.Sym->Sup, &(*o).Currentenv->Sup);
					res_244035 += 1;
				} LA49: ;
				searchforinnerprocs_243675(o, (*it).kindU.S6.Sons->data[(NI64)(l - 1)]);
			}
			goto LA35;
			LA47: ;
			{
				internalerror_129687((*it).Info, ((NimStringDesc*) &TMP2737));
			}
			LA35: ;
			res_244039 += 1;
		} LA34: ;
	}
	break;
	case ((NU8) 79):
	case ((NU8) 80):
	case ((NU8) 81):
	case ((NU8) 82):
	case ((NU8) 83):
	case ((NU8) 84):
	{
	}
	break;
	default:
	{
		NI i_244018;
		NI HEX3Atmp_244041;
		NI LOC53;
		NI res_244043;
		i_244018 = 0;
		HEX3Atmp_244041 = 0;
		LOC53 = sonslen_136002(n);
		HEX3Atmp_244041 = (NI64)(LOC53 - 1);
		res_244043 = 0;
		while (1) {
			if (!(res_244043 <= HEX3Atmp_244041)) goto LA54;
			i_244018 = res_244043;
			searchforinnerprocs_243675(o, (*n).kindU.S6.Sons->data[i_244018]);
			res_244043 += 1;
		} LA54: ;
	}
	break;
	}
	BeforeRet: ;
}

N_NIMCALL(tsym135677*, getclosurevar_244086)(toutercontext242023* o, tenv242019* e) {
	tsym135677* result;
	result = 0;
	{
		tident131018* LOC5;
		if (!((*e).Closure == NIM_NIL)) goto LA3;
		LOC5 = 0;
		LOC5 = getident_131448(((NimStringDesc*) &TMP2733));
		result = newsym_135874(((NU8) 8), LOC5, (*o).Fn, (*(*e).Attachednode).Info);
		(*result).Flags |=((NI32)(1)<<((((NU8) 21))%(sizeof(NI32)*8)));
		asgnRefNoCycle((void**) &(*result).Typ, newtype_135881(((NU8) 22), (*o).Fn));
		rawaddson_138897((*result).Typ, (*e).Tup);
		asgnRefNoCycle((void**) &(*e).Closure, result);
	}
	goto LA1;
	LA3: ;
	{
		result = (*e).Closure;
	}
	LA1: ;
	return result;
}

N_NIMCALL(tnode135647*, indirectaccess_242603)(tsym135677* a, tsym135677* b, tlineinfo128308 info) {
	tnode135647* result;
	tnode135647* LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = newsymnode_135916(a);
	result = indirectaccess_242424(LOC1, b, info);
	return result;
}

N_NIMCALL(tnode135647*, newasgnstmt_244051)(tnode135647* le, tnode135647* ri, tlineinfo128308 info) {
	tnode135647* result;
	result = 0;
	result = newnodei_137203(((NU8) 73), info, 2);
	asgnRefNoCycle((void**) &(*result).kindU.S6.Sons->data[0], le);
	asgnRefNoCycle((void**) &(*result).kindU.S6.Sons->data[1], ri);
	return result;
}

N_NIMCALL(tnode135647*, generateclosurecreation_244116)(toutercontext242023* o, tenv242019* scope) {
	tnode135647* result;
	tsym135677* env;
	tnode135647* v;
	tnode135647* LOC1;
	tsym135677* LOC2;
	tnode135647* LOC3;
	tsym135677* local_244133;
	tsymseq135649* HEX3Atmp_244154;
	NI i_244156;
	tenv242019* e_244152;
	tsym135677* field_244153;
	TY242030* HEX3Atmp_244157;
	NI i_244159;
	result = 0;
	env = getclosurevar_244086(o, scope);
	result = newnodei_135920(((NU8) 114), (*env).Info);
	v = newnodei_135920(((NU8) 99), (*env).Info);
	LOC1 = 0;
	LOC1 = newsymnode_135916(env);
	addvar_244079(v, LOC1);
	add_136175(result, v);
	LOC2 = 0;
	LOC2 = getsyssym_218034(((NimStringDesc*) &TMP2457));
	LOC3 = 0;
	LOC3 = newcall_242611(LOC2, env);
	add_136175(result, LOC3);
	local_244133 = 0;
	HEX3Atmp_244154 = 0;
	HEX3Atmp_244154 = (*scope).Capturedvars;
	i_244156 = 0;
	while (1) {
		tnode135647* fieldaccess;
		if (!(i_244156 < HEX3Atmp_244154->Sup.len)) goto LA4;
		local_244133 = HEX3Atmp_244154->data[i_244156];
		fieldaccess = indirectaccess_242603(env, local_244133, (*env).Info);
		{
			tnode135647* LOC9;
			tnode135647* LOC10;
			if (!((*local_244133).Kind == ((NU8) 3))) goto LA7;
			LOC9 = 0;
			LOC9 = newsymnode_135916(local_244133);
			LOC10 = 0;
			LOC10 = newasgnstmt_244051(fieldaccess, LOC9, (*env).Info);
			add_136175(result, LOC10);
		}
		LA7: ;
		idnodetableput_142164(&(*o).Localstoaccess, &local_244133->Sup, fieldaccess);
		i_244156 += 1;
	} LA4: ;
	e_244152 = 0;
	field_244153 = 0;
	HEX3Atmp_244157 = 0;
	HEX3Atmp_244157 = (*scope).Deps;
	i_244159 = 0;
	while (1) {
		tnode135647* LOC12;
		tsym135677* LOC13;
		tnode135647* LOC14;
		tnode135647* LOC15;
		if (!(i_244159 < HEX3Atmp_244157->Sup.len)) goto LA11;
		e_244152 = HEX3Atmp_244157->data[i_244159].Field0;
		field_244153 = HEX3Atmp_244157->data[i_244159].Field1;
		LOC12 = 0;
		LOC12 = indirectaccess_242603(env, field_244153, (*env).Info);
		LOC13 = 0;
		LOC13 = getclosurevar_244086(o, e_244152);
		LOC14 = 0;
		LOC14 = newsymnode_135916(LOC13);
		LOC15 = 0;
		LOC15 = newasgnstmt_244051(LOC12, LOC14, (*env).Info);
		add_136175(result, LOC15);
		i_244159 += 1;
	} LA11: ;
	return result;
}

N_NIMCALL(tnode135647*, generatethunk_243157)(tnode135647* prc, ttype135681* dest) {
	tnode135647* result;
	tnode135647* conv;
	ttype135681* LOC5;
	tnode135647* LOC6;
	result = 0;
	{
		if (!(gcmd_105110 == ((NU8) 4))) goto LA3;
		result = prc;
		goto BeforeRet;
	}
	LA3: ;
	result = newnodeit_135925(((NU8) 148), (*prc).Info, dest);
	conv = newnodeit_135925(((NU8) 58), (*prc).Info, dest);
	add_136175(conv, emptynode_136305);
	add_136175(conv, prc);
	add_136175(result, conv);
	LOC5 = 0;
	LOC5 = getsystype_218018(((NU8) 5));
	LOC6 = 0;
	LOC6 = newnodeit_135925(((NU8) 23), (*prc).Info, LOC5);
	add_136175(result, LOC6);
	BeforeRet: ;
	return result;
}

N_NIMCALL(tnode135647*, transformouterconv_243171)(tnode135647* n) {
	tnode135647* result;
	ttype135681* dest;
	ttype135681* source;
	result = 0;
	dest = skiptypes_202116((*n).Typ, IL64(211106242013440));
	source = skiptypes_202116((*(*n).kindU.S6.Sons->data[1]).Typ, IL64(211106242013440));
	{
		if (!((*dest).Kind == ((NU8) 25))) goto LA3;
		{
			NIM_BOOL LOC7;
			LOC7 = ((*dest).Callconv == ((NU8) 8));
			if (!(LOC7)) goto LA8;
			LOC7 = ((*source).Callconv == ((NU8) 0));
			LA8: ;
			if (!LOC7) goto LA9;
			result = generatethunk_243157((*n).kindU.S6.Sons->data[1], dest);
		}
		LA9: ;
	}
	LA3: ;
	return result;
}

N_NIMCALL(tnode135647*, transformouterproc_244164)(toutercontext242023* o, tnode135647* n) {
	tnode135647* result;
	result = 0;
	{
		if (!(n == NIM_NIL)) goto LA3;
		result = NIM_NIL;
		goto BeforeRet;
	}
	LA3: ;
	switch ((*n).Kind) {
	case ((NU8) 1) ... ((NU8) 2):
	case ((NU8) 4) ... ((NU8) 23):
	{
	}
	break;
	case ((NU8) 3):
	{
		tsym135677* local;
		tenv242019* closure;
		TNimObject* LOC7;
		tenv242019* env;
		TNimObject* LOC26;
		tnode135647* scope;
		local = (*n).kindU.S4.Sym;
		LOC7 = 0;
		LOC7 = idtableget_142137((*o).Lambdastoenv, &local->Sup);
		closure = ((tenv242019*) (LOC7));
		{
			tsym135677* a;
			if (!!((closure == NIM_NIL))) goto LA10;
			a = (*closure).Closure;
			{
				if (!!((a == NIM_NIL))) goto LA14;
				result = makeclosure_243217(local, a, (*n).Info);
				goto BeforeRet;
			}
			goto LA12;
			LA14: ;
			{
				tnode135647* scope;
				tsym135677* x;
				scope = (*closure).Attachednode;
				{
					if (!((*(*scope).kindU.S6.Sons->data[0]).Kind == ((NU8) 1))) goto LA19;
					asgnRefNoCycle((void**) &(*scope).kindU.S6.Sons->data[0], generateclosurecreation_244116(o, closure));
				}
				LA19: ;
				x = (*closure).Closure;
				result = makeclosure_243217(local, x, (*n).Info);
				goto BeforeRet;
			}
			LA12: ;
		}
		LA10: ;
		{
			NIM_BOOL LOC23;
			LOC23 = contains_132820(&(*o).Capturedvars, (*local).Sup.Id);
			if (!!(LOC23)) goto LA24;
			goto BeforeRet;
		}
		LA24: ;
		LOC26 = 0;
		LOC26 = idtableget_142137((*o).Localstoenv, &local->Sup);
		env = ((tenv242019*) (LOC26));
		{
			if (!(env == NIM_NIL)) goto LA29;
			goto BeforeRet;
		}
		LA29: ;
		scope = (*env).Attachednode;
		{
			if (!((*(*scope).kindU.S6.Sons->data[0]).Kind == ((NU8) 1))) goto LA33;
			asgnRefNoCycle((void**) &(*scope).kindU.S6.Sons->data[0], generateclosurecreation_244116(o, env));
		}
		LA33: ;
		result = idnodetableget_142159((*o).Localstoaccess, &local->Sup);
	}
	break;
	case ((NU8) 51):
	case ((NU8) 52):
	{
		result = transformouterproc_244164(o, (*n).kindU.S6.Sons->data[0]);
	}
	break;
	case ((NU8) 79):
	case ((NU8) 80):
	case ((NU8) 81):
	case ((NU8) 82):
	case ((NU8) 83):
	case ((NU8) 84):
	{
	}
	break;
	case ((NU8) 58):
	case ((NU8) 59):
	case ((NU8) 60):
	{
		tnode135647* x;
		x = transformouterproc_244164(o, (*n).kindU.S6.Sons->data[1]);
		{
			if (!!((x == NIM_NIL))) goto LA40;
			asgnRefNoCycle((void**) &(*n).kindU.S6.Sons->data[1], x);
		}
		LA40: ;
		result = transformouterconv_243171(n);
	}
	break;
	default:
	{
		NI i_245051;
		NI HEX3Atmp_245084;
		NI LOC43;
		NI res_245086;
		i_245051 = 0;
		HEX3Atmp_245084 = 0;
		LOC43 = sonslen_136002(n);
		HEX3Atmp_245084 = (NI64)(LOC43 - 1);
		res_245086 = 0;
		while (1) {
			tnode135647* x;
			if (!(res_245086 <= HEX3Atmp_245084)) goto LA44;
			i_245051 = res_245086;
			x = transformouterproc_244164(o, (*n).kindU.S6.Sons->data[i_245051]);
			{
				if (!!((x == NIM_NIL))) goto LA47;
				asgnRefNoCycle((void**) &(*n).kindU.S6.Sons->data[i_245051], x);
			}
			LA47: ;
			res_245086 += 1;
		} LA44: ;
	}
	break;
	}
	BeforeRet: ;
	return result;
}

N_NIMCALL(tnode135647*, liftlambdas_245091)(tsym135677* fn, tnode135647* body) {
	tnode135647* result;
	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = ((*body).Kind == ((NU8) 1));
		if (LOC3) goto LA4;
		LOC3 = (gcmd_105110 == ((NU8) 4));
		LA4: ;
		if (!LOC3) goto LA5;
		result = body;
	}
	goto LA1;
	LA5: ;
	{
		toutercontext242023* o;
		tnode135647* ex;
		tnode135647* params;
		NI i_245126;
		NI HEX3Atmp_245205;
		NI LOC8;
		NI res_245207;
		tnode135647* ast;
		tnode135647* LOC21;
		o = newoutercontext_242046(fn, NIM_NIL);
		ex = closurecreationpoint_243669(body);
		asgnRef((void**) &(*o).Currentenv, newenv_242093(fn, NIM_NIL, ex));
		params = (*(*fn).Typ).N;
		i_245126 = 0;
		HEX3Atmp_245205 = 0;
		LOC8 = len_136081(params);
		HEX3Atmp_245205 = LOC8 - 1;
		res_245207 = 1;
		while (1) {
			tsym135677* param;
			if (!(res_245207 <= HEX3Atmp_245205)) goto LA9;
			i_245126 = res_245207;
			{
				if (!!(((*(*params).kindU.S6.Sons->data[i_245126]).Kind == ((NU8) 3)))) goto LA12;
				internalerror_129687((*params).Info, ((NimStringDesc*) &TMP2730));
			}
			LA12: ;
			param = (*(*params).kindU.S6.Sons->data[i_245126]).kindU.S4.Sym;
			idtableput_142147(&(*o).Localstoenv, &param->Sup, &(*o).Currentenv->Sup);
			res_245207 += 1;
		} LA9: ;
		ast = (*fn).Ast;
		{
			NIM_BOOL LOC16;
			NI LOC17;
			LOC17 = sonslen_136002(ast);
			LOC16 = (7 < LOC17);
			if (!(LOC16)) goto LA18;
			LOC16 = ((*(*ast).kindU.S6.Sons->data[7]).Kind == ((NU8) 3));
			LA18: ;
			if (!LOC16) goto LA19;
			idtableput_142147(&(*o).Localstoenv, &(*(*ast).kindU.S6.Sons->data[7]).kindU.S4.Sym->Sup, &(*o).Currentenv->Sup);
		}
		LA19: ;
		searchforinnerprocs_243675(o, body);
		LOC21 = 0;
		LOC21 = transformouterproc_244164(o, body);
		result = ex;
	}
	LA1: ;
	return result;
}

N_NIMCALL(ttype135681*, getstatetype_245637)(tsym135677* iter) {
	ttype135681* result;
	tnode135647* n;
	tnode135647* LOC1;
	tnode135647* LOC2;
	ttype135681* LOC3;
	result = 0;
	n = newnodei_135920(((NU8) 44), (*iter).Info);
	LOC1 = 0;
	LOC1 = newintnode_135890(((NU8) 6), -1);
	addson_136028(n, LOC1);
	LOC2 = 0;
	LOC2 = newintnode_135890(((NU8) 6), 0);
	addson_136028(n, LOC2);
	result = newtype_135881(((NU8) 20), iter);
	asgnRefNoCycle((void**) &(*result).N, n);
	LOC3 = 0;
	LOC3 = getsystype_218018(((NU8) 31));
	rawaddson_138897(result, LOC3);
	return result;
}

N_NIMCALL(tsym135677*, newiterresult_245244)(tsym135677* iter) {
	tsym135677* result;
	result = 0;
	result = (*(*(*iter).Ast).kindU.S6.Sons->data[7]).kindU.S4.Sym;
	return result;
}

static N_INLINE(NIM_BOOL, interestingitervar_245403)(tsym135677* s) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	result = 0;
	LOC1 = ((1049376 &(1<<(((*s).Kind)&31)))!=0);
	if (!(LOC1)) goto LA2;
	LOC1 = !((((*s).Flags &(1<<((((NU8) 3))&31)))!=0));
	LA2: ;
	result = LOC1;
	return result;
}

N_NIMCALL(tnode135647*, transfiterbody_245428)(titercontext245236* c, tnode135647* n) {
	tnode135647* result;
	result = 0;
	{
		if (!(n == NIM_NIL)) goto LA3;
		result = NIM_NIL;
		goto BeforeRet;
	}
	LA3: ;
	switch ((*n).Kind) {
	case ((NU8) 3):
	{
		tsym135677* s;
		s = (*n).kindU.S4.Sym;
		{
			NIM_BOOL LOC8;
			tnode135647* LOC17;
			LOC8 = interestingitervar_245403(s);
			if (!(LOC8)) goto LA9;
			LOC8 = ((*(*c).Iter).Sup.Id == (*(*s).Owner).Sup.Id);
			LA9: ;
			if (!LOC8) goto LA10;
			{
				NIM_BOOL LOC14;
				LOC14 = containsorincl_132875(&(*c).Capturedvars, (*s).Sup.Id);
				if (!!(LOC14)) goto LA15;
				addfield_242154((*c).Tup, s);
			}
			LA15: ;
			LOC17 = 0;
			LOC17 = newsymnode_135916((*c).Closureparam);
			result = indirectaccess_242424(LOC17, s, (*n).Info);
		}
		LA10: ;
	}
	break;
	case ((NU8) 1) ... ((NU8) 2):
	case ((NU8) 4) ... ((NU8) 23):
	{
	}
	break;
	case ((NU8) 104):
	{
		NI64 stateno;
		tnode135647* stateasgnstmt;
		tnode135647* LOC20;
		tnode135647* LOC21;
		ttype135681* LOC22;
		tnode135647* LOC23;
		tnode135647* retstmt;
		tnode135647* statelabelstmt;
		ttype135681* LOC36;
		tnode135647* LOC37;
		(*(*(*(*(*c).State).Typ).N).kindU.S6.Sons->data[1]).kindU.S1.Intval += 1;
		stateno = (*(*(*(*(*c).State).Typ).N).kindU.S6.Sons->data[1]).kindU.S1.Intval;
		stateasgnstmt = newnodei_135920(((NU8) 73), (*n).Info);
		LOC20 = 0;
		LOC20 = newsymnode_135916((*c).Closureparam);
		LOC21 = 0;
		LOC21 = indirectaccess_242424(LOC20, (*c).State, (*n).Info);
		add_136175(stateasgnstmt, LOC21);
		LOC22 = 0;
		LOC22 = getsystype_218018(((NU8) 31));
		LOC23 = 0;
		LOC23 = newinttypenode_135895(((NU8) 6), stateno, LOC22);
		add_136175(stateasgnstmt, LOC23);
		retstmt = newnodei_135920(((NU8) 108), (*n).Info);
		{
			tnode135647* a;
			tnode135647* retval;
			tnode135647* LOC28;
			tnode135647* LOC29;
			if (!!(((*(*n).kindU.S6.Sons->data[0]).Kind == ((NU8) 1)))) goto LA26;
			a = newnodei_135920(((NU8) 73), (*(*n).kindU.S6.Sons->data[0]).Info);
			retval = transfiterbody_245428(c, (*n).kindU.S6.Sons->data[0]);
			LOC28 = 0;
			LOC28 = newsymnode_135916((*c).Resultsym);
			addson_136028(a, LOC28);
			LOC29 = 0;
			{
				if (!retval == 0) goto LA32;
				LOC29 = (*n).kindU.S6.Sons->data[0];
			}
			goto LA30;
			LA32: ;
			{
				LOC29 = retval;
			}
			LA30: ;
			addson_136028(a, LOC29);
			add_136175(retstmt, a);
		}
		goto LA24;
		LA26: ;
		{
			add_136175(retstmt, emptynode_136305);
		}
		LA24: ;
		statelabelstmt = newnodei_135920(((NU8) 150), (*n).Info);
		LOC36 = 0;
		LOC36 = getsystype_218018(((NU8) 31));
		LOC37 = 0;
		LOC37 = newinttypenode_135895(((NU8) 6), stateno, LOC36);
		add_136175(statelabelstmt, LOC37);
		result = newnodei_135920(((NU8) 114), (*n).Info);
		add_136175(result, stateasgnstmt);
		add_136175(result, retstmt);
		add_136175(result, statelabelstmt);
	}
	break;
	case ((NU8) 108):
	{
		tnode135647* stateasgnstmt;
		tnode135647* LOC39;
		tnode135647* LOC40;
		ttype135681* LOC41;
		tnode135647* LOC42;
		result = newnodei_135920(((NU8) 114), (*n).Info);
		stateasgnstmt = newnodei_135920(((NU8) 73), (*n).Info);
		LOC39 = 0;
		LOC39 = newsymnode_135916((*c).Closureparam);
		LOC40 = 0;
		LOC40 = indirectaccess_242424(LOC39, (*c).State, (*n).Info);
		add_136175(stateasgnstmt, LOC40);
		LOC41 = 0;
		LOC41 = getsystype_218018(((NU8) 31));
		LOC42 = 0;
		LOC42 = newinttypenode_135895(((NU8) 6), -1, LOC41);
		add_136175(stateasgnstmt, LOC42);
		add_136175(result, stateasgnstmt);
		add_136175(result, n);
	}
	break;
	default:
	{
		NI i_245597;
		NI HEX3Atmp_245630;
		NI LOC44;
		NI res_245632;
		i_245597 = 0;
		HEX3Atmp_245630 = 0;
		LOC44 = sonslen_136002(n);
		HEX3Atmp_245630 = (NI64)(LOC44 - 1);
		res_245632 = 0;
		while (1) {
			tnode135647* x;
			if (!(res_245632 <= HEX3Atmp_245630)) goto LA45;
			i_245597 = res_245632;
			x = transfiterbody_245428(c, (*n).kindU.S6.Sons->data[i_245597]);
			{
				if (!!((x == NIM_NIL))) goto LA48;
				asgnRefNoCycle((void**) &(*n).kindU.S6.Sons->data[i_245597], x);
			}
			LA48: ;
			res_245632 += 1;
		} LA45: ;
	}
	break;
	}
	BeforeRet: ;
	return result;
}

N_NIMCALL(tnode135647*, liftiterator_245644)(tsym135677* iter, tnode135647* body) {
	tnode135647* result;
	titercontext245236 c;
	tsym135677* cp;
	tident131018* LOC1;
	tident131018* LOC2;
	tnode135647* gs;
	tnode135647* LOC8;
	tnode135647* LOC9;
	tnode135647* state0;
	tnode135647* LOC10;
	tnode135647* newbody;
	tnode135647* stateasgnstmt;
	tnode135647* LOC16;
	tnode135647* LOC17;
	ttype135681* LOC18;
	tnode135647* LOC19;
	result = 0;
	memset((void*)&c, 0, sizeof(c));
	c.Iter = iter;
	initintset_132899(&c.Capturedvars);
	c.Tup = newtype_135881(((NU8) 18), iter);
	asgnRefNoCycle((void**) &(*c.Tup).N, newnodei_135920(((NU8) 131), (*iter).Info));
	LOC1 = 0;
	LOC1 = getident_131448(((NimStringDesc*) &TMP2733));
	cp = newsym_135874(((NU8) 3), LOC1, iter, (*iter).Info);
	(*cp).Flags |=((NI32)(1)<<((((NU8) 2))%(sizeof(NI32)*8)));
	asgnRefNoCycle((void**) &(*cp).Typ, newtype_135881(((NU8) 22), iter));
	rawaddson_138897((*cp).Typ, c.Tup);
	c.Closureparam = cp;
	addhiddenparam_242618(iter, cp);
	LOC2 = 0;
	LOC2 = getident_131448(((NimStringDesc*) &TMP2738));
	c.State = newsym_135874(((NU8) 18), LOC2, iter, (*iter).Info);
	asgnRefNoCycle((void**) &(*c.State).Typ, getstatetype_245637(iter));
	addfield_242154(c.Tup, c.State);
	{
		tnode135647* LOC7;
		if (!!(((*(*iter).Typ).Sons->data[0] == NIM_NIL))) goto LA5;
		c.Resultsym = newiterresult_245244(iter);
		LOC7 = 0;
		LOC7 = newsymnode_135916(c.Resultsym);
		add_136175((*iter).Ast, LOC7);
	}
	LA5: ;
	result = newnodei_135920(((NU8) 114), (*iter).Info);
	gs = newnodei_135920(((NU8) 149), (*iter).Info);
	LOC8 = 0;
	LOC8 = newsymnode_135916(c.Closureparam);
	LOC9 = 0;
	LOC9 = indirectaccess_242424(LOC8, c.State, (*iter).Info);
	add_136175(gs, LOC9);
	add_136175(result, gs);
	state0 = newnodei_135920(((NU8) 150), (*iter).Info);
	LOC10 = 0;
	LOC10 = newintnode_135890(((NU8) 6), 0);
	add_136175(state0, LOC10);
	add_136175(result, state0);
	newbody = transfiterbody_245428(&c, body);
	{
		if (!!((newbody == NIM_NIL))) goto LA13;
		add_136175(result, newbody);
	}
	goto LA11;
	LA13: ;
	{
		add_136175(result, body);
	}
	LA11: ;
	stateasgnstmt = newnodei_135920(((NU8) 73), (*iter).Info);
	LOC16 = 0;
	LOC16 = newsymnode_135916(c.Closureparam);
	LOC17 = 0;
	LOC17 = indirectaccess_242424(LOC16, c.State, (*iter).Info);
	add_136175(stateasgnstmt, LOC17);
	LOC18 = 0;
	LOC18 = getsystype_218018(((NU8) 31));
	LOC19 = 0;
	LOC19 = newinttypenode_135895(((NU8) 6), -1, LOC18);
	add_136175(stateasgnstmt, LOC19);
	add_136175(result, stateasgnstmt);
	return result;
}

N_NIMCALL(tnode135647*, liftlambdasfortoplevel_245212)(tsym135677* module, tnode135647* body) {
	tnode135647* result;
	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = ((*body).Kind == ((NU8) 1));
		if (LOC3) goto LA4;
		LOC3 = (gcmd_105110 == ((NU8) 4));
		LA4: ;
		if (!LOC3) goto LA5;
		result = body;
	}
	goto LA1;
	LA5: ;
	{
		toutercontext242023* o;
		tnode135647* ex;
		tnode135647* LOC8;
		o = newoutercontext_242046(module, NIM_NIL);
		ex = closurecreationpoint_243669(body);
		asgnRef((void**) &(*o).Currentenv, newenv_242093(module, NIM_NIL, ex));
		searchforinnerprocs_243675(o, body);
		LOC8 = 0;
		LOC8 = transformouterproc_244164(o, body);
		result = ex;
	}
	LA1: ;
	return result;
}
N_NOINLINE(void, lambdaliftingInit)(void) {
}

N_NOINLINE(void, lambdaliftingDatInit)(void) {
static TNimNode* TMP2724[8];
static TNimNode* TMP2725[6];
static TNimNode* TMP2726[2];
static TNimNode* TMP2731[3];
static TNimNode TMP848[23];
NTI242023.size = sizeof(toutercontext242023);
NTI242023.kind = 18;
NTI242023.base = 0;
TMP2724[0] = &TMP848[1];
TMP848[1].kind = 1;
TMP848[1].offset = offsetof(toutercontext242023, Fn);
TMP848[1].typ = (&NTI135645);
TMP848[1].name = "fn";
TMP2724[1] = &TMP848[2];
NTI242019.size = sizeof(tenv242019);
NTI242019.kind = 17;
NTI242019.base = (&NTI1009);
TMP2725[0] = &TMP848[4];
TMP848[4].kind = 1;
TMP848[4].offset = offsetof(tenv242019, Attachednode);
TMP848[4].typ = (&NTI135639);
TMP848[4].name = "attachedNode";
TMP2725[1] = &TMP848[5];
TMP848[5].kind = 1;
TMP848[5].offset = offsetof(tenv242019, Closure);
TMP848[5].typ = (&NTI135645);
TMP848[5].name = "closure";
TMP2725[2] = &TMP848[6];
TMP848[6].kind = 1;
TMP848[6].offset = offsetof(tenv242019, Capturedvars);
TMP848[6].typ = (&NTI135649);
TMP848[6].name = "capturedVars";
TMP2725[3] = &TMP848[7];
NTI242017.size = sizeof(tdep242017);
NTI242017.kind = 18;
NTI242017.base = 0;
TMP2726[0] = &TMP848[9];
TMP848[9].kind = 1;
TMP848[9].offset = offsetof(tdep242017, Field0);
TMP848[9].typ = (&NTI242015);
TMP848[9].name = "Field0";
TMP2726[1] = &TMP848[10];
TMP848[10].kind = 1;
TMP848[10].offset = offsetof(tdep242017, Field1);
TMP848[10].typ = (&NTI135645);
TMP848[10].name = "Field1";
TMP848[8].len = 2; TMP848[8].kind = 2; TMP848[8].sons = &TMP2726[0];
NTI242017.node = &TMP848[8];
NTI242030.size = sizeof(TY242030*);
NTI242030.kind = 24;
NTI242030.base = (&NTI242017);
NTI242030.marker = TMP2727;
TMP848[7].kind = 1;
TMP848[7].offset = offsetof(tenv242019, Deps);
TMP848[7].typ = (&NTI242030);
TMP848[7].name = "deps";
TMP2725[4] = &TMP848[11];
TMP848[11].kind = 1;
TMP848[11].offset = offsetof(tenv242019, Up);
TMP848[11].typ = (&NTI242015);
TMP848[11].name = "up";
TMP2725[5] = &TMP848[12];
TMP848[12].kind = 1;
TMP848[12].offset = offsetof(tenv242019, Tup);
TMP848[12].typ = (&NTI135643);
TMP848[12].name = "tup";
TMP848[3].len = 6; TMP848[3].kind = 2; TMP848[3].sons = &TMP2725[0];
NTI242019.node = &TMP848[3];
NTI242015.size = sizeof(tenv242019*);
NTI242015.kind = 22;
NTI242015.base = (&NTI242019);
NTI242015.marker = TMP2728;
TMP848[2].kind = 1;
TMP848[2].offset = offsetof(toutercontext242023, Currentenv);
TMP848[2].typ = (&NTI242015);
TMP848[2].name = "currentEnv";
TMP2724[2] = &TMP848[13];
TMP848[13].kind = 1;
TMP848[13].offset = offsetof(toutercontext242023, Capturedvars);
TMP848[13].typ = (&NTI132035);
TMP848[13].name = "capturedVars";
TMP2724[3] = &TMP848[14];
TMP848[14].kind = 1;
TMP848[14].offset = offsetof(toutercontext242023, Processed);
TMP848[14].typ = (&NTI132035);
TMP848[14].name = "processed";
TMP2724[4] = &TMP848[15];
TMP848[15].kind = 1;
TMP848[15].offset = offsetof(toutercontext242023, Localstoenv);
TMP848[15].typ = (&NTI135693);
TMP848[15].name = "localsToEnv";
TMP2724[5] = &TMP848[16];
TMP848[16].kind = 1;
TMP848[16].offset = offsetof(toutercontext242023, Localstoaccess);
TMP848[16].typ = (&NTI135699);
TMP848[16].name = "localsToAccess";
TMP2724[6] = &TMP848[17];
TMP848[17].kind = 1;
TMP848[17].offset = offsetof(toutercontext242023, Lambdastoenv);
TMP848[17].typ = (&NTI135693);
TMP848[17].name = "lambdasToEnv";
TMP2724[7] = &TMP848[18];
TMP848[18].kind = 1;
TMP848[18].offset = offsetof(toutercontext242023, Up);
TMP848[18].typ = (&NTI242013);
TMP848[18].name = "up";
TMP848[0].len = 8; TMP848[0].kind = 2; TMP848[0].sons = &TMP2724[0];
NTI242023.node = &TMP848[0];
NTI242013.size = sizeof(toutercontext242023*);
NTI242013.kind = 22;
NTI242013.base = (&NTI242023);
NTI242013.marker = TMP2729;
NTI242021.size = sizeof(tinnercontext242021);
NTI242021.kind = 18;
NTI242021.base = 0;
NTI242021.flags = 2;
TMP2731[0] = &TMP848[20];
TMP848[20].kind = 1;
TMP848[20].offset = offsetof(tinnercontext242021, Fn);
TMP848[20].typ = (&NTI135645);
TMP848[20].name = "fn";
TMP2731[1] = &TMP848[21];
TMP848[21].kind = 1;
TMP848[21].offset = offsetof(tinnercontext242021, Closureparam);
TMP848[21].typ = (&NTI135645);
TMP848[21].name = "closureParam";
TMP2731[2] = &TMP848[22];
TMP848[22].kind = 1;
TMP848[22].offset = offsetof(tinnercontext242021, Localstoaccess);
TMP848[22].typ = (&NTI135699);
TMP848[22].name = "localsToAccess";
TMP848[19].len = 3; TMP848[19].kind = 2; TMP848[19].sons = &TMP2731[0];
NTI242021.node = &TMP848[19];
NTI242011.size = sizeof(tinnercontext242021*);
NTI242011.kind = 22;
NTI242011.base = (&NTI242021);
NTI242011.flags = 2;
NTI242011.marker = TMP2732;
}

