/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/usr/src/extras/Nimrod/lib -o compiler/nimcache/nimconf.o compiler/nimcache/nimconf.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>

#include <stdio.h>
typedef struct TY188108 TY188108;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcell38449 tcell38449;
typedef struct tcellseq38465 tcellseq38465;
typedef struct tgcheap40416 tgcheap40416;
typedef struct tcellset38461 tcellset38461;
typedef struct tpagedesc38457 tpagedesc38457;
typedef struct tmemregion22010 tmemregion22010;
typedef struct tsmallchunk21243 tsmallchunk21243;
typedef struct tllchunk22004 tllchunk22004;
typedef struct tbigchunk21245 tbigchunk21245;
typedef struct tintset21218 tintset21218;
typedef struct ttrunk21214 ttrunk21214;
typedef struct tavlnode22008 tavlnode22008;
typedef struct tgcstat40414 tgcstat40414;
typedef struct NimStringDesc NimStringDesc;
typedef struct tlexer185168 tlexer185168;
typedef struct tbaselexer183018 tbaselexer183018;
typedef struct TNimObject TNimObject;
typedef struct tllstream182205 tllstream182205;
typedef struct ttoken185166 ttoken185166;
typedef struct tident131018 tident131018;
typedef struct tidobj131012 tidobj131012;
typedef struct tlineinfo128308 tlineinfo128308;
typedef struct tbasechunk21241 tbasechunk21241;
typedef struct tfreecell21233 tfreecell21233;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef N_NIMCALL_PTR(void, TY891) (void* p, NI op);
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY891 marker;
};
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tcell38449 {
NI Refcount;
TNimType* Typ;
};
struct tcellseq38465 {
NI Len;
NI Cap;
tcell38449** D;
};
struct tcellset38461 {
NI Counter;
NI Max;
tpagedesc38457* Head;
tpagedesc38457** Data;
};
typedef tsmallchunk21243* TY22022[512];
typedef ttrunk21214* ttrunkbuckets21216[256];
struct tintset21218 {
ttrunkbuckets21216 Data;
};
struct tmemregion22010 {
NI Minlargeobj;
NI Maxlargeobj;
TY22022 Freesmallchunks;
tllchunk22004* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk21245* Freechunkslist;
tintset21218 Chunkstarts;
tavlnode22008* Root;
tavlnode22008* Deleted;
tavlnode22008* Last;
tavlnode22008* Freeavlnodes;
};
struct tgcstat40414 {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct tgcheap40416 {
void* Stackbottom;
NI Cyclethreshold;
tcellseq38465 Zct;
tcellseq38465 Decstack;
tcellset38461 Cycleroots;
tcellseq38465 Tempstack;
NI Recgclock;
tmemregion22010 Region;
tgcstat40414 Stat;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
struct TNimObject {
TNimType* m_type;
};
struct tbaselexer183018 {
  TNimObject Sup;
NI Bufpos;
NCSTRING Buf;
NI Buflen;
tllstream182205* Stream;
NI Linenumber;
NI Sentinel;
NI Linestart;
};
struct tlexer185168 {
  tbaselexer183018 Sup;
NI32 Fileidx;
NI Indentahead;
};
struct ttoken185166 {
NU8 Toktype;
NI Indent;
tident131018* Ident;
NI64 Inumber;
NF64 Fnumber;
NU8 Base;
NimStringDesc* Literal;
};
struct tidobj131012 {
  TNimObject Sup;
NI Id;
};
struct tident131018 {
  tidobj131012 Sup;
NimStringDesc* S;
tident131018* Next;
NI H;
};
struct tlineinfo128308 {
NI16 Line;
NI16 Col;
NI32 Fileindex;
};
typedef NimStringDesc* TY173708[3];
typedef NI TY21221[8];
struct tpagedesc38457 {
tpagedesc38457* Next;
NI Key;
TY21221 Bits;
};
struct tbasechunk21241 {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct tsmallchunk21243 {
  tbasechunk21241 Sup;
tsmallchunk21243* Next;
tsmallchunk21243* Prev;
tfreecell21233* Freelist;
NI Free;
NI Acc;
NF64 Data;
};
struct tllchunk22004 {
NI Size;
NI Acc;
tllchunk22004* Next;
};
struct tbigchunk21245 {
  tbasechunk21241 Sup;
tbigchunk21245* Next;
tbigchunk21245* Prev;
NI Align;
NF64 Data;
};
struct ttrunk21214 {
ttrunk21214* Next;
NI Key;
TY21221 Bits;
};
typedef tavlnode22008* TY22014[2];
struct tavlnode22008 {
TY22014 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct tllstream182205 {
  TNimObject Sup;
NU8 Kind;
FILE* F;
NimStringDesc* S;
NI Rd;
NI Wr;
NI Lineoffset;
};
struct tfreecell21233 {
tfreecell21233* Next;
NI Zerofield;
};
struct TY188108 {
  TGenericSeq Sup;
  NIM_BOOL data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, TMP765)(void* p, NI op);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell38449*, usrtocell_41843)(void* usr);
static N_INLINE(void, rtladdzct_43002)(tcell38449* c);
N_NOINLINE(void, addzct_41815)(tcellseq38465* s, tcell38449* c);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_NIMCALL(NimStringDesc*, getprefixdir_105310)(void);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, nosjoinPath)(NimStringDesc* head, NimStringDesc* tail);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(void, readconfigfile_188390)(NimStringDesc* filename);
N_NIMCALL(tllstream182205*, llstreamopen_182228)(NimStringDesc* filename, NU8 mode);
N_NIMCALL(void, inittoken_185366)(ttoken185166* l);
N_NIMCALL(void, openlexer_185225)(tlexer185168* lex, NimStringDesc* filename, tllstream182205* inputstream);
N_NIMCALL(void, conftok_188291)(tlexer185168* l, ttoken185166* tok);
N_NIMCALL(void, ppgettok_188006)(tlexer185168* l, ttoken185166* tok);
N_NIMCALL(void, rawgettok_185197)(tlexer185168* l, ttoken185166* tok);
N_NIMCALL(void, parsedirective_188259)(tlexer185168* l, ttoken185166* tok);
N_NIMCALL(NU8, whichkeyword_157340)(tident131018* id);
N_NIMCALL(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemsize, NI newlen);
N_NIMCALL(NIM_BOOL, evalppif_188093)(tlexer185168* l, ttoken185166* tok);
N_NIMCALL(NIM_BOOL, parseexpr_188025)(tlexer185168* l, ttoken185166* tok);
N_NIMCALL(NIM_BOOL, parseandexpr_188059)(tlexer185168* l, ttoken185166* tok);
N_NIMCALL(NIM_BOOL, parseatom_188032)(tlexer185168* l, ttoken185166* tok);
N_NIMCALL(void, lexmessage_185233)(tlexer185168* l, NU16 msg, NimStringDesc* arg);
N_NIMCALL(NIM_BOOL, isdefined_149056)(tident131018* symbol);
N_NIMCALL(void, jumptodirective_188158)(tlexer185168* l, ttoken185166* tok, NU8 dest);
N_NIMCALL(void, doelse_188166)(tlexer185168* l, ttoken185166* tok);
N_NIMCALL(void, doelif_188182)(tlexer185168* l, ttoken185166* tok);
N_NIMCALL(void, doend_188131)(tlexer185168* l, ttoken185166* tok);
N_NIMCALL(void, msgwriteln_129225)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, toktostr_185221)(ttoken185166* tok);
N_NIMCALL(NimStringDesc*, nsuNormalize)(NimStringDesc* s);
N_NIMCALL(void, putenv_95840)(NimStringDesc* key, NimStringDesc* val);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, getenv_95823)(NimStringDesc* key);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(void, parseassignment_188336)(tlexer185168* l, ttoken185166* tok);
N_NIMCALL(tident131018*, getident_131448)(NimStringDesc* identifier);
N_NIMCALL(tlineinfo128308, getlineinfo_185208)(tlexer185168* l);
N_NIMCALL(void, checksymbol_188311)(tlexer185168* l, ttoken185166* tok);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(void, processswitch_159016)(NimStringDesc* switch_159018, NimStringDesc* arg, NU8 pass, tlineinfo128308 info);
N_NIMCALL(void, closelexer_185212)(tlexer185168* lex);
N_NIMCALL(void, rawmessage_129518)(NU16 msg, NimStringDesc* arg);
N_NIMCALL(NimStringDesc*, getsystemconfigpath_188444)(NimStringDesc* filename);
N_NIMCALL(NimStringDesc*, nosjoinPathOpenArray)(NimStringDesc** parts, NI partslen0);
N_NIMCALL(NIM_BOOL, nosexistsFile)(NimStringDesc* filename);
N_NIMCALL(NimStringDesc*, getuserconfigpath_188436)(NimStringDesc* filename);
N_NIMCALL(NimStringDesc*, nosgetConfigDir)(void);
N_NIMCALL(NimStringDesc*, nosgetCurrentDir)(void);
N_NIMCALL(NimStringDesc*, HEX2F_94062)(NimStringDesc* head, NimStringDesc* tail);
N_NIMCALL(NIM_BOOL, nosisRootDir)(NimStringDesc* path);
N_NIMCALL(NimStringDesc*, nosparentDir)(NimStringDesc* path);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_63424, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_NIMCALL(NimStringDesc*, noschangeFileExt)(NimStringDesc* filename, NimStringDesc* ext);
STRING_LITERAL(TMP1304, "/usr", 4);
STRING_LITERAL(TMP1305, "/usr/lib/nimrod", 15);
STRING_LITERAL(TMP1306, "/usr/local", 10);
STRING_LITERAL(TMP1307, "/usr/local/lib/nimrod", 21);
STRING_LITERAL(TMP1308, "lib", 3);
STRING_LITERAL(TMP1338, "@", 1);
STRING_LITERAL(TMP1339, "\')\'", 3);
STRING_LITERAL(TMP1340, "\':\'", 3);
STRING_LITERAL(TMP1341, "@if", 3);
STRING_LITERAL(TMP1342, "@end", 4);
STRING_LITERAL(TMP1461, "putenv", 6);
STRING_LITERAL(TMP1462, "prependenv", 10);
STRING_LITERAL(TMP1463, "appendenv", 9);
STRING_LITERAL(TMP1464, "-", 1);
STRING_LITERAL(TMP1465, "--", 2);
STRING_LITERAL(TMP1466, "", 0);
STRING_LITERAL(TMP1467, "\']\'", 3);
STRING_LITERAL(TMP1468, "&", 1);
STRING_LITERAL(TMP1469, "config", 6);
STRING_LITERAL(TMP1470, "/etc/", 5);
STRING_LITERAL(TMP1472, "cfg", 3);
STRING_LITERAL(TMP1473, "nimrod.cfg", 10);
TY188108* condstack_188128;
extern TNimType NTI132; /* bool */
TNimType NTI188108; /* seq[bool] */
extern tgcheap40416 gch_40442;
extern NimStringDesc* libpath_105190;
extern NU32 gglobaloptions_105108;
extern TNimType NTI185168; /* TLexer */
extern NI gverbosity_105116;
extern NimStringDesc* gprojectpath_105192;
extern NimStringDesc* gprojectname_105191;
extern NimStringDesc* gprojectfull_105193;
N_NIMCALL(void, TMP765)(void* p, NI op) {
	TY188108* a;
	NI LOC1;
	a = (TY188108*)p;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	}
}

static N_INLINE(tcell38449*, usrtocell_41843)(void* usr) {
	tcell38449* result;
	result = 0;
	result = ((tcell38449*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell38449))))));
	return result;
}

static N_INLINE(void, rtladdzct_43002)(tcell38449* c) {
	addzct_41815(&gch_40442.Zct, c);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell38449* c;
	c = usrtocell_41843(p);
	{
		(*c).Refcount -= 8;
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		rtladdzct_43002(c);
	}
	LA3: ;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (NI64)((*a).Sup.len * 1));
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		tcell38449* c;
		if (!!((src == NIM_NIL))) goto LA3;
		c = usrtocell_41843(src);
		(*c).Refcount += 8;
	}
	LA3: ;
	{
		tcell38449* c;
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		c = usrtocell_41843((*dest));
		{
			(*c).Refcount -= 8;
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			rtladdzct_43002(c);
		}
		LA11: ;
	}
	LA7: ;
	(*dest) = src;
}

N_NIMCALL(void, ppgettok_188006)(tlexer185168* l, ttoken185166* tok) {
	rawgettok_185197(l, tok);
	while (1) {
		if (!((*tok).Toktype == ((NU8) 111))) goto LA1;
		rawgettok_185197(l, tok);
	} LA1: ;
}

N_NIMCALL(NIM_BOOL, parseatom_188032)(tlexer185168* l, ttoken185166* tok) {
	NIM_BOOL result;
	result = 0;
	{
		if (!((*tok).Toktype == ((NU8) 91))) goto LA3;
		ppgettok_188006(l, tok);
		result = parseexpr_188025(l, tok);
		{
			if (!((*tok).Toktype == ((NU8) 92))) goto LA7;
			ppgettok_188006(l, tok);
		}
		goto LA5;
		LA7: ;
		{
			lexmessage_185233(&(*l), ((NU16) 23), ((NimStringDesc*) &TMP1339));
		}
		LA5: ;
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC13;
		if (!((*(*tok).Ident).Sup.Id == 43)) goto LA11;
		ppgettok_188006(l, tok);
		LOC13 = parseatom_188032(l, tok);
		result = !(LOC13);
	}
	goto LA1;
	LA11: ;
	{
		result = isdefined_149056((*tok).Ident);
		ppgettok_188006(l, tok);
	}
	LA1: ;
	return result;
}

N_NIMCALL(NIM_BOOL, parseandexpr_188059)(tlexer185168* l, ttoken185166* tok) {
	NIM_BOOL result;
	result = 0;
	result = parseatom_188032(l, tok);
	while (1) {
		NIM_BOOL b;
		NIM_BOOL LOC2;
		if (!((*(*tok).Ident).Sup.Id == 2)) goto LA1;
		ppgettok_188006(l, tok);
		b = parseatom_188032(l, tok);
		LOC2 = result;
		if (!(LOC2)) goto LA3;
		LOC2 = b;
		LA3: ;
		result = LOC2;
	} LA1: ;
	return result;
}

N_NIMCALL(NIM_BOOL, parseexpr_188025)(tlexer185168* l, ttoken185166* tok) {
	NIM_BOOL result;
	result = 0;
	result = parseandexpr_188059(l, tok);
	while (1) {
		NIM_BOOL b;
		NIM_BOOL LOC2;
		if (!((*(*tok).Ident).Sup.Id == 47)) goto LA1;
		ppgettok_188006(l, tok);
		b = parseandexpr_188059(l, tok);
		LOC2 = result;
		if (LOC2) goto LA3;
		LOC2 = b;
		LA3: ;
		result = LOC2;
	} LA1: ;
	return result;
}

N_NIMCALL(NIM_BOOL, evalppif_188093)(tlexer185168* l, ttoken185166* tok) {
	NIM_BOOL result;
	result = 0;
	ppgettok_188006(l, tok);
	result = parseexpr_188025(l, tok);
	{
		if (!((*tok).Toktype == ((NU8) 105))) goto LA3;
		ppgettok_188006(l, tok);
	}
	goto LA1;
	LA3: ;
	{
		lexmessage_185233(&(*l), ((NU16) 23), ((NimStringDesc*) &TMP1340));
	}
	LA1: ;
	return result;
}

N_NIMCALL(void, doelse_188166)(tlexer185168* l, ttoken185166* tok) {
	{
		if (!((condstack_188128->Sup.len-1) < 0)) goto LA3;
		lexmessage_185233(&(*l), ((NU16) 23), ((NimStringDesc*) &TMP1341));
	}
	LA3: ;
	ppgettok_188006(l, tok);
	{
		if (!((*tok).Toktype == ((NU8) 105))) goto LA7;
		ppgettok_188006(l, tok);
	}
	LA7: ;
	{
		if (!condstack_188128->data[(condstack_188128->Sup.len-1)]) goto LA11;
		jumptodirective_188158(l, tok, ((NU8) 0));
	}
	LA11: ;
}

N_NIMCALL(void, doelif_188182)(tlexer185168* l, ttoken185166* tok) {
	NIM_BOOL res;
	{
		if (!((condstack_188128->Sup.len-1) < 0)) goto LA3;
		lexmessage_185233(&(*l), ((NU16) 23), ((NimStringDesc*) &TMP1341));
	}
	LA3: ;
	res = evalppif_188093(l, tok);
	{
		NIM_BOOL LOC7;
		LOC7 = condstack_188128->data[(condstack_188128->Sup.len-1)];
		if (LOC7) goto LA8;
		LOC7 = !(res);
		LA8: ;
		if (!LOC7) goto LA9;
		jumptodirective_188158(l, tok, ((NU8) 1));
	}
	goto LA5;
	LA9: ;
	{
		condstack_188128->data[(condstack_188128->Sup.len-1)] = NIM_TRUE;
	}
	LA5: ;
}

N_NIMCALL(void, doend_188131)(tlexer185168* l, ttoken185166* tok) {
	{
		if (!((condstack_188128->Sup.len-1) < 0)) goto LA3;
		lexmessage_185233(&(*l), ((NU16) 23), ((NimStringDesc*) &TMP1341));
	}
	LA3: ;
	ppgettok_188006(l, tok);
	condstack_188128 = (TY188108*) setLengthSeq(&(condstack_188128)->Sup, sizeof(NIM_BOOL), (condstack_188128->Sup.len-1));
}

N_NIMCALL(void, jumptodirective_188158)(tlexer185168* l, ttoken185166* tok, NU8 dest) {
	NI nestedifs;
	nestedifs = 0;
	while (1) {
		{
			NIM_BOOL LOC4;
			NU8 LOC8;
			LOC4 = !(((*tok).Ident == NIM_NIL));
			if (!(LOC4)) goto LA5;
			LOC4 = eqStrings((*(*tok).Ident).S, ((NimStringDesc*) &TMP1338));
			LA5: ;
			if (!LOC4) goto LA6;
			ppgettok_188006(l, tok);
			LOC8 = whichkeyword_157340((*tok).Ident);
			switch (LOC8) {
			case ((NU8) 28):
			{
				nestedifs += 1;
			}
			break;
			case ((NU8) 19):
			{
				{
					NIM_BOOL LOC13;
					LOC13 = (dest == ((NU8) 1));
					if (!(LOC13)) goto LA14;
					LOC13 = (nestedifs == 0);
					LA14: ;
					if (!LOC13) goto LA15;
					doelse_188166(l, tok);
					goto LA1;
				}
				LA15: ;
			}
			break;
			case ((NU8) 18):
			{
				{
					NIM_BOOL LOC20;
					LOC20 = (dest == ((NU8) 1));
					if (!(LOC20)) goto LA21;
					LOC20 = (nestedifs == 0);
					LA21: ;
					if (!LOC20) goto LA22;
					doelif_188182(l, tok);
					goto LA1;
				}
				LA22: ;
			}
			break;
			case ((NU8) 20):
			{
				{
					if (!(nestedifs == 0)) goto LA27;
					doend_188131(l, tok);
					goto LA1;
				}
				LA27: ;
				{
					if (!(0 < nestedifs)) goto LA31;
					nestedifs -= 1;
				}
				LA31: ;
			}
			break;
			default:
			{
			}
			break;
			}
			ppgettok_188006(l, tok);
		}
		goto LA2;
		LA6: ;
		{
			if (!((*tok).Toktype == ((NU8) 1))) goto LA35;
			lexmessage_185233(&(*l), ((NU16) 23), ((NimStringDesc*) &TMP1342));
		}
		goto LA2;
		LA35: ;
		{
			ppgettok_188006(l, tok);
		}
		LA2: ;
	} LA1: ;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) (&(*dest).data[((*dest).Sup.len)- 0])), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(void, parsedirective_188259)(tlexer185168* l, ttoken185166* tok) {
	NU8 LOC1;
	ppgettok_188006(l, tok);
	LOC1 = whichkeyword_157340((*tok).Ident);
	switch (LOC1) {
	case ((NU8) 28):
	{
		NIM_BOOL res;
		condstack_188128 = (TY188108*) setLengthSeq(&(condstack_188128)->Sup, sizeof(NIM_BOOL), (NI64)(condstack_188128->Sup.len + 1));
		res = evalppif_188093(l, tok);
		condstack_188128->data[(condstack_188128->Sup.len-1)] = res;
		{
			if (!!(res)) goto LA5;
			jumptodirective_188158(l, tok, ((NU8) 1));
		}
		LA5: ;
	}
	break;
	case ((NU8) 18):
	{
		doelif_188182(l, tok);
	}
	break;
	case ((NU8) 19):
	{
		doelse_188166(l, tok);
	}
	break;
	case ((NU8) 20):
	{
		doend_188131(l, tok);
	}
	break;
	case ((NU8) 171):
	{
		NimStringDesc* LOC11;
		ppgettok_188006(l, tok);
		LOC11 = 0;
		LOC11 = toktostr_185221(&(*tok));
		msgwriteln_129225(LOC11);
		ppgettok_188006(l, tok);
	}
	break;
	default:
	{
		NimStringDesc* LOC13;
		LOC13 = 0;
		LOC13 = nsuNormalize((*(*tok).Ident).S);
		if (eqStrings(LOC13, ((NimStringDesc*) &TMP1461))) goto LA14;
		if (eqStrings(LOC13, ((NimStringDesc*) &TMP1462))) goto LA15;
		if (eqStrings(LOC13, ((NimStringDesc*) &TMP1463))) goto LA16;
		goto LA17;
		LA14: ;
		{
			NimStringDesc* key;
			NimStringDesc* LOC20;
			ppgettok_188006(l, tok);
			key = toktostr_185221(&(*tok));
			ppgettok_188006(l, tok);
			LOC20 = 0;
			LOC20 = toktostr_185221(&(*tok));
			putenv_95840(key, LOC20);
			ppgettok_188006(l, tok);
		}
		goto LA18;
		LA15: ;
		{
			NimStringDesc* key;
			NimStringDesc* LOC22;
			NimStringDesc* LOC23;
			NimStringDesc* LOC24;
			ppgettok_188006(l, tok);
			key = toktostr_185221(&(*tok));
			ppgettok_188006(l, tok);
			LOC22 = 0;
			LOC23 = 0;
			LOC23 = toktostr_185221(&(*tok));
			LOC24 = 0;
			LOC24 = getenv_95823(key);
			LOC22 = rawNewString(LOC23->Sup.len + LOC24->Sup.len + 0);
appendString(LOC22, LOC23);
appendString(LOC22, LOC24);
			putenv_95840(key, LOC22);
			ppgettok_188006(l, tok);
		}
		goto LA18;
		LA16: ;
		{
			NimStringDesc* key;
			NimStringDesc* LOC26;
			NimStringDesc* LOC27;
			NimStringDesc* LOC28;
			ppgettok_188006(l, tok);
			key = toktostr_185221(&(*tok));
			ppgettok_188006(l, tok);
			LOC26 = 0;
			LOC27 = 0;
			LOC27 = getenv_95823(key);
			LOC28 = 0;
			LOC28 = toktostr_185221(&(*tok));
			LOC26 = rawNewString(LOC27->Sup.len + LOC28->Sup.len + 0);
appendString(LOC26, LOC27);
appendString(LOC26, LOC28);
			putenv_95840(key, LOC26);
			ppgettok_188006(l, tok);
		}
		goto LA18;
		LA17: ;
		{
			NimStringDesc* LOC30;
			LOC30 = 0;
			LOC30 = toktostr_185221(&(*tok));
			lexmessage_185233(&(*l), ((NU16) 30), LOC30);
		}
		LA18: ;
	}
	break;
	}
}

N_NIMCALL(void, conftok_188291)(tlexer185168* l, ttoken185166* tok) {
	ppgettok_188006(l, tok);
	while (1) {
		NIM_BOOL LOC2;
		LOC2 = !(((*tok).Ident == NIM_NIL));
		if (!(LOC2)) goto LA3;
		LOC2 = eqStrings((*(*tok).Ident).S, ((NimStringDesc*) &TMP1338));
		LA3: ;
		if (!LOC2) goto LA1;
		parsedirective_188259(l, tok);
	} LA1: ;
}

N_NIMCALL(void, checksymbol_188311)(tlexer185168* l, ttoken185166* tok) {
	{
		NimStringDesc* LOC5;
		if (!!(((*tok).Toktype >= ((NU8) 2) && (*tok).Toktype <= ((NU8) 70) || (*tok).Toktype >= ((NU8) 85) && (*tok).Toktype <= ((NU8) 87)))) goto LA3;
		LOC5 = 0;
		LOC5 = toktostr_185221(tok);
		lexmessage_185233(l, ((NU16) 19), LOC5);
	}
	LA3: ;
}

N_NIMCALL(void, parseassignment_188336)(tlexer185168* l, ttoken185166* tok) {
	tlineinfo128308 info;
	NimStringDesc* s;
	NimStringDesc* val;
	{
		NIM_BOOL LOC3;
		tident131018* LOC4;
		tident131018* LOC6;
		LOC4 = 0;
		LOC4 = getident_131448(((NimStringDesc*) &TMP1464));
		LOC3 = ((*(*tok).Ident).Sup.Id == (*LOC4).Sup.Id);
		if (LOC3) goto LA5;
		LOC6 = 0;
		LOC6 = getident_131448(((NimStringDesc*) &TMP1465));
		LOC3 = ((*(*tok).Ident).Sup.Id == (*LOC6).Sup.Id);
		LA5: ;
		if (!LOC3) goto LA7;
		conftok_188291(l, tok);
	}
	LA7: ;
	info = getlineinfo_185208(&(*l));
	checksymbol_188311(&(*l), &(*tok));
	s = toktostr_185221(&(*tok));
	conftok_188291(l, tok);
	val = copyString(((NimStringDesc*) &TMP1466));
	while (1) {
		NimStringDesc* LOC10;
		if (!((*tok).Toktype == ((NU8) 108))) goto LA9;
		s = addChar(s, 46);
		conftok_188291(l, tok);
		checksymbol_188311(&(*l), &(*tok));
		LOC10 = 0;
		LOC10 = toktostr_185221(&(*tok));
		s = resizeString(s, LOC10->Sup.len + 0);
appendString(s, LOC10);
		conftok_188291(l, tok);
	} LA9: ;
	{
		NimStringDesc* LOC15;
		if (!((*tok).Toktype == ((NU8) 93))) goto LA13;
		conftok_188291(l, tok);
		checksymbol_188311(&(*l), &(*tok));
		LOC15 = 0;
		LOC15 = toktostr_185221(&(*tok));
		val = resizeString(val, LOC15->Sup.len + 0);
appendString(val, LOC15);
		conftok_188291(l, tok);
		{
			if (!((*tok).Toktype == ((NU8) 94))) goto LA18;
			conftok_188291(l, tok);
		}
		goto LA16;
		LA18: ;
		{
			lexmessage_185233(&(*l), ((NU16) 23), ((NimStringDesc*) &TMP1467));
		}
		LA16: ;
		val = addChar(val, 93);
	}
	LA13: ;
	{
		NimStringDesc* LOC29;
		if (!((*tok).Toktype == ((NU8) 105) || (*tok).Toktype == ((NU8) 107))) goto LA23;
		{
			if (!(0 < val->Sup.len)) goto LA27;
			val = addChar(val, 58);
		}
		LA27: ;
		conftok_188291(l, tok);
		checksymbol_188311(&(*l), &(*tok));
		LOC29 = 0;
		LOC29 = toktostr_185221(&(*tok));
		val = resizeString(val, LOC29->Sup.len + 0);
appendString(val, LOC29);
		conftok_188291(l, tok);
		while (1) {
			NIM_BOOL LOC31;
			tident131018* LOC33;
			NimStringDesc* LOC34;
			LOC31 = !(((*tok).Ident == NIM_NIL));
			if (!(LOC31)) goto LA32;
			LOC33 = 0;
			LOC33 = getident_131448(((NimStringDesc*) &TMP1468));
			LOC31 = ((*(*tok).Ident).Sup.Id == (*LOC33).Sup.Id);
			LA32: ;
			if (!LOC31) goto LA30;
			conftok_188291(l, tok);
			checksymbol_188311(&(*l), &(*tok));
			LOC34 = 0;
			LOC34 = toktostr_185221(&(*tok));
			val = resizeString(val, LOC34->Sup.len + 0);
appendString(val, LOC34);
			conftok_188291(l, tok);
		} LA30: ;
	}
	LA23: ;
	processswitch_159016(s, val, ((NU8) 2), info);
}

N_NIMCALL(void, readconfigfile_188390)(NimStringDesc* filename) {
	tlexer185168 l;
	ttoken185166 tok;
	tllstream182205* stream;
	memset((void*)&l, 0, sizeof(l));
	l.Sup.Sup.m_type = (&NTI185168);
	memset((void*)&tok, 0, sizeof(tok));
	stream = 0;
	stream = llstreamopen_182228(filename, ((NU8) 0));
	{
		if (!!((stream == NIM_NIL))) goto LA3;
		inittoken_185366(&tok);
		openlexer_185225(&l, filename, stream);
		tok.Toktype = ((NU8) 1);
		conftok_188291(&l, &tok);
		while (1) {
			if (!!((tok.Toktype == ((NU8) 1)))) goto LA5;
			parseassignment_188336(&l, &tok);
		} LA5: ;
		{
			if (!(0 < condstack_188128->Sup.len)) goto LA8;
			lexmessage_185233(&l, ((NU16) 23), ((NimStringDesc*) &TMP1342));
		}
		LA8: ;
		closelexer_185212(&l);
		{
			if (!(1 <= gverbosity_105116)) goto LA12;
			rawmessage_129518(((NU16) 255), filename);
		}
		LA12: ;
	}
	LA3: ;
}

N_NIMCALL(NimStringDesc*, getsystemconfigpath_188444)(NimStringDesc* filename) {
	NimStringDesc* result;
	TY173708 LOC1;
	result = 0;
	memset((void*)LOC1, 0, sizeof(LOC1));
	LOC1[0] = getprefixdir_105310();
	LOC1[1] = copyString(((NimStringDesc*) &TMP1469));
	LOC1[2] = copyString(filename);
	result = nosjoinPathOpenArray(LOC1, 3);
	{
		NIM_BOOL LOC4;
		NimStringDesc* LOC7;
		LOC4 = nosexistsFile(result);
		if (!!(LOC4)) goto LA5;
		LOC7 = 0;
		LOC7 = rawNewString(filename->Sup.len + 5);
appendString(LOC7, ((NimStringDesc*) &TMP1470));
appendString(LOC7, filename);
		result = LOC7;
	}
	LA5: ;
	return result;
}

N_NIMCALL(NimStringDesc*, getuserconfigpath_188436)(NimStringDesc* filename) {
	NimStringDesc* result;
	NimStringDesc* LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = nosgetConfigDir();
	result = nosjoinPath(LOC1, filename);
	return result;
}

N_NIMCALL(void, loadconfigs_188454)(NimStringDesc* cfg) {
	NimStringDesc* pd;
	{
		NimStringDesc* prefix;
		if (!((libpath_105190) && (libpath_105190)->Sup.len == 0)) goto LA3;
		prefix = getprefixdir_105310();
		{
			NimStringDesc* LOC9;
			if (!eqStrings(prefix, ((NimStringDesc*) &TMP1304))) goto LA7;
			LOC9 = 0;
			LOC9 = libpath_105190; libpath_105190 = copyStringRC1(((NimStringDesc*) &TMP1305));
			if (LOC9) nimGCunrefNoCycle(LOC9);
		}
		goto LA5;
		LA7: ;
		{
			NimStringDesc* LOC13;
			if (!eqStrings(prefix, ((NimStringDesc*) &TMP1306))) goto LA11;
			LOC13 = 0;
			LOC13 = libpath_105190; libpath_105190 = copyStringRC1(((NimStringDesc*) &TMP1307));
			if (LOC13) nimGCunrefNoCycle(LOC13);
		}
		goto LA5;
		LA11: ;
		{
			asgnRefNoCycle((void**) &libpath_105190, nosjoinPath(prefix, ((NimStringDesc*) &TMP1308)));
		}
		LA5: ;
	}
	LA3: ;
	{
		NimStringDesc* LOC19;
		if (!!(((gglobaloptions_105108 &(1<<((((NU8) 16))&31)))!=0))) goto LA17;
		LOC19 = 0;
		LOC19 = getsystemconfigpath_188444(cfg);
		readconfigfile_188390(LOC19);
	}
	LA17: ;
	{
		NimStringDesc* LOC24;
		if (!!(((gglobaloptions_105108 &(1<<((((NU8) 18))&31)))!=0))) goto LA22;
		LOC24 = 0;
		LOC24 = getuserconfigpath_188436(cfg);
		readconfigfile_188390(LOC24);
	}
	LA22: ;
	{
		if (!(0 < gprojectpath_105192->Sup.len)) goto LA27;
		pd = copyString(gprojectpath_105192);
	}
	goto LA25;
	LA27: ;
	{
		pd = nosgetCurrentDir();
	}
	LA25: ;
	{
		NimStringDesc* dir_188490;
		if (!!(((gglobaloptions_105108 &(1<<((((NU8) 19))&31)))!=0))) goto LA32;
		dir_188490 = 0;
		{
			NimStringDesc* current_188502;
			if (!NIM_FALSE) goto LA36;
			current_188502 = copyString(pd);
			{
				NimStringDesc* LOC42;
				if (!NIM_FALSE) goto LA40;
				dir_188490 = pd;
				LOC42 = 0;
				LOC42 = HEX2F_94062(dir_188490, cfg);
				readconfigfile_188390(LOC42);
			}
			LA40: ;
			while (1) {
				NimStringDesc* LOC49;
				{
					NIM_BOOL LOC46;
					LOC46 = nosisRootDir(current_188502);
					if (!LOC46) goto LA47;
					goto LA43;
				}
				LA47: ;
				current_188502 = nosparentDir(current_188502);
				dir_188490 = current_188502;
				LOC49 = 0;
				LOC49 = HEX2F_94062(dir_188490, cfg);
				readconfigfile_188390(LOC49);
			} LA43: ;
		}
		goto LA34;
		LA36: ;
		{
			NI i_188504;
			NI HEX3Atmp_188506;
			NI res_188508;
			i_188504 = 0;
			HEX3Atmp_188506 = 0;
			HEX3Atmp_188506 = (NI64)(pd->Sup.len - 2);
			res_188508 = 0;
			while (1) {
				if (!(res_188508 <= HEX3Atmp_188506)) goto LA51;
				i_188504 = res_188508;
				{
					NIM_BOOL LOC54;
					NIM_BOOL LOC56;
					NimStringDesc* LOC60;
					LOC54 = (((NU8)(pd->data[i_188504])) == ((NU8)(47)) || ((NU8)(pd->data[i_188504])) == ((NU8)(47)));
					if (!(LOC54)) goto LA55;
					LOC56 = (i_188504 == 0);
					if (LOC56) goto LA57;
					LOC56 = !((((NU8)(pd->data[(NI64)(i_188504 - 1)])) == ((NU8)(47)) || ((NU8)(pd->data[(NI64)(i_188504 - 1)])) == ((NU8)(47))));
					LA57: ;
					LOC54 = LOC56;
					LA55: ;
					if (!LOC54) goto LA58;
					dir_188490 = copyStrLast(pd, 0, i_188504);
					LOC60 = 0;
					LOC60 = HEX2F_94062(dir_188490, cfg);
					readconfigfile_188390(LOC60);
				}
				LA58: ;
				res_188508 += 1;
			} LA51: ;
			{
				NimStringDesc* LOC65;
				if (!NIM_FALSE) goto LA63;
				dir_188490 = pd;
				LOC65 = 0;
				LOC65 = HEX2F_94062(dir_188490, cfg);
				readconfigfile_188390(LOC65);
			}
			LA63: ;
		}
		LA34: ;
	}
	LA32: ;
	{
		NimStringDesc* LOC70;
		if (!!(((gglobaloptions_105108 &(1<<((((NU8) 17))&31)))!=0))) goto LA68;
		LOC70 = 0;
		LOC70 = HEX2F_94062(pd, cfg);
		readconfigfile_188390(LOC70);
		{
			NimStringDesc* conffile;
			NimStringDesc* LOC82;
			if (!!((gprojectname_105191->Sup.len == 0))) goto LA73;
			conffile = noschangeFileExt(gprojectfull_105193, ((NimStringDesc*) &TMP1472));
			{
				NIM_BOOL LOC77;
				NimStringDesc* LOC78;
				LOC78 = 0;
				LOC78 = HEX2F_94062(pd, cfg);
				LOC77 = !(eqStrings(conffile, LOC78));
				if (!(LOC77)) goto LA79;
				LOC77 = nosexistsFile(conffile);
				LA79: ;
				if (!LOC77) goto LA80;
				readconfigfile_188390(conffile);
				rawmessage_129518(((NU16) 225), conffile);
			}
			LA80: ;
			LOC82 = 0;
			LOC82 = noschangeFileExt(gprojectfull_105193, ((NimStringDesc*) &TMP1473));
			readconfigfile_188390(LOC82);
		}
		LA73: ;
	}
	LA68: ;
}
N_NOINLINE(void, nimconfInit)(void) {
	if (condstack_188128) nimGCunrefNoCycle(condstack_188128);
	condstack_188128 = (TY188108*) newSeqRC1((&NTI188108), 0);
}

N_NOINLINE(void, nimconfDatInit)(void) {
NTI188108.size = sizeof(TY188108*);
NTI188108.kind = 24;
NTI188108.base = (&NTI132);
NTI188108.flags = 2;
NTI188108.marker = TMP765;
}

