/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/usr/src/extras/Nimrod/lib -o compiler/nimcache/nimlexbase.o compiler/nimcache/nimlexbase.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>

#include <stdio.h>
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tbaselexer183018 tbaselexer183018;
typedef struct TNimObject TNimObject;
typedef struct tllstream182205 tllstream182205;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef N_NIMCALL_PTR(void, TY891) (void* p, NI op);
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY891 marker;
};
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TNimObject {
TNimType* m_type;
};
struct tbaselexer183018 {
  TNimObject Sup;
NI Bufpos;
NCSTRING Buf;
NI Buflen;
tllstream182205* Stream;
NI Linenumber;
NI Sentinel;
NI Linestart;
};
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
struct tllstream182205 {
  TNimObject Sup;
NU8 Kind;
FILE* F;
NimStringDesc* S;
NI Rd;
NI Wr;
NI Lineoffset;
};
N_NOCONV(void*, alloc_4001)(NI size);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(void, fillbuffer_183073)(tbaselexer183018* l);
N_NIMCALL(NI, llstreamread_182243)(tllstream182205* s, void* buf, NI buflen);
N_NOCONV(void*, realloc_4007)(void* p, NI newsize);
N_NIMCALL(void, skiputf8bom_184415)(tbaselexer183018* l);
N_NIMCALL(NI, fillbaselexer_183813)(tbaselexer183018* l, NI pos);
N_NOCONV(void, dealloc_4011)(void* p);
N_NIMCALL(void, llstreamclose_182239)(tllstream182205* s);
extern TNimType NTI1009; /* TObject */
TNimType NTI183018; /* TBaseLexer */
extern TNimType NTI105; /* int */
extern TNimType NTI145; /* cstring */
extern TNimType NTI182207; /* PLLStream */

N_NIMCALL(void, fillbuffer_183073)(tbaselexer183018* l) {
	NI charsread;
	NI tocopy;
	NI s;
	NI oldbuflen;
	NI LOC5;
	charsread = 0;
	tocopy = 0;
	s = 0;
	oldbuflen = 0;
	tocopy = (NI64)((NI64)((*l).Buflen - (*l).Sentinel) - 1);
	{
		if (!(0 < tocopy)) goto LA3;
		memmove(((void*) ((*l).Buf)), ((void*) (&(*l).Buf[(NI64)((*l).Sentinel + 1)])), (NI64)(tocopy * 1));
	}
	LA3: ;
	LOC5 = llstreamread_182243((*l).Stream, ((void*) (&(*l).Buf[tocopy])), (NI64)((NI64)((*l).Sentinel + 1) * 1));
	charsread = (NI64)(LOC5 / 1);
	s = (NI64)(tocopy + charsread);
	{
		if (!(charsread < (NI64)((*l).Sentinel + 1))) goto LA8;
		(*l).Buf[s] = 0;
		(*l).Sentinel = s;
	}
	goto LA6;
	LA8: ;
	{
		s -= 1;
		while (1) {
			while (1) {
				NIM_BOOL LOC13;
				LOC13 = (0 <= s);
				if (!(LOC13)) goto LA14;
				LOC13 = !((((NU8)((*l).Buf[s])) == ((NU8)(13)) || ((NU8)((*l).Buf[s])) == ((NU8)(10))));
				LA14: ;
				if (!LOC13) goto LA12;
				s -= 1;
			} LA12: ;
			{
				if (!(0 <= s)) goto LA17;
				(*l).Sentinel = s;
				goto LA11;
			}
			goto LA15;
			LA17: ;
			{
				void* LOC20;
				NI LOC21;
				oldbuflen = (*l).Buflen;
				(*l).Buflen = (NI64)((*l).Buflen * 2);
				LOC20 = realloc_4007(((void*) ((*l).Buf)), (NI64)((*l).Buflen * 1));
				(*l).Buf = ((NCSTRING) (LOC20));
				LOC21 = llstreamread_182243((*l).Stream, ((void*) (&(*l).Buf[oldbuflen])), (NI64)(oldbuflen * 1));
				charsread = (NI64)(LOC21 / 1);
				{
					if (!(charsread < oldbuflen)) goto LA24;
					(*l).Buf[(NI64)(oldbuflen + charsread)] = 0;
					(*l).Sentinel = (NI64)(oldbuflen + charsread);
					goto LA11;
				}
				LA24: ;
				s = (NI64)((*l).Buflen - 1);
			}
			LA15: ;
		} LA11: ;
	}
	LA6: ;
}

N_NIMCALL(void, skiputf8bom_184415)(tbaselexer183018* l) {
	{
		NIM_BOOL LOC3;
		NIM_BOOL LOC4;
		LOC4 = ((NU8)((*l).Buf[0]) == (NU8)(239));
		if (!(LOC4)) goto LA5;
		LOC4 = ((NU8)((*l).Buf[1]) == (NU8)(187));
		LA5: ;
		LOC3 = LOC4;
		if (!(LOC3)) goto LA6;
		LOC3 = ((NU8)((*l).Buf[2]) == (NU8)(191));
		LA6: ;
		if (!LOC3) goto LA7;
		(*l).Bufpos += 3;
		(*l).Linestart += 3;
	}
	LA7: ;
}

N_NIMCALL(void, openbaselexer_183027)(tbaselexer183018* l, tllstream182205* inputstream, NI buflen) {
	void* LOC1;
	(*l).Bufpos = 0;
	(*l).Buflen = buflen;
	LOC1 = alloc_4001((NI64)(buflen * 1));
	(*l).Buf = ((NCSTRING) (LOC1));
	(*l).Sentinel = (NI64)(buflen - 1);
	(*l).Linestart = 0;
	(*l).Linenumber = 1;
	unsureAsgnRef((void**) &(*l).Stream, inputstream);
	fillbuffer_183073(l);
	skiputf8bom_184415(l);
}

N_NIMCALL(NI, getcolnumber_183046)(tbaselexer183018* l, NI pos) {
	NI result;
	result = 0;
	result = (NI64)abs((NI64)(pos - (*l).Linestart));
	return result;
}

N_NIMCALL(NI, fillbaselexer_183813)(tbaselexer183018* l, NI pos) {
	NI result;
	result = 0;
	{
		if (!(pos < (*l).Sentinel)) goto LA3;
		result = (NI64)(pos + 1);
	}
	goto LA1;
	LA3: ;
	{
		fillbuffer_183073(l);
		(*l).Bufpos = 0;
		result = 0;
	}
	LA1: ;
	(*l).Linestart = result;
	return result;
}

N_NIMCALL(NI, handlecr_183051)(tbaselexer183018* l, NI pos) {
	NI result;
	result = 0;
	(*l).Linenumber += 1;
	result = fillbaselexer_183813(l, pos);
	{
		if (!((NU8)((*l).Buf[result]) == (NU8)(10))) goto LA3;
		result = fillbaselexer_183813(l, result);
	}
	LA3: ;
	return result;
}

N_NIMCALL(NI, handlelf_183057)(tbaselexer183018* l, NI pos) {
	NI result;
	result = 0;
	(*l).Linenumber += 1;
	result = fillbaselexer_183813(l, pos);
	return result;
}

N_NIMCALL(void, closebaselexer_183036)(tbaselexer183018* l) {
	dealloc_4011(((void*) ((*l).Buf)));
	llstreamclose_182239((*l).Stream);
}
N_NOINLINE(void, nimlexbaseInit)(void) {
}

N_NOINLINE(void, nimlexbaseDatInit)(void) {
static TNimNode* TMP1309[7];
static TNimNode TMP743[8];
NTI183018.size = sizeof(tbaselexer183018);
NTI183018.kind = 17;
NTI183018.base = (&NTI1009);
NTI183018.flags = 2;
TMP1309[0] = &TMP743[1];
TMP743[1].kind = 1;
TMP743[1].offset = offsetof(tbaselexer183018, Bufpos);
TMP743[1].typ = (&NTI105);
TMP743[1].name = "bufpos";
TMP1309[1] = &TMP743[2];
TMP743[2].kind = 1;
TMP743[2].offset = offsetof(tbaselexer183018, Buf);
TMP743[2].typ = (&NTI145);
TMP743[2].name = "buf";
TMP1309[2] = &TMP743[3];
TMP743[3].kind = 1;
TMP743[3].offset = offsetof(tbaselexer183018, Buflen);
TMP743[3].typ = (&NTI105);
TMP743[3].name = "bufLen";
TMP1309[3] = &TMP743[4];
TMP743[4].kind = 1;
TMP743[4].offset = offsetof(tbaselexer183018, Stream);
TMP743[4].typ = (&NTI182207);
TMP743[4].name = "stream";
TMP1309[4] = &TMP743[5];
TMP743[5].kind = 1;
TMP743[5].offset = offsetof(tbaselexer183018, Linenumber);
TMP743[5].typ = (&NTI105);
TMP743[5].name = "lineNumber";
TMP1309[5] = &TMP743[6];
TMP743[6].kind = 1;
TMP743[6].offset = offsetof(tbaselexer183018, Sentinel);
TMP743[6].typ = (&NTI105);
TMP743[6].name = "sentinel";
TMP1309[6] = &TMP743[7];
TMP743[7].kind = 1;
TMP743[7].offset = offsetof(tbaselexer183018, Linestart);
TMP743[7].typ = (&NTI105);
TMP743[7].name = "lineStart";
TMP743[0].len = 7; TMP743[0].kind = 2; TMP743[0].sons = &TMP1309[0];
NTI183018.node = &TMP743[0];
}

