/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/usr/src/extras/Nimrod/lib -o compiler/nimcache/nversion.o compiler/nimcache/nversion.c */
#define NIM_INTBITS 64
#include "nimbase.h"
N_NOINLINE(void, nversionInit)(void) {
}

N_NOINLINE(void, nversionDatInit)(void) {
}

