/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/usr/src/extras/Nimrod/lib -o compiler/nimcache/passes.o compiler/nimcache/passes.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <stdio.h>
typedef struct tsym135677 tsym135677;
typedef struct tnode135647 tnode135647;
typedef struct tpass224015 tpass224015;
typedef struct tpasscontext224003 tpasscontext224003;
typedef struct trodreader213023 trodreader213023;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TNimObject TNimObject;
typedef struct tllstream182205 tllstream182205;
typedef struct tparsers200026 tparsers200026;
typedef struct tparser189203 tparser189203;
typedef struct tlexer185168 tlexer185168;
typedef struct tbaselexer183018 tbaselexer183018;
typedef struct ttoken185166 ttoken185166;
typedef struct tident131018 tident131018;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tidobj131012 tidobj131012;
typedef struct ttypeseq135679 ttypeseq135679;
typedef struct ttype135681 ttype135681;
typedef struct TY135771 TY135771;
typedef struct tinstantiation135667 tinstantiation135667;
typedef struct tscope135671 tscope135671;
typedef struct tstrtable135651 tstrtable135651;
typedef struct tsymseq135649 tsymseq135649;
typedef struct tlineinfo128308 tlineinfo128308;
typedef struct tloc135661 tloc135661;
typedef struct trope126007 trope126007;
typedef struct tlib135665 tlib135665;
typedef struct TY95234 TY95234;
typedef struct tnodeseq135641 tnodeseq135641;
typedef struct TY324559 TY324559;
typedef struct TY135763 TY135763;
typedef struct tindex213021 tindex213021;
typedef struct tiitable142212 tiitable142212;
typedef struct tiipairseq142210 tiipairseq142210;
typedef struct tiipair142208 tiipair142208;
typedef struct tidtable135693 tidtable135693;
typedef struct tidpairseq135691 tidpairseq135691;
typedef struct tidpair135689 tidpair135689;
typedef struct tmemfile211204 tmemfile211204;
typedef struct tlistentry100011 tlistentry100011;
typedef N_NIMCALL_PTR(tsym135677*, TY224056) (tsym135677* m, NI32 fileidx);
typedef N_NIMCALL_PTR(tnode135647*, TY224061) (tsym135677* m, NI32 fileidx);
typedef N_NIMCALL_PTR(tpasscontext224003*, tpassopen224007) (tsym135677* module);
typedef N_NIMCALL_PTR(tpasscontext224003*, tpassopencached224009) (tsym135677* module, trodreader213023* rd);
typedef N_NIMCALL_PTR(tnode135647*, tpassprocess224013) (tpasscontext224003* p, tnode135647* toplevelstmt);
typedef N_NIMCALL_PTR(tnode135647*, tpassclose224011) (tpasscontext224003* p, tnode135647* n);
struct tpass224015 {
tpassopen224007 Field0;
tpassopencached224009 Field1;
tpassprocess224013 Field2;
tpassclose224011 Field3;
};
typedef tpass224015 TY224150[10];
typedef N_NIMCALL_PTR(void, TY891) (void* p, NI op);
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY891 marker;
};
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TNimObject {
TNimType* m_type;
};
struct tpasscontext224003 {
  TNimObject Sup;
NIM_BOOL Fromcache;
};
struct tbaselexer183018 {
  TNimObject Sup;
NI Bufpos;
NCSTRING Buf;
NI Buflen;
tllstream182205* Stream;
NI Linenumber;
NI Sentinel;
NI Linestart;
};
struct tlexer185168 {
  tbaselexer183018 Sup;
NI32 Fileidx;
NI Indentahead;
};
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
struct ttoken185166 {
NU8 Toktype;
NI Indent;
tident131018* Ident;
NI64 Inumber;
NF64 Fnumber;
NU8 Base;
NimStringDesc* Literal;
};
struct tparser189203 {
NI Currind;
NIM_BOOL Firsttok;
tlexer185168 Lex;
ttoken185166 Tok;
};
struct tparsers200026 {
NU8 Skin;
tparser189203 Parser;
};
typedef tpasscontext224003* tpasscontextarray224147[10];
struct tidobj131012 {
  TNimObject Sup;
NI Id;
};
struct tstrtable135651 {
NI Counter;
tsymseq135649* Data;
};
struct tlineinfo128308 {
NI16 Line;
NI16 Col;
NI32 Fileindex;
};
struct tloc135661 {
NU8 K;
NU8 S;
NU8 Flags;
ttype135681* T;
trope126007* R;
trope126007* Heaproot;
NI A;
};
struct tsym135677 {
  tidobj131012 Sup;
NU8 Kind;
union {
struct {ttypeseq135679* Typeinstcache;
} S1;
struct {TY135771* Procinstcache;
tscope135671* Scope;
} S2;
struct {TY135771* Usedgenerics;
tstrtable135651 Tab;
} S3;
} kindU;
NU16 Magic;
ttype135681* Typ;
tident131018* Name;
tlineinfo128308 Info;
tsym135677* Owner;
NU32 Flags;
tnode135647* Ast;
NU32 Options;
NI Position;
NI Offset;
tloc135661 Loc;
tlib135665* Annex;
tnode135647* Constraint;
};
struct tnode135647 {
ttype135681* Typ;
tlineinfo128308 Info;
NU8 Flags;
NU8 Kind;
union {
struct {NI64 Intval;
} S1;
struct {NF64 Floatval;
} S2;
struct {NimStringDesc* Strval;
} S3;
struct {tsym135677* Sym;
} S4;
struct {tident131018* Ident;
} S5;
struct {tnodeseq135641* Sons;
} S6;
} kindU;
NimStringDesc* Comment;
};
struct tllstream182205 {
  TNimObject Sup;
NU8 Kind;
FILE* F;
NimStringDesc* S;
NI Rd;
NI Wr;
NI Lineoffset;
};
struct ttype135681 {
  tidobj131012 Sup;
NU8 Kind;
NU8 Callconv;
NU32 Flags;
ttypeseq135679* Sons;
tnode135647* N;
tsym135677* Destructor;
tsym135677* Owner;
tsym135677* Sym;
NI64 Size;
NI Align;
tloc135661 Loc;
};
struct TY324559 {
tnode135647* Field0;
tnode135647* Field1;
};
struct tiipair142208 {
NI Key;
NI Val;
};
struct tiitable142212 {
NI Counter;
tiipairseq142210* Data;
};
struct tindex213021 {
NI Lastidxkey;
NI Lastidxval;
tiitable142212 Tab;
NimStringDesc* R;
NI Offset;
};
struct tidpair135689 {
tidobj131012* Key;
TNimObject* Val;
};
struct tidtable135693 {
NI Counter;
tidpairseq135691* Data;
};
struct tmemfile211204 {
void* Mem;
NI Size;
int Handle;
};
struct trodreader213023 {
  TNimObject Sup;
NI Pos;
NCSTRING S;
NU32 Options;
NU8 Reason;
TY135763* Moddeps;
TY135763* Files;
NI Dataidx;
NI Convertersidx;
NI Initidx;
NI Interfidx;
NI Compilerprocsidx;
NI Methodsidx;
NimStringDesc* Filename;
tindex213021 Index;
tindex213021 Imports;
NI Readerindex;
NI Line;
NI Moduleid;
tidtable135693 Syms;
tmemfile211204 Memfile;
tsymseq135649* Methods;
NIM_BOOL Inviewmode;
};
struct tident131018 {
  tidobj131012 Sup;
NimStringDesc* S;
tident131018* Next;
NI H;
};
struct tinstantiation135667 {
tsym135677* Sym;
ttypeseq135679* Concretetypes;
TY135763* Usedby;
};
struct tscope135671 {
NI Depthlevel;
tstrtable135651 Symbols;
tscope135671* Parent;
};
struct trope126007 {
  TNimObject Sup;
trope126007* Left;
trope126007* Right;
NI Length;
NimStringDesc* Data;
};
struct tlistentry100011 {
  TNimObject Sup;
tlistentry100011* Prev;
tlistentry100011* Next;
};
struct tlib135665 {
  tlistentry100011 Sup;
NU8 Kind;
NIM_BOOL Generated;
NIM_BOOL Isoverriden;
trope126007* Name;
tnode135647* Path;
};
struct ttypeseq135679 {
  TGenericSeq Sup;
  ttype135681* data[SEQ_DECL_SIZE];
};
struct TY135771 {
  TGenericSeq Sup;
  tinstantiation135667* data[SEQ_DECL_SIZE];
};
struct tsymseq135649 {
  TGenericSeq Sup;
  tsym135677* data[SEQ_DECL_SIZE];
};
struct TY95234 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tnodeseq135641 {
  TGenericSeq Sup;
  tnode135647* data[SEQ_DECL_SIZE];
};
struct TY135763 {
  TGenericSeq Sup;
  NI32 data[SEQ_DECL_SIZE];
};
struct tiipairseq142210 {
  TGenericSeq Sup;
  tiipair142208 data[SEQ_DECL_SIZE];
};
struct tidpairseq135691 {
  TGenericSeq Sup;
  tidpair135689 data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, objectInit)(void* dest, TNimType* typ);
N_NIMCALL(void, openpasses_224237)(tpasscontext224003** a, tsym135677* module);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, tofullpath_129095)(NI32 fileidx);
N_NIMCALL(tllstream182205*, llstreamopen_182228)(NimStringDesc* filename, NU8 mode);
N_NIMCALL(void, rawmessage_129518)(NU16 msg, NimStringDesc* arg);
N_NIMCALL(void, openparsers_200034)(tparsers200026* p, NI32 fileidx, tllstream182205* inputstream);
N_NIMCALL(void, processimplicits_224423)(TY95234* implicits, NU8 nodekind, tpasscontext224003** a);
N_NIMCALL(tnode135647*, newnodei_135920)(NU8 kind, tlineinfo128308 info);
N_NIMCALL(tnode135647*, newstrnode_135906)(NU8 kind, NimStringDesc* strval);
N_NIMCALL(void, addson_136028)(tnode135647* father, tnode135647* son);
N_NIMCALL(NIM_BOOL, processtoplevelstmt_224328)(tnode135647* n, tpasscontext224003** a);
N_NIMCALL(tnode135647*, parsetoplevelstmt_200051)(tparsers200026* p);
N_NIMCALL(void, closeparsers_200041)(tparsers200026* p);
N_NIMCALL(void, closepasses_224301)(tpasscontext224003** a);
N_NIMCALL(void, idsynchronizationpoint_134445)(NI idrange);
N_NIMCALL(void, openpassescached_224263)(tpasscontext224003** a, tsym135677* module, trodreader213023* rd);
N_NIMCALL(tnode135647*, loadinitsection_213064)(trodreader213023* r);
static N_INLINE(NI, sonslen_136002)(tnode135647* n);
N_NIMCALL(void, processtoplevelstmtcached_224364)(tnode135647* n, tpasscontext224003** a);
N_NIMCALL(void, closepassescached_224391)(tpasscontext224003** a);
N_NIMCALL(NIM_BOOL, needsglobalanalysis_223359)(void);
N_NIMCALL(void, carrypass_224178)(tpass224015* p, tsym135677* module, TY324559 m, TY324559* Result);
TY224056 gimportmodule_224060;
TY224061 gincludefile_224065;
TY224150 gpasses_224152;
NI gpasseslen_224153;
extern TNimType NTI1009; /* TObject */
TNimType NTI224003; /* TPassContext */
extern TNimType NTI132; /* bool */
extern TNimType NTI200026; /* TParsers */
extern tlineinfo128308 gcmdlineinfo_128801;
extern TY95234* implicitimports_105240;
extern TY95234* implicitincludes_105261;

N_NIMCALL(void, clearpasses_224157)(void) {
	gpasseslen_224153 = 0;
}

N_NIMCALL(void, openpasses_224237)(tpasscontext224003** a, tsym135677* module) {
	NI i_224250;
	NI HEX3Atmp_224256;
	NI res_224258;
	i_224250 = 0;
	HEX3Atmp_224256 = 0;
	HEX3Atmp_224256 = (NI64)(gpasseslen_224153 - 1);
	res_224258 = 0;
	while (1) {
		if (!(res_224258 <= HEX3Atmp_224256)) goto LA1;
		i_224250 = res_224258;
		{
			if (!!(gpasses_224152[(i_224250)- 0].Field0 == 0)) goto LA4;
			unsureAsgnRef((void**) &a[(i_224250)- 0], gpasses_224152[(i_224250)- 0].Field0(module));
		}
		goto LA2;
		LA4: ;
		{
			unsureAsgnRef((void**) &a[(i_224250)- 0], NIM_NIL);
		}
		LA2: ;
		res_224258 += 1;
	} LA1: ;
}

N_NIMCALL(NIM_BOOL, processtoplevelstmt_224328)(tnode135647* n, tpasscontext224003** a) {
	NIM_BOOL result;
	tnode135647* m;
	NI i_224343;
	NI HEX3Atmp_224357;
	NI res_224359;
	result = 0;
	m = n;
	i_224343 = 0;
	HEX3Atmp_224357 = 0;
	HEX3Atmp_224357 = (NI64)(gpasseslen_224153 - 1);
	res_224359 = 0;
	while (1) {
		if (!(res_224359 <= HEX3Atmp_224357)) goto LA1;
		i_224343 = res_224359;
		{
			if (!!(gpasses_224152[(i_224343)- 0].Field2 == 0)) goto LA4;
			m = gpasses_224152[(i_224343)- 0].Field2(a[(i_224343)- 0], m);
			{
				if (!m == 0) goto LA8;
				result = NIM_FALSE;
				goto BeforeRet;
			}
			LA8: ;
		}
		LA4: ;
		res_224359 += 1;
	} LA1: ;
	result = NIM_TRUE;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, processimplicits_224423)(TY95234* implicits, NU8 nodekind, tpasscontext224003** a) {
	NimStringDesc* module_224440;
	NI i_224444;
	module_224440 = 0;
	i_224444 = 0;
	while (1) {
		tnode135647* importstmt;
		tnode135647* str;
		if (!(i_224444 < implicits->Sup.len)) goto LA1;
		module_224440 = implicits->data[i_224444];
		importstmt = newnodei_135920(nodekind, gcmdlineinfo_128801);
		str = newstrnode_135906(((NU8) 20), module_224440);
		(*str).Info = gcmdlineinfo_128801;
		addson_136028(importstmt, str);
		{
			NIM_BOOL LOC4;
			LOC4 = processtoplevelstmt_224328(importstmt, a);
			if (!!(LOC4)) goto LA5;
			goto LA1;
		}
		LA5: ;
		i_224444 += 1;
	} LA1: ;
}

N_NIMCALL(void, closepasses_224301)(tpasscontext224003** a) {
	tnode135647* m;
	NI i_224314;
	NI HEX3Atmp_224321;
	NI res_224323;
	m = NIM_NIL;
	i_224314 = 0;
	HEX3Atmp_224321 = 0;
	HEX3Atmp_224321 = (NI64)(gpasseslen_224153 - 1);
	res_224323 = 0;
	while (1) {
		if (!(res_224323 <= HEX3Atmp_224321)) goto LA1;
		i_224314 = res_224323;
		{
			if (!!(gpasses_224152[(i_224314)- 0].Field3 == 0)) goto LA4;
			m = gpasses_224152[(i_224314)- 0].Field3(a[(i_224314)- 0], m);
		}
		LA4: ;
		unsureAsgnRef((void**) &a[(i_224314)- 0], NIM_NIL);
		res_224323 += 1;
	} LA1: ;
}

N_NIMCALL(void, openpassescached_224263)(tpasscontext224003** a, tsym135677* module, trodreader213023* rd) {
	NI i_224277;
	NI HEX3Atmp_224294;
	NI res_224296;
	i_224277 = 0;
	HEX3Atmp_224294 = 0;
	HEX3Atmp_224294 = (NI64)(gpasseslen_224153 - 1);
	res_224296 = 0;
	while (1) {
		if (!(res_224296 <= HEX3Atmp_224294)) goto LA1;
		i_224277 = res_224296;
		{
			if (!!(gpasses_224152[(i_224277)- 0].Field1 == 0)) goto LA4;
			unsureAsgnRef((void**) &a[(i_224277)- 0], gpasses_224152[(i_224277)- 0].Field1(module, rd));
			{
				if (!!((a[(i_224277)- 0] == NIM_NIL))) goto LA8;
				(*a[(i_224277)- 0]).Fromcache = NIM_TRUE;
			}
			LA8: ;
		}
		goto LA2;
		LA4: ;
		{
			unsureAsgnRef((void**) &a[(i_224277)- 0], NIM_NIL);
		}
		LA2: ;
		res_224296 += 1;
	} LA1: ;
}

static N_INLINE(NI, sonslen_136002)(tnode135647* n) {
	NI result;
	result = 0;
	{
		if (!(*n).kindU.S6.Sons == 0) goto LA3;
		result = 0;
	}
	goto LA1;
	LA3: ;
	{
		result = (*n).kindU.S6.Sons->Sup.len;
	}
	LA1: ;
	return result;
}

N_NIMCALL(void, processtoplevelstmtcached_224364)(tnode135647* n, tpasscontext224003** a) {
	tnode135647* m;
	NI i_224378;
	NI HEX3Atmp_224384;
	NI res_224386;
	m = n;
	i_224378 = 0;
	HEX3Atmp_224384 = 0;
	HEX3Atmp_224384 = (NI64)(gpasseslen_224153 - 1);
	res_224386 = 0;
	while (1) {
		if (!(res_224386 <= HEX3Atmp_224384)) goto LA1;
		i_224378 = res_224386;
		{
			if (!!(gpasses_224152[(i_224378)- 0].Field1 == 0)) goto LA4;
			m = gpasses_224152[(i_224378)- 0].Field2(a[(i_224378)- 0], m);
		}
		LA4: ;
		res_224386 += 1;
	} LA1: ;
}

N_NIMCALL(void, closepassescached_224391)(tpasscontext224003** a) {
	tnode135647* m;
	NI i_224404;
	NI HEX3Atmp_224416;
	NI res_224418;
	m = NIM_NIL;
	i_224404 = 0;
	HEX3Atmp_224416 = 0;
	HEX3Atmp_224416 = (NI64)(gpasseslen_224153 - 1);
	res_224418 = 0;
	while (1) {
		if (!(res_224418 <= HEX3Atmp_224416)) goto LA1;
		i_224404 = res_224418;
		{
			NIM_BOOL LOC4;
			LOC4 = !(gpasses_224152[(i_224404)- 0].Field1 == 0);
			if (!(LOC4)) goto LA5;
			LOC4 = !(gpasses_224152[(i_224404)- 0].Field3 == 0);
			LA5: ;
			if (!LOC4) goto LA6;
			m = gpasses_224152[(i_224404)- 0].Field3(a[(i_224404)- 0], m);
		}
		LA6: ;
		unsureAsgnRef((void**) &a[(i_224404)- 0], NIM_NIL);
		res_224418 += 1;
	} LA1: ;
}

N_NIMCALL(void, processmodule_224049)(tsym135677* module, tllstream182205* stream, trodreader213023* rd) {
	tparsers200026 p;
	tpasscontextarray224147 a;
	tllstream182205* s;
	NI32 fileidx;
	memset((void*)&p, 0, sizeof(p));
	objectInit(&p, (&NTI200026));
	memset((void*)a, 0, sizeof(a));
	s = 0;
	fileidx = ((NI32) ((*module).Position));
	{
		if (!(rd == NIM_NIL)) goto LA3;
		openpasses_224237(a, module);
		{
			NimStringDesc* filename;
			if (!(stream == NIM_NIL)) goto LA7;
			filename = tofullpath_129095(fileidx);
			s = llstreamopen_182228(filename, ((NU8) 0));
			{
				if (!(s == NIM_NIL)) goto LA11;
				rawmessage_129518(((NU16) 3), filename);
				goto BeforeRet;
			}
			LA11: ;
		}
		goto LA5;
		LA7: ;
		{
			s = stream;
		}
		LA5: ;
		while (1) {
			openparsers_200034(&p, fileidx, s);
			{
				if (!!((((*module).Flags &(1<<((((NU8) 13))&31)))!=0))) goto LA17;
				processimplicits_224423(implicitimports_105240, ((NU8) 115), a);
				processimplicits_224423(implicitincludes_105261, ((NU8) 120), a);
			}
			LA17: ;
			while (1) {
				tnode135647* n;
				n = parsetoplevelstmt_200051(&p);
				{
					if (!((*n).Kind == ((NU8) 1))) goto LA22;
					goto LA19;
				}
				LA22: ;
				{
					NIM_BOOL LOC26;
					LOC26 = processtoplevelstmt_224328(n, a);
					if (!!(LOC26)) goto LA27;
					goto LA19;
				}
				LA27: ;
			} LA19: ;
			closeparsers_200041(&p);
			{
				if (!!(((*s).Kind == ((NU8) 3)))) goto LA31;
				goto LA14;
			}
			LA31: ;
		} LA14: ;
		closepasses_224301(a);
		idsynchronizationpoint_134445(1000);
	}
	goto LA1;
	LA3: ;
	{
		tnode135647* n;
		NI i_224533;
		NI HEX3Atmp_224549;
		NI LOC34;
		NI res_224551;
		openpassescached_224263(a, module, rd);
		n = loadinitsection_213064(rd);
		i_224533 = 0;
		HEX3Atmp_224549 = 0;
		LOC34 = sonslen_136002(n);
		HEX3Atmp_224549 = (NI64)(LOC34 - 1);
		res_224551 = 0;
		while (1) {
			if (!(res_224551 <= HEX3Atmp_224549)) goto LA35;
			i_224533 = res_224551;
			processtoplevelstmtcached_224364((*n).kindU.S6.Sons->data[i_224533], a);
			res_224551 += 1;
		} LA35: ;
		closepassescached_224391(a);
	}
	LA1: ;
	BeforeRet: ;
}

N_NIMCALL(void, registerpass_224161)(tpass224015* p) {
	gpasses_224152[(gpasseslen_224153)- 0] = (*p);
	gpasseslen_224153 += 1;
}

N_NIMCALL(NIM_BOOL, astneeded_224082)(tsym135677* s) {
	NIM_BOOL result;
	result = 0;
	{
		NIM_BOOL LOC3;
		NIM_BOOL LOC4;
		NIM_BOOL LOC5;
		LOC5 = ((12288 &(1<<(((*s).Kind)&31)))!=0);
		if (!(LOC5)) goto LA6;
		LOC5 = ((8454144 & (*s).Flags) == 0);
		LA6: ;
		LOC4 = LOC5;
		if (!(LOC4)) goto LA7;
		LOC4 = !(((*(*s).Typ).Callconv == ((NU8) 5)));
		LA7: ;
		LOC3 = LOC4;
		if (!(LOC3)) goto LA8;
		LOC3 = ((*(*(*s).Ast).kindU.S6.Sons->data[2]).Kind == ((NU8) 1));
		LA8: ;
		if (!LOC3) goto LA9;
		result = needsglobalanalysis_223359();
	}
	goto LA1;
	LA9: ;
	{
		result = NIM_TRUE;
	}
	LA1: ;
	return result;
}

N_NIMCALL(void, carrypass_224178)(tpass224015* p, tsym135677* module, TY324559 m, TY324559* Result) {
	tpasscontext224003* c;
	c = (*p).Field0(module);
	unsureAsgnRef((void**) &(*Result).Field0, (*p).Field2(c, m.Field0));
	{
		if (!!(((*p).Field3 == NIM_NIL))) goto LA3;
		unsureAsgnRef((void**) &(*Result).Field1, (*p).Field3(c, m.Field1));
	}
	goto LA1;
	LA3: ;
	{
		unsureAsgnRef((void**) &(*Result).Field1, m.Field1);
	}
	LA1: ;
}

N_NIMCALL(void, carrypasses_224194)(tnode135647* nodes, tsym135677* module, tpass224015* passes, NI passeslen0) {
	TY324559 passdata;
	tpass224015 pass_224230;
	NI i_224233;
	memset((void*)&passdata, 0, sizeof(passdata));
	passdata.Field0 = nodes;
	memset((void*)&pass_224230, 0, sizeof(pass_224230));
	i_224233 = 0;
	while (1) {
		TY324559 LOC2;
		if (!(i_224233 < passeslen0)) goto LA1;
		pass_224230 = passes[i_224233];
		memset((void*)&LOC2, 0, sizeof(LOC2));
		carrypass_224178(&pass_224230, module, passdata, &LOC2);
		passdata.Field0 = LOC2.Field0;
		passdata.Field1 = LOC2.Field1;
		i_224233 += 1;
	} LA1: ;
}
N_NOINLINE(void, passesInit)(void) {
}

N_NOINLINE(void, passesDatInit)(void) {
static TNimNode TMP807[1];
NTI224003.size = sizeof(tpasscontext224003);
NTI224003.kind = 17;
NTI224003.base = (&NTI1009);
NTI224003.flags = 3;
TMP807[0].kind = 1;
TMP807[0].offset = offsetof(tpasscontext224003, Fromcache);
TMP807[0].typ = (&NTI132);
TMP807[0].name = "fromCache";
NTI224003.node = &TMP807[0];
}

