/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/usr/src/extras/Nimrod/lib -o compiler/nimcache/pbraces.o compiler/nimcache/pbraces.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <stdio.h>
typedef struct tnode135647 tnode135647;
typedef struct tparser189203 tparser189203;
typedef struct ttype135681 ttype135681;
typedef struct tlineinfo128308 tlineinfo128308;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tsym135677 tsym135677;
typedef struct tident131018 tident131018;
typedef struct tnodeseq135641 tnodeseq135641;
typedef struct tlexer185168 tlexer185168;
typedef struct tbaselexer183018 tbaselexer183018;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tllstream182205 tllstream182205;
typedef struct ttoken185166 ttoken185166;
typedef struct tidobj131012 tidobj131012;
typedef struct ttypeseq135679 ttypeseq135679;
typedef struct tloc135661 tloc135661;
typedef struct trope126007 trope126007;
typedef struct TY135771 TY135771;
typedef struct tinstantiation135667 tinstantiation135667;
typedef struct tscope135671 tscope135671;
typedef struct tstrtable135651 tstrtable135651;
typedef struct tsymseq135649 tsymseq135649;
typedef struct tlib135665 tlib135665;
typedef struct TY135763 TY135763;
typedef struct tlistentry100011 tlistentry100011;
struct tlineinfo128308 {
NI16 Line;
NI16 Col;
NI32 Fileindex;
};
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
struct tnode135647 {
ttype135681* Typ;
tlineinfo128308 Info;
NU8 Flags;
NU8 Kind;
union {
struct {NI64 Intval;
} S1;
struct {NF64 Floatval;
} S2;
struct {NimStringDesc* Strval;
} S3;
struct {tsym135677* Sym;
} S4;
struct {tident131018* Ident;
} S5;
struct {tnodeseq135641* Sons;
} S6;
} kindU;
NimStringDesc* Comment;
};
typedef N_NIMCALL_PTR(void, TY891) (void* p, NI op);
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY891 marker;
};
struct TNimObject {
TNimType* m_type;
};
struct tbaselexer183018 {
  TNimObject Sup;
NI Bufpos;
NCSTRING Buf;
NI Buflen;
tllstream182205* Stream;
NI Linenumber;
NI Sentinel;
NI Linestart;
};
struct tlexer185168 {
  tbaselexer183018 Sup;
NI32 Fileidx;
NI Indentahead;
};
struct ttoken185166 {
NU8 Toktype;
NI Indent;
tident131018* Ident;
NI64 Inumber;
NF64 Fnumber;
NU8 Base;
NimStringDesc* Literal;
};
struct tparser189203 {
NI Currind;
NIM_BOOL Firsttok;
tlexer185168 Lex;
ttoken185166 Tok;
};
struct tidobj131012 {
  TNimObject Sup;
NI Id;
};
struct tloc135661 {
NU8 K;
NU8 S;
NU8 Flags;
ttype135681* T;
trope126007* R;
trope126007* Heaproot;
NI A;
};
struct ttype135681 {
  tidobj131012 Sup;
NU8 Kind;
NU8 Callconv;
NU32 Flags;
ttypeseq135679* Sons;
tnode135647* N;
tsym135677* Destructor;
tsym135677* Owner;
tsym135677* Sym;
NI64 Size;
NI Align;
tloc135661 Loc;
};
struct tstrtable135651 {
NI Counter;
tsymseq135649* Data;
};
struct tsym135677 {
  tidobj131012 Sup;
NU8 Kind;
union {
struct {ttypeseq135679* Typeinstcache;
} S1;
struct {TY135771* Procinstcache;
tscope135671* Scope;
} S2;
struct {TY135771* Usedgenerics;
tstrtable135651 Tab;
} S3;
} kindU;
NU16 Magic;
ttype135681* Typ;
tident131018* Name;
tlineinfo128308 Info;
tsym135677* Owner;
NU32 Flags;
tnode135647* Ast;
NU32 Options;
NI Position;
NI Offset;
tloc135661 Loc;
tlib135665* Annex;
tnode135647* Constraint;
};
struct tident131018 {
  tidobj131012 Sup;
NimStringDesc* S;
tident131018* Next;
NI H;
};
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tllstream182205 {
  TNimObject Sup;
NU8 Kind;
FILE* F;
NimStringDesc* S;
NI Rd;
NI Wr;
NI Lineoffset;
};
struct trope126007 {
  TNimObject Sup;
trope126007* Left;
trope126007* Right;
NI Length;
NimStringDesc* Data;
};
struct tinstantiation135667 {
tsym135677* Sym;
ttypeseq135679* Concretetypes;
TY135763* Usedby;
};
struct tscope135671 {
NI Depthlevel;
tstrtable135651 Symbols;
tscope135671* Parent;
};
struct tlistentry100011 {
  TNimObject Sup;
tlistentry100011* Prev;
tlistentry100011* Next;
};
struct tlib135665 {
  tlistentry100011 Sup;
NU8 Kind;
NIM_BOOL Generated;
NIM_BOOL Isoverriden;
trope126007* Name;
tnode135647* Path;
};
struct tnodeseq135641 {
  TGenericSeq Sup;
  tnode135647* data[SEQ_DECL_SIZE];
};
struct ttypeseq135679 {
  TGenericSeq Sup;
  ttype135681* data[SEQ_DECL_SIZE];
};
struct TY135771 {
  TGenericSeq Sup;
  tinstantiation135667* data[SEQ_DECL_SIZE];
};
struct tsymseq135649 {
  TGenericSeq Sup;
  tsym135677* data[SEQ_DECL_SIZE];
};
struct TY135763 {
  TGenericSeq Sup;
  NI32 data[SEQ_DECL_SIZE];
};

N_NIMCALL(tnode135647*, parseall_192004)(tparser189203* p) {
	tnode135647* result;
	result = 0;
	result = NIM_NIL;
	return result;
}

N_NIMCALL(tnode135647*, parsetoplevelstmt_192011)(tparser189203* p) {
	tnode135647* result;
	result = 0;
	result = NIM_NIL;
	return result;
}
N_NOINLINE(void, pbracesInit)(void) {
}

N_NOINLINE(void, pbracesDatInit)(void) {
}

