/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/usr/src/extras/Nimrod/lib -o compiler/nimcache/pragmas.o compiler/nimcache/pragmas.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct tcontext261019 tcontext261019;
typedef struct tsym135677 tsym135677;
typedef struct tnode135647 tnode135647;
typedef struct ttype135681 ttype135681;
typedef struct tlineinfo128308 tlineinfo128308;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tident131018 tident131018;
typedef struct tnodeseq135641 tnodeseq135641;
typedef struct tstrtable135651 tstrtable135651;
typedef struct tsymseq135649 tsymseq135649;
typedef struct tpasscontext224003 tpasscontext224003;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tscope135671 tscope135671;
typedef struct tproccon261009 tproccon261009;
typedef struct tintset132035 tintset132035;
typedef struct ttrunk132031 ttrunk132031;
typedef struct ttrunkseq132033 ttrunkseq132033;
typedef struct tlinkedlist100017 tlinkedlist100017;
typedef struct tlistentry100011 tlistentry100011;
typedef struct tidtable135693 tidtable135693;
typedef struct tidpairseq135691 tidpairseq135691;
typedef struct tidpair135689 tidpair135689;
typedef struct tidobj131012 tidobj131012;
typedef struct tevalcontext252212 tevalcontext252212;
typedef struct TY261100 TY261100;
typedef struct tinstantiationpair261011 tinstantiationpair261011;
typedef struct tinstantiation135667 tinstantiation135667;
typedef struct ttypeseq135679 ttypeseq135679;
typedef struct TY135771 TY135771;
typedef struct tloc135661 tloc135661;
typedef struct trope126007 trope126007;
typedef struct tlib135665 tlib135665;
typedef struct tcell38449 tcell38449;
typedef struct tcellseq38465 tcellseq38465;
typedef struct tgcheap40416 tgcheap40416;
typedef struct tcellset38461 tcellset38461;
typedef struct tpagedesc38457 tpagedesc38457;
typedef struct tmemregion22010 tmemregion22010;
typedef struct tsmallchunk21243 tsmallchunk21243;
typedef struct tllchunk22004 tllchunk22004;
typedef struct tbigchunk21245 tbigchunk21245;
typedef struct tintset21218 tintset21218;
typedef struct ttrunk21214 ttrunk21214;
typedef struct tavlnode22008 tavlnode22008;
typedef struct tgcstat40414 tgcstat40414;
typedef struct toptionentry261003 toptionentry261003;
typedef struct TY94237 TY94237;
typedef struct tinfocc155009 tinfocc155009;
typedef struct tstackframe252204 tstackframe252204;
typedef struct tidnodetable135699 tidnodetable135699;
typedef struct tidnodepairseq135697 tidnodepairseq135697;
typedef struct tidnodepair135695 tidnodepair135695;
typedef struct TY135763 TY135763;
typedef struct tbasechunk21241 tbasechunk21241;
typedef struct tfreecell21233 tfreecell21233;
typedef NU8 tspecialwords157009[31];
struct tlineinfo128308 {
NI16 Line;
NI16 Col;
NI32 Fileindex;
};
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
struct tnode135647 {
ttype135681* Typ;
tlineinfo128308 Info;
NU8 Flags;
NU8 Kind;
union {
struct {NI64 Intval;
} S1;
struct {NF64 Floatval;
} S2;
struct {NimStringDesc* Strval;
} S3;
struct {tsym135677* Sym;
} S4;
struct {tident131018* Ident;
} S5;
struct {tnodeseq135641* Sons;
} S6;
} kindU;
NimStringDesc* Comment;
};
struct tstrtable135651 {
NI Counter;
tsymseq135649* Data;
};
typedef N_NIMCALL_PTR(void, TY891) (void* p, NI op);
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY891 marker;
};
struct TNimObject {
TNimType* m_type;
};
struct tpasscontext224003 {
  TNimObject Sup;
NIM_BOOL Fromcache;
};
struct tintset132035 {
NI Counter;
NI Max;
ttrunk132031* Head;
ttrunkseq132033* Data;
};
struct tlinkedlist100017 {
tlistentry100011* Head;
tlistentry100011* Tail;
NI Counter;
};
struct tidpair135689 {
tidobj131012* Key;
TNimObject* Val;
};
struct tidtable135693 {
NI Counter;
tidpairseq135691* Data;
};
typedef N_NIMCALL_PTR(tnode135647*, TY261057) (tcontext261019* c, tnode135647* n);
typedef N_NIMCALL_PTR(tnode135647*, TY261062) (tcontext261019* c, tnode135647* n, NU8 flags);
typedef N_NIMCALL_PTR(tnode135647*, TY261070) (tcontext261019* c, tnode135647* n, NU8 flags);
typedef N_NIMCALL_PTR(tnode135647*, TY261078) (tcontext261019* c, tnode135647* n);
typedef N_NIMCALL_PTR(tnode135647*, TY261083) (tcontext261019* c, tnode135647* n, tnode135647* norig, NU32 filter);
typedef N_NIMCALL_PTR(ttype135681*, TY261090) (tcontext261019* c, tnode135647* n, ttype135681* prev);
struct tinstantiationpair261011 {
tsym135677* Genericsym;
tinstantiation135667* Inst;
};
struct tcontext261019 {
  tpasscontext224003 Sup;
tsym135677* Module;
tscope135671* Currentscope;
tscope135671* Importtable;
tscope135671* Toplevelscope;
tproccon261009* P;
tsym135677* Friendmodule;
NI Instcounter;
tsymseq135649* Threadentries;
tintset132035 Ambiguoussymbols;
NI Ingenericcontext;
NI Inunrolledcontext;
NI Incompilescontext;
NI Ingenericinst;
tsymseq135649* Converters;
tsymseq135649* Patterns;
tlinkedlist100017 Optionstack;
tidtable135693 Symmapping;
tlinkedlist100017 Libs;
TY261057 Semconstexpr;
TY261062 Semexpr;
TY261070 Semoperand;
TY261078 Semconstboolexpr;
TY261083 Semoverloadedcall;
TY261090 Semtypenode;
tintset132035 Includedfiles;
tstrtable135651 Userpragmas;
tevalcontext252212* Evalcontext;
tintset132035 Unknownidents;
TY261100* Generics;
NI Lastgenericidx;
};
struct tidobj131012 {
  TNimObject Sup;
NI Id;
};
struct tloc135661 {
NU8 K;
NU8 S;
NU8 Flags;
ttype135681* T;
trope126007* R;
trope126007* Heaproot;
NI A;
};
struct tsym135677 {
  tidobj131012 Sup;
NU8 Kind;
union {
struct {ttypeseq135679* Typeinstcache;
} S1;
struct {TY135771* Procinstcache;
tscope135671* Scope;
} S2;
struct {TY135771* Usedgenerics;
tstrtable135651 Tab;
} S3;
} kindU;
NU16 Magic;
ttype135681* Typ;
tident131018* Name;
tlineinfo128308 Info;
tsym135677* Owner;
NU32 Flags;
tnode135647* Ast;
NU32 Options;
NI Position;
NI Offset;
tloc135661 Loc;
tlib135665* Annex;
tnode135647* Constraint;
};
struct tident131018 {
  tidobj131012 Sup;
NimStringDesc* S;
tident131018* Next;
NI H;
};
struct tcell38449 {
NI Refcount;
TNimType* Typ;
};
struct tcellseq38465 {
NI Len;
NI Cap;
tcell38449** D;
};
struct tcellset38461 {
NI Counter;
NI Max;
tpagedesc38457* Head;
tpagedesc38457** Data;
};
typedef tsmallchunk21243* TY22022[512];
typedef ttrunk21214* ttrunkbuckets21216[256];
struct tintset21218 {
ttrunkbuckets21216 Data;
};
struct tmemregion22010 {
NI Minlargeobj;
NI Maxlargeobj;
TY22022 Freesmallchunks;
tllchunk22004* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk21245* Freechunkslist;
tintset21218 Chunkstarts;
tavlnode22008* Root;
tavlnode22008* Deleted;
tavlnode22008* Last;
tavlnode22008* Freeavlnodes;
};
struct tgcstat40414 {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct tgcheap40416 {
void* Stackbottom;
NI Cyclethreshold;
tcellseq38465 Zct;
tcellseq38465 Decstack;
tcellset38461 Cycleroots;
tcellseq38465 Tempstack;
NI Recgclock;
tmemregion22010 Region;
tgcstat40414 Stat;
};
struct ttype135681 {
  tidobj131012 Sup;
NU8 Kind;
NU8 Callconv;
NU32 Flags;
ttypeseq135679* Sons;
tnode135647* N;
tsym135677* Destructor;
tsym135677* Owner;
tsym135677* Sym;
NI64 Size;
NI Align;
tloc135661 Loc;
};
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tlistentry100011 {
  TNimObject Sup;
tlistentry100011* Prev;
tlistentry100011* Next;
};
struct tlib135665 {
  tlistentry100011 Sup;
NU8 Kind;
NIM_BOOL Generated;
NIM_BOOL Isoverriden;
trope126007* Name;
tnode135647* Path;
};
struct toptionentry261003 {
  tlistentry100011 Sup;
NU32 Options;
NU8 Defaultcc;
tlib135665* Dynlib;
NU64 Notes;
tnode135647* Otherpragmas;
};
struct TY94237 {
NimStringDesc* Field0;
NimStringDesc* Field1;
NimStringDesc* Field2;
};
struct tinfocc155009 {
NimStringDesc* Field0;
NimStringDesc* Field1;
NimStringDesc* Field2;
NimStringDesc* Field3;
NimStringDesc* Field4;
NimStringDesc* Field5;
NimStringDesc* Field6;
NimStringDesc* Field7;
NimStringDesc* Field8;
NimStringDesc* Field9;
NimStringDesc* Field10;
NimStringDesc* Field11;
NimStringDesc* Field12;
NimStringDesc* Field13;
NimStringDesc* Field14;
NimStringDesc* Field15;
NimStringDesc* Field16;
NU8 Field17;
};
typedef tinfocc155009 TY155382[13];
typedef NimStringDesc* TY128277[16];
typedef NimStringDesc* TY128272[24];
struct tproccon261009 {
tsym135677* Owner;
tsym135677* Resultsym;
NI Nestedloopcounter;
NI Nestedblockcounter;
NI Intrystmt;
tproccon261009* Next;
};
struct tscope135671 {
NI Depthlevel;
tstrtable135651 Symbols;
tscope135671* Parent;
};
typedef NI TY21221[8];
struct ttrunk132031 {
ttrunk132031* Next;
NI Key;
TY21221 Bits;
};
struct tidnodepair135695 {
tidobj131012* Key;
tnode135647* Val;
};
struct tidnodetable135699 {
NI Counter;
tidnodepairseq135697* Data;
};
typedef struct {
N_NIMCALL_PTR(tnode135647*, ClPrc) (tnode135647* n, void* ClEnv);
void* ClEnv;
} TY252237;
struct tevalcontext252212 {
  tpasscontext224003 Sup;
tsym135677* Module;
tstackframe252204* Tos;
tnode135647* Lastexception;
tnode135647* Callsite;
NU8 Mode;
NU8 Features;
tidnodetable135699 Globals;
TY252237 Gettype;
};
struct tinstantiation135667 {
tsym135677* Sym;
ttypeseq135679* Concretetypes;
TY135763* Usedby;
};
struct trope126007 {
  TNimObject Sup;
trope126007* Left;
trope126007* Right;
NI Length;
NimStringDesc* Data;
};
struct tpagedesc38457 {
tpagedesc38457* Next;
NI Key;
TY21221 Bits;
};
struct tbasechunk21241 {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct tsmallchunk21243 {
  tbasechunk21241 Sup;
tsmallchunk21243* Next;
tsmallchunk21243* Prev;
tfreecell21233* Freelist;
NI Free;
NI Acc;
NF64 Data;
};
struct tllchunk22004 {
NI Size;
NI Acc;
tllchunk22004* Next;
};
struct tbigchunk21245 {
  tbasechunk21241 Sup;
tbigchunk21245* Next;
tbigchunk21245* Prev;
NI Align;
NF64 Data;
};
struct ttrunk21214 {
ttrunk21214* Next;
NI Key;
TY21221 Bits;
};
typedef tavlnode22008* TY22014[2];
struct tavlnode22008 {
TY22014 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct tstackframe252204 {
tsym135677* Prc;
tnodeseq135641* Slots;
tnode135647* Call;
tstackframe252204* Next;
};
struct tfreecell21233 {
tfreecell21233* Next;
NI Zerofield;
};
struct tnodeseq135641 {
  TGenericSeq Sup;
  tnode135647* data[SEQ_DECL_SIZE];
};
struct tsymseq135649 {
  TGenericSeq Sup;
  tsym135677* data[SEQ_DECL_SIZE];
};
struct ttrunkseq132033 {
  TGenericSeq Sup;
  ttrunk132031* data[SEQ_DECL_SIZE];
};
struct tidpairseq135691 {
  TGenericSeq Sup;
  tidpair135689 data[SEQ_DECL_SIZE];
};
struct TY261100 {
  TGenericSeq Sup;
  tinstantiationpair261011 data[SEQ_DECL_SIZE];
};
struct ttypeseq135679 {
  TGenericSeq Sup;
  ttype135681* data[SEQ_DECL_SIZE];
};
struct TY135771 {
  TGenericSeq Sup;
  tinstantiation135667* data[SEQ_DECL_SIZE];
};
struct tidnodepairseq135697 {
  TGenericSeq Sup;
  tidnodepair135695 data[SEQ_DECL_SIZE];
};
struct TY135763 {
  TGenericSeq Sup;
  NI32 data[SEQ_DECL_SIZE];
};
static N_INLINE(NI, sonslen_136002)(tnode135647* n);
N_NIMCALL(NIM_BOOL, singlepragma_271210)(tcontext261019* c, tsym135677* sym, tnode135647* n, NI i, tspecialwords157009 validpragmas);
N_NIMCALL(tsym135677*, strtableget_142084)(tstrtable135651 t, tident131018* name);
N_NIMCALL(void, globalerror_129660)(tlineinfo128308 info, NU16 msg, NimStringDesc* arg);
N_NIMCALL(void, pragma_269057)(tcontext261019* c, tsym135677* sym, tnode135647* n, tspecialwords157009 validpragmas);
N_NIMCALL(NU8, whichkeyword_157340)(tident131018* id);
N_NIMCALL(void, makeexternexport_269229)(tsym135677* s, NimStringDesc* extname);
N_NIMCALL(void, setexternname_269193)(tsym135677* s, NimStringDesc* extname);
N_NIMCALL(trope126007*, torope_126058)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, nsuFormatSingleElem)(NimStringDesc* formatstr, NimStringDesc* a);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell38449*, usrtocell_41843)(void* usr);
static N_INLINE(void, rtladdzct_43002)(tcell38449* c);
N_NOINLINE(void, addzct_41815)(tcellseq38465* s, tcell38449* c);
N_NIMCALL(NimStringDesc*, getoptionalstr_269523)(tcontext261019* c, tnode135647* n, NimStringDesc* defaultstr);
N_NIMCALL(NimStringDesc*, expectstrlit_269442)(tcontext261019* c, tnode135647* n);
N_NIMCALL(tnode135647*, getstrlitnode_269389)(tcontext261019* c, tnode135647* n);
N_NIMCALL(void, localerror_129673)(tlineinfo128308 info, NU16 msg, NimStringDesc* arg);
N_NOINLINE(tnode135647*, newemptystrnode_269373)(tnode135647* n);
N_NIMCALL(tnode135647*, newnodeit_135925)(NU8 kind, tlineinfo128308 info, ttype135681* typ);
N_NIMCALL(ttype135681*, getsystype_218018)(NU8 kind);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(void, makeexternimport_269199)(tsym135677* s, NimStringDesc* extname);
N_NIMCALL(void, processimportcompilerproc_269247)(tsym135677* s, NimStringDesc* extname);
N_NIMCALL(void, invalidpragma_269065)(tnode135647* n);
N_NIMCALL(NimStringDesc*, rendertree_193046)(tnode135647* n, NU8 renderflags);
N_NIMCALL(void, processimportcpp_269289)(tsym135677* s, NimStringDesc* extname);
N_NIMCALL(void, processimportobjc_269331)(tsym135677* s, NimStringDesc* extname);
N_NIMCALL(NI, expectintlit_269459)(tcontext261019* c, tnode135647* n);
N_NIMCALL(NIM_BOOL, ispoweroftwo_106264)(NI x);
N_NIMCALL(void, noval_270869)(tnode135647* n);
N_NIMCALL(void, pragmadeadcodeelim_269751)(tcontext261019* c, tnode135647* n);
N_NIMCALL(NIM_BOOL, isturnedon_269674)(tcontext261019* c, tnode135647* n);
N_NIMCALL(void, pragmanoforward_269781)(tcontext261019* c, tnode135647* n);
N_NIMCALL(void, processmagic_269544)(tcontext261019* c, tnode135647* n, tsym135677* s);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI start);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI first);
N_NIMCALL(NimStringDesc*, reprEnum)(NI e_68275, TNimType* typ);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(void, message_129680)(tlineinfo128308 info, NU16 msg, NimStringDesc* arg);
N_NIMCALL(tlib135665*, getlib_269860)(tcontext261019* c, NU8 kind, tnode135647* path);
N_NIMCALL(NIM_BOOL, exprstructuralequivalent_201111)(tnode135647* a, tnode135647* b);
N_NIMCALL(tlib135665*, newlib_261128)(NU8 kind);
N_NIMCALL(void, append_100036)(tlinkedlist100017* list, tlistentry100011* entry);
N_NIMCALL(NIM_BOOL, isdynliboverride_105596)(NimStringDesc* lib);
N_NIMCALL(void, addtolib_261132)(tlib135665* lib, tsym135677* sym);
N_NIMCALL(void, processdynlib_269984)(tcontext261019* c, tnode135647* n, tsym135677* sym);
N_NIMCALL(tnode135647*, expectdynlibnode_269908)(tcontext261019* c, tnode135647* n);
N_NIMCALL(void, registercompilerproc_218026)(tsym135677* s);
static N_INLINE(NIM_BOOL, isroutine_140368)(tsym135677* s);
N_NIMCALL(void, fatal_129653)(tlineinfo128308 info, NU16 msg, NimStringDesc* arg);
N_NIMCALL(void, processdefine_270601)(tcontext261019* c, tnode135647* n);
N_NIMCALL(void, definesymbol_149005)(NimStringDesc* symbol);
N_NIMCALL(void, processundef_270649)(tcontext261019* c, tnode135647* n);
N_NIMCALL(void, undefsymbol_149039)(NimStringDesc* symbol);
N_NIMCALL(void, processcompile_270702)(tcontext261019* c, tnode135647* n);
N_NIMCALL(NimStringDesc*, findfile_105532)(NimStringDesc* f);
N_NIMCALL(NimStringDesc*, noschangeFileExt)(NimStringDesc* filename, NimStringDesc* ext);
N_NIMCALL(void, addexternalfiletocompile_156035)(NimStringDesc* filename);
N_NIMCALL(void, addfiletolink_155701)(NimStringDesc* filename);
N_NIMCALL(NimStringDesc*, completecfilepath_155675)(NimStringDesc* cfile, NIM_BOOL createsubdir);
N_NIMCALL(void, processcommonlink_270711)(tcontext261019* c, tnode135647* n, NU8 feature);
N_NIMCALL(void, nossplitFile)(NimStringDesc* path, TY94237* Result);
N_NIMCALL(NimStringDesc*, nosaddFileExt)(NimStringDesc* filename, NimStringDesc* ext);
N_NIMCALL(NimStringDesc*, HEX2F_94062)(NimStringDesc* head, NimStringDesc* tail);
N_NIMCALL(void, internalerror_129687)(tlineinfo128308 info, NimStringDesc* errmsg);
N_NIMCALL(void, addlinkoption_155630)(NimStringDesc* option);
N_NIMCALL(void, addcompileoption_155638)(NimStringDesc* option);
N_NIMCALL(void, pragmabreakpoint_270720)(tcontext261019* c, tnode135647* n);
N_NIMCALL(void, pragmawatchpoint_270745)(tcontext261019* c, tnode135647* n);
N_NIMCALL(void, processpush_270526)(tcontext261019* c, tnode135647* n, NI start);
N_NIMCALL(toptionentry261003*, newoptionentry_261125)(void);
N_NIMCALL(NIM_BOOL, processoption_270332)(tcontext261019* c, tnode135647* n);
N_NIMCALL(void, processnote_270065)(tcontext261019* c, tnode135647* n);
N_NIMCALL(NI, findstr_157318)(NimStringDesc** a, NI alen0, NimStringDesc* s);
N_NIMCALL(void, onoff_269724)(tcontext261019* c, tnode135647* n, NU32 op);
N_NIMCALL(void, processcallconv_269811)(tcontext261019* c, tnode135647* n);
N_NIMCALL(NU8, wordtocallconv_269646)(NU8 sw);
N_NIMCALL(NimStringDesc*, nsuNormalize)(NimStringDesc* s);
N_NIMCALL(tnode135647*, newnodei_135920)(NU8 kind, tlineinfo128308 info);
N_NIMCALL(void, add_136175)(tnode135647* father, tnode135647* son);
N_NIMCALL(void, processpop_270594)(tcontext261019* c, tnode135647* n);
N_NIMCALL(void, remove_100635)(tlinkedlist100017* list, tlistentry100011* entry);
N_NIMCALL(void, processpragma_271054)(tcontext261019* c, tnode135647* n, NI i);
N_NIMCALL(tsym135677*, newsym_135874)(NU8 symkind, tident131018* name, tsym135677* owner, tlineinfo128308 info);
N_NIMCALL(void, addson_136028)(tnode135647* father, tnode135647* son);
N_NIMCALL(void, strtableadd_142078)(tstrtable135651* t, tsym135677* n);
N_NIMCALL(void, processcodegendecl_269537)(tcontext261019* c, tnode135647* n, tsym135677* sym);
N_NIMCALL(void, pragmaemit_270853)(tcontext261019* c, tnode135647* n);
N_NIMCALL(tnode135647*, semasmoremit_270777)(tcontext261019* con, tnode135647* n, NIM_CHAR marker);
N_NIMCALL(tnode135647*, newnode_137403)(NU8 kind, tlineinfo128308 info, tnodeseq135641* sons, ttype135681* typ);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(NI, nsuFindChar)(NimStringDesc* s, NIM_CHAR sub, NI start);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_63424, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_NIMCALL(tnode135647*, newstrnode_135906)(NU8 kind, NimStringDesc* strval);
N_NIMCALL(tsym135677*, searchinscopes_262151)(tcontext261019* c, tident131018* s);
N_NIMCALL(tident131018*, getident_131448)(NimStringDesc* identifier);
N_NIMCALL(void, loadstub_215571)(tsym135677* s);
N_NIMCALL(tnode135647*, newsymnode_135916)(tsym135677* sym);
N_NIMCALL(void, illformedast_261646)(tnode135647* n);
N_NIMCALL(void, pragmaunroll_270880)(tcontext261019* c, tnode135647* n);
N_NIMCALL(tnode135647*, newintnode_135890)(NU8 kind, NI64 intval);
N_NIMCALL(void, pragmalinearscanend_270913)(tcontext261019* c, tnode135647* n);
N_NIMCALL(void, pragmaline_270919)(tcontext261019* c, tnode135647* n);
N_NIMCALL(NI32, fileinfoidx_128506)(NimStringDesc* filename);
N_NIMCALL(tlineinfo128308, getinfocontext_129057)(NI index);
N_NIMCALL(void, pragmaraisesortags_271157)(tcontext261019* c, tnode135647* n);
N_NIMCALL(void, processexc_271161)(tcontext261019* c, tnode135647* x);
N_NIMCALL(ttype135681*, skiptypes_202116)(ttype135681* t, NU64 kinds);
static N_INLINE(NI, len_136081)(tnode135647* n);
N_NIMCALL(void, implictpragmas_272145)(tcontext261019* c, tsym135677* sym, tnode135647* n, tspecialwords157009 validpragmas);
STRING_LITERAL(TMP2613, "", 0);
STRING_LITERAL(TMP2614, "define", 6);
STRING_LITERAL(TMP2615, "undef", 5);
extern NIM_CONST TY155382 cc_155381;
STRING_LITERAL(TMP2616, "processCommonLink", 17);
STRING_LITERAL(TMP2617, "\':\' after \'push\' not supported", 30);
STRING_LITERAL(TMP2619, "Success", 7);
STRING_LITERAL(TMP2620, "SuccessX", 8);
STRING_LITERAL(TMP2621, "LineTooLong", 11);
STRING_LITERAL(TMP2622, "XDeclaredButNotUsed", 19);
STRING_LITERAL(TMP2623, "ConvToBaseNotNeeded", 19);
STRING_LITERAL(TMP2624, "ConvFromXtoItselfNotNeeded", 26);
STRING_LITERAL(TMP2625, "ExprAlwaysX", 11);
STRING_LITERAL(TMP2626, "QuitCalled", 10);
STRING_LITERAL(TMP2627, "Processing", 10);
STRING_LITERAL(TMP2628, "CodeBegin", 9);
STRING_LITERAL(TMP2629, "CodeEnd", 7);
STRING_LITERAL(TMP2630, "Conf", 4);
STRING_LITERAL(TMP2631, "Path", 4);
STRING_LITERAL(TMP2632, "Condtrue", 8);
STRING_LITERAL(TMP2633, "Pattern", 7);
STRING_LITERAL(TMP2634, "User", 4);
NIM_CONST TY128277 TMP2618 = {((NimStringDesc*) &TMP2619),
((NimStringDesc*) &TMP2620),
((NimStringDesc*) &TMP2621),
((NimStringDesc*) &TMP2622),
((NimStringDesc*) &TMP2623),
((NimStringDesc*) &TMP2624),
((NimStringDesc*) &TMP2625),
((NimStringDesc*) &TMP2626),
((NimStringDesc*) &TMP2627),
((NimStringDesc*) &TMP2628),
((NimStringDesc*) &TMP2629),
((NimStringDesc*) &TMP2630),
((NimStringDesc*) &TMP2631),
((NimStringDesc*) &TMP2632),
((NimStringDesc*) &TMP2633),
((NimStringDesc*) &TMP2634)}
;
STRING_LITERAL(TMP2636, "CannotOpenFile", 14);
STRING_LITERAL(TMP2637, "OctalEscape", 11);
STRING_LITERAL(TMP2638, "XIsNeverRead", 12);
STRING_LITERAL(TMP2639, "XmightNotBeenInit", 17);
STRING_LITERAL(TMP2640, "Deprecated", 10);
STRING_LITERAL(TMP2641, "ConfigDeprecated", 16);
STRING_LITERAL(TMP2642, "SmallLshouldNotBeUsed", 21);
STRING_LITERAL(TMP2643, "UnknownMagic", 12);
STRING_LITERAL(TMP2644, "RedefinitionOfLabel", 19);
STRING_LITERAL(TMP2645, "UnknownSubstitutionX", 20);
STRING_LITERAL(TMP2646, "LanguageXNotSupported", 21);
STRING_LITERAL(TMP2647, "CommentXIgnored", 15);
STRING_LITERAL(TMP2648, "NilStmt", 7);
STRING_LITERAL(TMP2649, "AnalysisLoophole", 16);
STRING_LITERAL(TMP2650, "DifferentHeaps", 14);
STRING_LITERAL(TMP2651, "WriteToForeignHeap", 18);
STRING_LITERAL(TMP2652, "ImplicitClosure", 15);
STRING_LITERAL(TMP2653, "EachIdentIsTuple", 16);
STRING_LITERAL(TMP2654, "ShadowIdent", 11);
STRING_LITERAL(TMP2655, "ProveInit", 9);
STRING_LITERAL(TMP2656, "ProveField", 10);
STRING_LITERAL(TMP2657, "ProveIndex", 10);
STRING_LITERAL(TMP2658, "Uninit", 6);
NIM_CONST TY128272 TMP2635 = {((NimStringDesc*) &TMP2636),
((NimStringDesc*) &TMP2637),
((NimStringDesc*) &TMP2638),
((NimStringDesc*) &TMP2639),
((NimStringDesc*) &TMP2640),
((NimStringDesc*) &TMP2641),
((NimStringDesc*) &TMP2642),
((NimStringDesc*) &TMP2643),
((NimStringDesc*) &TMP2644),
((NimStringDesc*) &TMP2645),
((NimStringDesc*) &TMP2646),
((NimStringDesc*) &TMP2647),
((NimStringDesc*) &TMP2648),
((NimStringDesc*) &TMP2649),
((NimStringDesc*) &TMP2650),
((NimStringDesc*) &TMP2651),
((NimStringDesc*) &TMP2652),
((NimStringDesc*) &TMP2653),
((NimStringDesc*) &TMP2654),
((NimStringDesc*) &TMP2655),
((NimStringDesc*) &TMP2656),
((NimStringDesc*) &TMP2657),
((NimStringDesc*) &TMP2658),
((NimStringDesc*) &TMP2634)}
;
STRING_LITERAL(TMP2659, "speed", 5);
STRING_LITERAL(TMP2660, "size", 4);
STRING_LITERAL(TMP2661, "none", 4);
STRING_LITERAL(TMP2662, "tuple", 5);
STRING_LITERAL(TMP2663, "invalid type for raises/tags list", 33);
STRING_LITERAL(TMP2664, "implicitPragmas", 15);
extern tgcheap40416 gch_40442;
extern TNimType NTI135369; /* TMagic */
extern NU8 ccompiler_155400;
extern NimStringDesc* libpath_105190;
extern NU32 goptions_105106;
extern NU64 gnotes_128867;
extern TNimType NTI135641; /* TNodeSeq */

static N_INLINE(NI, sonslen_136002)(tnode135647* n) {
	NI result;
	result = 0;
	{
		if (!(*n).kindU.S6.Sons == 0) goto LA3;
		result = 0;
	}
	goto LA1;
	LA3: ;
	{
		result = (*n).kindU.S6.Sons->Sup.len;
	}
	LA1: ;
	return result;
}

static N_INLINE(tcell38449*, usrtocell_41843)(void* usr) {
	tcell38449* result;
	result = 0;
	result = ((tcell38449*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell38449))))));
	return result;
}

static N_INLINE(void, rtladdzct_43002)(tcell38449* c) {
	addzct_41815(&gch_40442.Zct, c);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		tcell38449* c;
		if (!!((src == NIM_NIL))) goto LA3;
		c = usrtocell_41843(src);
		(*c).Refcount += 8;
	}
	LA3: ;
	{
		tcell38449* c;
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		c = usrtocell_41843((*dest));
		{
			(*c).Refcount -= 8;
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			rtladdzct_43002(c);
		}
		LA11: ;
	}
	LA7: ;
	(*dest) = src;
}

N_NIMCALL(void, setexternname_269193)(tsym135677* s, NimStringDesc* extname) {
	NimStringDesc* LOC1;
	LOC1 = 0;
	LOC1 = nsuFormatSingleElem(extname, (*(*s).Name).S);
	asgnRefNoCycle((void**) &(*s).Loc.R, torope_126058(LOC1));
}

N_NIMCALL(void, makeexternexport_269229)(tsym135677* s, NimStringDesc* extname) {
	setexternname_269193(s, extname);
	(*s).Flags |=((NI32)(1)<<((((NU8) 6))%(sizeof(NI32)*8)));
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell38449* c;
	c = usrtocell_41843(p);
	{
		(*c).Refcount -= 8;
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		rtladdzct_43002(c);
	}
	LA3: ;
}

N_NOINLINE(tnode135647*, newemptystrnode_269373)(tnode135647* n) {
	tnode135647* result;
	ttype135681* LOC1;
	NimStringDesc* LOC2;
	result = 0;
	LOC1 = 0;
	LOC1 = getsystype_218018(((NU8) 28));
	result = newnodeit_135925(((NU8) 20), (*n).Info, LOC1);
	LOC2 = 0;
	LOC2 = (*result).kindU.S3.Strval; (*result).kindU.S3.Strval = copyStringRC1(((NimStringDesc*) &TMP2613));
	if (LOC2) nimGCunrefNoCycle(LOC2);
	return result;
}

N_NIMCALL(tnode135647*, getstrlitnode_269389)(tcontext261019* c, tnode135647* n) {
	tnode135647* result;
	result = 0;
	{
		if (!!(((*n).Kind == ((NU8) 34)))) goto LA3;
		localerror_129673((*n).Info, ((NU16) 6), ((NimStringDesc*) &TMP2613));
		result = newemptystrnode_269373(n);
	}
	goto LA1;
	LA3: ;
	{
		asgnRefNoCycle((void**) &(*n).kindU.S6.Sons->data[1], (*c).Semconstexpr(c, (*n).kindU.S6.Sons->data[1]));
		switch ((*(*n).kindU.S6.Sons->data[1]).Kind) {
		case ((NU8) 20):
		case ((NU8) 21):
		case ((NU8) 22):
		{
			result = (*n).kindU.S6.Sons->data[1];
		}
		break;
		default:
		{
			localerror_129673((*n).Info, ((NU16) 6), ((NimStringDesc*) &TMP2613));
			result = newemptystrnode_269373(n);
		}
		break;
		}
	}
	LA1: ;
	return result;
}

N_NIMCALL(NimStringDesc*, expectstrlit_269442)(tcontext261019* c, tnode135647* n) {
	NimStringDesc* result;
	tnode135647* LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = getstrlitnode_269389(c, n);
	result = copyString((*LOC1).kindU.S3.Strval);
	return result;
}

N_NIMCALL(NimStringDesc*, getoptionalstr_269523)(tcontext261019* c, tnode135647* n, NimStringDesc* defaultstr) {
	NimStringDesc* result;
	result = 0;
	{
		if (!((*n).Kind == ((NU8) 34))) goto LA3;
		result = expectstrlit_269442(c, n);
	}
	goto LA1;
	LA3: ;
	{
		result = copyString(defaultstr);
	}
	LA1: ;
	return result;
}

N_NIMCALL(void, makeexternimport_269199)(tsym135677* s, NimStringDesc* extname) {
	setexternname_269193(s, extname);
	(*s).Flags |=((NI32)(1)<<((((NU8) 5))%(sizeof(NI32)*8)));
	(*s).Flags &= ~((NI32)(1) << ((((NU8) 4)) % (sizeof(NI32)*8)));
}

N_NIMCALL(void, processimportcompilerproc_269247)(tsym135677* s, NimStringDesc* extname) {
	setexternname_269193(s, extname);
	(*s).Flags |=((NI32)(1)<<((((NU8) 5))%(sizeof(NI32)*8)));
	(*s).Flags &= ~((NI32)(1) << ((((NU8) 4)) % (sizeof(NI32)*8)));
	(*s).Loc.Flags |=((NI8)(1)<<((((NU8) 7))%(sizeof(NI8)*8)));
}

N_NIMCALL(void, invalidpragma_269065)(tnode135647* n) {
	NimStringDesc* LOC1;
	LOC1 = 0;
	LOC1 = rendertree_193046(n, 4);
	localerror_129673((*n).Info, ((NU16) 162), LOC1);
}

N_NIMCALL(void, processimportcpp_269289)(tsym135677* s, NimStringDesc* extname) {
	setexternname_269193(s, extname);
	(*s).Flags |=((NI32)(1)<<((((NU8) 5))%(sizeof(NI32)*8)));
	(*s).Flags |=((NI32)(1)<<((((NU8) 27))%(sizeof(NI32)*8)));
	(*s).Flags &= ~((NI32)(1) << ((((NU8) 4)) % (sizeof(NI32)*8)));
}

N_NIMCALL(void, processimportobjc_269331)(tsym135677* s, NimStringDesc* extname) {
	setexternname_269193(s, extname);
	(*s).Flags |=((NI32)(1)<<((((NU8) 5))%(sizeof(NI32)*8)));
	(*s).Flags |=((NI32)(1)<<((((NU8) 28))%(sizeof(NI32)*8)));
	(*s).Flags &= ~((NI32)(1) << ((((NU8) 4)) % (sizeof(NI32)*8)));
}

N_NIMCALL(NI, expectintlit_269459)(tcontext261019* c, tnode135647* n) {
	NI result;
	result = 0;
	{
		if (!!(((*n).Kind == ((NU8) 34)))) goto LA3;
		localerror_129673((*n).Info, ((NU16) 7), ((NimStringDesc*) &TMP2613));
	}
	goto LA1;
	LA3: ;
	{
		asgnRefNoCycle((void**) &(*n).kindU.S6.Sons->data[1], (*c).Semconstexpr(c, (*n).kindU.S6.Sons->data[1]));
		switch ((*(*n).kindU.S6.Sons->data[1]).Kind) {
		case ((NU8) 6) ... ((NU8) 10):
		{
			result = ((NI) ((*(*n).kindU.S6.Sons->data[1]).kindU.S1.Intval));
		}
		break;
		default:
		{
			localerror_129673((*n).Info, ((NU16) 7), ((NimStringDesc*) &TMP2613));
		}
		break;
		}
	}
	LA1: ;
	return result;
}

N_NIMCALL(void, noval_270869)(tnode135647* n) {
	{
		if (!((*n).Kind == ((NU8) 34))) goto LA3;
		invalidpragma_269065(n);
	}
	LA3: ;
}

N_NIMCALL(NIM_BOOL, isturnedon_269674)(tcontext261019* c, tnode135647* n) {
	NIM_BOOL result;
	result = 0;
	{
		tnode135647* x;
		if (!((*n).Kind == ((NU8) 34))) goto LA3;
		x = (*c).Semconstboolexpr(c, (*n).kindU.S6.Sons->data[1]);
		asgnRefNoCycle((void**) &(*n).kindU.S6.Sons->data[1], x);
		{
			if (!((*x).Kind == ((NU8) 6))) goto LA7;
			result = !(((*x).kindU.S1.Intval == 0));
			goto BeforeRet;
		}
		LA7: ;
	}
	LA3: ;
	localerror_129673((*n).Info, ((NU16) 26), ((NimStringDesc*) &TMP2613));
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, pragmadeadcodeelim_269751)(tcontext261019* c, tnode135647* n) {
	{
		NIM_BOOL LOC3;
		LOC3 = isturnedon_269674(c, n);
		if (!LOC3) goto LA4;
		(*(*c).Module).Flags |=((NI32)(1)<<((((NU8) 25))%(sizeof(NI32)*8)));
	}
	goto LA1;
	LA4: ;
	{
		(*(*c).Module).Flags &= ~((NI32)(1) << ((((NU8) 25)) % (sizeof(NI32)*8)));
	}
	LA1: ;
}

N_NIMCALL(void, pragmanoforward_269781)(tcontext261019* c, tnode135647* n) {
	{
		NIM_BOOL LOC3;
		LOC3 = isturnedon_269674(c, n);
		if (!LOC3) goto LA4;
		(*(*c).Module).Flags |=((NI32)(1)<<((((NU8) 8))%(sizeof(NI32)*8)));
	}
	goto LA1;
	LA4: ;
	{
		(*(*c).Module).Flags &= ~((NI32)(1) << ((((NU8) 8)) % (sizeof(NI32)*8)));
	}
	LA1: ;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (NI64)((*a).Sup.len * 1));
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, processmagic_269544)(tcontext261019* c, tnode135647* n, tsym135677* s) {
	NimStringDesc* v;
	NU16 m_269625;
	NU16 res_269641;
	{
		if (!!(((*n).Kind == ((NU8) 34)))) goto LA3;
		localerror_129673((*n).Info, ((NU16) 6), ((NimStringDesc*) &TMP2613));
		goto BeforeRet;
	}
	LA3: ;
	v = 0;
	{
		if (!((*(*n).kindU.S6.Sons->data[1]).Kind == ((NU8) 2))) goto LA7;
		v = copyString((*(*(*n).kindU.S6.Sons->data[1]).kindU.S5.Ident).S);
	}
	goto LA5;
	LA7: ;
	{
		v = expectstrlit_269442(c, n);
	}
	LA5: ;
	m_269625 = 0;
	res_269641 = ((NU16) 0);
	while (1) {
		if (!(res_269641 <= ((NU16) 260))) goto LA10;
		m_269625 = res_269641;
		{
			NimStringDesc* LOC13;
			LOC13 = 0;
			LOC13 = copyStr(reprEnum(m_269625, (&NTI135369)), 1);
			if (!eqStrings(LOC13, v)) goto LA14;
			(*s).Magic = m_269625;
			goto LA10;
		}
		LA14: ;
		res_269641 += 1;
	} LA10: ;
	{
		if (!((*s).Magic == ((NU16) 0))) goto LA18;
		message_129680((*n).Info, ((NU16) 227), v);
	}
	LA18: ;
	BeforeRet: ;
}

N_NIMCALL(tlib135665*, getlib_269860)(tcontext261019* c, NU8 kind, tnode135647* path) {
	tlib135665* result;
	tlib135665* it;
	result = 0;
	it = ((tlib135665*) ((*c).Libs.Head));
	while (1) {
		if (!!((it == NIM_NIL))) goto LA1;
		{
			if (!((*it).Kind == kind)) goto LA4;
			{
				NIM_BOOL LOC8;
				LOC8 = exprstructuralequivalent_201111((*it).Path, path);
				if (!LOC8) goto LA9;
				result = it;
				goto BeforeRet;
			}
			LA9: ;
		}
		LA4: ;
		it = ((tlib135665*) ((*it).Sup.Next));
	} LA1: ;
	result = newlib_261128(kind);
	asgnRefNoCycle((void**) &(*result).Path, path);
	append_100036(&(*c).Libs, &result->Sup);
	{
		if (!((*path).Kind >= ((NU8) 20) && (*path).Kind <= ((NU8) 22))) goto LA13;
		(*result).Isoverriden = isdynliboverride_105596((*path).kindU.S3.Strval);
	}
	LA13: ;
	BeforeRet: ;
	return result;
}

N_NIMCALL(tnode135647*, expectdynlibnode_269908)(tcontext261019* c, tnode135647* n) {
	tnode135647* result;
	result = 0;
	{
		if (!!(((*n).Kind == ((NU8) 34)))) goto LA3;
		localerror_129673((*n).Info, ((NU16) 6), ((NimStringDesc*) &TMP2613));
		result = newemptystrnode_269373(n);
	}
	goto LA1;
	LA3: ;
	{
		result = (*c).Semexpr(c, (*n).kindU.S6.Sons->data[1], 0);
		{
			NIM_BOOL LOC8;
			LOC8 = ((*result).Kind == ((NU8) 3));
			if (!(LOC8)) goto LA9;
			LOC8 = ((*(*result).kindU.S4.Sym).Kind == ((NU8) 10));
			LA9: ;
			if (!LOC8) goto LA10;
			result = (*(*result).kindU.S4.Sym).Ast;
		}
		LA10: ;
		{
			NIM_BOOL LOC14;
			LOC14 = ((*result).Typ == NIM_NIL);
			if (LOC14) goto LA15;
			LOC14 = !(((369098752 &(IL64(1)<<(((*(*result).Typ).Kind)&IL64(63))))!=0));
			LA15: ;
			if (!LOC14) goto LA16;
			localerror_129673((*n).Info, ((NU16) 6), ((NimStringDesc*) &TMP2613));
			result = newemptystrnode_269373(n);
		}
		LA16: ;
	}
	LA1: ;
	return result;
}

N_NIMCALL(void, processdynlib_269984)(tcontext261019* c, tnode135647* n, tsym135677* sym) {
	{
		NIM_BOOL LOC3;
		tnode135647* LOC7;
		LOC3 = (sym == NIM_NIL);
		if (LOC3) goto LA4;
		LOC3 = ((*sym).Kind == ((NU8) 6));
		LA4: ;
		if (!LOC3) goto LA5;
		LOC7 = 0;
		LOC7 = expectdynlibnode_269908(c, n);
		asgnRefNoCycle((void**) &(*((toptionentry261003*) ((*c).Optionstack.Tail))).Dynlib, getlib_269860(c, ((NU8) 1), LOC7));
	}
	goto LA1;
	LA5: ;
	{
		{
			tlib135665* lib;
			tnode135647* LOC13;
			if (!((*n).Kind == ((NU8) 34))) goto LA11;
			LOC13 = 0;
			LOC13 = expectdynlibnode_269908(c, n);
			lib = getlib_269860(c, ((NU8) 1), LOC13);
			{
				if (!!((*lib).Isoverriden)) goto LA16;
				addtolib_261132(lib, sym);
				(*sym).Loc.Flags |=((NI8)(1)<<((((NU8) 4))%(sizeof(NI8)*8)));
			}
			LA16: ;
		}
		goto LA9;
		LA11: ;
		{
			(*sym).Loc.Flags |=((NI8)(1)<<((((NU8) 5))%(sizeof(NI8)*8)));
		}
		LA9: ;
		{
			NIM_BOOL LOC21;
			NIM_BOOL LOC22;
			LOC22 = ((258048 &(1<<(((*sym).Kind)&31)))!=0);
			if (!(LOC22)) goto LA23;
			LOC22 = !(((*sym).Typ == NIM_NIL));
			LA23: ;
			LOC21 = LOC22;
			if (!(LOC21)) goto LA24;
			LOC21 = ((*(*sym).Typ).Callconv == ((NU8) 0));
			LA24: ;
			if (!LOC21) goto LA25;
			(*(*sym).Typ).Callconv = ((NU8) 2);
		}
		LA25: ;
	}
	LA1: ;
}

static N_INLINE(NIM_BOOL, isroutine_140368)(tsym135677* s) {
	NIM_BOOL result;
	result = 0;
	result = ((258048 &(1<<(((*s).Kind)&31)))!=0);
	return result;
}

N_NIMCALL(void, processdefine_270601)(tcontext261019* c, tnode135647* n) {
	{
		NIM_BOOL LOC3;
		LOC3 = ((*n).Kind == ((NU8) 34));
		if (!(LOC3)) goto LA4;
		LOC3 = ((*(*n).kindU.S6.Sons->data[1]).Kind == ((NU8) 2));
		LA4: ;
		if (!LOC3) goto LA5;
		definesymbol_149005((*(*(*n).kindU.S6.Sons->data[1]).kindU.S5.Ident).S);
		message_129680((*n).Info, ((NU16) 224), ((NimStringDesc*) &TMP2614));
	}
	goto LA1;
	LA5: ;
	{
		invalidpragma_269065(n);
	}
	LA1: ;
}

N_NIMCALL(void, processundef_270649)(tcontext261019* c, tnode135647* n) {
	{
		NIM_BOOL LOC3;
		LOC3 = ((*n).Kind == ((NU8) 34));
		if (!(LOC3)) goto LA4;
		LOC3 = ((*(*n).kindU.S6.Sons->data[1]).Kind == ((NU8) 2));
		LA4: ;
		if (!LOC3) goto LA5;
		undefsymbol_149039((*(*(*n).kindU.S6.Sons->data[1]).kindU.S5.Ident).S);
		message_129680((*n).Info, ((NU16) 224), ((NimStringDesc*) &TMP2615));
	}
	goto LA1;
	LA5: ;
	{
		invalidpragma_269065(n);
	}
	LA1: ;
}

N_NIMCALL(void, processcompile_270702)(tcontext261019* c, tnode135647* n) {
	NimStringDesc* s;
	NimStringDesc* found;
	NimStringDesc* trunc;
	NimStringDesc* LOC5;
	s = expectstrlit_269442(c, n);
	found = findfile_105532(s);
	{
		if (!((found) && (found)->Sup.len == 0)) goto LA3;
		found = copyString(s);
	}
	LA3: ;
	trunc = noschangeFileExt(found, ((NimStringDesc*) &TMP2613));
	addexternalfiletocompile_156035(found);
	LOC5 = 0;
	LOC5 = completecfilepath_155675(trunc, NIM_FALSE);
	addfiletolink_155701(LOC5);
}

N_NIMCALL(void, processcommonlink_270711)(tcontext261019* c, tnode135647* n, NU8 feature) {
	NimStringDesc* f;
	NimStringDesc* found;
	f = expectstrlit_269442(c, n);
	{
		TY94237 LOC3;
		memset((void*)&LOC3, 0, sizeof(LOC3));
		nossplitFile(f, &LOC3);
		if (!((LOC3.Field2) && (LOC3.Field2)->Sup.len == 0)) goto LA4;
		f = nosaddFileExt(f, cc_155381[(ccompiler_155400)- 1].Field1);
	}
	LA4: ;
	found = findfile_105532(f);
	{
		if (!((found) && (found)->Sup.len == 0)) goto LA8;
		found = copyString(f);
	}
	LA8: ;
	switch (feature) {
	case ((NU8) 0):
	{
		addfiletolink_155701(found);
	}
	break;
	case ((NU8) 1):
	{
		NimStringDesc* LOC12;
		NimStringDesc* LOC13;
		LOC12 = 0;
		LOC12 = completecfilepath_155675(found, NIM_FALSE);
		LOC13 = 0;
		LOC13 = HEX2F_94062(libpath_105190, LOC12);
		addfiletolink_155701(LOC13);
	}
	break;
	default:
	{
		internalerror_129687((*n).Info, ((NimStringDesc*) &TMP2616));
	}
	break;
	}
}

N_NIMCALL(void, pragmabreakpoint_270720)(tcontext261019* c, tnode135647* n) {
	NimStringDesc* LOC1;
	LOC1 = 0;
	LOC1 = getoptionalstr_269523(c, n, ((NimStringDesc*) &TMP2613));
}

N_NIMCALL(void, pragmawatchpoint_270745)(tcontext261019* c, tnode135647* n) {
	{
		if (!((*n).Kind == ((NU8) 34))) goto LA3;
		asgnRefNoCycle((void**) &(*n).kindU.S6.Sons->data[1], (*c).Semexpr(c, (*n).kindU.S6.Sons->data[1], 0));
	}
	goto LA1;
	LA3: ;
	{
		invalidpragma_269065(n);
	}
	LA1: ;
}

N_NIMCALL(void, processnote_270065)(tcontext261019* c, tnode135647* n) {
	{
		NIM_BOOL LOC3;
		NIM_BOOL LOC4;
		NIM_BOOL LOC5;
		NIM_BOOL LOC6;
		NIM_BOOL LOC7;
		NI LOC9;
		NU16 nk;
		NU8 LOC16;
		tnode135647* x;
		LOC7 = ((*n).Kind == ((NU8) 34));
		if (!(LOC7)) goto LA8;
		LOC9 = sonslen_136002(n);
		LOC7 = (LOC9 == 2);
		LA8: ;
		LOC6 = LOC7;
		if (!(LOC6)) goto LA10;
		LOC6 = ((*(*n).kindU.S6.Sons->data[0]).Kind == ((NU8) 42));
		LA10: ;
		LOC5 = LOC6;
		if (!(LOC5)) goto LA11;
		LOC5 = ((*(*(*n).kindU.S6.Sons->data[0]).kindU.S6.Sons->data[1]).Kind == ((NU8) 2));
		LA11: ;
		LOC4 = LOC5;
		if (!(LOC4)) goto LA12;
		LOC4 = ((*(*(*n).kindU.S6.Sons->data[0]).kindU.S6.Sons->data[0]).Kind == ((NU8) 2));
		LA12: ;
		LOC3 = LOC4;
		if (!(LOC3)) goto LA13;
		LOC3 = ((*(*n).kindU.S6.Sons->data[1]).Kind == ((NU8) 2));
		LA13: ;
		if (!LOC3) goto LA14;
		nk = 0;
		LOC16 = whichkeyword_157340((*(*(*n).kindU.S6.Sons->data[0]).kindU.S6.Sons->data[0]).kindU.S5.Ident);
		switch (LOC16) {
		case ((NU8) 106):
		{
			NI x;
			x = findstr_157318(TMP2618, 16, (*(*(*(*n).kindU.S6.Sons->data[0]).kindU.S6.Sons->data[1]).kindU.S5.Ident).S);
			{
				if (!(0 <= x)) goto LA20;
				nk = ((NU16) ((NI64)(x + 244)));
			}
			goto LA18;
			LA20: ;
			{
				invalidpragma_269065(n);
				goto BeforeRet;
			}
			LA18: ;
		}
		break;
		case ((NU8) 105):
		{
			NI x;
			x = findstr_157318(TMP2635, 24, (*(*(*(*n).kindU.S6.Sons->data[0]).kindU.S6.Sons->data[1]).kindU.S5.Ident).S);
			{
				if (!(0 <= x)) goto LA26;
				nk = ((NU16) ((NI64)(x + 220)));
			}
			goto LA24;
			LA26: ;
			{
				invalidpragma_269065(n);
				goto BeforeRet;
			}
			LA24: ;
		}
		break;
		default:
		{
			invalidpragma_269065(n);
			goto BeforeRet;
		}
		break;
		}
		x = (*c).Semconstboolexpr(c, (*n).kindU.S6.Sons->data[1]);
		asgnRefNoCycle((void**) &(*n).kindU.S6.Sons->data[1], x);
		{
			NIM_BOOL LOC32;
			LOC32 = ((*x).Kind == ((NU8) 6));
			if (!(LOC32)) goto LA33;
			LOC32 = !(((*x).kindU.S1.Intval == 0));
			LA33: ;
			if (!LOC32) goto LA34;
			gnotes_128867 |=((NI64)(1)<<(((nk- 220))%(sizeof(NI64)*8)));
		}
		goto LA30;
		LA34: ;
		{
			gnotes_128867 &= ~((NI64)(1) << (((nk- 220)) % (sizeof(NI64)*8)));
		}
		LA30: ;
	}
	goto LA1;
	LA14: ;
	{
		invalidpragma_269065(n);
	}
	LA1: ;
	BeforeRet: ;
}

N_NIMCALL(void, onoff_269724)(tcontext261019* c, tnode135647* n, NU32 op) {
	{
		NIM_BOOL LOC3;
		LOC3 = isturnedon_269674(c, n);
		if (!LOC3) goto LA4;
		goptions_105106 = (goptions_105106 | op);
	}
	goto LA1;
	LA4: ;
	{
		goptions_105106 = (goptions_105106 & ~ op);
	}
	LA1: ;
}

N_NIMCALL(NU8, wordtocallconv_269646)(NU8 sw) {
	NU8 result;
	result = 0;
	result = ((NU8) ((NI64)(((NI) ((NI64)(0 + ((NI) (sw))))) - 123)));
	return result;
}

N_NIMCALL(void, processcallconv_269811)(tcontext261019* c, tnode135647* n) {
	{
		NIM_BOOL LOC3;
		NU8 sw;
		LOC3 = ((*n).Kind == ((NU8) 34));
		if (!(LOC3)) goto LA4;
		LOC3 = ((*(*n).kindU.S6.Sons->data[1]).Kind == ((NU8) 2));
		LA4: ;
		if (!LOC3) goto LA5;
		sw = whichkeyword_157340((*(*n).kindU.S6.Sons->data[1]).kindU.S5.Ident);
		switch (sw) {
		case ((NU8) 123) ... ((NU8) 132):
		{
			(*((toptionentry261003*) ((*c).Optionstack.Tail))).Defaultcc = wordtocallconv_269646(sw);
		}
		break;
		default:
		{
			localerror_129673((*n).Info, ((NU16) 100), ((NimStringDesc*) &TMP2613));
		}
		break;
		}
	}
	goto LA1;
	LA5: ;
	{
		localerror_129673((*n).Info, ((NU16) 100), ((NimStringDesc*) &TMP2613));
	}
	LA1: ;
}

N_NIMCALL(NIM_BOOL, processoption_270332)(tcontext261019* c, tnode135647* n) {
	NIM_BOOL result;
	result = 0;
	{
		if (!!(((*n).Kind == ((NU8) 34)))) goto LA3;
		result = NIM_TRUE;
	}
	goto LA1;
	LA3: ;
	{
		if (!((*(*n).kindU.S6.Sons->data[0]).Kind == ((NU8) 42))) goto LA6;
		processnote_270065(c, n);
	}
	goto LA1;
	LA6: ;
	{
		if (!!(((*(*n).kindU.S6.Sons->data[0]).Kind == ((NU8) 2)))) goto LA9;
		result = NIM_TRUE;
	}
	goto LA1;
	LA9: ;
	{
		NU8 sw;
		sw = whichkeyword_157340((*(*n).kindU.S6.Sons->data[0]).kindU.S5.Ident);
		switch (sw) {
		case ((NU8) 135):
		{
			onoff_269724(c, n, 1022);
		}
		break;
		case ((NU8) 80):
		{
			onoff_269724(c, n, 2);
		}
		break;
		case ((NU8) 164):
		{
			onoff_269724(c, n, 4);
		}
		break;
		case ((NU8) 136):
		{
			onoff_269724(c, n, 8);
		}
		break;
		case ((NU8) 137):
		{
			onoff_269724(c, n, 16);
		}
		break;
		case ((NU8) 138):
		{
			onoff_269724(c, n, 32);
		}
		break;
		case ((NU8) 139):
		{
			onoff_269724(c, n, 64);
		}
		break;
		case ((NU8) 140):
		{
			onoff_269724(c, n, 384);
		}
		break;
		case ((NU8) 141):
		{
			onoff_269724(c, n, 128);
		}
		break;
		case ((NU8) 142):
		{
			onoff_269724(c, n, 256);
		}
		break;
		case ((NU8) 143):
		{
			onoff_269724(c, n, 512);
		}
		break;
		case ((NU8) 145):
		{
			onoff_269724(c, n, 2048);
		}
		break;
		case ((NU8) 146):
		{
			onoff_269724(c, n, 4096);
		}
		break;
		case ((NU8) 120):
		{
			processcallconv_269811(c, n);
		}
		break;
		case ((NU8) 112):
		{
			onoff_269724(c, n, 1024);
		}
		break;
		case ((NU8) 113):
		{
			onoff_269724(c, n, 32768);
		}
		break;
		case ((NU8) 114):
		{
			onoff_269724(c, n, 65536);
		}
		break;
		case ((NU8) 122):
		{
			onoff_269724(c, n, 131072);
		}
		break;
		case ((NU8) 79):
		{
			onoff_269724(c, n, 524288);
		}
		break;
		case ((NU8) 243):
		{
			onoff_269724(c, n, 262144);
		}
		break;
		case ((NU8) 100):
		{
			processdynlib_269984(c, n, NIM_NIL);
		}
		break;
		case ((NU8) 147):
		{
			{
				if (!!(((*(*n).kindU.S6.Sons->data[1]).Kind == ((NU8) 2)))) goto LA36;
				invalidpragma_269065(n);
			}
			goto LA34;
			LA36: ;
			{
				NimStringDesc* LOC39;
				LOC39 = 0;
				LOC39 = nsuNormalize((*(*(*n).kindU.S6.Sons->data[1]).kindU.S5.Ident).S);
				if (eqStrings(LOC39, ((NimStringDesc*) &TMP2659))) goto LA40;
				if (eqStrings(LOC39, ((NimStringDesc*) &TMP2660))) goto LA41;
				if (eqStrings(LOC39, ((NimStringDesc*) &TMP2661))) goto LA42;
				goto LA43;
				LA40: ;
				{
					goptions_105106 |=((NI32)(1)<<((((NU8) 13))%(sizeof(NI32)*8)));
					goptions_105106 &= ~((NI32)(1) << ((((NU8) 14)) % (sizeof(NI32)*8)));
				}
				goto LA44;
				LA41: ;
				{
					goptions_105106 &= ~((NI32)(1) << ((((NU8) 13)) % (sizeof(NI32)*8)));
					goptions_105106 |=((NI32)(1)<<((((NU8) 14))%(sizeof(NI32)*8)));
				}
				goto LA44;
				LA42: ;
				{
					goptions_105106 &= ~((NI32)(1) << ((((NU8) 13)) % (sizeof(NI32)*8)));
					goptions_105106 &= ~((NI32)(1) << ((((NU8) 14)) % (sizeof(NI32)*8)));
				}
				goto LA44;
				LA43: ;
				{
					localerror_129673((*n).Info, ((NU16) 27), ((NimStringDesc*) &TMP2613));
				}
				LA44: ;
			}
			LA34: ;
		}
		break;
		case ((NU8) 179):
		{
			onoff_269724(c, n, 1048576);
		}
		break;
		case ((NU8) 144):
		{
			onoff_269724(c, n, 2097152);
		}
		break;
		default:
		{
			result = NIM_TRUE;
		}
		break;
		}
	}
	LA1: ;
	return result;
}

N_NIMCALL(void, processpush_270526)(tcontext261019* c, tnode135647* n, NI start) {
	toptionentry261003* x;
	toptionentry261003* y;
	NI i_270558;
	NI HEX3Atmp_270587;
	NI LOC5;
	NI res_270589;
	{
		if (!((*(*n).kindU.S6.Sons->data[(NI64)(start - 1)]).Kind == ((NU8) 34))) goto LA3;
		localerror_129673((*n).Info, ((NU16) 4), ((NimStringDesc*) &TMP2617));
	}
	LA3: ;
	x = newoptionentry_261125();
	y = ((toptionentry261003*) ((*c).Optionstack.Tail));
	(*x).Options = goptions_105106;
	(*x).Defaultcc = (*y).Defaultcc;
	asgnRefNoCycle((void**) &(*x).Dynlib, (*y).Dynlib);
	(*x).Notes = gnotes_128867;
	append_100036(&(*c).Optionstack, &x->Sup);
	i_270558 = 0;
	HEX3Atmp_270587 = 0;
	LOC5 = sonslen_136002(n);
	HEX3Atmp_270587 = (NI64)(LOC5 - 1);
	res_270589 = start;
	while (1) {
		if (!(res_270589 <= HEX3Atmp_270587)) goto LA6;
		i_270558 = res_270589;
		{
			NIM_BOOL LOC9;
			LOC9 = processoption_270332(c, (*n).kindU.S6.Sons->data[i_270558]);
			if (!LOC9) goto LA10;
			{
				if (!(*x).Otherpragmas == 0) goto LA14;
				asgnRefNoCycle((void**) &(*x).Otherpragmas, newnodei_135920(((NU8) 90), (*n).Info));
			}
			LA14: ;
			add_136175((*x).Otherpragmas, (*n).kindU.S6.Sons->data[i_270558]);
		}
		LA10: ;
		res_270589 += 1;
	} LA6: ;
}

N_NIMCALL(void, processpop_270594)(tcontext261019* c, tnode135647* n) {
	{
		if (!((*c).Optionstack.Counter <= 1)) goto LA3;
		localerror_129673((*n).Info, ((NU16) 31), ((NimStringDesc*) &TMP2613));
	}
	goto LA1;
	LA3: ;
	{
		goptions_105106 = (*((toptionentry261003*) ((*c).Optionstack.Tail))).Options;
		gnotes_128867 = (*((toptionentry261003*) ((*c).Optionstack.Tail))).Notes;
		remove_100635(&(*c).Optionstack, (*c).Optionstack.Tail);
	}
	LA1: ;
}

N_NIMCALL(void, processpragma_271054)(tcontext261019* c, tnode135647* n, NI i) {
	tnode135647* it;
	tsym135677* userpragma;
	tnode135647* body;
	NI j_271137;
	NI HEX3Atmp_271149;
	NI HEX3Atmp_271150;
	NI LOC11;
	NI res_271152;
	it = (*n).kindU.S6.Sons->data[i];
	{
		if (!!(((*it).Kind == ((NU8) 34)))) goto LA3;
		invalidpragma_269065(n);
	}
	goto LA1;
	LA3: ;
	{
		if (!!(((*(*it).kindU.S6.Sons->data[0]).Kind == ((NU8) 2)))) goto LA6;
		invalidpragma_269065(n);
	}
	goto LA1;
	LA6: ;
	{
		if (!!(((*(*it).kindU.S6.Sons->data[1]).Kind == ((NU8) 2)))) goto LA9;
		invalidpragma_269065(n);
	}
	goto LA1;
	LA9: ;
	LA1: ;
	userpragma = newsym_135874(((NU8) 17), (*(*it).kindU.S6.Sons->data[1]).kindU.S5.Ident, NIM_NIL, (*it).Info);
	body = newnodei_135920(((NU8) 90), (*n).Info);
	j_271137 = 0;
	HEX3Atmp_271149 = 0;
	HEX3Atmp_271150 = 0;
	HEX3Atmp_271149 = (NI64)(i + 1);
	LOC11 = sonslen_136002(n);
	HEX3Atmp_271150 = (NI64)(LOC11 - 1);
	res_271152 = HEX3Atmp_271149;
	while (1) {
		if (!(res_271152 <= HEX3Atmp_271150)) goto LA12;
		j_271137 = res_271152;
		addson_136028(body, (*n).kindU.S6.Sons->data[j_271137]);
		res_271152 += 1;
	} LA12: ;
	asgnRefNoCycle((void**) &(*userpragma).Ast, body);
	strtableadd_142078(&(*c).Userpragmas, userpragma);
}

N_NIMCALL(void, processcodegendecl_269537)(tcontext261019* c, tnode135647* n, tsym135677* sym) {
	asgnRefNoCycle((void**) &(*sym).Constraint, getstrlitnode_269389(c, n));
}

N_NIMCALL(tnode135647*, semasmoremit_270777)(tcontext261019* con, tnode135647* n, NIM_CHAR marker) {
	tnode135647* result;
	result = 0;
	switch ((*(*n).kindU.S6.Sons->data[1]).Kind) {
	case ((NU8) 20):
	case ((NU8) 21):
	case ((NU8) 22):
	{
		NU8 LOC2;
		tnodeseq135641* LOC8;
		NimStringDesc* str;
		NI a;
		{
			if (!((*n).Kind == ((NU8) 89))) goto LA5;
			LOC2 = ((NU8) 89);
		}
		goto LA3;
		LA5: ;
		{
			LOC2 = ((NU8) 145);
		}
		LA3: ;
		LOC8 = 0;
		LOC8 = (tnodeseq135641*) newSeq((&NTI135641), 0);
		result = newnode_137403(LOC2, (*n).Info, LOC8, NIM_NIL);
		str = copyString((*(*n).kindU.S6.Sons->data[1]).kindU.S3.Strval);
		{
			if (!((str) && (str)->Sup.len == 0)) goto LA11;
			localerror_129673((*n).Info, ((NU16) 32), ((NimStringDesc*) &TMP2613));
			goto BeforeRet;
		}
		LA11: ;
		a = 0;
		while (1) {
			NI b;
			NimStringDesc* sub;
			NI c;
			b = nsuFindChar(str, marker, a);
			{
				if (!(b < 0)) goto LA16;
				sub = copyStr(str, a);
			}
			goto LA14;
			LA16: ;
			{
				sub = copyStrLast(str, a, (NI64)(b - 1));
			}
			LA14: ;
			{
				tnode135647* LOC23;
				if (!!(((sub) && (sub)->Sup.len == 0))) goto LA21;
				LOC23 = 0;
				LOC23 = newstrnode_135906(((NU8) 20), sub);
				addson_136028(result, LOC23);
			}
			LA21: ;
			{
				if (!(b < 0)) goto LA26;
				goto LA13;
			}
			LA26: ;
			c = nsuFindChar(str, marker, (NI64)(b + 1));
			{
				if (!(c < 0)) goto LA30;
				sub = copyStr(str, (NI64)(b + 1));
			}
			goto LA28;
			LA30: ;
			{
				sub = copyStrLast(str, (NI64)(b + 1), (NI64)(c - 1));
			}
			LA28: ;
			{
				tsym135677* e;
				tident131018* LOC37;
				if (!!(((sub) && (sub)->Sup.len == 0))) goto LA35;
				LOC37 = 0;
				LOC37 = getident_131448(sub);
				e = searchinscopes_262151(con, LOC37);
				{
					tnode135647* LOC46;
					if (!!((e == NIM_NIL))) goto LA40;
					{
						if (!((*e).Kind == ((NU8) 22))) goto LA44;
						loadstub_215571(e);
					}
					LA44: ;
					LOC46 = 0;
					LOC46 = newsymnode_135916(e);
					addson_136028(result, LOC46);
				}
				goto LA38;
				LA40: ;
				{
					tnode135647* LOC48;
					LOC48 = 0;
					LOC48 = newstrnode_135906(((NU8) 20), sub);
					addson_136028(result, LOC48);
				}
				LA38: ;
			}
			LA35: ;
			{
				if (!(c < 0)) goto LA51;
				goto LA13;
			}
			LA51: ;
			a = (NI64)(c + 1);
		} LA13: ;
	}
	break;
	default:
	{
		illformedast_261646(n);
	}
	break;
	}
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, pragmaemit_270853)(tcontext261019* c, tnode135647* n) {
	tnode135647* LOC1;
	LOC1 = 0;
	LOC1 = getstrlitnode_269389(c, n);
	asgnRefNoCycle((void**) &(*n).kindU.S6.Sons->data[1], semasmoremit_270777(c, n, 96));
}

N_NIMCALL(void, pragmaunroll_270880)(tcontext261019* c, tnode135647* n) {
	{
		if (!((*(*c).P).Nestedloopcounter <= 0)) goto LA3;
		invalidpragma_269065(n);
	}
	goto LA1;
	LA3: ;
	{
		NI unrollfactor;
		if (!((*n).Kind == ((NU8) 34))) goto LA6;
		unrollfactor = expectintlit_269459(c, n);
		{
			if (!((NU64)(unrollfactor) < (NU64)(32))) goto LA10;
			asgnRefNoCycle((void**) &(*n).kindU.S6.Sons->data[1], newintnode_135890(((NU8) 6), ((NI64) (unrollfactor))));
		}
		goto LA8;
		LA10: ;
		{
			invalidpragma_269065(n);
		}
		LA8: ;
	}
	goto LA1;
	LA6: ;
	LA1: ;
}

N_NIMCALL(void, pragmalinearscanend_270913)(tcontext261019* c, tnode135647* n) {
	noval_270869(n);
}

N_NIMCALL(void, pragmaline_270919)(tcontext261019* c, tnode135647* n) {
	{
		tnode135647* a;
		if (!((*n).Kind == ((NU8) 34))) goto LA3;
		asgnRefNoCycle((void**) &(*n).kindU.S6.Sons->data[1], (*c).Semconstexpr(c, (*n).kindU.S6.Sons->data[1]));
		a = (*n).kindU.S6.Sons->data[1];
		{
			tnode135647* x;
			tnode135647* y;
			if (!((*a).Kind == ((NU8) 37))) goto LA7;
			x = (*a).kindU.S6.Sons->data[0];
			y = (*a).kindU.S6.Sons->data[1];
			{
				if (!((*x).Kind == ((NU8) 34))) goto LA11;
				x = (*x).kindU.S6.Sons->data[1];
			}
			LA11: ;
			{
				if (!((*y).Kind == ((NU8) 34))) goto LA15;
				y = (*y).kindU.S6.Sons->data[1];
			}
			LA15: ;
			{
				if (!!(((*x).Kind == ((NU8) 20)))) goto LA19;
				localerror_129673((*n).Info, ((NU16) 6), ((NimStringDesc*) &TMP2613));
			}
			goto LA17;
			LA19: ;
			{
				if (!!(((*y).Kind == ((NU8) 6)))) goto LA22;
				localerror_129673((*n).Info, ((NU16) 7), ((NimStringDesc*) &TMP2613));
			}
			goto LA17;
			LA22: ;
			{
				(*n).Info.Fileindex = fileinfoidx_128506((*x).kindU.S3.Strval);
				(*n).Info.Line = ((NI16) ((*y).kindU.S1.Intval));
			}
			LA17: ;
		}
		goto LA5;
		LA7: ;
		{
			localerror_129673((*n).Info, ((NU16) 188), ((NimStringDesc*) &TMP2662));
		}
		LA5: ;
	}
	goto LA1;
	LA3: ;
	{
		(*n).Info = getinfocontext_129057(-1);
	}
	LA1: ;
}

N_NIMCALL(void, processexc_271161)(tcontext261019* c, tnode135647* x) {
	ttype135681* t;
	ttype135681* LOC1;
	LOC1 = 0;
	LOC1 = (*c).Semtypenode(c, x, NIM_NIL);
	t = skiptypes_202116(LOC1, IL64(211106247215360));
	{
		if (!!(((*t).Kind == ((NU8) 17)))) goto LA4;
		localerror_129673((*x).Info, ((NU16) 4), ((NimStringDesc*) &TMP2663));
	}
	LA4: ;
	asgnRefNoCycle((void**) &(*x).Typ, t);
}

static N_INLINE(NI, len_136081)(tnode135647* n) {
	NI result;
	result = 0;
	{
		if (!(*n).kindU.S6.Sons == 0) goto LA3;
		result = 0;
	}
	goto LA1;
	LA3: ;
	{
		result = (*n).kindU.S6.Sons->Sup.len;
	}
	LA1: ;
	return result;
}

N_NIMCALL(void, pragmaraisesortags_271157)(tcontext261019* c, tnode135647* n) {
	{
		tnode135647* it;
		if (!((*n).Kind == ((NU8) 34))) goto LA3;
		it = (*n).kindU.S6.Sons->data[1];
		{
			if (!!(((*it).Kind == ((NU8) 39) || (*it).Kind == ((NU8) 41)))) goto LA7;
			processexc_271161(c, it);
		}
		goto LA5;
		LA7: ;
		{
			tnode135647* e_271200;
			NI i_271202;
			NI HEX3Atmp_271204;
			NI LOC10;
			NI res_271206;
			e_271200 = 0;
			i_271202 = 0;
			HEX3Atmp_271204 = 0;
			LOC10 = len_136081(it);
			HEX3Atmp_271204 = LOC10 - 1;
			res_271206 = 0;
			while (1) {
				if (!(res_271206 <= HEX3Atmp_271204)) goto LA11;
				i_271202 = res_271206;
				e_271200 = (*it).kindU.S6.Sons->data[i_271202];
				processexc_271161(c, e_271200);
				res_271206 += 1;
			} LA11: ;
		}
		LA5: ;
	}
	goto LA1;
	LA3: ;
	{
		invalidpragma_269065(n);
	}
	LA1: ;
}

N_NIMCALL(NIM_BOOL, singlepragma_271210)(tcontext261019* c, tsym135677* sym, tnode135647* n, NI i, tspecialwords157009 validpragmas) {
	NIM_BOOL result;
	tnode135647* it;
	tnode135647* key;
	result = 0;
	it = (*n).kindU.S6.Sons->data[i];
	{
		if (!((*it).Kind == ((NU8) 34))) goto LA3;
		key = (*it).kindU.S6.Sons->data[0];
	}
	goto LA1;
	LA3: ;
	{
		key = it;
	}
	LA1: ;
	{
		tsym135677* userpragma;
		if (!((*key).Kind == ((NU8) 2))) goto LA8;
		userpragma = strtableget_142084((*c).Userpragmas, (*key).kindU.S5.Ident);
		{
			if (!!((userpragma == NIM_NIL))) goto LA12;
			(*c).Instcounter += 1;
			{
				if (!(100 < (*c).Instcounter)) goto LA16;
				globalerror_129660((*it).Info, ((NU16) 25), (*(*userpragma).Name).S);
			}
			LA16: ;
			pragma_269057(c, sym, (*userpragma).Ast, validpragmas);
			(*c).Instcounter -= 1;
		}
		goto LA10;
		LA12: ;
		{
			NU8 k;
			k = whichkeyword_157340((*key).kindU.S5.Ident);
			{
				if (!((validpragmas[k/8] &(1<<(k%8)))!=0)) goto LA21;
				switch (k) {
				case ((NU8) 88):
				{
					NimStringDesc* LOC24;
					LOC24 = 0;
					LOC24 = getoptionalstr_269523(c, it, (*(*sym).Name).S);
					makeexternexport_269229(sym, LOC24);
					(*sym).Flags |=((NI32)(1)<<((((NU8) 0))%(sizeof(NI32)*8)));
				}
				break;
				case ((NU8) 87):
				{
					NimStringDesc* LOC26;
					LOC26 = 0;
					LOC26 = getoptionalstr_269523(c, it, (*(*sym).Name).S);
					makeexternimport_269199(sym, LOC26);
				}
				break;
				case ((NU8) 86):
				{
					NimStringDesc* LOC28;
					LOC28 = 0;
					LOC28 = getoptionalstr_269523(c, it, (*(*sym).Name).S);
					processimportcompilerproc_269247(sym, LOC28);
				}
				break;
				case ((NU8) 193):
				{
					NimStringDesc* LOC30;
					LOC30 = 0;
					LOC30 = expectstrlit_269442(c, it);
					setexternname_269193(sym, LOC30);
				}
				break;
				case ((NU8) 82):
				{
					{
						if (!((196608 &(1<<(((*sym).Kind)&31)))!=0)) goto LA34;
						(*sym).Flags |=((NI32)(1)<<((((NU8) 25))%(sizeof(NI32)*8)));
					}
					goto LA32;
					LA34: ;
					{
						invalidpragma_269065(it);
					}
					LA32: ;
				}
				break;
				case ((NU8) 174):
				{
					{
						if (!((*sym).Kind == ((NU8) 17))) goto LA40;
						(*sym).Flags |=((NI32)(1)<<((((NU8) 9))%(sizeof(NI32)*8)));
					}
					goto LA38;
					LA40: ;
					{
						invalidpragma_269065(it);
					}
					LA38: ;
				}
				break;
				case ((NU8) 84):
				{
					NimStringDesc* LOC44;
					LOC44 = 0;
					LOC44 = getoptionalstr_269523(c, it, (*(*sym).Name).S);
					processimportcpp_269289(sym, LOC44);
				}
				break;
				case ((NU8) 85):
				{
					NimStringDesc* LOC46;
					LOC46 = 0;
					LOC46 = getoptionalstr_269523(c, it, (*(*sym).Name).S);
					processimportobjc_269331(sym, LOC46);
				}
				break;
				case ((NU8) 91):
				{
					NI align;
					{
						if (!((*sym).Typ == NIM_NIL)) goto LA50;
						invalidpragma_269065(it);
					}
					LA50: ;
					align = expectintlit_269459(c, it);
					{
						NIM_BOOL LOC54;
						NIM_BOOL LOC55;
						LOC55 = ispoweroftwo_106264(align);
						LOC54 = !(LOC55);
						if (!(LOC54)) goto LA56;
						LOC54 = !((align == 0));
						LA56: ;
						if (!LOC54) goto LA57;
						localerror_129673((*it).Info, ((NU16) 98), ((NimStringDesc*) &TMP2613));
					}
					goto LA52;
					LA57: ;
					{
						(*(*sym).Typ).Align = align;
					}
					LA52: ;
				}
				break;
				case ((NU8) 151):
				{
					NI size;
					{
						if (!((*sym).Typ == NIM_NIL)) goto LA63;
						invalidpragma_269065(it);
					}
					LA63: ;
					size = expectintlit_269459(c, it);
					{
						NIM_BOOL LOC67;
						NIM_BOOL LOC68;
						NIM_BOOL LOC69;
						LOC69 = ispoweroftwo_106264(size);
						LOC68 = !(LOC69);
						if (LOC68) goto LA70;
						LOC68 = (size <= 0);
						LA70: ;
						LOC67 = LOC68;
						if (LOC67) goto LA71;
						LOC67 = (8 < size);
						LA71: ;
						if (!LOC67) goto LA72;
						localerror_129673((*it).Info, ((NU16) 98), ((NimStringDesc*) &TMP2613));
					}
					goto LA65;
					LA72: ;
					{
						(*(*sym).Typ).Size = ((NI64) (size));
					}
					LA65: ;
				}
				break;
				case ((NU8) 92):
				{
					noval_270869(it);
					(*sym).Loc.Flags |=((NI8)(1)<<((((NU8) 3))%(sizeof(NI8)*8)));
				}
				break;
				case ((NU8) 93):
				case ((NU8) 178):
				{
					noval_270869(it);
					{
						if (!!((sym == NIM_NIL))) goto LA79;
						(*sym).Flags |=((NI32)(1)<<((((NU8) 9))%(sizeof(NI32)*8)));
					}
					LA79: ;
				}
				break;
				case ((NU8) 226):
				{
					noval_270869(it);
					(*sym).Flags |=((NI32)(1)<<((((NU8) 7))%(sizeof(NI32)*8)));
				}
				break;
				case ((NU8) 207):
				{
					noval_270869(it);
					(*sym).Flags |=((NI32)(1)<<((((NU8) 8))%(sizeof(NI32)*8)));
				}
				break;
				case ((NU8) 176):
				{
					noval_270869(it);
					(*sym).Flags |=((NI32)(1)<<((((NU8) 22))%(sizeof(NI32)*8)));
				}
				break;
				case ((NU8) 154):
				{
					pragmadeadcodeelim_269751(c, it);
				}
				break;
				case ((NU8) 156):
				{
					pragmanoforward_269781(c, it);
				}
				break;
				case ((NU8) 76):
				{
					processmagic_269544(c, it, sym);
				}
				break;
				case ((NU8) 158):
				{
					noval_270869(it);
					(*sym).Flags |=((NI32)(1)<<((((NU8) 23))%(sizeof(NI32)*8)));
					(*sym).Loc.Flags |=((NI8)(1)<<((((NU8) 3))%(sizeof(NI8)*8)));
				}
				break;
				case ((NU8) 180):
				{
					noval_270869(it);
					(*sym).Flags |=((NI32)(1)<<((((NU8) 3))%(sizeof(NI32)*8)));
				}
				break;
				case ((NU8) 98):
				{
					noval_270869(it);
					(*sym).Flags |=((NI32)(1)<<((((NU8) 24))%(sizeof(NI32)*8)));
				}
				break;
				case ((NU8) 95):
				{
					tlib135665* lib;
					tnode135647* LOC91;
					LOC91 = 0;
					LOC91 = getstrlitnode_269389(c, it);
					lib = getlib_269860(c, ((NU8) 0), LOC91);
					addtolib_261132(lib, sym);
					(*sym).Flags |=((NI32)(1)<<((((NU8) 5))%(sizeof(NI32)*8)));
					(*sym).Loc.Flags |=((NI8)(1)<<((((NU8) 6))%(sizeof(NI8)*8)));
					(*sym).Loc.Flags |=((NI8)(1)<<((((NU8) 3))%(sizeof(NI8)*8)));
					{
						if (!((*sym).Loc.R == NIM_NIL)) goto LA94;
						asgnRefNoCycle((void**) &(*sym).Loc.R, torope_126058((*(*sym).Name).S));
					}
					LA94: ;
				}
				break;
				case ((NU8) 83):
				{
					{
						if (!((*(*sym).Typ).Sons->Sup.len == 2)) goto LA99;
						(*sym).Flags |=((NI32)(1)<<((((NU8) 30))%(sizeof(NI32)*8)));
					}
					goto LA97;
					LA99: ;
					{
						invalidpragma_269065(it);
					}
					LA97: ;
				}
				break;
				case ((NU8) 96):
				{
					noval_270869(it);
					(*sym).Flags |=((NI32)(1)<<((((NU8) 10))%(sizeof(NI32)*8)));
					{
						if (!!(((*sym).Typ == NIM_NIL))) goto LA105;
						(*(*sym).Typ).Flags |=((NI32)(1)<<((((NU8) 1))%(sizeof(NI32)*8)));
					}
					LA105: ;
				}
				break;
				case ((NU8) 94):
				{
					noval_270869(it);
					(*sym).Flags |=((NI32)(1)<<((((NU8) 11))%(sizeof(NI32)*8)));
				}
				break;
				case ((NU8) 97):
				{
					noval_270869(it);
					(*sym).Flags |=((NI32)(1)<<((((NU8) 14))%(sizeof(NI32)*8)));
				}
				break;
				case ((NU8) 100):
				{
					processdynlib_269984(c, it, sym);
				}
				break;
				case ((NU8) 101):
				{
					noval_270869(it);
					makeexternexport_269229(sym, (*(*sym).Name).S);
					(*sym).Flags |=((NI32)(1)<<((((NU8) 16))%(sizeof(NI32)*8)));
					(*sym).Flags |=((NI32)(1)<<((((NU8) 0))%(sizeof(NI32)*8)));
					registercompilerproc_218026(sym);
				}
				break;
				case ((NU8) 102):
				{
					noval_270869(it);
					(*sym).Flags |=((NI32)(1)<<((((NU8) 17))%(sizeof(NI32)*8)));
				}
				break;
				case ((NU8) 118):
				{
					noval_270869(it);
					{
						if (!!((sym == NIM_NIL))) goto LA115;
						(*sym).Flags |=((NI32)(1)<<((((NU8) 19))%(sizeof(NI32)*8)));
					}
					goto LA113;
					LA115: ;
					{
						(*(*c).Module).Flags |=((NI32)(1)<<((((NU8) 19))%(sizeof(NI32)*8)));
					}
					LA113: ;
				}
				break;
				case ((NU8) 119):
				{
					noval_270869(it);
					{
						if (!((*sym).Typ == NIM_NIL)) goto LA121;
						invalidpragma_269065(it);
					}
					goto LA119;
					LA121: ;
					{
						(*(*sym).Typ).Flags |=((NI32)(1)<<((((NU8) 0))%(sizeof(NI32)*8)));
					}
					LA119: ;
				}
				break;
				case ((NU8) 162):
				{
					noval_270869(it);
					(*sym).Flags |=((NI32)(1)<<((((NU8) 26))%(sizeof(NI32)*8)));
				}
				break;
				case ((NU8) 78):
				{
					noval_270869(it);
					{
						if (!((*sym).Typ == NIM_NIL)) goto LA128;
						invalidpragma_269065(it);
					}
					goto LA126;
					LA128: ;
					{
						(*(*sym).Typ).Flags |=((NI32)(1)<<((((NU8) 2))%(sizeof(NI32)*8)));
					}
					LA126: ;
				}
				break;
				case ((NU8) 175):
				{
					noval_270869(it);
					{
						NIM_BOOL LOC134;
						LOC134 = ((*sym).Typ == NIM_NIL);
						if (LOC134) goto LA135;
						LOC134 = (((*(*sym).Typ).Flags &(1<<((((NU8) 2))&31)))!=0);
						LA135: ;
						if (!LOC134) goto LA136;
						invalidpragma_269065(it);
					}
					goto LA132;
					LA136: ;
					{
						(*(*sym).Typ).Flags |=((NI32)(1)<<((((NU8) 3))%(sizeof(NI32)*8)));
					}
					LA132: ;
				}
				break;
				case ((NU8) 167):
				{
					noval_270869(it);
					{
						if (!((*sym).Typ == NIM_NIL)) goto LA142;
						invalidpragma_269065(it);
					}
					goto LA140;
					LA142: ;
					{
						(*(*sym).Typ).Flags |=((NI32)(1)<<((((NU8) 4))%(sizeof(NI32)*8)));
					}
					LA140: ;
				}
				break;
				case ((NU8) 168):
				{
					noval_270869(it);
					{
						if (!((*sym).Typ == NIM_NIL)) goto LA148;
						invalidpragma_269065(it);
					}
					goto LA146;
					LA148: ;
					{
						(*(*sym).Typ).Flags |=((NI32)(1)<<((((NU8) 6))%(sizeof(NI32)*8)));
					}
					LA146: ;
				}
				break;
				case ((NU8) 77):
				{
					noval_270869(it);
					(*sym).Flags |=((NI32)(1)<<((((NU8) 22))%(sizeof(NI32)*8)));
					(*sym).Flags |=((NI32)(1)<<((((NU8) 17))%(sizeof(NI32)*8)));
					{
						if (!!(((*sym).Typ == NIM_NIL))) goto LA154;
						(*(*sym).Typ).Flags |=((NI32)(1)<<((((NU8) 7))%(sizeof(NI32)*8)));
					}
					LA154: ;
				}
				break;
				case ((NU8) 106):
				{
					NimStringDesc* LOC157;
					LOC157 = 0;
					LOC157 = expectstrlit_269442(c, it);
					message_129680((*it).Info, ((NU16) 259), LOC157);
				}
				break;
				case ((NU8) 105):
				{
					NimStringDesc* LOC159;
					LOC159 = 0;
					LOC159 = expectstrlit_269442(c, it);
					message_129680((*it).Info, ((NU16) 243), LOC159);
				}
				break;
				case ((NU8) 104):
				{
					{
						NIM_BOOL LOC163;
						LOC163 = !((sym == NIM_NIL));
						if (!(LOC163)) goto LA164;
						LOC163 = isroutine_140368(sym);
						LA164: ;
						if (!LOC163) goto LA165;
						noval_270869(it);
						(*sym).Flags |=((NI32)(1)<<((((NU8) 20))%(sizeof(NI32)*8)));
					}
					goto LA161;
					LA165: ;
					{
						NimStringDesc* LOC168;
						LOC168 = 0;
						LOC168 = expectstrlit_269442(c, it);
						localerror_129673((*it).Info, ((NU16) 219), LOC168);
					}
					LA161: ;
				}
				break;
				case ((NU8) 103):
				{
					NimStringDesc* LOC170;
					LOC170 = 0;
					LOC170 = expectstrlit_269442(c, it);
					fatal_129653((*it).Info, ((NU16) 219), LOC170);
				}
				break;
				case ((NU8) 110):
				{
					processdefine_270601(c, it);
				}
				break;
				case ((NU8) 111):
				{
					processundef_270649(c, it);
				}
				break;
				case ((NU8) 116):
				{
					processcompile_270702(c, it);
				}
				break;
				case ((NU8) 115):
				{
					processcommonlink_270711(c, it, ((NU8) 0));
				}
				break;
				case ((NU8) 117):
				{
					processcommonlink_270711(c, it, ((NU8) 1));
				}
				break;
				case ((NU8) 161):
				{
					NimStringDesc* LOC177;
					LOC177 = 0;
					LOC177 = expectstrlit_269442(c, it);
					addlinkoption_155630(LOC177);
				}
				break;
				case ((NU8) 160):
				{
					NimStringDesc* LOC179;
					LOC179 = 0;
					LOC179 = expectstrlit_269442(c, it);
					addcompileoption_155638(LOC179);
				}
				break;
				case ((NU8) 121):
				{
					pragmabreakpoint_270720(c, it);
				}
				break;
				case ((NU8) 165):
				{
					pragmawatchpoint_270745(c, it);
				}
				break;
				case ((NU8) 108):
				{
					processpush_270526(c, n, (NI64)(i + 1));
					result = NIM_TRUE;
				}
				break;
				case ((NU8) 109):
				{
					processpop_270594(c, it);
				}
				break;
				case ((NU8) 157):
				{
					processpragma_271054(c, n, i);
					result = NIM_TRUE;
				}
				break;
				case ((NU8) 163):
				{
					noval_270869(it);
					{
						if (!!((sym == NIM_NIL))) goto LA188;
						(*sym).Flags |=((NI32)(1)<<((((NU8) 29))%(sizeof(NI32)*8)));
					}
					LA188: ;
				}
				break;
				case ((NU8) 159):
				{
					noval_270869(it);
					{
						if (!!((sym == NIM_NIL))) goto LA193;
						(*sym).Flags |=((NI32)(1)<<((((NU8) 12))%(sizeof(NI32)*8)));
					}
					LA193: ;
				}
				break;
				case ((NU8) 181):
				{
					processcodegendecl_269537(c, it, sym);
				}
				break;
				case ((NU8) 135):
				case ((NU8) 80):
				case ((NU8) 164):
				case ((NU8) 136):
				case ((NU8) 137):
				case ((NU8) 138):
				case ((NU8) 139):
				case ((NU8) 143):
				case ((NU8) 145):
				case ((NU8) 146):
				case ((NU8) 112):
				case ((NU8) 113):
				case ((NU8) 114):
				case ((NU8) 147):
				case ((NU8) 120):
				case ((NU8) 122):
				case ((NU8) 79):
				case ((NU8) 140):
				case ((NU8) 141):
				case ((NU8) 142):
				case ((NU8) 144):
				{
					{
						NIM_BOOL LOC199;
						LOC199 = processoption_270332(c, it);
						if (!LOC199) goto LA200;
						localerror_129673((*it).Info, ((NU16) 149), ((NimStringDesc*) &TMP2613));
					}
					LA200: ;
				}
				break;
				case ((NU8) 123) ... ((NU8) 132):
				{
					{
						if (!((*sym).Typ == NIM_NIL)) goto LA205;
						invalidpragma_269065(it);
					}
					goto LA203;
					LA205: ;
					{
						(*(*sym).Typ).Callconv = wordtocallconv_269646(k);
					}
					LA203: ;
				}
				break;
				case ((NU8) 177):
				{
					pragmaemit_270853(c, it);
				}
				break;
				case ((NU8) 169):
				{
					pragmaunroll_270880(c, it);
				}
				break;
				case ((NU8) 170):
				{
					pragmalinearscanend_270913(c, it);
				}
				break;
				case ((NU8) 152):
				{
					noval_270869(it);
				}
				break;
				case ((NU8) 89):
				{
					noval_270869(it);
					{
						if (!((*sym).Typ == NIM_NIL)) goto LA215;
						invalidpragma_269065(it);
					}
					goto LA213;
					LA215: ;
					{
						(*(*sym).Typ).Flags |=((NI32)(1)<<((((NU8) 0))%(sizeof(NI32)*8)));
					}
					LA213: ;
				}
				break;
				case ((NU8) 90):
				{
					noval_270869(it);
					{
						if (!((*sym).Typ == NIM_NIL)) goto LA221;
						invalidpragma_269065(it);
					}
					goto LA219;
					LA221: ;
					{
						(*(*sym).Typ).Flags |=((NI32)(1)<<((((NU8) 19))%(sizeof(NI32)*8)));
					}
					LA219: ;
				}
				break;
				case ((NU8) 243):
				{
					noval_270869(it);
					{
						NIM_BOOL LOC227;
						LOC227 = (sym == NIM_NIL);
						if (LOC227) goto LA228;
						LOC227 = ((*sym).Typ == NIM_NIL);
						LA228: ;
						if (!LOC227) goto LA229;
						{
							NIM_BOOL LOC233;
							LOC233 = processoption_270332(c, it);
							if (!LOC233) goto LA234;
							localerror_129673((*it).Info, ((NU16) 149), ((NimStringDesc*) &TMP2613));
						}
						LA234: ;
					}
					goto LA225;
					LA229: ;
					{
						(*(*sym).Typ).Flags |=((NI32)(1)<<((((NU8) 15))%(sizeof(NI32)*8)));
					}
					LA225: ;
				}
				break;
				case ((NU8) 242):
				{
					noval_270869(it);
					{
						NIM_BOOL LOC240;
						LOC240 = !(((*sym).Kind == ((NU8) 7)));
						if (LOC240) goto LA241;
						LOC240 = ((*sym).Typ == NIM_NIL);
						LA241: ;
						if (!LOC240) goto LA242;
						invalidpragma_269065(it);
					}
					goto LA238;
					LA242: ;
					{
						(*(*sym).Typ).Flags |=((NI32)(1)<<((((NU8) 14))%(sizeof(NI32)*8)));
					}
					LA238: ;
				}
				break;
				case ((NU8) 173):
				case ((NU8) 172):
				{
					noval_270869(it);
					{
						if (!(sym == NIM_NIL)) goto LA248;
						invalidpragma_269065(it);
					}
					LA248: ;
				}
				break;
				case ((NU8) 107):
				{
					pragmaline_270919(c, it);
				}
				break;
				case ((NU8) 148):
				case ((NU8) 153):
				{
					pragmaraisesortags_271157(c, it);
				}
				break;
				case ((NU8) 203):
				{
					{
						if (!(sym == NIM_NIL)) goto LA255;
						invalidpragma_269065(it);
					}
					goto LA253;
					LA255: ;
					{
						(*sym).Position = expectintlit_269459(c, it);
					}
					LA253: ;
				}
				break;
				default:
				{
					invalidpragma_269065(it);
				}
				break;
				}
			}
			goto LA19;
			LA21: ;
			{
				invalidpragma_269065(it);
			}
			LA19: ;
		}
		LA10: ;
	}
	goto LA6;
	LA8: ;
	{
		processnote_270065(c, it);
	}
	LA6: ;
	return result;
}

N_NIMCALL(void, implictpragmas_272145)(tcontext261019* c, tsym135677* sym, tnode135647* n, tspecialwords157009 validpragmas) {
	{
		NIM_BOOL LOC3;
		toptionentry261003* it;
		tlib135665* lib;
		LOC3 = !((sym == NIM_NIL));
		if (!(LOC3)) goto LA4;
		LOC3 = !(((*sym).Kind == ((NU8) 6)));
		LA4: ;
		if (!LOC3) goto LA5;
		it = ((toptionentry261003*) ((*c).Optionstack.Head));
		while (1) {
			tnode135647* o;
			if (!!((it == NIM_NIL))) goto LA7;
			o = (*it).Otherpragmas;
			{
				NI i_272197;
				NI HEX3Atmp_272284;
				NI LOC12;
				NI res_272286;
				if (!!(o == 0)) goto LA10;
				i_272197 = 0;
				HEX3Atmp_272284 = 0;
				LOC12 = sonslen_136002(o);
				HEX3Atmp_272284 = (NI64)(LOC12 - 1);
				res_272286 = 0;
				while (1) {
					if (!(res_272286 <= HEX3Atmp_272284)) goto LA13;
					i_272197 = res_272286;
					{
						NIM_BOOL LOC16;
						LOC16 = singlepragma_271210(c, sym, o, i_272197, validpragmas);
						if (!LOC16) goto LA17;
						internalerror_129687((*n).Info, ((NimStringDesc*) &TMP2664));
					}
					LA17: ;
					res_272286 += 1;
				} LA13: ;
			}
			LA10: ;
			it = ((toptionentry261003*) ((*it).Sup.Next));
		} LA7: ;
		{
			NIM_BOOL LOC21;
			LOC21 = (((*sym).Loc.Flags &(1<<((((NU8) 5))&7)))!=0);
			if (!(LOC21)) goto LA22;
			LOC21 = !((((*sym).Flags &(1<<((((NU8) 6))&31)))!=0));
			LA22: ;
			if (!LOC21) goto LA23;
			localerror_129673((*n).Info, ((NU16) 79), ((NimStringDesc*) &TMP2613));
		}
		LA23: ;
		lib = (*((toptionentry261003*) ((*c).Optionstack.Tail))).Dynlib;
		{
			NIM_BOOL LOC27;
			NIM_BOOL LOC28;
			LOC28 = ((80 & (*sym).Loc.Flags) == 0);
			if (!(LOC28)) goto LA29;
			LOC28 = (((*sym).Flags &(1<<((((NU8) 5))&31)))!=0);
			LA29: ;
			LOC27 = LOC28;
			if (!(LOC27)) goto LA30;
			LOC27 = !((lib == NIM_NIL));
			LA30: ;
			if (!LOC27) goto LA31;
			(*sym).Loc.Flags |=((NI8)(1)<<((((NU8) 4))%(sizeof(NI8)*8)));
			addtolib_261132(lib, sym);
			{
				if (!((*sym).Loc.R == NIM_NIL)) goto LA35;
				asgnRefNoCycle((void**) &(*sym).Loc.R, torope_126058((*(*sym).Name).S));
			}
			LA35: ;
		}
		LA31: ;
	}
	LA5: ;
}

N_NIMCALL(void, pragma_269057)(tcontext261019* c, tsym135677* sym, tnode135647* n, tspecialwords157009 validpragmas) {
	NI i_272317;
	NI HEX3Atmp_272318;
	NI LOC5;
	NI res_272320;
	{
		if (!(n == NIM_NIL)) goto LA3;
		goto BeforeRet;
	}
	LA3: ;
	i_272317 = 0;
	HEX3Atmp_272318 = 0;
	LOC5 = sonslen_136002(n);
	HEX3Atmp_272318 = (NI64)(LOC5 - 1);
	res_272320 = 0;
	while (1) {
		if (!(res_272320 <= HEX3Atmp_272318)) goto LA6;
		i_272317 = res_272320;
		{
			NIM_BOOL LOC9;
			LOC9 = singlepragma_271210(c, sym, n, i_272317, validpragmas);
			if (!LOC9) goto LA10;
			goto LA6;
		}
		LA10: ;
		res_272320 += 1;
	} LA6: ;
	implictpragmas_272145(c, sym, n, validpragmas);
	BeforeRet: ;
}

N_NIMCALL(NIM_CHAR, pragmaasm_269071)(tcontext261019* c, tnode135647* n) {
	NIM_CHAR result;
	result = 0;
	result = 0;
	{
		NI i_269095;
		NI HEX3Atmp_269186;
		NI LOC5;
		NI res_269188;
		if (!!((n == NIM_NIL))) goto LA3;
		i_269095 = 0;
		HEX3Atmp_269186 = 0;
		LOC5 = sonslen_136002(n);
		HEX3Atmp_269186 = (NI64)(LOC5 - 1);
		res_269188 = 0;
		while (1) {
			tnode135647* it;
			if (!(res_269188 <= HEX3Atmp_269186)) goto LA6;
			i_269095 = res_269188;
			it = (*n).kindU.S6.Sons->data[i_269095];
			{
				NIM_BOOL LOC9;
				NU8 LOC13;
				LOC9 = ((*it).Kind == ((NU8) 34));
				if (!(LOC9)) goto LA10;
				LOC9 = ((*(*it).kindU.S6.Sons->data[0]).Kind == ((NU8) 2));
				LA10: ;
				if (!LOC9) goto LA11;
				LOC13 = whichkeyword_157340((*(*it).kindU.S6.Sons->data[0]).kindU.S5.Ident);
				switch (LOC13) {
				case ((NU8) 166):
				{
					{
						if (!((*(*it).kindU.S6.Sons->data[1]).Kind == ((NU8) 5))) goto LA17;
						result = ((NIM_CHAR) (((NI) (((NI) ((*(*it).kindU.S6.Sons->data[1]).kindU.S1.Intval))))));
					}
					goto LA15;
					LA17: ;
					{
						invalidpragma_269065(it);
					}
					LA15: ;
				}
				break;
				default:
				{
					invalidpragma_269065(it);
				}
				break;
				}
			}
			goto LA7;
			LA11: ;
			{
				invalidpragma_269065(it);
			}
			LA7: ;
			res_269188 += 1;
		} LA6: ;
	}
	LA3: ;
	return result;
}
N_NOINLINE(void, pragmasInit)(void) {
}

N_NOINLINE(void, pragmasDatInit)(void) {
}

