/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/usr/src/extras/Nimrod/lib -o compiler/nimcache/rstast.o compiler/nimcache/rstast.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct trstnode277016 trstnode277016;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct trstnodeseq277014 trstnodeseq277014;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcell38449 tcell38449;
typedef struct tcellseq38465 tcellseq38465;
typedef struct tgcheap40416 tgcheap40416;
typedef struct tcellset38461 tcellset38461;
typedef struct tpagedesc38457 tpagedesc38457;
typedef struct tmemregion22010 tmemregion22010;
typedef struct tsmallchunk21243 tsmallchunk21243;
typedef struct tllchunk22004 tllchunk22004;
typedef struct tbigchunk21245 tbigchunk21245;
typedef struct tintset21218 tintset21218;
typedef struct ttrunk21214 ttrunk21214;
typedef struct tavlnode22008 tavlnode22008;
typedef struct tgcstat40414 tgcstat40414;
typedef struct tbasechunk21241 tbasechunk21241;
typedef struct tfreecell21233 tfreecell21233;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
struct trstnode277016 {
NU8 Kind;
NimStringDesc* Text;
NI Level;
trstnodeseq277014* Sons;
};
typedef N_NIMCALL_PTR(void, TY891) (void* p, NI op);
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY891 marker;
};
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tcell38449 {
NI Refcount;
TNimType* Typ;
};
struct tcellseq38465 {
NI Len;
NI Cap;
tcell38449** D;
};
struct tcellset38461 {
NI Counter;
NI Max;
tpagedesc38457* Head;
tpagedesc38457** Data;
};
typedef tsmallchunk21243* TY22022[512];
typedef ttrunk21214* ttrunkbuckets21216[256];
struct tintset21218 {
ttrunkbuckets21216 Data;
};
struct tmemregion22010 {
NI Minlargeobj;
NI Maxlargeobj;
TY22022 Freesmallchunks;
tllchunk22004* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk21245* Freechunkslist;
tintset21218 Chunkstarts;
tavlnode22008* Root;
tavlnode22008* Deleted;
tavlnode22008* Last;
tavlnode22008* Freeavlnodes;
};
struct tgcstat40414 {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct tgcheap40416 {
void* Stackbottom;
NI Cyclethreshold;
tcellseq38465 Zct;
tcellseq38465 Decstack;
tcellset38461 Cycleroots;
tcellseq38465 Tempstack;
NI Recgclock;
tmemregion22010 Region;
tgcstat40414 Stat;
};
typedef NI TY21221[8];
struct tpagedesc38457 {
tpagedesc38457* Next;
NI Key;
TY21221 Bits;
};
struct tbasechunk21241 {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct tsmallchunk21243 {
  tbasechunk21241 Sup;
tsmallchunk21243* Next;
tsmallchunk21243* Prev;
tfreecell21233* Freelist;
NI Free;
NI Acc;
NF64 Data;
};
struct tllchunk22004 {
NI Size;
NI Acc;
tllchunk22004* Next;
};
struct tbigchunk21245 {
  tbasechunk21241 Sup;
tbigchunk21245* Next;
tbigchunk21245* Prev;
NI Align;
NF64 Data;
};
struct ttrunk21214 {
ttrunk21214* Next;
NI Key;
TY21221 Bits;
};
typedef tavlnode22008* TY22014[2];
struct tavlnode22008 {
TY22014 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct tfreecell21233 {
tfreecell21233* Next;
NI Zerofield;
};
struct trstnodeseq277014 {
  TGenericSeq Sup;
  trstnode277016* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP2218)(void* p, NI op);
N_NIMCALL(void, TMP2219)(void* p, NI op);
N_NIMCALL(trstnode277016*, newrstnode_277101)(NU8 kind);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell38449*, usrtocell_41843)(void* usr);
static N_INLINE(void, rtladdzct_43002)(tcell38449* c);
N_NOINLINE(void, addzct_41815)(tcellseq38465* s, tcell38449* c);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
N_NIMCALL(TGenericSeq*, incrSeq)(TGenericSeq* seq, NI elemsize);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(void, add_277162)(trstnode277016* father, trstnode277016* son);
TNimType NTI277016; /* TRSTNode */
TNimType NTI277010; /* TRstNodeKind */
extern TNimType NTI143; /* string */
extern TNimType NTI105; /* int */
TNimType NTI277014; /* TRstNodeSeq */
TNimType NTI277012; /* PRSTNode */
extern tgcheap40416 gch_40442;

N_NIMCALL(NI, len_277087)(trstnode277016* n) {
	NI result;
	result = 0;
	result = (*n).Sons->Sup.len;
	return result;
}

N_NIMCALL(trstnode277016*, lastson_277148)(trstnode277016* n) {
	trstnode277016* result;
	result = 0;
	result = (*n).Sons->data[(NI64)((*n).Sons->Sup.len - 1)];
	return result;
}
N_NIMCALL(void, TMP2218)(void* p, NI op) {
	trstnodeseq277014* a;
	NI LOC1;
	a = (trstnodeseq277014*)p;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1], op);
	}
}
N_NIMCALL(void, TMP2219)(void* p, NI op) {
	trstnode277016* a;
	a = (trstnode277016*)p;
	nimGCvisit((void*)(*a).Text, op);
	nimGCvisit((void*)(*a).Sons, op);
}

static N_INLINE(tcell38449*, usrtocell_41843)(void* usr) {
	tcell38449* result;
	result = 0;
	result = ((tcell38449*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell38449))))));
	return result;
}

static N_INLINE(void, rtladdzct_43002)(tcell38449* c) {
	addzct_41815(&gch_40442.Zct, c);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell38449* c;
	c = usrtocell_41843(p);
	{
		(*c).Refcount -= 8;
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		rtladdzct_43002(c);
	}
	LA3: ;
}

N_NIMCALL(trstnode277016*, newrstnode_277101)(NU8 kind) {
	trstnode277016* result;
	result = 0;
	result = (trstnode277016*) newObj((&NTI277012), sizeof(trstnode277016));
	if ((*result).Sons) nimGCunrefNoCycle((*result).Sons);
	(*result).Sons = (trstnodeseq277014*) newSeqRC1((&NTI277014), 0);
	(*result).Kind = kind;
	return result;
}

N_NIMCALL(trstnode277016*, newrstnode_277141)(NU8 kind, NimStringDesc* s) {
	trstnode277016* result;
	NimStringDesc* LOC1;
	result = 0;
	result = newrstnode_277101(kind);
	LOC1 = 0;
	LOC1 = (*result).Text; (*result).Text = copyStringRC1(s);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	return result;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		tcell38449* c;
		if (!!((src == NIM_NIL))) goto LA3;
		c = usrtocell_41843(src);
		(*c).Refcount += 8;
	}
	LA3: ;
	{
		tcell38449* c;
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		c = usrtocell_41843((*dest));
		{
			(*c).Refcount -= 8;
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			rtladdzct_43002(c);
		}
		LA11: ;
	}
	LA7: ;
	(*dest) = src;
}

N_NIMCALL(void, add_277162)(trstnode277016* father, trstnode277016* son) {
	(*father).Sons = (trstnodeseq277014*) incrSeq(&((*father).Sons)->Sup, sizeof(trstnode277016*));
	asgnRefNoCycle((void**) &(*father).Sons->data[(*father).Sons->Sup.len-1], son);
}

N_NIMCALL(void, addifnotnil_277184)(trstnode277016* father, trstnode277016* son) {
	{
		if (!!((son == NIM_NIL))) goto LA3;
		add_277162(father, son);
	}
	LA3: ;
}
N_NOINLINE(void, rstastInit)(void) {
}

N_NOINLINE(void, rstastDatInit)(void) {
static TNimNode* TMP2214[4];
static TNimNode* TMP2215[65];
NI TMP2217;
static char* NIM_CONST TMP2216[65] = {
"rnInner", 
"rnHeadline", 
"rnOverline", 
"rnTransition", 
"rnParagraph", 
"rnBulletList", 
"rnBulletItem", 
"rnEnumList", 
"rnEnumItem", 
"rnDefList", 
"rnDefItem", 
"rnDefName", 
"rnDefBody", 
"rnFieldList", 
"rnField", 
"rnFieldName", 
"rnFieldBody", 
"rnOptionList", 
"rnOptionListItem", 
"rnOptionGroup", 
"rnOption", 
"rnOptionString", 
"rnOptionArgument", 
"rnDescription", 
"rnLiteralBlock", 
"rnQuotedLiteralBlock", 
"rnLineBlock", 
"rnLineBlockItem", 
"rnBlockQuote", 
"rnTable", 
"rnGridTable", 
"rnTableRow", 
"rnTableHeaderCell", 
"rnTableDataCell", 
"rnLabel", 
"rnFootnote", 
"rnCitation", 
"rnStandaloneHyperlink", 
"rnHyperlink", 
"rnRef", 
"rnDirective", 
"rnDirArg", 
"rnRaw", 
"rnTitle", 
"rnContents", 
"rnImage", 
"rnFigure", 
"rnCodeBlock", 
"rnRawHtml", 
"rnRawLatex", 
"rnContainer", 
"rnIndex", 
"rnSubstitutionDef", 
"rnGeneralRole", 
"rnSub", 
"rnSup", 
"rnIdx", 
"rnEmphasis", 
"rnStrongEmphasis", 
"rnTripleEmphasis", 
"rnInterpretedText", 
"rnInlineLiteral", 
"rnSubstitutionReferences", 
"rnSmiley", 
"rnLeaf"};
static TNimNode TMP866[71];
NTI277016.size = sizeof(trstnode277016);
NTI277016.kind = 18;
NTI277016.base = 0;
NTI277016.flags = 2;
TMP2214[0] = &TMP866[1];
NTI277010.size = sizeof(NU8);
NTI277010.kind = 14;
NTI277010.base = 0;
NTI277010.flags = 3;
for (TMP2217 = 0; TMP2217 < 65; TMP2217++) {
TMP866[TMP2217+2].kind = 1;
TMP866[TMP2217+2].offset = TMP2217;
TMP866[TMP2217+2].name = TMP2216[TMP2217];
TMP2215[TMP2217] = &TMP866[TMP2217+2];
}
TMP866[67].len = 65; TMP866[67].kind = 2; TMP866[67].sons = &TMP2215[0];
NTI277010.node = &TMP866[67];
TMP866[1].kind = 1;
TMP866[1].offset = offsetof(trstnode277016, Kind);
TMP866[1].typ = (&NTI277010);
TMP866[1].name = "kind";
TMP2214[1] = &TMP866[68];
TMP866[68].kind = 1;
TMP866[68].offset = offsetof(trstnode277016, Text);
TMP866[68].typ = (&NTI143);
TMP866[68].name = "text";
TMP2214[2] = &TMP866[69];
TMP866[69].kind = 1;
TMP866[69].offset = offsetof(trstnode277016, Level);
TMP866[69].typ = (&NTI105);
TMP866[69].name = "level";
TMP2214[3] = &TMP866[70];
NTI277014.size = sizeof(trstnodeseq277014*);
NTI277014.kind = 24;
NTI277014.base = (&NTI277012);
NTI277014.flags = 2;
NTI277014.marker = TMP2218;
TMP866[70].kind = 1;
TMP866[70].offset = offsetof(trstnode277016, Sons);
TMP866[70].typ = (&NTI277014);
TMP866[70].name = "sons";
TMP866[0].len = 4; TMP866[0].kind = 2; TMP866[0].sons = &TMP2214[0];
NTI277016.node = &TMP866[0];
NTI277012.size = sizeof(trstnode277016*);
NTI277012.kind = 22;
NTI277012.base = (&NTI277016);
NTI277012.flags = 2;
NTI277012.marker = TMP2219;
}

