/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/usr/src/extras/Nimrod/lib -o compiler/nimcache/semdata.o compiler/nimcache/semdata.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct tsymseq135649 tsymseq135649;
typedef struct tsym135677 tsym135677;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcell38449 tcell38449;
typedef struct tcellseq38465 tcellseq38465;
typedef struct tgcheap40416 tgcheap40416;
typedef struct tcellset38461 tcellset38461;
typedef struct tpagedesc38457 tpagedesc38457;
typedef struct tmemregion22010 tmemregion22010;
typedef struct tsmallchunk21243 tsmallchunk21243;
typedef struct tllchunk22004 tllchunk22004;
typedef struct tbigchunk21245 tbigchunk21245;
typedef struct tintset21218 tintset21218;
typedef struct ttrunk21214 ttrunk21214;
typedef struct tavlnode22008 tavlnode22008;
typedef struct tgcstat40414 tgcstat40414;
typedef struct tcontext261019 tcontext261019;
typedef struct tpasscontext224003 tpasscontext224003;
typedef struct TNimObject TNimObject;
typedef struct tscope135671 tscope135671;
typedef struct tproccon261009 tproccon261009;
typedef struct tintset132035 tintset132035;
typedef struct ttrunk132031 ttrunk132031;
typedef struct ttrunkseq132033 ttrunkseq132033;
typedef struct tlinkedlist100017 tlinkedlist100017;
typedef struct tlistentry100011 tlistentry100011;
typedef struct tidtable135693 tidtable135693;
typedef struct tidpairseq135691 tidpairseq135691;
typedef struct tidpair135689 tidpair135689;
typedef struct tidobj131012 tidobj131012;
typedef struct tnode135647 tnode135647;
typedef struct ttype135681 ttype135681;
typedef struct tstrtable135651 tstrtable135651;
typedef struct tevalcontext252212 tevalcontext252212;
typedef struct TY261100 TY261100;
typedef struct tinstantiationpair261011 tinstantiationpair261011;
typedef struct tinstantiation135667 tinstantiation135667;
typedef struct toptionentry261003 toptionentry261003;
typedef struct tlib135665 tlib135665;
typedef struct tlineinfo128308 tlineinfo128308;
typedef struct NimStringDesc NimStringDesc;
typedef struct tident131018 tident131018;
typedef struct tnodeseq135641 tnodeseq135641;
typedef struct ttypeseq135679 ttypeseq135679;
typedef struct tloc135661 tloc135661;
typedef struct trope126007 trope126007;
typedef struct TY71082 TY71082;
typedef struct TY135771 TY135771;
typedef struct tbasechunk21241 tbasechunk21241;
typedef struct tfreecell21233 tfreecell21233;
typedef struct tstackframe252204 tstackframe252204;
typedef struct tidnodetable135699 tidnodetable135699;
typedef struct tidnodepairseq135697 tidnodepairseq135697;
typedef struct tidnodepair135695 tidnodepair135695;
typedef struct TY135763 TY135763;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef N_NIMCALL_PTR(void, TY891) (void* p, NI op);
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY891 marker;
};
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tcell38449 {
NI Refcount;
TNimType* Typ;
};
struct tcellseq38465 {
NI Len;
NI Cap;
tcell38449** D;
};
struct tcellset38461 {
NI Counter;
NI Max;
tpagedesc38457* Head;
tpagedesc38457** Data;
};
typedef tsmallchunk21243* TY22022[512];
typedef ttrunk21214* ttrunkbuckets21216[256];
struct tintset21218 {
ttrunkbuckets21216 Data;
};
struct tmemregion22010 {
NI Minlargeobj;
NI Maxlargeobj;
TY22022 Freesmallchunks;
tllchunk22004* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk21245* Freechunkslist;
tintset21218 Chunkstarts;
tavlnode22008* Root;
tavlnode22008* Deleted;
tavlnode22008* Last;
tavlnode22008* Freeavlnodes;
};
struct tgcstat40414 {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct tgcheap40416 {
void* Stackbottom;
NI Cyclethreshold;
tcellseq38465 Zct;
tcellseq38465 Decstack;
tcellset38461 Cycleroots;
tcellseq38465 Tempstack;
NI Recgclock;
tmemregion22010 Region;
tgcstat40414 Stat;
};
struct TNimObject {
TNimType* m_type;
};
struct tpasscontext224003 {
  TNimObject Sup;
NIM_BOOL Fromcache;
};
struct tintset132035 {
NI Counter;
NI Max;
ttrunk132031* Head;
ttrunkseq132033* Data;
};
struct tlinkedlist100017 {
tlistentry100011* Head;
tlistentry100011* Tail;
NI Counter;
};
struct tidpair135689 {
tidobj131012* Key;
TNimObject* Val;
};
struct tidtable135693 {
NI Counter;
tidpairseq135691* Data;
};
typedef N_NIMCALL_PTR(tnode135647*, TY261057) (tcontext261019* c, tnode135647* n);
typedef N_NIMCALL_PTR(tnode135647*, TY261062) (tcontext261019* c, tnode135647* n, NU8 flags);
typedef N_NIMCALL_PTR(tnode135647*, TY261070) (tcontext261019* c, tnode135647* n, NU8 flags);
typedef N_NIMCALL_PTR(tnode135647*, TY261078) (tcontext261019* c, tnode135647* n);
typedef N_NIMCALL_PTR(tnode135647*, TY261083) (tcontext261019* c, tnode135647* n, tnode135647* norig, NU32 filter);
typedef N_NIMCALL_PTR(ttype135681*, TY261090) (tcontext261019* c, tnode135647* n, ttype135681* prev);
struct tstrtable135651 {
NI Counter;
tsymseq135649* Data;
};
struct tinstantiationpair261011 {
tsym135677* Genericsym;
tinstantiation135667* Inst;
};
struct tcontext261019 {
  tpasscontext224003 Sup;
tsym135677* Module;
tscope135671* Currentscope;
tscope135671* Importtable;
tscope135671* Toplevelscope;
tproccon261009* P;
tsym135677* Friendmodule;
NI Instcounter;
tsymseq135649* Threadentries;
tintset132035 Ambiguoussymbols;
NI Ingenericcontext;
NI Inunrolledcontext;
NI Incompilescontext;
NI Ingenericinst;
tsymseq135649* Converters;
tsymseq135649* Patterns;
tlinkedlist100017 Optionstack;
tidtable135693 Symmapping;
tlinkedlist100017 Libs;
TY261057 Semconstexpr;
TY261062 Semexpr;
TY261070 Semoperand;
TY261078 Semconstboolexpr;
TY261083 Semoverloadedcall;
TY261090 Semtypenode;
tintset132035 Includedfiles;
tstrtable135651 Userpragmas;
tevalcontext252212* Evalcontext;
tintset132035 Unknownidents;
TY261100* Generics;
NI Lastgenericidx;
};
struct tproccon261009 {
tsym135677* Owner;
tsym135677* Resultsym;
NI Nestedloopcounter;
NI Nestedblockcounter;
NI Intrystmt;
tproccon261009* Next;
};
struct tlistentry100011 {
  TNimObject Sup;
tlistentry100011* Prev;
tlistentry100011* Next;
};
struct toptionentry261003 {
  tlistentry100011 Sup;
NU32 Options;
NU8 Defaultcc;
tlib135665* Dynlib;
NU64 Notes;
tnode135647* Otherpragmas;
};
struct tlineinfo128308 {
NI16 Line;
NI16 Col;
NI32 Fileindex;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
struct tnode135647 {
ttype135681* Typ;
tlineinfo128308 Info;
NU8 Flags;
NU8 Kind;
union {
struct {NI64 Intval;
} S1;
struct {NF64 Floatval;
} S2;
struct {NimStringDesc* Strval;
} S3;
struct {tsym135677* Sym;
} S4;
struct {tident131018* Ident;
} S5;
struct {tnodeseq135641* Sons;
} S6;
} kindU;
NimStringDesc* Comment;
};
struct tidobj131012 {
  TNimObject Sup;
NI Id;
};
struct tloc135661 {
NU8 K;
NU8 S;
NU8 Flags;
ttype135681* T;
trope126007* R;
trope126007* Heaproot;
NI A;
};
struct ttype135681 {
  tidobj131012 Sup;
NU8 Kind;
NU8 Callconv;
NU32 Flags;
ttypeseq135679* Sons;
tnode135647* N;
tsym135677* Destructor;
tsym135677* Owner;
tsym135677* Sym;
NI64 Size;
NI Align;
tloc135661 Loc;
};
struct TY71082 {
NimStringDesc* Field0;
NI Field1;
};
struct tlib135665 {
  tlistentry100011 Sup;
NU8 Kind;
NIM_BOOL Generated;
NIM_BOOL Isoverriden;
trope126007* Name;
tnode135647* Path;
};
struct tsym135677 {
  tidobj131012 Sup;
NU8 Kind;
union {
struct {ttypeseq135679* Typeinstcache;
} S1;
struct {TY135771* Procinstcache;
tscope135671* Scope;
} S2;
struct {TY135771* Usedgenerics;
tstrtable135651 Tab;
} S3;
} kindU;
NU16 Magic;
ttype135681* Typ;
tident131018* Name;
tlineinfo128308 Info;
tsym135677* Owner;
NU32 Flags;
tnode135647* Ast;
NU32 Options;
NI Position;
NI Offset;
tloc135661 Loc;
tlib135665* Annex;
tnode135647* Constraint;
};
typedef NI TY21221[8];
struct tpagedesc38457 {
tpagedesc38457* Next;
NI Key;
TY21221 Bits;
};
struct tbasechunk21241 {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct tsmallchunk21243 {
  tbasechunk21241 Sup;
tsmallchunk21243* Next;
tsmallchunk21243* Prev;
tfreecell21233* Freelist;
NI Free;
NI Acc;
NF64 Data;
};
struct tllchunk22004 {
NI Size;
NI Acc;
tllchunk22004* Next;
};
struct tbigchunk21245 {
  tbasechunk21241 Sup;
tbigchunk21245* Next;
tbigchunk21245* Prev;
NI Align;
NF64 Data;
};
struct ttrunk21214 {
ttrunk21214* Next;
NI Key;
TY21221 Bits;
};
typedef tavlnode22008* TY22014[2];
struct tavlnode22008 {
TY22014 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct tscope135671 {
NI Depthlevel;
tstrtable135651 Symbols;
tscope135671* Parent;
};
struct ttrunk132031 {
ttrunk132031* Next;
NI Key;
TY21221 Bits;
};
struct tidnodepair135695 {
tidobj131012* Key;
tnode135647* Val;
};
struct tidnodetable135699 {
NI Counter;
tidnodepairseq135697* Data;
};
typedef struct {
N_NIMCALL_PTR(tnode135647*, ClPrc) (tnode135647* n, void* ClEnv);
void* ClEnv;
} TY252237;
struct tevalcontext252212 {
  tpasscontext224003 Sup;
tsym135677* Module;
tstackframe252204* Tos;
tnode135647* Lastexception;
tnode135647* Callsite;
NU8 Mode;
NU8 Features;
tidnodetable135699 Globals;
TY252237 Gettype;
};
struct tinstantiation135667 {
tsym135677* Sym;
ttypeseq135679* Concretetypes;
TY135763* Usedby;
};
struct tident131018 {
  tidobj131012 Sup;
NimStringDesc* S;
tident131018* Next;
NI H;
};
struct trope126007 {
  TNimObject Sup;
trope126007* Left;
trope126007* Right;
NI Length;
NimStringDesc* Data;
};
struct tfreecell21233 {
tfreecell21233* Next;
NI Zerofield;
};
struct tstackframe252204 {
tsym135677* Prc;
tnodeseq135641* Slots;
tnode135647* Call;
tstackframe252204* Next;
};
struct tsymseq135649 {
  TGenericSeq Sup;
  tsym135677* data[SEQ_DECL_SIZE];
};
struct ttrunkseq132033 {
  TGenericSeq Sup;
  ttrunk132031* data[SEQ_DECL_SIZE];
};
struct tidpairseq135691 {
  TGenericSeq Sup;
  tidpair135689 data[SEQ_DECL_SIZE];
};
struct TY261100 {
  TGenericSeq Sup;
  tinstantiationpair261011 data[SEQ_DECL_SIZE];
};
struct tnodeseq135641 {
  TGenericSeq Sup;
  tnode135647* data[SEQ_DECL_SIZE];
};
struct ttypeseq135679 {
  TGenericSeq Sup;
  ttype135681* data[SEQ_DECL_SIZE];
};
struct TY135771 {
  TGenericSeq Sup;
  tinstantiation135667* data[SEQ_DECL_SIZE];
};
struct tidnodepairseq135697 {
  TGenericSeq Sup;
  tidnodepair135695 data[SEQ_DECL_SIZE];
};
struct TY135763 {
  TGenericSeq Sup;
  NI32 data[SEQ_DECL_SIZE];
};
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell38449*, usrtocell_41843)(void* usr);
static N_INLINE(void, rtladdzct_43002)(tcell38449* c);
N_NOINLINE(void, addzct_41815)(tcellseq38465* s, tcell38449* c);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP1748)(void* p, NI op);
N_NIMCALL(void, TMP1765)(void* p, NI op);
N_NIMCALL(void, TMP1766)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(void, initintset_132899)(tintset132035* Result);
N_NIMCALL(void, initlinkedlist_100030)(tlinkedlist100017* list);
N_NIMCALL(void, append_100036)(tlinkedlist100017* list, tlistentry100011* entry);
N_NIMCALL(toptionentry261003*, newoptionentry_261125)(void);
N_NIMCALL(void, TMP1771)(void* p, NI op);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(void, initstrtable_135931)(tstrtable135651* x);
N_NIMCALL(ttype135681*, newtype_135881)(NU8 kind, tsym135677* owner);
N_NIMCALL(tsym135677*, getcurrowner_261176)(void);
N_NIMCALL(ttype135681*, newtypes_261147)(NU8 kind, tcontext261019* c);
N_NIMCALL(void, globalerror_129660)(tlineinfo128308 info, NU16 msg, NimStringDesc* arg);
N_NIMCALL(NimStringDesc*, rendertree_193046)(tnode135647* n, NU8 renderflags);
static N_INLINE(NI, sonslen_136002)(tnode135647* n);
N_NIMCALL(void, illformedast_261646)(tnode135647* n);
N_NIMCALL(tnode135647*, newnodei_135920)(NU8 kind, tlineinfo128308 info);
N_NIMCALL(void, addson_136028)(tnode135647* father, tnode135647* son);
N_NIMCALL(tnode135647*, newintnode_135890)(NU8 kind, NI64 intval);
N_NIMCALL(void, rawaddson_138897)(ttype135681* father, ttype135681* son);
N_NIMCALL(ttype135681*, getsystype_218018)(NU8 kind);
N_NIMCALL(void, addsonskipintlit_218347)(ttype135681* father, ttype135681* son);
N_NIMCALL(void, internalerror_129699)(NimStringDesc* errmsg);
N_NIMCALL(TGenericSeq*, incrSeq)(TGenericSeq* seq, NI elemsize);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemsize, NI newlen);
N_NIMCALL(ttype135681*, errortype_261588)(tcontext261019* c);
N_NIMCALL(void, inclsym_261429)(tsymseq135649** sq, tsym135677* s);
N_NIMCALL(NimStringDesc*, HEX24_129777)(TY71082 x);
STRING_LITERAL(TMP2449, "compiler/semdata.nim", 20);
NIM_CONST TY71082 TMP2448 = {((NimStringDesc*) &TMP2449),
205}
;
STRING_LITERAL(TMP2681, "popOwner", 8);
NIM_CONST TY71082 TMP2715 = {((NimStringDesc*) &TMP2449),
201}
;
NIM_CONST TY71082 TMP2783 = {((NimStringDesc*) &TMP2449),
197}
;
tsymseq135649* gowners_261207;
extern TNimType NTI135649; /* TSymSeq */
extern tgcheap40416 gch_40442;
extern TNimType NTI224003; /* TPassContext */
TNimType NTI261019; /* TContext */
extern TNimType NTI135645; /* PSym */
extern TNimType NTI135673; /* PScope */
TNimType NTI261009; /* TProcCon */
extern TNimType NTI105; /* int */
TNimType NTI261007; /* PProcCon */
extern TNimType NTI132035; /* TIntSet */
extern TNimType NTI100017; /* TLinkedList */
extern TNimType NTI135693; /* TIdTable */
TNimType NTI261057; /* proc (PContext, PNode): PNode */
TNimType NTI261062; /* proc (PContext, PNode, TExprFlags): PNode */
TNimType NTI261070; /* proc (PContext, PNode, TExprFlags): PNode */
TNimType NTI261078; /* proc (PContext, PNode): PNode */
TNimType NTI261083; /* proc (PContext, PNode, PNode, TSymKinds): PNode */
TNimType NTI261090; /* proc (PContext, PNode, PType): PType */
extern TNimType NTI135651; /* TStrTable */
extern TNimType NTI252214; /* PEvalContext */
TNimType NTI261011; /* TInstantiationPair */
extern TNimType NTI135669; /* PInstantiation */
TNimType NTI261100; /* seq[TInstantiationPair] */
TNimType NTI261017; /* PContext */
extern TNimType NTI100011; /* TListEntry */
TNimType NTI261003; /* TOptionEntry */
extern TNimType NTI105010; /* TOptions */
extern TNimType NTI135003; /* TCallingConvention */
extern TNimType NTI135675; /* PLib */
extern TNimType NTI128304; /* TNoteKinds */
extern TNimType NTI135639; /* PNode */
TNimType NTI261005; /* POptionEntry */
extern NU32 goptions_105106;
extern NU64 gnotes_128867;
extern TNimType NTI135665; /* TLib */

static N_INLINE(tcell38449*, usrtocell_41843)(void* usr) {
	tcell38449* result;
	result = 0;
	result = ((tcell38449*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell38449))))));
	return result;
}

static N_INLINE(void, rtladdzct_43002)(tcell38449* c) {
	addzct_41815(&gch_40442.Zct, c);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell38449* c;
	c = usrtocell_41843(p);
	{
		(*c).Refcount -= 8;
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		rtladdzct_43002(c);
	}
	LA3: ;
}
N_NIMCALL(void, TMP1748)(void* p, NI op) {
	tproccon261009* a;
	a = (tproccon261009*)p;
	nimGCvisit((void*)(*a).Owner, op);
	nimGCvisit((void*)(*a).Resultsym, op);
	nimGCvisit((void*)(*a).Next, op);
}
N_NIMCALL(void, TMP1765)(void* p, NI op) {
	TY261100* a;
	NI LOC1;
	a = (TY261100*)p;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Genericsym, op);
	nimGCvisit((void*)a->data[LOC1].Inst, op);
	}
}
N_NIMCALL(void, TMP1766)(void* p, NI op) {
	tcontext261019* a;
	a = (tcontext261019*)p;
	nimGCvisit((void*)(*a).Module, op);
	nimGCvisit((void*)(*a).Currentscope, op);
	nimGCvisit((void*)(*a).Importtable, op);
	nimGCvisit((void*)(*a).Toplevelscope, op);
	nimGCvisit((void*)(*a).P, op);
	nimGCvisit((void*)(*a).Friendmodule, op);
	nimGCvisit((void*)(*a).Threadentries, op);
	nimGCvisit((void*)(*a).Ambiguoussymbols.Head, op);
	nimGCvisit((void*)(*a).Ambiguoussymbols.Data, op);
	nimGCvisit((void*)(*a).Converters, op);
	nimGCvisit((void*)(*a).Patterns, op);
	nimGCvisit((void*)(*a).Optionstack.Head, op);
	nimGCvisit((void*)(*a).Optionstack.Tail, op);
	nimGCvisit((void*)(*a).Symmapping.Data, op);
	nimGCvisit((void*)(*a).Libs.Head, op);
	nimGCvisit((void*)(*a).Libs.Tail, op);
	nimGCvisit((void*)(*a).Includedfiles.Head, op);
	nimGCvisit((void*)(*a).Includedfiles.Data, op);
	nimGCvisit((void*)(*a).Userpragmas.Data, op);
	nimGCvisit((void*)(*a).Evalcontext, op);
	nimGCvisit((void*)(*a).Unknownidents.Head, op);
	nimGCvisit((void*)(*a).Unknownidents.Data, op);
	nimGCvisit((void*)(*a).Generics, op);
}
N_NIMCALL(void, TMP1771)(void* p, NI op) {
	toptionentry261003* a;
	a = (toptionentry261003*)p;
	nimGCvisit((void*)(*a).Sup.Prev, op);
	nimGCvisit((void*)(*a).Sup.Next, op);
	nimGCvisit((void*)(*a).Dynlib, op);
	nimGCvisit((void*)(*a).Otherpragmas, op);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		tcell38449* c;
		if (!!((src == NIM_NIL))) goto LA3;
		c = usrtocell_41843(src);
		(*c).Refcount += 8;
	}
	LA3: ;
	{
		tcell38449* c;
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		c = usrtocell_41843((*dest));
		{
			(*c).Refcount -= 8;
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			rtladdzct_43002(c);
		}
		LA11: ;
	}
	LA7: ;
	(*dest) = src;
}

N_NIMCALL(toptionentry261003*, newoptionentry_261125)(void) {
	toptionentry261003* result;
	result = 0;
	result = (toptionentry261003*) newObj((&NTI261005), sizeof(toptionentry261003));
	(*result).Sup.Sup.m_type = (&NTI261003);
	(*result).Options = goptions_105106;
	(*result).Defaultcc = ((NU8) 0);
	asgnRefNoCycle((void**) &(*result).Dynlib, NIM_NIL);
	(*result).Notes = gnotes_128867;
	return result;
}

N_NIMCALL(tcontext261019*, newcontext_261117)(tsym135677* module) {
	tcontext261019* result;
	toptionentry261003* LOC1;
	result = 0;
	result = (tcontext261019*) newObj((&NTI261017), sizeof(tcontext261019));
	(*result).Sup.Sup.m_type = (&NTI261019);
	initintset_132899(&(*result).Ambiguoussymbols);
	initlinkedlist_100030(&(*result).Optionstack);
	initlinkedlist_100030(&(*result).Libs);
	LOC1 = 0;
	LOC1 = newoptionentry_261125();
	append_100036(&(*result).Optionstack, &LOC1->Sup);
	asgnRefNoCycle((void**) &(*result).Module, module);
	asgnRefNoCycle((void**) &(*result).Friendmodule, module);
	if ((*result).Threadentries) nimGCunrefNoCycle((*result).Threadentries);
	(*result).Threadentries = (tsymseq135649*) newSeqRC1((&NTI135649), 0);
	if ((*result).Converters) nimGCunrefNoCycle((*result).Converters);
	(*result).Converters = (tsymseq135649*) newSeqRC1((&NTI135649), 0);
	if ((*result).Patterns) nimGCunrefNoCycle((*result).Patterns);
	(*result).Patterns = (tsymseq135649*) newSeqRC1((&NTI135649), 0);
	initintset_132899(&(*result).Includedfiles);
	initstrtable_135931(&(*result).Userpragmas);
	if ((*result).Generics) nimGCunrefNoCycle((*result).Generics);
	(*result).Generics = (TY261100*) newSeqRC1((&NTI261100), 0);
	initintset_132899(&(*result).Unknownidents);
	return result;
}

N_NIMCALL(tsym135677*, getcurrowner_261176)(void) {
	tsym135677* result;
	result = 0;
	result = gowners_261207->data[(gowners_261207->Sup.len-1)];
	return result;
}

N_NIMCALL(ttype135681*, newtypes_261147)(NU8 kind, tcontext261019* c) {
	ttype135681* result;
	tsym135677* LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = getcurrowner_261176();
	result = newtype_135881(kind, LOC1);
	return result;
}

N_NIMCALL(ttype135681*, errortype_261588)(tcontext261019* c) {
	ttype135681* result;
	result = 0;
	result = newtypes_261147(((NU8) 50), c);
	return result;
}

N_NIMCALL(void, illformedast_261646)(tnode135647* n) {
	NimStringDesc* LOC1;
	LOC1 = 0;
	LOC1 = rendertree_193046(n, 4);
	globalerror_129660((*n).Info, ((NU16) 1), LOC1);
}

static N_INLINE(NI, sonslen_136002)(tnode135647* n) {
	NI result;
	result = 0;
	{
		if (!(*n).kindU.S6.Sons == 0) goto LA3;
		result = 0;
	}
	goto LA1;
	LA3: ;
	{
		result = (*n).kindU.S6.Sons->Sup.len;
	}
	LA1: ;
	return result;
}

N_NIMCALL(void, checksonslen_261652)(tnode135647* n, NI length) {
	{
		NI LOC3;
		LOC3 = sonslen_136002(n);
		if (!!((LOC3 == length))) goto LA4;
		illformedast_261646(n);
	}
	LA4: ;
}

N_NIMCALL(ttype135681*, makerangetype_261608)(tcontext261019* c, NI64 first, NI64 last, tlineinfo128308 info) {
	ttype135681* result;
	tnode135647* n;
	tnode135647* LOC1;
	tnode135647* LOC2;
	ttype135681* LOC3;
	result = 0;
	n = newnodei_135920(((NU8) 44), info);
	LOC1 = 0;
	LOC1 = newintnode_135890(((NU8) 6), first);
	addson_136028(n, LOC1);
	LOC2 = 0;
	LOC2 = newintnode_135890(((NU8) 6), last);
	addson_136028(n, LOC2);
	result = newtypes_261147(((NU8) 20), c);
	asgnRefNoCycle((void**) &(*result).N, n);
	LOC3 = 0;
	LOC3 = getsystype_218018(((NU8) 31));
	rawaddson_138897(result, LOC3);
	return result;
}

N_NIMCALL(ttype135681*, maketypedesc_261558)(tcontext261019* c, ttype135681* typ) {
	ttype135681* result;
	result = 0;
	result = newtypes_261147(((NU8) 8), c);
	{
		NimStringDesc* LOC5;
		if (!(typ == NIM_NIL)) goto LA3;
		LOC5 = 0;
		LOC5 = HEX24_129777(TMP2448);
		internalerror_129699(LOC5);
	}
	LA3: ;
	addsonskipintlit_218347(result, typ);
	return result;
}

N_NIMCALL(void, checkminsonslen_261658)(tnode135647* n, NI length) {
	{
		NI LOC3;
		LOC3 = sonslen_136002(n);
		if (!(LOC3 < length)) goto LA4;
		illformedast_261646(n);
	}
	LA4: ;
}

N_NIMCALL(void, pushowner_261179)(tsym135677* owner) {
	gowners_261207 = (tsymseq135649*) incrSeq(&(gowners_261207)->Sup, sizeof(tsym135677*));
	asgnRefNoCycle((void**) &gowners_261207->data[gowners_261207->Sup.len-1], owner);
}

N_NIMCALL(toptionentry261003*, lastoptionentry_261121)(tcontext261019* c) {
	toptionentry261003* result;
	result = 0;
	result = ((toptionentry261003*) ((*c).Optionstack.Tail));
	return result;
}

N_NIMCALL(void, makeinstpair_261104)(tsym135677* s, tinstantiation135667* inst, tinstantiationpair261011* Result) {
	unsureAsgnRef((void**) &(*Result).Genericsym, s);
	unsureAsgnRef((void**) &(*Result).Inst, inst);
}

N_NIMCALL(tlib135665*, newlib_261128)(NU8 kind) {
	tlib135665* result;
	result = 0;
	result = (tlib135665*) newObj((&NTI135675), sizeof(tlib135665));
	(*result).Sup.Sup.m_type = (&NTI135665);
	(*result).Kind = kind;
	return result;
}

N_NIMCALL(void, addtolib_261132)(tlib135665* lib, tsym135677* sym) {
	asgnRefNoCycle((void**) &(*sym).Annex, lib);
}

N_NIMCALL(void, popowner_261183)(void) {
	NI length;
	length = gowners_261207->Sup.len;
	{
		if (!(0 < length)) goto LA3;
		gowners_261207 = (tsymseq135649*) setLengthSeq(&(gowners_261207)->Sup, sizeof(tsym135677*), (NI64)(length - 1));
	}
	goto LA1;
	LA3: ;
	{
		internalerror_129699(((NimStringDesc*) &TMP2681));
	}
	LA1: ;
}

N_NIMCALL(tnode135647*, errornode_261594)(tcontext261019* c, tnode135647* n) {
	tnode135647* result;
	result = 0;
	result = newnodei_135920(((NU8) 1), (*n).Info);
	asgnRefNoCycle((void**) &(*result).Typ, errortype_261588(c));
	return result;
}

N_NIMCALL(ttype135681*, makevartype_261142)(tcontext261019* c, ttype135681* basetype) {
	ttype135681* result;
	result = 0;
	result = newtypes_261147(((NU8) 23), c);
	{
		NimStringDesc* LOC5;
		if (!(basetype == NIM_NIL)) goto LA3;
		LOC5 = 0;
		LOC5 = HEX24_129777(TMP2715);
		internalerror_129699(LOC5);
	}
	LA3: ;
	addsonskipintlit_218347(result, basetype);
	return result;
}

N_NIMCALL(ttype135681*, makeptrtype_261137)(tcontext261019* c, ttype135681* basetype) {
	ttype135681* result;
	result = 0;
	result = newtypes_261147(((NU8) 21), c);
	{
		NimStringDesc* LOC5;
		if (!(basetype == NIM_NIL)) goto LA3;
		LOC5 = 0;
		LOC5 = HEX24_129777(TMP2783);
		internalerror_129699(LOC5);
	}
	LA3: ;
	addsonskipintlit_218347(result, basetype);
	return result;
}

N_NIMCALL(void, inclsym_261429)(tsymseq135649** sq, tsym135677* s) {
	NI l;
	NI i_261451;
	NI HEX3Atmp_261464;
	NI res_261466;
	l = (*sq)->Sup.len;
	i_261451 = 0;
	HEX3Atmp_261464 = 0;
	HEX3Atmp_261464 = (NI64)(l - 1);
	res_261466 = 0;
	while (1) {
		if (!(res_261466 <= HEX3Atmp_261464)) goto LA1;
		i_261451 = res_261466;
		{
			if (!((*(*sq)->data[i_261451]).Sup.Id == (*s).Sup.Id)) goto LA4;
			goto BeforeRet;
		}
		LA4: ;
		res_261466 += 1;
	} LA1: ;
	(*sq) = (tsymseq135649*) setLengthSeq(&((*sq))->Sup, sizeof(tsym135677*), (NI64)(l + 1));
	asgnRefNoCycle((void**) &(*sq)->data[l], s);
	BeforeRet: ;
}

N_NIMCALL(void, addconverter_261471)(tcontext261019* c, tsym135677* conv) {
	inclsym_261429(&(*c).Converters, conv);
}

N_NIMCALL(void, addpattern_261478)(tcontext261019* c, tsym135677* p) {
	inclsym_261429(&(*c).Patterns, p);
}
N_NOINLINE(void, semdataInit)(void) {
	if (gowners_261207) nimGCunrefNoCycle(gowners_261207);
	gowners_261207 = (tsymseq135649*) newSeqRC1((&NTI135649), 0);
}

N_NOINLINE(void, semdataDatInit)(void) {
static TNimNode* TMP1746[30];
static TNimNode* TMP1747[6];
static TNimNode* TMP1764[2];
static TNimNode* TMP1767[5];
static TNimNode TMP829[47];
NTI261019.size = sizeof(tcontext261019);
NTI261019.kind = 17;
NTI261019.base = (&NTI224003);
TMP1746[0] = &TMP829[1];
TMP829[1].kind = 1;
TMP829[1].offset = offsetof(tcontext261019, Module);
TMP829[1].typ = (&NTI135645);
TMP829[1].name = "module";
TMP1746[1] = &TMP829[2];
TMP829[2].kind = 1;
TMP829[2].offset = offsetof(tcontext261019, Currentscope);
TMP829[2].typ = (&NTI135673);
TMP829[2].name = "currentScope";
TMP1746[2] = &TMP829[3];
TMP829[3].kind = 1;
TMP829[3].offset = offsetof(tcontext261019, Importtable);
TMP829[3].typ = (&NTI135673);
TMP829[3].name = "importTable";
TMP1746[3] = &TMP829[4];
TMP829[4].kind = 1;
TMP829[4].offset = offsetof(tcontext261019, Toplevelscope);
TMP829[4].typ = (&NTI135673);
TMP829[4].name = "topLevelScope";
TMP1746[4] = &TMP829[5];
NTI261009.size = sizeof(tproccon261009);
NTI261009.kind = 18;
NTI261009.base = 0;
TMP1747[0] = &TMP829[7];
TMP829[7].kind = 1;
TMP829[7].offset = offsetof(tproccon261009, Owner);
TMP829[7].typ = (&NTI135645);
TMP829[7].name = "owner";
TMP1747[1] = &TMP829[8];
TMP829[8].kind = 1;
TMP829[8].offset = offsetof(tproccon261009, Resultsym);
TMP829[8].typ = (&NTI135645);
TMP829[8].name = "resultSym";
TMP1747[2] = &TMP829[9];
TMP829[9].kind = 1;
TMP829[9].offset = offsetof(tproccon261009, Nestedloopcounter);
TMP829[9].typ = (&NTI105);
TMP829[9].name = "nestedLoopCounter";
TMP1747[3] = &TMP829[10];
TMP829[10].kind = 1;
TMP829[10].offset = offsetof(tproccon261009, Nestedblockcounter);
TMP829[10].typ = (&NTI105);
TMP829[10].name = "nestedBlockCounter";
TMP1747[4] = &TMP829[11];
TMP829[11].kind = 1;
TMP829[11].offset = offsetof(tproccon261009, Intrystmt);
TMP829[11].typ = (&NTI105);
TMP829[11].name = "InTryStmt";
TMP1747[5] = &TMP829[12];
TMP829[12].kind = 1;
TMP829[12].offset = offsetof(tproccon261009, Next);
TMP829[12].typ = (&NTI261007);
TMP829[12].name = "next";
TMP829[6].len = 6; TMP829[6].kind = 2; TMP829[6].sons = &TMP1747[0];
NTI261009.node = &TMP829[6];
NTI261007.size = sizeof(tproccon261009*);
NTI261007.kind = 22;
NTI261007.base = (&NTI261009);
NTI261007.marker = TMP1748;
TMP829[5].kind = 1;
TMP829[5].offset = offsetof(tcontext261019, P);
TMP829[5].typ = (&NTI261007);
TMP829[5].name = "p";
TMP1746[5] = &TMP829[13];
TMP829[13].kind = 1;
TMP829[13].offset = offsetof(tcontext261019, Friendmodule);
TMP829[13].typ = (&NTI135645);
TMP829[13].name = "friendModule";
TMP1746[6] = &TMP829[14];
TMP829[14].kind = 1;
TMP829[14].offset = offsetof(tcontext261019, Instcounter);
TMP829[14].typ = (&NTI105);
TMP829[14].name = "InstCounter";
TMP1746[7] = &TMP829[15];
TMP829[15].kind = 1;
TMP829[15].offset = offsetof(tcontext261019, Threadentries);
TMP829[15].typ = (&NTI135649);
TMP829[15].name = "threadEntries";
TMP1746[8] = &TMP829[16];
TMP829[16].kind = 1;
TMP829[16].offset = offsetof(tcontext261019, Ambiguoussymbols);
TMP829[16].typ = (&NTI132035);
TMP829[16].name = "AmbiguousSymbols";
TMP1746[9] = &TMP829[17];
TMP829[17].kind = 1;
TMP829[17].offset = offsetof(tcontext261019, Ingenericcontext);
TMP829[17].typ = (&NTI105);
TMP829[17].name = "InGenericContext";
TMP1746[10] = &TMP829[18];
TMP829[18].kind = 1;
TMP829[18].offset = offsetof(tcontext261019, Inunrolledcontext);
TMP829[18].typ = (&NTI105);
TMP829[18].name = "InUnrolledContext";
TMP1746[11] = &TMP829[19];
TMP829[19].kind = 1;
TMP829[19].offset = offsetof(tcontext261019, Incompilescontext);
TMP829[19].typ = (&NTI105);
TMP829[19].name = "InCompilesContext";
TMP1746[12] = &TMP829[20];
TMP829[20].kind = 1;
TMP829[20].offset = offsetof(tcontext261019, Ingenericinst);
TMP829[20].typ = (&NTI105);
TMP829[20].name = "InGenericInst";
TMP1746[13] = &TMP829[21];
TMP829[21].kind = 1;
TMP829[21].offset = offsetof(tcontext261019, Converters);
TMP829[21].typ = (&NTI135649);
TMP829[21].name = "converters";
TMP1746[14] = &TMP829[22];
TMP829[22].kind = 1;
TMP829[22].offset = offsetof(tcontext261019, Patterns);
TMP829[22].typ = (&NTI135649);
TMP829[22].name = "patterns";
TMP1746[15] = &TMP829[23];
TMP829[23].kind = 1;
TMP829[23].offset = offsetof(tcontext261019, Optionstack);
TMP829[23].typ = (&NTI100017);
TMP829[23].name = "optionStack";
TMP1746[16] = &TMP829[24];
TMP829[24].kind = 1;
TMP829[24].offset = offsetof(tcontext261019, Symmapping);
TMP829[24].typ = (&NTI135693);
TMP829[24].name = "symMapping";
TMP1746[17] = &TMP829[25];
TMP829[25].kind = 1;
TMP829[25].offset = offsetof(tcontext261019, Libs);
TMP829[25].typ = (&NTI100017);
TMP829[25].name = "libs";
TMP1746[18] = &TMP829[26];
NTI261057.size = sizeof(TY261057);
NTI261057.kind = 25;
NTI261057.base = 0;
NTI261057.flags = 3;
TMP829[26].kind = 1;
TMP829[26].offset = offsetof(tcontext261019, Semconstexpr);
TMP829[26].typ = (&NTI261057);
TMP829[26].name = "semConstExpr";
TMP1746[19] = &TMP829[27];
NTI261062.size = sizeof(TY261062);
NTI261062.kind = 25;
NTI261062.base = 0;
NTI261062.flags = 3;
TMP829[27].kind = 1;
TMP829[27].offset = offsetof(tcontext261019, Semexpr);
TMP829[27].typ = (&NTI261062);
TMP829[27].name = "semExpr";
TMP1746[20] = &TMP829[28];
NTI261070.size = sizeof(TY261070);
NTI261070.kind = 25;
NTI261070.base = 0;
NTI261070.flags = 3;
TMP829[28].kind = 1;
TMP829[28].offset = offsetof(tcontext261019, Semoperand);
TMP829[28].typ = (&NTI261070);
TMP829[28].name = "semOperand";
TMP1746[21] = &TMP829[29];
NTI261078.size = sizeof(TY261078);
NTI261078.kind = 25;
NTI261078.base = 0;
NTI261078.flags = 3;
TMP829[29].kind = 1;
TMP829[29].offset = offsetof(tcontext261019, Semconstboolexpr);
TMP829[29].typ = (&NTI261078);
TMP829[29].name = "semConstBoolExpr";
TMP1746[22] = &TMP829[30];
NTI261083.size = sizeof(TY261083);
NTI261083.kind = 25;
NTI261083.base = 0;
NTI261083.flags = 3;
TMP829[30].kind = 1;
TMP829[30].offset = offsetof(tcontext261019, Semoverloadedcall);
TMP829[30].typ = (&NTI261083);
TMP829[30].name = "semOverloadedCall";
TMP1746[23] = &TMP829[31];
NTI261090.size = sizeof(TY261090);
NTI261090.kind = 25;
NTI261090.base = 0;
NTI261090.flags = 3;
TMP829[31].kind = 1;
TMP829[31].offset = offsetof(tcontext261019, Semtypenode);
TMP829[31].typ = (&NTI261090);
TMP829[31].name = "semTypeNode";
TMP1746[24] = &TMP829[32];
TMP829[32].kind = 1;
TMP829[32].offset = offsetof(tcontext261019, Includedfiles);
TMP829[32].typ = (&NTI132035);
TMP829[32].name = "includedFiles";
TMP1746[25] = &TMP829[33];
TMP829[33].kind = 1;
TMP829[33].offset = offsetof(tcontext261019, Userpragmas);
TMP829[33].typ = (&NTI135651);
TMP829[33].name = "userPragmas";
TMP1746[26] = &TMP829[34];
TMP829[34].kind = 1;
TMP829[34].offset = offsetof(tcontext261019, Evalcontext);
TMP829[34].typ = (&NTI252214);
TMP829[34].name = "evalContext";
TMP1746[27] = &TMP829[35];
TMP829[35].kind = 1;
TMP829[35].offset = offsetof(tcontext261019, Unknownidents);
TMP829[35].typ = (&NTI132035);
TMP829[35].name = "UnknownIdents";
TMP1746[28] = &TMP829[36];
NTI261011.size = sizeof(tinstantiationpair261011);
NTI261011.kind = 18;
NTI261011.base = 0;
NTI261011.flags = 2;
TMP1764[0] = &TMP829[38];
TMP829[38].kind = 1;
TMP829[38].offset = offsetof(tinstantiationpair261011, Genericsym);
TMP829[38].typ = (&NTI135645);
TMP829[38].name = "genericSym";
TMP1764[1] = &TMP829[39];
TMP829[39].kind = 1;
TMP829[39].offset = offsetof(tinstantiationpair261011, Inst);
TMP829[39].typ = (&NTI135669);
TMP829[39].name = "inst";
TMP829[37].len = 2; TMP829[37].kind = 2; TMP829[37].sons = &TMP1764[0];
NTI261011.node = &TMP829[37];
NTI261100.size = sizeof(TY261100*);
NTI261100.kind = 24;
NTI261100.base = (&NTI261011);
NTI261100.flags = 2;
NTI261100.marker = TMP1765;
TMP829[36].kind = 1;
TMP829[36].offset = offsetof(tcontext261019, Generics);
TMP829[36].typ = (&NTI261100);
TMP829[36].name = "generics";
TMP1746[29] = &TMP829[40];
TMP829[40].kind = 1;
TMP829[40].offset = offsetof(tcontext261019, Lastgenericidx);
TMP829[40].typ = (&NTI105);
TMP829[40].name = "lastGenericIdx";
TMP829[0].len = 30; TMP829[0].kind = 2; TMP829[0].sons = &TMP1746[0];
NTI261019.node = &TMP829[0];
NTI261017.size = sizeof(tcontext261019*);
NTI261017.kind = 22;
NTI261017.base = (&NTI261019);
NTI261017.marker = TMP1766;
NTI261003.size = sizeof(toptionentry261003);
NTI261003.kind = 17;
NTI261003.base = (&NTI100011);
NTI261003.flags = 2;
TMP1767[0] = &TMP829[42];
TMP829[42].kind = 1;
TMP829[42].offset = offsetof(toptionentry261003, Options);
TMP829[42].typ = (&NTI105010);
TMP829[42].name = "options";
TMP1767[1] = &TMP829[43];
TMP829[43].kind = 1;
TMP829[43].offset = offsetof(toptionentry261003, Defaultcc);
TMP829[43].typ = (&NTI135003);
TMP829[43].name = "defaultCC";
TMP1767[2] = &TMP829[44];
TMP829[44].kind = 1;
TMP829[44].offset = offsetof(toptionentry261003, Dynlib);
TMP829[44].typ = (&NTI135675);
TMP829[44].name = "dynlib";
TMP1767[3] = &TMP829[45];
TMP829[45].kind = 1;
TMP829[45].offset = offsetof(toptionentry261003, Notes);
TMP829[45].typ = (&NTI128304);
TMP829[45].name = "notes";
TMP1767[4] = &TMP829[46];
TMP829[46].kind = 1;
TMP829[46].offset = offsetof(toptionentry261003, Otherpragmas);
TMP829[46].typ = (&NTI135639);
TMP829[46].name = "otherPragmas";
TMP829[41].len = 5; TMP829[41].kind = 2; TMP829[41].sons = &TMP1767[0];
NTI261003.node = &TMP829[41];
NTI261005.size = sizeof(toptionentry261003*);
NTI261005.kind = 22;
NTI261005.base = (&NTI261003);
NTI261005.flags = 2;
NTI261005.marker = TMP1771;
}

