/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/usr/src/extras/Nimrod/lib -o compiler/nimcache/service.o compiler/nimcache/service.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>

#include <stdio.h>

#include <stdlib.h>

#include <sys/socket.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tcell38449 tcell38449;
typedef struct TNimType TNimType;
typedef struct tcellseq38465 tcellseq38465;
typedef struct tgcheap40416 tgcheap40416;
typedef struct tcellset38461 tcellset38461;
typedef struct tpagedesc38457 tpagedesc38457;
typedef struct tmemregion22010 tmemregion22010;
typedef struct tsmallchunk21243 tsmallchunk21243;
typedef struct tllchunk22004 tllchunk22004;
typedef struct tbigchunk21245 tbigchunk21245;
typedef struct tintset21218 tintset21218;
typedef struct ttrunk21214 ttrunk21214;
typedef struct tavlnode22008 tavlnode22008;
typedef struct tgcstat40414 tgcstat40414;
typedef struct toptparser422606 toptparser422606;
typedef struct TNimObject TNimObject;
typedef struct TNimNode TNimNode;
typedef struct tlineinfo128308 tlineinfo128308;
typedef struct TY95234 TY95234;
typedef struct tsocketimpl110806 tsocketimpl110806;
typedef struct tbasechunk21241 tbasechunk21241;
typedef struct tfreecell21233 tfreecell21233;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
struct tcell38449 {
NI Refcount;
TNimType* Typ;
};
struct tcellseq38465 {
NI Len;
NI Cap;
tcell38449** D;
};
struct tcellset38461 {
NI Counter;
NI Max;
tpagedesc38457* Head;
tpagedesc38457** Data;
};
typedef tsmallchunk21243* TY22022[512];
typedef ttrunk21214* ttrunkbuckets21216[256];
struct tintset21218 {
ttrunkbuckets21216 Data;
};
struct tmemregion22010 {
NI Minlargeobj;
NI Maxlargeobj;
TY22022 Freesmallchunks;
tllchunk22004* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk21245* Freechunkslist;
tintset21218 Chunkstarts;
tavlnode22008* Root;
tavlnode22008* Deleted;
tavlnode22008* Last;
tavlnode22008* Freeavlnodes;
};
struct tgcstat40414 {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct tgcheap40416 {
void* Stackbottom;
NI Cyclethreshold;
tcellseq38465 Zct;
tcellseq38465 Decstack;
tcellset38461 Cycleroots;
tcellseq38465 Tempstack;
NI Recgclock;
tmemregion22010 Region;
tgcstat40414 Stat;
};
typedef N_NIMCALL_PTR(void, TY891) (void* p, NI op);
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY891 marker;
};
struct TNimObject {
TNimType* m_type;
};
struct toptparser422606 {
  TNimObject Sup;
NimStringDesc* Cmd;
NI Pos;
NIM_BOOL Inshortstate;
NU8 Kind;
NimStringDesc* Key;
NimStringDesc* Val;
};
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tlineinfo128308 {
NI16 Line;
NI16 Col;
NI32 Fileindex;
};
typedef NimStringDesc* TY424073[1];
typedef N_NIMCALL_PTR(void, TY424079) (void);
typedef NIM_CHAR TY110829[4001];
struct tsocketimpl110806 {
int Fd;
NIM_BOOL Isbuffered;
union {
struct {TY110829 Buffer;
NI Currpos;
NI Buflen;
} S1;
} isbufferedU;
NIM_BOOL Nonblocking;
};
typedef NI TY21221[8];
struct tpagedesc38457 {
tpagedesc38457* Next;
NI Key;
TY21221 Bits;
};
struct tbasechunk21241 {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct tsmallchunk21243 {
  tbasechunk21241 Sup;
tsmallchunk21243* Next;
tsmallchunk21243* Prev;
tfreecell21233* Freelist;
NI Free;
NI Acc;
NF64 Data;
};
struct tllchunk22004 {
NI Size;
NI Acc;
tllchunk22004* Next;
};
struct tbigchunk21245 {
  tbasechunk21241 Sup;
tbigchunk21245* Next;
tbigchunk21245* Prev;
NI Align;
NF64 Data;
};
struct ttrunk21214 {
ttrunk21214* Next;
NI Key;
TY21221 Bits;
};
typedef tavlnode22008* TY22014[2];
struct tavlnode22008 {
TY22014 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct tfreecell21233 {
tfreecell21233* Next;
NI Zerofield;
};
struct TY95234 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell38449*, usrtocell_41843)(void* usr);
static N_INLINE(void, rtladdzct_43002)(tcell38449* c);
N_NOINLINE(void, addzct_41815)(tcellseq38465* s, tcell38449* c);
N_NIMCALL(void, initoptparser_422618)(NimStringDesc* cmdline, toptparser422606* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, nponext)(toptparser422606* p);
N_NIMCALL(NI, nsuFindChar)(NimStringDesc* s, NIM_CHAR sub, NI start);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_63424, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI start);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI first);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(void, processswitch_159016)(NimStringDesc* switch_159018, NimStringDesc* arg, NU8 pass, tlineinfo128308 info);
N_NIMCALL(TGenericSeq*, incrSeq)(TGenericSeq* seq, NI elemsize);
N_NIMCALL(NimStringDesc*, nosunixToNativePath)(NimStringDesc* path);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, npocmdLineRest)(toptparser422606* p);
N_NIMCALL(void, rawmessage_129448)(NU16 msg, NimStringDesc** args, NI argslen0);
N_NIMCALL(NimStringDesc*, getconfigvar_105291)(NimStringDesc* key);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NimStringDesc*, readline_9083)(FILE* f);
N_NIMCALL(void, processcmdline_424007)(NU8 pass, NimStringDesc* cmd);
N_NIMCALL(tsocketimpl110806*, socket_111402)(NU8 domain, NU8 typ, NU8 protocol, NIM_BOOL buffered);
N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s);
N_NIMCALL(void, bindaddr_112552)(tsocketimpl110806* socket, NI16 port, NimStringDesc* address);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(void, listen_112405)(tsocketimpl110806* socket, int backlog);
N_NIMCALL(void*, newObjRC1)(TNimType* typ, NI size);
N_NIMCALL(void, accept_114201)(tsocketimpl110806* server, tsocketimpl110806** client);
N_NIMCALL(void, readline_118831)(tsocketimpl110806* socket, NimStringDesc** line, NI timeout);
N_NIMCALL(void, send_120404)(tsocketimpl110806* socket, NimStringDesc* data);
N_NIMCALL(void, close_114264)(tsocketimpl110806* socket);
STRING_LITERAL(TMP932, "", 0);
STRING_LITERAL(TMP4163, "server.type", 11);
STRING_LITERAL(TMP4164, "stdin", 5);
STRING_LITERAL(TMP4165, "tcp", 3);
STRING_LITERAL(TMP4167, "quit", 4);
STRING_LITERAL(TMP4171, "server.port", 11);
STRING_LITERAL(TMP4172, "server.address", 14);
STRING_LITERAL(TMP4180, "\015\012", 2);
STRING_LITERAL(TMP4181, "Invalid server.type:", 20);
NimStringDesc* curcaascmd_424003;
extern tgcheap40416 gch_40442;
NimStringDesc* lastcaascmd_424004;
NimStringDesc* arguments_424005;
extern TNimType NTI422606; /* TOptParser */
extern tlineinfo128308 gcmdlineinfo_128801;
extern NimStringDesc* command_105197;
extern TY95234* commandargs_105218;
extern NimStringDesc* gprojectname_105191;
extern NU32 gglobaloptions_105108;
extern NI32 gdirtybufferidx_105123;
extern NI32 gdirtyoriginalidx_105124;
extern NI gerrorcounter_128868;
extern tsocketimpl110806* stdoutsocket_128873;
extern TNimType NTI110808; /* TSocket */

static N_INLINE(tcell38449*, usrtocell_41843)(void* usr) {
	tcell38449* result;
	result = 0;
	result = ((tcell38449*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell38449))))));
	return result;
}

static N_INLINE(void, rtladdzct_43002)(tcell38449* c) {
	addzct_41815(&gch_40442.Zct, c);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell38449* c;
	c = usrtocell_41843(p);
	{
		(*c).Refcount -= 8;
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		rtladdzct_43002(c);
	}
	LA3: ;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) (&(*dest).data[((*dest).Sup.len)- 0])), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI64)((*dest).Sup.len + 1))- 0] = 0;
	(*dest).Sup.len += 1;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		tcell38449* c;
		if (!!((src == NIM_NIL))) goto LA3;
		c = usrtocell_41843(src);
		(*c).Refcount += 8;
	}
	LA3: ;
	{
		tcell38449* c;
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		c = usrtocell_41843((*dest));
		{
			(*c).Refcount -= 8;
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			rtladdzct_43002(c);
		}
		LA11: ;
	}
	LA7: ;
	(*dest) = src;
}

N_NIMCALL(void, processcmdline_424007)(NU8 pass, NimStringDesc* cmd) {
	toptparser422606 p;
	NI argscount;
	chckNil((void*)&p);
	memset((void*)&p, 0, sizeof(p));
	p.Sup.m_type = (&NTI422606);
	initoptparser_422618(cmd, &p);
	argscount = 0;
	while (1) {
		nponext(&p);
		switch (p.Kind) {
		case ((NU8) 0):
		{
			goto LA1;
		}
		break;
		case ((NU8) 2):
		case ((NU8) 3):
		{
			NI bracketle;
			bracketle = nsuFindChar(p.Key, 91, 0);
			{
				NimStringDesc* key;
				NimStringDesc* val;
				NimStringDesc* LOC8;
				NimStringDesc* LOC9;
				if (!(0 <= bracketle)) goto LA6;
				key = copyStrLast(p.Key, 0, (NI64)(bracketle - 1));
				LOC8 = 0;
				LOC9 = 0;
				LOC9 = copyStr(p.Key, (NI64)(bracketle + 1));
				LOC8 = rawNewString(LOC9->Sup.len + p.Val->Sup.len + 1);
appendString(LOC8, LOC9);
appendChar(LOC8, 58);
appendString(LOC8, p.Val);
				val = LOC8;
				processswitch_159016(key, val, pass, gcmdlineinfo_128801);
			}
			goto LA4;
			LA6: ;
			{
				processswitch_159016(p.Key, p.Val, pass, gcmdlineinfo_128801);
			}
			LA4: ;
		}
		break;
		case ((NU8) 1):
		{
			{
				NimStringDesc* LOC16;
				if (!(argscount == 0)) goto LA14;
				LOC16 = 0;
				LOC16 = command_105197; command_105197 = copyStringRC1(p.Key);
				if (LOC16) nimGCunrefNoCycle(LOC16);
			}
			goto LA12;
			LA14: ;
			{
				{
					NimStringDesc* LOC22;
					if (!(pass == ((NU8) 0))) goto LA20;
					commandargs_105218 = (TY95234*) incrSeq(&(commandargs_105218)->Sup, sizeof(NimStringDesc*));
					LOC22 = 0;
					LOC22 = commandargs_105218->data[commandargs_105218->Sup.len-1]; commandargs_105218->data[commandargs_105218->Sup.len-1] = copyStringRC1(p.Key);
					if (LOC22) nimGCunrefNoCycle(LOC22);
				}
				LA20: ;
				{
					if (!(argscount == 1)) goto LA25;
					asgnRefNoCycle((void**) &gprojectname_105191, nosunixToNativePath(p.Key));
					asgnRefNoCycle((void**) &arguments_424005, npocmdLineRest(&p));
					goto LA1;
				}
				LA25: ;
			}
			LA12: ;
			argscount += 1;
		}
		break;
		}
	} LA1: ;
	{
		if (!(pass == ((NU8) 1))) goto LA29;
		{
			NIM_BOOL LOC33;
			TY424073 LOC37;
			LOC33 = !(((gglobaloptions_105108 &(1<<((((NU8) 13))&31)))!=0));
			if (!(LOC33)) goto LA34;
			LOC33 = !(((arguments_424005) && (arguments_424005)->Sup.len == 0));
			LA34: ;
			if (!LOC33) goto LA35;
			memset((void*)LOC37, 0, sizeof(LOC37));
			rawmessage_129448(((NU16) 57), LOC37, 0);
		}
		LA35: ;
	}
	LA29: ;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (NI64)((*a).Sup.len * 1));
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, serve_424077)(TY424079 action) {
	NimStringDesc* typ;
	typ = getconfigvar_105291(((NimStringDesc*) &TMP4163));
	if (eqStrings(typ, ((NimStringDesc*) &TMP4164))) goto LA1;
	if (eqStrings(typ, ((NimStringDesc*) &TMP4165))) goto LA2;
	if (eqStrings(typ, ((NimStringDesc*) &TMP932))) goto LA2;
	goto LA3;
	LA1: ;
	{
		while (1) {
			NimStringDesc* line;
			NimStringDesc* LOC11;
			line = readline_9083(stdin);
			{
				if (!eqStrings(line, ((NimStringDesc*) &TMP4167))) goto LA9;
				exit(0);
			}
			LA9: ;
			LOC11 = 0;
			LOC11 = curcaascmd_424003; curcaascmd_424003 = copyStringRC1(line);
			if (LOC11) nimGCunrefNoCycle(LOC11);
			processcmdline_424007(((NU8) 1), line);
			action();
			gdirtybufferidx_105123 = ((NI32) 0);
			gdirtyoriginalidx_105124 = ((NI32) 0);
			gerrorcounter_128868 = 0;
			printf("%s\012", (((NimStringDesc*) &TMP932))->data);
			fflush(stdout);
		}
	}
	goto LA4;
	LA2: ;
	{
		tsocketimpl110806* server;
		NimStringDesc* p;
		NI16 port;
		NimStringDesc* LOC19;
		NimStringDesc* inp;
		server = socket_111402(((NU8) 2), ((NU8) 1), ((NU8) 6), NIM_TRUE);
		p = getconfigvar_105291(((NimStringDesc*) &TMP4171));
		{
			NI LOC17;
			if (!(0 < p->Sup.len)) goto LA15;
			LOC17 = nsuParseInt(p);
			port = ((NI16) (LOC17));
		}
		goto LA13;
		LA15: ;
		{
			port = ((NI16) 6000);
		}
		LA13: ;
		LOC19 = 0;
		LOC19 = getconfigvar_105291(((NimStringDesc*) &TMP4172));
		bindaddr_112552(server, port, LOC19);
		inp = copyString(((NimStringDesc*) &TMP932));
		listen_112405(server, SOMAXCONN);
		if (stdoutsocket_128873) nimGCunrefNoCycle(stdoutsocket_128873);
		stdoutsocket_128873 = (tsocketimpl110806*) newObjRC1((&NTI110808), sizeof(tsocketimpl110806));
		while (1) {
			NimStringDesc* LOC21;
			accept_114201(server, &stdoutsocket_128873);
			readline_118831(stdoutsocket_128873, &inp, -1);
			LOC21 = 0;
			LOC21 = curcaascmd_424003; curcaascmd_424003 = copyStringRC1(inp);
			if (LOC21) nimGCunrefNoCycle(LOC21);
			processcmdline_424007(((NU8) 1), inp);
			action();
			gdirtybufferidx_105123 = ((NI32) 0);
			gdirtyoriginalidx_105124 = ((NI32) 0);
			gerrorcounter_128868 = 0;
			send_120404(stdoutsocket_128873, ((NimStringDesc*) &TMP4180));
			close_114264(stdoutsocket_128873);
		}
	}
	goto LA4;
	LA3: ;
	{
		printf("%s%s\012", (((NimStringDesc*) &TMP4181))->data, (typ)->data);
		exit(1);
	}
	LA4: ;
}
N_NOINLINE(void, serviceInit)(void) {
	NimStringDesc* LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
	LOC1 = 0;
	LOC1 = curcaascmd_424003; curcaascmd_424003 = copyStringRC1(((NimStringDesc*) &TMP932));
	if (LOC1) nimGCunrefNoCycle(LOC1);
	LOC2 = 0;
	LOC2 = lastcaascmd_424004; lastcaascmd_424004 = copyStringRC1(((NimStringDesc*) &TMP932));
	if (LOC2) nimGCunrefNoCycle(LOC2);
	LOC3 = 0;
	LOC3 = arguments_424005; arguments_424005 = copyStringRC1(((NimStringDesc*) &TMP932));
	if (LOC3) nimGCunrefNoCycle(LOC3);
}

N_NOINLINE(void, serviceDatInit)(void) {
}

