/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/usr/src/extras/Nimrod/lib -o compiler/nimcache/tables.o compiler/nimcache/tables.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct ttable128335 ttable128335;
typedef struct tkeyvaluepairseq128340 tkeyvaluepairseq128340;
typedef struct tkeyvaluepair128345 tkeyvaluepair128345;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct ttable221068 ttable221068;
typedef struct tkeyvaluepairseq221073 tkeyvaluepairseq221073;
typedef struct tkeyvaluepair221078 tkeyvaluepair221078;
typedef struct tcall221008 tcall221008;
typedef struct tsym135677 tsym135677;
typedef struct TY221019 TY221019;
typedef struct ttable221028 ttable221028;
typedef struct tkeyvaluepairseq221033 tkeyvaluepairseq221033;
typedef struct tkeyvaluepair221038 tkeyvaluepair221038;
typedef struct tidobj131012 tidobj131012;
typedef struct TNimObject TNimObject;
typedef struct ttypeseq135679 ttypeseq135679;
typedef struct ttype135681 ttype135681;
typedef struct TY135771 TY135771;
typedef struct tinstantiation135667 tinstantiation135667;
typedef struct tscope135671 tscope135671;
typedef struct tstrtable135651 tstrtable135651;
typedef struct tsymseq135649 tsymseq135649;
typedef struct tident131018 tident131018;
typedef struct tlineinfo128308 tlineinfo128308;
typedef struct tnode135647 tnode135647;
typedef struct tloc135661 tloc135661;
typedef struct trope126007 trope126007;
typedef struct tlib135665 tlib135665;
typedef struct TY135763 TY135763;
typedef struct tnodeseq135641 tnodeseq135641;
typedef struct tlistentry100011 tlistentry100011;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
struct tkeyvaluepair128345 {
NU8 Field0;
NimStringDesc* Field1;
NI32 Field2;
};
struct ttable128335 {
tkeyvaluepairseq128340* Data;
NI Counter;
};
typedef N_NIMCALL_PTR(void, TY891) (void* p, NI op);
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY891 marker;
};
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tcall221008 {
tsym135677* Callee;
TY221019* Args;
};
struct tkeyvaluepair221078 {
NU8 Field0;
tcall221008 Field1;
NU8 Field2;
};
struct ttable221068 {
tkeyvaluepairseq221073* Data;
NI Counter;
};
struct tkeyvaluepair221038 {
NU8 Field0;
NI Field1;
NU8 Field2;
};
struct ttable221028 {
tkeyvaluepairseq221033* Data;
NI Counter;
};
struct TNimObject {
TNimType* m_type;
};
struct tidobj131012 {
  TNimObject Sup;
NI Id;
};
struct tstrtable135651 {
NI Counter;
tsymseq135649* Data;
};
struct tlineinfo128308 {
NI16 Line;
NI16 Col;
NI32 Fileindex;
};
struct tloc135661 {
NU8 K;
NU8 S;
NU8 Flags;
ttype135681* T;
trope126007* R;
trope126007* Heaproot;
NI A;
};
struct tsym135677 {
  tidobj131012 Sup;
NU8 Kind;
union {
struct {ttypeseq135679* Typeinstcache;
} S1;
struct {TY135771* Procinstcache;
tscope135671* Scope;
} S2;
struct {TY135771* Usedgenerics;
tstrtable135651 Tab;
} S3;
} kindU;
NU16 Magic;
ttype135681* Typ;
tident131018* Name;
tlineinfo128308 Info;
tsym135677* Owner;
NU32 Flags;
tnode135647* Ast;
NU32 Options;
NI Position;
NI Offset;
tloc135661 Loc;
tlib135665* Annex;
tnode135647* Constraint;
};
struct ttype135681 {
  tidobj131012 Sup;
NU8 Kind;
NU8 Callconv;
NU32 Flags;
ttypeseq135679* Sons;
tnode135647* N;
tsym135677* Destructor;
tsym135677* Owner;
tsym135677* Sym;
NI64 Size;
NI Align;
tloc135661 Loc;
};
struct tinstantiation135667 {
tsym135677* Sym;
ttypeseq135679* Concretetypes;
TY135763* Usedby;
};
struct tscope135671 {
NI Depthlevel;
tstrtable135651 Symbols;
tscope135671* Parent;
};
struct tident131018 {
  tidobj131012 Sup;
NimStringDesc* S;
tident131018* Next;
NI H;
};
struct tnode135647 {
ttype135681* Typ;
tlineinfo128308 Info;
NU8 Flags;
NU8 Kind;
union {
struct {NI64 Intval;
} S1;
struct {NF64 Floatval;
} S2;
struct {NimStringDesc* Strval;
} S3;
struct {tsym135677* Sym;
} S4;
struct {tident131018* Ident;
} S5;
struct {tnodeseq135641* Sons;
} S6;
} kindU;
NimStringDesc* Comment;
};
struct trope126007 {
  TNimObject Sup;
trope126007* Left;
trope126007* Right;
NI Length;
NimStringDesc* Data;
};
struct tlistentry100011 {
  TNimObject Sup;
tlistentry100011* Prev;
tlistentry100011* Next;
};
struct tlib135665 {
  tlistentry100011 Sup;
NU8 Kind;
NIM_BOOL Generated;
NIM_BOOL Isoverriden;
trope126007* Name;
tnode135647* Path;
};
struct tkeyvaluepairseq128340 {
  TGenericSeq Sup;
  tkeyvaluepair128345 data[SEQ_DECL_SIZE];
};
struct TY221019 {
  TGenericSeq Sup;
  NU8 data[SEQ_DECL_SIZE];
};
struct tkeyvaluepairseq221073 {
  TGenericSeq Sup;
  tkeyvaluepair221078 data[SEQ_DECL_SIZE];
};
struct tkeyvaluepairseq221033 {
  TGenericSeq Sup;
  tkeyvaluepair221038 data[SEQ_DECL_SIZE];
};
struct ttypeseq135679 {
  TGenericSeq Sup;
  ttype135681* data[SEQ_DECL_SIZE];
};
struct TY135771 {
  TGenericSeq Sup;
  tinstantiation135667* data[SEQ_DECL_SIZE];
};
struct tsymseq135649 {
  TGenericSeq Sup;
  tsym135677* data[SEQ_DECL_SIZE];
};
struct TY135763 {
  TGenericSeq Sup;
  NI32 data[SEQ_DECL_SIZE];
};
struct tnodeseq135641 {
  TGenericSeq Sup;
  tnode135647* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP125)(void* p, NI op);
N_NIMCALL(void, TMP824)(void* p, NI op);
N_NIMCALL(void, TMP2865)(void* p, NI op);
TNimType NTI128335; /* TTable */
TNimType NTI128345; /* TKeyValuePair */
TNimType NTI108005; /* TSlotEnum */
extern TNimType NTI143; /* string */
extern TNimType NTI111; /* int32 */
TNimType NTI128340; /* TKeyValuePairSeq */
extern TNimType NTI105; /* int */
TNimType NTI221068; /* TTable */
TNimType NTI221078; /* TKeyValuePair */
extern TNimType NTI221008; /* TCall */
extern TNimType NTI221006; /* TThreadOwner */
TNimType NTI221073; /* TKeyValuePairSeq */
TNimType NTI221028; /* TTable */
TNimType NTI221038; /* TKeyValuePair */
TNimType NTI221033; /* TKeyValuePairSeq */
N_NIMCALL(void, TMP125)(void* p, NI op) {
	tkeyvaluepairseq128340* a;
	NI LOC1;
	a = (tkeyvaluepairseq128340*)p;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field1, op);
	}
}
N_NIMCALL(void, TMP824)(void* p, NI op) {
	tkeyvaluepairseq221073* a;
	NI LOC1;
	a = (tkeyvaluepairseq221073*)p;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field1.Callee, op);
	nimGCvisit((void*)a->data[LOC1].Field1.Args, op);
	}
}
N_NIMCALL(void, TMP2865)(void* p, NI op) {
	tkeyvaluepairseq221033* a;
	NI LOC1;
	a = (tkeyvaluepairseq221033*)p;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	}
}
N_NOINLINE(void, tablesInit)(void) {
}

N_NOINLINE(void, tablesDatInit)(void) {
static TNimNode* TMP120[2];
static TNimNode* TMP121[3];
static TNimNode* TMP122[3];
NI TMP124;
static char* NIM_CONST TMP123[3] = {
"seEmpty", 
"seFilled", 
"seDeleted"};
static TNimNode* TMP817[2];
static TNimNode* TMP818[3];
static TNimNode* TMP2863[2];
static TNimNode* TMP2864[3];
static TNimNode TMP41[25];
NTI128335.size = sizeof(ttable128335);
NTI128335.kind = 18;
NTI128335.base = 0;
NTI128335.flags = 2;
TMP120[0] = &TMP41[1];
NTI128345.size = sizeof(tkeyvaluepair128345);
NTI128345.kind = 18;
NTI128345.base = 0;
NTI128345.flags = 2;
TMP121[0] = &TMP41[3];
NTI108005.size = sizeof(NU8);
NTI108005.kind = 14;
NTI108005.base = 0;
NTI108005.flags = 3;
for (TMP124 = 0; TMP124 < 3; TMP124++) {
TMP41[TMP124+4].kind = 1;
TMP41[TMP124+4].offset = TMP124;
TMP41[TMP124+4].name = TMP123[TMP124];
TMP122[TMP124] = &TMP41[TMP124+4];
}
TMP41[7].len = 3; TMP41[7].kind = 2; TMP41[7].sons = &TMP122[0];
NTI108005.node = &TMP41[7];
TMP41[3].kind = 1;
TMP41[3].offset = offsetof(tkeyvaluepair128345, Field0);
TMP41[3].typ = (&NTI108005);
TMP41[3].name = "Field0";
TMP121[1] = &TMP41[8];
TMP41[8].kind = 1;
TMP41[8].offset = offsetof(tkeyvaluepair128345, Field1);
TMP41[8].typ = (&NTI143);
TMP41[8].name = "Field1";
TMP121[2] = &TMP41[9];
TMP41[9].kind = 1;
TMP41[9].offset = offsetof(tkeyvaluepair128345, Field2);
TMP41[9].typ = (&NTI111);
TMP41[9].name = "Field2";
TMP41[2].len = 3; TMP41[2].kind = 2; TMP41[2].sons = &TMP121[0];
NTI128345.node = &TMP41[2];
NTI128340.size = sizeof(tkeyvaluepairseq128340*);
NTI128340.kind = 24;
NTI128340.base = (&NTI128345);
NTI128340.flags = 2;
NTI128340.marker = TMP125;
TMP41[1].kind = 1;
TMP41[1].offset = offsetof(ttable128335, Data);
TMP41[1].typ = (&NTI128340);
TMP41[1].name = "data";
TMP120[1] = &TMP41[10];
TMP41[10].kind = 1;
TMP41[10].offset = offsetof(ttable128335, Counter);
TMP41[10].typ = (&NTI105);
TMP41[10].name = "counter";
TMP41[0].len = 2; TMP41[0].kind = 2; TMP41[0].sons = &TMP120[0];
NTI128335.node = &TMP41[0];
NTI221068.size = sizeof(ttable221068);
NTI221068.kind = 18;
NTI221068.base = 0;
NTI221068.flags = 2;
TMP817[0] = &TMP41[12];
NTI221078.size = sizeof(tkeyvaluepair221078);
NTI221078.kind = 18;
NTI221078.base = 0;
NTI221078.flags = 2;
TMP818[0] = &TMP41[14];
TMP41[14].kind = 1;
TMP41[14].offset = offsetof(tkeyvaluepair221078, Field0);
TMP41[14].typ = (&NTI108005);
TMP41[14].name = "Field0";
TMP818[1] = &TMP41[15];
TMP41[15].kind = 1;
TMP41[15].offset = offsetof(tkeyvaluepair221078, Field1);
TMP41[15].typ = (&NTI221008);
TMP41[15].name = "Field1";
TMP818[2] = &TMP41[16];
TMP41[16].kind = 1;
TMP41[16].offset = offsetof(tkeyvaluepair221078, Field2);
TMP41[16].typ = (&NTI221006);
TMP41[16].name = "Field2";
TMP41[13].len = 3; TMP41[13].kind = 2; TMP41[13].sons = &TMP818[0];
NTI221078.node = &TMP41[13];
NTI221073.size = sizeof(tkeyvaluepairseq221073*);
NTI221073.kind = 24;
NTI221073.base = (&NTI221078);
NTI221073.flags = 2;
NTI221073.marker = TMP824;
TMP41[12].kind = 1;
TMP41[12].offset = offsetof(ttable221068, Data);
TMP41[12].typ = (&NTI221073);
TMP41[12].name = "data";
TMP817[1] = &TMP41[17];
TMP41[17].kind = 1;
TMP41[17].offset = offsetof(ttable221068, Counter);
TMP41[17].typ = (&NTI105);
TMP41[17].name = "counter";
TMP41[11].len = 2; TMP41[11].kind = 2; TMP41[11].sons = &TMP817[0];
NTI221068.node = &TMP41[11];
NTI221028.size = sizeof(ttable221028);
NTI221028.kind = 18;
NTI221028.base = 0;
NTI221028.flags = 2;
TMP2863[0] = &TMP41[19];
NTI221038.size = sizeof(tkeyvaluepair221038);
NTI221038.kind = 18;
NTI221038.base = 0;
NTI221038.flags = 3;
TMP2864[0] = &TMP41[21];
TMP41[21].kind = 1;
TMP41[21].offset = offsetof(tkeyvaluepair221038, Field0);
TMP41[21].typ = (&NTI108005);
TMP41[21].name = "Field0";
TMP2864[1] = &TMP41[22];
TMP41[22].kind = 1;
TMP41[22].offset = offsetof(tkeyvaluepair221038, Field1);
TMP41[22].typ = (&NTI105);
TMP41[22].name = "Field1";
TMP2864[2] = &TMP41[23];
TMP41[23].kind = 1;
TMP41[23].offset = offsetof(tkeyvaluepair221038, Field2);
TMP41[23].typ = (&NTI221006);
TMP41[23].name = "Field2";
TMP41[20].len = 3; TMP41[20].kind = 2; TMP41[20].sons = &TMP2864[0];
NTI221038.node = &TMP41[20];
NTI221033.size = sizeof(tkeyvaluepairseq221033*);
NTI221033.kind = 24;
NTI221033.base = (&NTI221038);
NTI221033.flags = 2;
NTI221033.marker = TMP2865;
TMP41[19].kind = 1;
TMP41[19].offset = offsetof(ttable221028, Data);
TMP41[19].typ = (&NTI221033);
TMP41[19].name = "data";
TMP2863[1] = &TMP41[24];
TMP41[24].kind = 1;
TMP41[24].offset = offsetof(ttable221028, Counter);
TMP41[24].typ = (&NTI105);
TMP41[24].name = "counter";
TMP41[18].len = 2; TMP41[18].kind = 2; TMP41[18].sons = &TMP2863[0];
NTI221028.node = &TMP41[18];
}

