/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/usr/src/extras/Nimrod/lib -o compiler/nimcache/wordrecg.o compiler/nimcache/wordrecg.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct tident131018 tident131018;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tidobj131012 tidobj131012;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
typedef NimStringDesc* TY157311[245];
typedef N_NIMCALL_PTR(void, TY891) (void* p, NI op);
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY891 marker;
};
struct TNimObject {
TNimType* m_type;
};
struct tidobj131012 {
  TNimObject Sup;
NI Id;
};
struct tident131018 {
  tidobj131012 Sup;
NimStringDesc* S;
tident131018* Next;
NI H;
};
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_NIMCALL(void, initspecials_157354)(void);
N_NIMCALL(tident131018*, getident_131454)(NimStringDesc* identifier, NI h);
N_NIMCALL(NI, hashignorestyle_101852)(NimStringDesc* x);
N_NIMCALL(NU8, whichkeyword_157340)(tident131018* id);
N_NIMCALL(tident131018*, getident_131448)(NimStringDesc* identifier);
N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringDesc* a, NimStringDesc* b);
STRING_LITERAL(TMP494, "", 0);
STRING_LITERAL(TMP495, "addr", 4);
STRING_LITERAL(TMP496, "and", 3);
STRING_LITERAL(TMP497, "as", 2);
STRING_LITERAL(TMP498, "asm", 3);
STRING_LITERAL(TMP499, "atomic", 6);
STRING_LITERAL(TMP500, "bind", 4);
STRING_LITERAL(TMP501, "block", 5);
STRING_LITERAL(TMP502, "break", 5);
STRING_LITERAL(TMP503, "case", 4);
STRING_LITERAL(TMP504, "cast", 4);
STRING_LITERAL(TMP505, "const", 5);
STRING_LITERAL(TMP506, "continue", 8);
STRING_LITERAL(TMP507, "converter", 9);
STRING_LITERAL(TMP508, "discard", 7);
STRING_LITERAL(TMP509, "distinct", 8);
STRING_LITERAL(TMP510, "div", 3);
STRING_LITERAL(TMP511, "do", 2);
STRING_LITERAL(TMP512, "elif", 4);
STRING_LITERAL(TMP513, "else", 4);
STRING_LITERAL(TMP514, "end", 3);
STRING_LITERAL(TMP515, "enum", 4);
STRING_LITERAL(TMP516, "except", 6);
STRING_LITERAL(TMP517, "export", 6);
STRING_LITERAL(TMP518, "finally", 7);
STRING_LITERAL(TMP519, "for", 3);
STRING_LITERAL(TMP520, "from", 4);
STRING_LITERAL(TMP521, "generic", 7);
STRING_LITERAL(TMP522, "if", 2);
STRING_LITERAL(TMP523, "import", 6);
STRING_LITERAL(TMP524, "in", 2);
STRING_LITERAL(TMP525, "include", 7);
STRING_LITERAL(TMP526, "interface", 9);
STRING_LITERAL(TMP527, "is", 2);
STRING_LITERAL(TMP528, "isnot", 5);
STRING_LITERAL(TMP529, "iterator", 8);
STRING_LITERAL(TMP530, "lambda", 6);
STRING_LITERAL(TMP531, "let", 3);
STRING_LITERAL(TMP532, "macro", 5);
STRING_LITERAL(TMP533, "method", 6);
STRING_LITERAL(TMP534, "mixin", 5);
STRING_LITERAL(TMP535, "mod", 3);
STRING_LITERAL(TMP536, "nil", 3);
STRING_LITERAL(TMP537, "not", 3);
STRING_LITERAL(TMP538, "notin", 5);
STRING_LITERAL(TMP539, "object", 6);
STRING_LITERAL(TMP540, "of", 2);
STRING_LITERAL(TMP541, "or", 2);
STRING_LITERAL(TMP542, "out", 3);
STRING_LITERAL(TMP543, "proc", 4);
STRING_LITERAL(TMP544, "ptr", 3);
STRING_LITERAL(TMP545, "raise", 5);
STRING_LITERAL(TMP546, "ref", 3);
STRING_LITERAL(TMP547, "return", 6);
STRING_LITERAL(TMP548, "shared", 6);
STRING_LITERAL(TMP549, "shl", 3);
STRING_LITERAL(TMP550, "shr", 3);
STRING_LITERAL(TMP551, "static", 6);
STRING_LITERAL(TMP552, "template", 8);
STRING_LITERAL(TMP553, "try", 3);
STRING_LITERAL(TMP554, "tuple", 5);
STRING_LITERAL(TMP555, "type", 4);
STRING_LITERAL(TMP556, "var", 3);
STRING_LITERAL(TMP557, "when", 4);
STRING_LITERAL(TMP558, "while", 5);
STRING_LITERAL(TMP559, "with", 4);
STRING_LITERAL(TMP560, "without", 7);
STRING_LITERAL(TMP561, "xor", 3);
STRING_LITERAL(TMP562, "yield", 5);
STRING_LITERAL(TMP563, ":", 1);
STRING_LITERAL(TMP564, "::", 2);
STRING_LITERAL(TMP565, "=", 1);
STRING_LITERAL(TMP566, ".", 1);
STRING_LITERAL(TMP567, "..", 2);
STRING_LITERAL(TMP568, "*", 1);
STRING_LITERAL(TMP569, "-", 1);
STRING_LITERAL(TMP570, "magic", 5);
STRING_LITERAL(TMP571, "thread", 6);
STRING_LITERAL(TMP572, "final", 5);
STRING_LITERAL(TMP573, "profiler", 8);
STRING_LITERAL(TMP574, "objchecks", 9);
STRING_LITERAL(TMP575, "destroy", 7);
STRING_LITERAL(TMP576, "immediate", 9);
STRING_LITERAL(TMP577, "destructor", 10);
STRING_LITERAL(TMP578, "importcpp", 9);
STRING_LITERAL(TMP579, "importobjc", 10);
STRING_LITERAL(TMP580, "importcompilerproc", 18);
STRING_LITERAL(TMP581, "importc", 7);
STRING_LITERAL(TMP582, "exportc", 7);
STRING_LITERAL(TMP583, "incompletestruct", 16);
STRING_LITERAL(TMP584, "requiresinit", 12);
STRING_LITERAL(TMP585, "align", 5);
STRING_LITERAL(TMP586, "nodecl", 6);
STRING_LITERAL(TMP587, "pure", 4);
STRING_LITERAL(TMP588, "sideeffect", 10);
STRING_LITERAL(TMP589, "header", 6);
STRING_LITERAL(TMP590, "nosideeffect", 12);
STRING_LITERAL(TMP591, "noreturn", 8);
STRING_LITERAL(TMP592, "merge", 5);
STRING_LITERAL(TMP593, "lib", 3);
STRING_LITERAL(TMP594, "dynlib", 6);
STRING_LITERAL(TMP595, "compilerproc", 12);
STRING_LITERAL(TMP596, "procvar", 7);
STRING_LITERAL(TMP597, "fatal", 5);
STRING_LITERAL(TMP598, "error", 5);
STRING_LITERAL(TMP599, "warning", 7);
STRING_LITERAL(TMP600, "hint", 4);
STRING_LITERAL(TMP601, "line", 4);
STRING_LITERAL(TMP602, "push", 4);
STRING_LITERAL(TMP603, "pop", 3);
STRING_LITERAL(TMP604, "define", 6);
STRING_LITERAL(TMP605, "undef", 5);
STRING_LITERAL(TMP606, "linedir", 7);
STRING_LITERAL(TMP607, "stacktrace", 10);
STRING_LITERAL(TMP608, "linetrace", 9);
STRING_LITERAL(TMP609, "link", 4);
STRING_LITERAL(TMP610, "compile", 7);
STRING_LITERAL(TMP611, "linksys", 7);
STRING_LITERAL(TMP612, "deprecated", 10);
STRING_LITERAL(TMP613, "varargs", 7);
STRING_LITERAL(TMP614, "callconv", 8);
STRING_LITERAL(TMP615, "breakpoint", 10);
STRING_LITERAL(TMP616, "debugger", 8);
STRING_LITERAL(TMP617, "nimcall", 7);
STRING_LITERAL(TMP618, "stdcall", 7);
STRING_LITERAL(TMP619, "cdecl", 5);
STRING_LITERAL(TMP620, "safecall", 8);
STRING_LITERAL(TMP621, "syscall", 7);
STRING_LITERAL(TMP622, "inline", 6);
STRING_LITERAL(TMP623, "noinline", 8);
STRING_LITERAL(TMP624, "fastcall", 8);
STRING_LITERAL(TMP625, "closure", 7);
STRING_LITERAL(TMP626, "noconv", 6);
STRING_LITERAL(TMP627, "on", 2);
STRING_LITERAL(TMP628, "off", 3);
STRING_LITERAL(TMP629, "checks", 6);
STRING_LITERAL(TMP630, "rangechecks", 11);
STRING_LITERAL(TMP631, "boundchecks", 11);
STRING_LITERAL(TMP632, "overflowchecks", 14);
STRING_LITERAL(TMP633, "nilchecks", 9);
STRING_LITERAL(TMP634, "floatchecks", 11);
STRING_LITERAL(TMP635, "nanchecks", 9);
STRING_LITERAL(TMP636, "infchecks", 9);
STRING_LITERAL(TMP637, "assertions", 10);
STRING_LITERAL(TMP638, "patterns", 8);
STRING_LITERAL(TMP639, "warnings", 8);
STRING_LITERAL(TMP640, "hints", 5);
STRING_LITERAL(TMP641, "optimization", 12);
STRING_LITERAL(TMP642, "raises", 6);
STRING_LITERAL(TMP643, "writes", 6);
STRING_LITERAL(TMP644, "reads", 5);
STRING_LITERAL(TMP645, "size", 4);
STRING_LITERAL(TMP646, "effects", 7);
STRING_LITERAL(TMP647, "tags", 4);
STRING_LITERAL(TMP648, "deadcodeelim", 12);
STRING_LITERAL(TMP649, "safecode", 8);
STRING_LITERAL(TMP650, "noforward", 9);
STRING_LITERAL(TMP651, "pragma", 6);
STRING_LITERAL(TMP652, "compiletime", 11);
STRING_LITERAL(TMP653, "noinit", 6);
STRING_LITERAL(TMP654, "passc", 5);
STRING_LITERAL(TMP655, "passl", 5);
STRING_LITERAL(TMP656, "borrow", 6);
STRING_LITERAL(TMP657, "discardable", 11);
STRING_LITERAL(TMP658, "fieldchecks", 11);
STRING_LITERAL(TMP659, "watchpoint", 10);
STRING_LITERAL(TMP660, "subschar", 8);
STRING_LITERAL(TMP661, "acyclic", 7);
STRING_LITERAL(TMP662, "shallow", 7);
STRING_LITERAL(TMP663, "unroll", 6);
STRING_LITERAL(TMP664, "linearscanend", 13);
STRING_LITERAL(TMP665, "write", 5);
STRING_LITERAL(TMP666, "gensym", 6);
STRING_LITERAL(TMP667, "inject", 6);
STRING_LITERAL(TMP668, "dirty", 5);
STRING_LITERAL(TMP669, "inheritable", 11);
STRING_LITERAL(TMP670, "threadvar", 9);
STRING_LITERAL(TMP671, "emit", 4);
STRING_LITERAL(TMP672, "nostackframe", 12);
STRING_LITERAL(TMP673, "implicitstatic", 14);
STRING_LITERAL(TMP674, "global", 6);
STRING_LITERAL(TMP675, "codegendecl", 11);
STRING_LITERAL(TMP676, "auto", 4);
STRING_LITERAL(TMP677, "bool", 4);
STRING_LITERAL(TMP678, "catch", 5);
STRING_LITERAL(TMP679, "char", 4);
STRING_LITERAL(TMP680, "class", 5);
STRING_LITERAL(TMP681, "const_cast", 10);
STRING_LITERAL(TMP682, "default", 7);
STRING_LITERAL(TMP683, "delete", 6);
STRING_LITERAL(TMP684, "double", 6);
STRING_LITERAL(TMP685, "dynamic_cast", 12);
STRING_LITERAL(TMP686, "explicit", 8);
STRING_LITERAL(TMP687, "extern", 6);
STRING_LITERAL(TMP688, "false", 5);
STRING_LITERAL(TMP689, "float", 5);
STRING_LITERAL(TMP690, "friend", 6);
STRING_LITERAL(TMP691, "goto", 4);
STRING_LITERAL(TMP692, "int", 3);
STRING_LITERAL(TMP693, "long", 4);
STRING_LITERAL(TMP694, "mutable", 7);
STRING_LITERAL(TMP695, "namespace", 9);
STRING_LITERAL(TMP696, "new", 3);
STRING_LITERAL(TMP697, "operator", 8);
STRING_LITERAL(TMP698, "private", 7);
STRING_LITERAL(TMP699, "protected", 9);
STRING_LITERAL(TMP700, "public", 6);
STRING_LITERAL(TMP701, "register", 8);
STRING_LITERAL(TMP702, "reinterpret_cast", 16);
STRING_LITERAL(TMP703, "short", 5);
STRING_LITERAL(TMP704, "signed", 6);
STRING_LITERAL(TMP705, "sizeof", 6);
STRING_LITERAL(TMP706, "static_cast", 11);
STRING_LITERAL(TMP707, "struct", 6);
STRING_LITERAL(TMP708, "switch", 6);
STRING_LITERAL(TMP709, "this", 4);
STRING_LITERAL(TMP710, "throw", 5);
STRING_LITERAL(TMP711, "true", 4);
STRING_LITERAL(TMP712, "typedef", 7);
STRING_LITERAL(TMP713, "typeid", 6);
STRING_LITERAL(TMP714, "typename", 8);
STRING_LITERAL(TMP715, "union", 5);
STRING_LITERAL(TMP716, "unsigned", 8);
STRING_LITERAL(TMP717, "using", 5);
STRING_LITERAL(TMP718, "virtual", 7);
STRING_LITERAL(TMP719, "void", 4);
STRING_LITERAL(TMP720, "volatile", 8);
STRING_LITERAL(TMP721, "wchar_t", 7);
STRING_LITERAL(TMP722, "alignas", 7);
STRING_LITERAL(TMP723, "alignof", 7);
STRING_LITERAL(TMP724, "constexpr", 9);
STRING_LITERAL(TMP725, "decltype", 8);
STRING_LITERAL(TMP726, "nullptr", 7);
STRING_LITERAL(TMP727, "noexcept", 8);
STRING_LITERAL(TMP728, "thread_local", 12);
STRING_LITERAL(TMP729, "static_assert", 13);
STRING_LITERAL(TMP730, "char16_t", 8);
STRING_LITERAL(TMP731, "char32_t", 8);
STRING_LITERAL(TMP732, "stdin", 5);
STRING_LITERAL(TMP733, "stdout", 6);
STRING_LITERAL(TMP734, "stderr", 6);
STRING_LITERAL(TMP735, "inout", 5);
STRING_LITERAL(TMP736, "bycopy", 6);
STRING_LITERAL(TMP737, "byref", 5);
STRING_LITERAL(TMP738, "oneway", 6);
NIM_CONST TY157311 specialwords_157310 = {((NimStringDesc*) &TMP494),
((NimStringDesc*) &TMP495),
((NimStringDesc*) &TMP496),
((NimStringDesc*) &TMP497),
((NimStringDesc*) &TMP498),
((NimStringDesc*) &TMP499),
((NimStringDesc*) &TMP500),
((NimStringDesc*) &TMP501),
((NimStringDesc*) &TMP502),
((NimStringDesc*) &TMP503),
((NimStringDesc*) &TMP504),
((NimStringDesc*) &TMP505),
((NimStringDesc*) &TMP506),
((NimStringDesc*) &TMP507),
((NimStringDesc*) &TMP508),
((NimStringDesc*) &TMP509),
((NimStringDesc*) &TMP510),
((NimStringDesc*) &TMP511),
((NimStringDesc*) &TMP512),
((NimStringDesc*) &TMP513),
((NimStringDesc*) &TMP514),
((NimStringDesc*) &TMP515),
((NimStringDesc*) &TMP516),
((NimStringDesc*) &TMP517),
((NimStringDesc*) &TMP518),
((NimStringDesc*) &TMP519),
((NimStringDesc*) &TMP520),
((NimStringDesc*) &TMP521),
((NimStringDesc*) &TMP522),
((NimStringDesc*) &TMP523),
((NimStringDesc*) &TMP524),
((NimStringDesc*) &TMP525),
((NimStringDesc*) &TMP526),
((NimStringDesc*) &TMP527),
((NimStringDesc*) &TMP528),
((NimStringDesc*) &TMP529),
((NimStringDesc*) &TMP530),
((NimStringDesc*) &TMP531),
((NimStringDesc*) &TMP532),
((NimStringDesc*) &TMP533),
((NimStringDesc*) &TMP534),
((NimStringDesc*) &TMP535),
((NimStringDesc*) &TMP536),
((NimStringDesc*) &TMP537),
((NimStringDesc*) &TMP538),
((NimStringDesc*) &TMP539),
((NimStringDesc*) &TMP540),
((NimStringDesc*) &TMP541),
((NimStringDesc*) &TMP542),
((NimStringDesc*) &TMP543),
((NimStringDesc*) &TMP544),
((NimStringDesc*) &TMP545),
((NimStringDesc*) &TMP546),
((NimStringDesc*) &TMP547),
((NimStringDesc*) &TMP548),
((NimStringDesc*) &TMP549),
((NimStringDesc*) &TMP550),
((NimStringDesc*) &TMP551),
((NimStringDesc*) &TMP552),
((NimStringDesc*) &TMP553),
((NimStringDesc*) &TMP554),
((NimStringDesc*) &TMP555),
((NimStringDesc*) &TMP556),
((NimStringDesc*) &TMP557),
((NimStringDesc*) &TMP558),
((NimStringDesc*) &TMP559),
((NimStringDesc*) &TMP560),
((NimStringDesc*) &TMP561),
((NimStringDesc*) &TMP562),
((NimStringDesc*) &TMP563),
((NimStringDesc*) &TMP564),
((NimStringDesc*) &TMP565),
((NimStringDesc*) &TMP566),
((NimStringDesc*) &TMP567),
((NimStringDesc*) &TMP568),
((NimStringDesc*) &TMP569),
((NimStringDesc*) &TMP570),
((NimStringDesc*) &TMP571),
((NimStringDesc*) &TMP572),
((NimStringDesc*) &TMP573),
((NimStringDesc*) &TMP574),
((NimStringDesc*) &TMP575),
((NimStringDesc*) &TMP576),
((NimStringDesc*) &TMP577),
((NimStringDesc*) &TMP578),
((NimStringDesc*) &TMP579),
((NimStringDesc*) &TMP580),
((NimStringDesc*) &TMP581),
((NimStringDesc*) &TMP582),
((NimStringDesc*) &TMP583),
((NimStringDesc*) &TMP584),
((NimStringDesc*) &TMP585),
((NimStringDesc*) &TMP586),
((NimStringDesc*) &TMP587),
((NimStringDesc*) &TMP588),
((NimStringDesc*) &TMP589),
((NimStringDesc*) &TMP590),
((NimStringDesc*) &TMP591),
((NimStringDesc*) &TMP592),
((NimStringDesc*) &TMP593),
((NimStringDesc*) &TMP594),
((NimStringDesc*) &TMP595),
((NimStringDesc*) &TMP596),
((NimStringDesc*) &TMP597),
((NimStringDesc*) &TMP598),
((NimStringDesc*) &TMP599),
((NimStringDesc*) &TMP600),
((NimStringDesc*) &TMP601),
((NimStringDesc*) &TMP602),
((NimStringDesc*) &TMP603),
((NimStringDesc*) &TMP604),
((NimStringDesc*) &TMP605),
((NimStringDesc*) &TMP606),
((NimStringDesc*) &TMP607),
((NimStringDesc*) &TMP608),
((NimStringDesc*) &TMP609),
((NimStringDesc*) &TMP610),
((NimStringDesc*) &TMP611),
((NimStringDesc*) &TMP612),
((NimStringDesc*) &TMP613),
((NimStringDesc*) &TMP614),
((NimStringDesc*) &TMP615),
((NimStringDesc*) &TMP616),
((NimStringDesc*) &TMP617),
((NimStringDesc*) &TMP618),
((NimStringDesc*) &TMP619),
((NimStringDesc*) &TMP620),
((NimStringDesc*) &TMP621),
((NimStringDesc*) &TMP622),
((NimStringDesc*) &TMP623),
((NimStringDesc*) &TMP624),
((NimStringDesc*) &TMP625),
((NimStringDesc*) &TMP626),
((NimStringDesc*) &TMP627),
((NimStringDesc*) &TMP628),
((NimStringDesc*) &TMP629),
((NimStringDesc*) &TMP630),
((NimStringDesc*) &TMP631),
((NimStringDesc*) &TMP632),
((NimStringDesc*) &TMP633),
((NimStringDesc*) &TMP634),
((NimStringDesc*) &TMP635),
((NimStringDesc*) &TMP636),
((NimStringDesc*) &TMP637),
((NimStringDesc*) &TMP638),
((NimStringDesc*) &TMP639),
((NimStringDesc*) &TMP640),
((NimStringDesc*) &TMP641),
((NimStringDesc*) &TMP642),
((NimStringDesc*) &TMP643),
((NimStringDesc*) &TMP644),
((NimStringDesc*) &TMP645),
((NimStringDesc*) &TMP646),
((NimStringDesc*) &TMP647),
((NimStringDesc*) &TMP648),
((NimStringDesc*) &TMP649),
((NimStringDesc*) &TMP650),
((NimStringDesc*) &TMP651),
((NimStringDesc*) &TMP652),
((NimStringDesc*) &TMP653),
((NimStringDesc*) &TMP654),
((NimStringDesc*) &TMP655),
((NimStringDesc*) &TMP656),
((NimStringDesc*) &TMP657),
((NimStringDesc*) &TMP658),
((NimStringDesc*) &TMP659),
((NimStringDesc*) &TMP660),
((NimStringDesc*) &TMP661),
((NimStringDesc*) &TMP662),
((NimStringDesc*) &TMP663),
((NimStringDesc*) &TMP664),
((NimStringDesc*) &TMP665),
((NimStringDesc*) &TMP666),
((NimStringDesc*) &TMP667),
((NimStringDesc*) &TMP668),
((NimStringDesc*) &TMP669),
((NimStringDesc*) &TMP670),
((NimStringDesc*) &TMP671),
((NimStringDesc*) &TMP672),
((NimStringDesc*) &TMP673),
((NimStringDesc*) &TMP674),
((NimStringDesc*) &TMP675),
((NimStringDesc*) &TMP676),
((NimStringDesc*) &TMP677),
((NimStringDesc*) &TMP678),
((NimStringDesc*) &TMP679),
((NimStringDesc*) &TMP680),
((NimStringDesc*) &TMP681),
((NimStringDesc*) &TMP682),
((NimStringDesc*) &TMP683),
((NimStringDesc*) &TMP684),
((NimStringDesc*) &TMP685),
((NimStringDesc*) &TMP686),
((NimStringDesc*) &TMP687),
((NimStringDesc*) &TMP688),
((NimStringDesc*) &TMP689),
((NimStringDesc*) &TMP690),
((NimStringDesc*) &TMP691),
((NimStringDesc*) &TMP692),
((NimStringDesc*) &TMP693),
((NimStringDesc*) &TMP694),
((NimStringDesc*) &TMP695),
((NimStringDesc*) &TMP696),
((NimStringDesc*) &TMP697),
((NimStringDesc*) &TMP698),
((NimStringDesc*) &TMP699),
((NimStringDesc*) &TMP700),
((NimStringDesc*) &TMP701),
((NimStringDesc*) &TMP702),
((NimStringDesc*) &TMP703),
((NimStringDesc*) &TMP704),
((NimStringDesc*) &TMP705),
((NimStringDesc*) &TMP706),
((NimStringDesc*) &TMP707),
((NimStringDesc*) &TMP708),
((NimStringDesc*) &TMP709),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP712),
((NimStringDesc*) &TMP713),
((NimStringDesc*) &TMP714),
((NimStringDesc*) &TMP715),
((NimStringDesc*) &TMP716),
((NimStringDesc*) &TMP717),
((NimStringDesc*) &TMP718),
((NimStringDesc*) &TMP719),
((NimStringDesc*) &TMP720),
((NimStringDesc*) &TMP721),
((NimStringDesc*) &TMP722),
((NimStringDesc*) &TMP723),
((NimStringDesc*) &TMP724),
((NimStringDesc*) &TMP725),
((NimStringDesc*) &TMP726),
((NimStringDesc*) &TMP727),
((NimStringDesc*) &TMP728),
((NimStringDesc*) &TMP729),
((NimStringDesc*) &TMP730),
((NimStringDesc*) &TMP731),
((NimStringDesc*) &TMP732),
((NimStringDesc*) &TMP733),
((NimStringDesc*) &TMP734),
((NimStringDesc*) &TMP735),
((NimStringDesc*) &TMP736),
((NimStringDesc*) &TMP737),
((NimStringDesc*) &TMP738)}
;

N_NIMCALL(void, initspecials_157354)(void) {
	NU8 s_157396;
	NU8 res_157404;
	s_157396 = 0;
	res_157404 = ((NU8) 1);
	while (1) {
		NI LOC2;
		tident131018* LOC3;
		if (!(res_157404 <= ((NU8) 244))) goto LA1;
		s_157396 = res_157404;
		LOC2 = hashignorestyle_101852(specialwords_157310[(s_157396)- 0]);
		LOC3 = 0;
		LOC3 = getident_131454(specialwords_157310[(s_157396)- 0], LOC2);
		(*LOC3).Sup.Id = ((NI) (s_157396));
		res_157404 += 1;
	} LA1: ;
}

N_NIMCALL(NU8, whichkeyword_157340)(tident131018* id) {
	NU8 result;
	result = 0;
	{
		if (!((*id).Sup.Id < 0)) goto LA3;
		result = ((NU8) 0);
	}
	goto LA1;
	LA3: ;
	{
		result = ((NU8) ((*id).Sup.Id));
	}
	LA1: ;
	return result;
}

N_NIMCALL(NU8, whichkeyword_157348)(NimStringDesc* id) {
	NU8 result;
	tident131018* LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = getident_131448(id);
	result = whichkeyword_157340(LOC1);
	return result;
}

N_NIMCALL(NI, findstr_157318)(NimStringDesc** a, NI alen0, NimStringDesc* s) {
	NI result;
	NI i_157332;
	NI HEX3Atmp_157333;
	NI res_157335;
	result = 0;
	i_157332 = 0;
	HEX3Atmp_157333 = 0;
	HEX3Atmp_157333 = (alen0-1);
	res_157335 = 0;
	while (1) {
		if (!(res_157335 <= HEX3Atmp_157333)) goto LA1;
		i_157332 = res_157335;
		{
			NI LOC4;
			LOC4 = nsuCmpIgnoreStyle(a[i_157332], s);
			if (!(LOC4 == 0)) goto LA5;
			result = i_157332;
			goto BeforeRet;
		}
		LA5: ;
		res_157335 += 1;
	} LA1: ;
	result = -1;
	BeforeRet: ;
	return result;
}
N_NOINLINE(void, wordrecgInit)(void) {
	initspecials_157354();
}

N_NOINLINE(void, wordrecgDatInit)(void) {
}

