#
# THIS IS A GENERATED FILE
#
# Do not change!  Changing this file implies a protocol change!
#

import  
  X

const 
  XaPrimary* = TAtom(1)
  XaSecondary* = TAtom(2)
  XaArc* = TAtom(3)
  XaAtom* = TAtom(4)
  XaBitmap* = TAtom(5)
  XaCardinal* = TAtom(6)
  XaColormap* = TAtom(7)
  XaCursor* = TAtom(8)
  XaCutBuffer0* = TAtom(9)
  XaCutBuffer1* = TAtom(10)
  XaCutBuffer2* = TAtom(11)
  XaCutBuffer3* = TAtom(12)
  XaCutBuffer4* = TAtom(13)
  XaCutBuffer5* = TAtom(14)
  XaCutBuffer6* = TAtom(15)
  XaCutBuffer7* = TAtom(16)
  XaDrawable* = TAtom(17)
  XaFont* = TAtom(18)
  XaInteger* = TAtom(19)
  XaPixmap* = TAtom(20)
  XaPoint* = TAtom(21)
  XaRectangle* = TAtom(22)
  XaResourceManager* = TAtom(23)
  XaRgbColorMap* = TAtom(24)
  XaRgbBestMap* = TAtom(25)
  XaRgbBlueMap* = TAtom(26)
  XaRgbDefaultMap* = TAtom(27)
  XaRgbGrayMap* = TAtom(28)
  XaRgbGreenMap* = TAtom(29)
  XaRgbRedMap* = TAtom(30)
  XaString* = TAtom(31)
  XaVisualid* = TAtom(32)
  XaWindow* = TAtom(33)
  XaWmCommand* = TAtom(34)
  XaWmHints* = TAtom(35)
  XaWmClientMachine* = TAtom(36)
  XaWmIconName* = TAtom(37)
  XaWmIconSize* = TAtom(38)
  XaWmName* = TAtom(39)
  XaWmNormalHints* = TAtom(40)
  XaWmSizeHints* = TAtom(41)
  XaWmZoomHints* = TAtom(42)
  XaMinSpace* = TAtom(43)
  XaNormSpace* = TAtom(44)
  XaMaxSpace* = TAtom(45)
  XaEndSpace* = TAtom(46)
  XaSuperscriptX* = TAtom(47)
  XaSuperscriptY* = TAtom(48)
  XaSubscriptX* = TAtom(49)
  XaSubscriptY* = TAtom(50)
  XaUnderlinePosition* = TAtom(51)
  XaUnderlineThickness* = TAtom(52)
  XaStrikeoutAscent* = TAtom(53)
  XaStrikeoutDescent* = TAtom(54)
  XaItalicAngle* = TAtom(55)
  XaXHeight* = TAtom(56)
  XaQuadWidth* = TAtom(57)
  XaWeight* = TAtom(58)
  XaPointSize* = TAtom(59)
  XaResolution* = TAtom(60)
  XaCopyright* = TAtom(61)
  XaNotice* = TAtom(62)
  XaFontName* = TAtom(63)
  XaFamilyName* = TAtom(64)
  XaFullName* = TAtom(65)
  XaCapHeight* = TAtom(66)
  XaWmClass* = TAtom(67)
  XaWmTransientFor* = TAtom(68)
  XaLastPredefined* = TAtom(68)

# implementation
